/**
 * Regression suite for the Neon-backed Occu-Med relevance profile, run through the REAL application path.
 *
 * What is real: the Neon rows -> SQL strings (PROFILE_SQL) -> refreshRelevanceProfile -> buildProfile ->
 * setRelevanceProfile -> classifyResult -> decideRelevance -> decideOpportunityQuality, i.e. the same
 * functions ingestion calls. No rule adapter, no ontology overwrite.
 *
 * What is mocked: only the database transport. The sandbox cannot reach Neon, so `query` answers the
 * loader's exact SQL with rows reconstructed from the migration files (docs/neon-profile/regression/rows.json,
 * generated by build_rows.py; the migration files are checksum-verified equal to the Neon test branch).
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { after, before, describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { decideOpportunityQuality } from "../../ingestion/opportunityIdentity";
import { PROFILE_SQL, refreshRelevanceProfile, type QueryFn } from "../../occumedAware/relevanceProfileLoader";
import type { NormalizedOpportunity, OpportunitySource } from "../../providers/types";
import { classifyResult } from "../relevance";
import { decideRelevance } from "../relevanceDecision";
import { buildProfile, getRelevanceProfile, setRelevanceProfile, type ProfileRows } from "../relevanceProfile";

const here = path.dirname(fileURLToPath(import.meta.url));
const reg = path.resolve(here, "../../../../../docs/neon-profile/regression");
const ROWS = JSON.parse(fs.readFileSync(path.join(reg, "rows.json"), "utf8")) as ProfileRows;
type Case = { id: string; group: string; title: string; description: string; expect: string; url?: string; date?: string; deadline?: boolean };
const CASES = JSON.parse(fs.readFileSync(path.join(reg, "cases.json"), "utf8")) as Case[];

/** Mock Neon transport: answers the loader's exact SQL, and nothing else. */
function neonTransport(rows: ProfileRows): QueryFn {
  return (async (sql: string) => {
    if (sql === PROFILE_SQL.terms) return rows.terms;
    if (sql === PROFILE_SQL.rules) return rows.rules;
    if (sql === PROFILE_SQL.facts) return rows.facts;
    if (sql === PROFILE_SQL.policies) return rows.policies;
    throw new Error(`unexpected SQL in mocked transport: ${sql.slice(0, 60)}`);
  }) as QueryFn;
}

const NOW = new Date("2026-10-03T12:00:00Z");
const PROVIDERS: Array<{ source: OpportunitySource; url: (c: Case) => string; agency: string }> = [
  { source: "samGov", url: () => "https://sam.gov/opp/abc/view", agency: "Department of Veterans Affairs" },
  { source: "texasEsbd", url: () => "https://www.txsmartbuy.gov/esbd/123", agency: "Texas DPS" },
  { source: "nyScr", url: () => "https://www.nyscr.ny.gov/ad/1", agency: "NY OGS" },
  { source: "publicPortalProviders", url: () => "https://www.bidnetdirect.com/x/1", agency: "City of Example" },
  { source: "eunaBonfire", url: () => "https://example.bonfirehub.com/opportunities/9", agency: "Example University" },
  { source: "langsearch", url: (c) => c.url ?? "https://example.org/x", agency: "Unknown" },
  { source: "tango", url: () => "https://tango.makegov.com/o/1", agency: "GSA" },
  { source: "gemini", url: () => "https://example.com/found/by/ai", agency: "Example County" },
];

function record(c: Case, provider = PROVIDERS[0]): NormalizedOpportunity {
  return {
    externalId: `${provider.source}-${c.id}`,
    title: c.title,
    agency: provider.agency,
    type: "Solicitation",
    status: "active",
    postedDate: c.date ? new Date(c.date) : new Date("2026-09-20T00:00:00Z"),
    responseDeadline: c.deadline === false ? undefined : new Date("2026-12-15T00:00:00Z"),
    description: c.description,
    sourceUrl: provider.url(c),
    source: provider.source,
    providerName: provider.source,
  };
}
const verdictOf = (r: NormalizedOpportunity) => {
  const d = decideOpportunityQuality(r);
  return d.status === "accepted" ? "accept" : d.status === "quarantined" ? "review" : "reject";
};
const meets = (expect: string, v: string) =>
  expect === "accept" ? v === "accept" : expect === "not_reject" ? v !== "reject" : expect === "not_accept" ? v !== "accept" : v === "reject";

describe("Neon relevance profile: real application path", () => {
  before(async () => {
    const r = await refreshRelevanceProfile(neonTransport(ROWS));
    assert.equal(r.applied, true, `profile must load from rows: ${r.missing.join(", ")}`);
  });
  after(() => setRelevanceProfile(null));

  it("loads from Neon rows with no phrase cap (terms Neon already had are present)", () => {
    const p = getRelevanceProfile();
    assert.equal(p.source, "neon");
    assert.ok(p.generalExplicit.length >= 43, `general explicit phrases ${p.generalExplicit.length}`);
    for (const phrase of ["spirometry", "urine drug testing", "pulmonary function testing"]) {
      const all = [...p.generalExplicit, ...p.categories.flatMap((c) => [...c.explicit, ...c.component])];
      assert.ok(all.some((t) => t.includes(phrase)), `${phrase} must be in the profile`);
    }
    assert.equal(p.thresholds.acceptMin, 70);
    assert.equal(p.thresholds.reviewMin, 45);
  });

  it("profile built by the app equals the independently built reference profile", () => {
    const ref = JSON.parse(fs.readFileSync(path.join(reg, "profile.json"), "utf8"));
    const p = getRelevanceProfile();
    for (const k of ["procurementSignals", "workforceSignals", "networkTerms", "titleMedical", "genericTitle", "prime", "regulatory", "generalExplicit"] as const)
      assert.deepEqual(p[k], ref[k], k);
    for (const c of p.categories) {
      const rc = ref.categories[c.id];
      assert.deepEqual({ explicit: c.explicit, component: c.component, regulatory: c.regulatory }, { explicit: rc.explicit, component: rc.component, regulatory: rc.regulatory }, c.id);
    }
  });

  it("an incomplete Neon profile is not applied; with nothing else loaded the app fails closed", async () => {
    setRelevanceProfile(null);
    const partial: ProfileRows = { ...ROWS, facts: ROWS.facts.filter((f) => f.category !== "relevance_threshold") };
    const r = await refreshRelevanceProfile(neonTransport(partial));
    assert.equal(r.applied, false);
    assert.ok(r.missing.includes("canonical thresholds"));
    assert.equal(getRelevanceProfile().source, "unavailable");
    const input = { title: "Pre-Employment Physical Examination Services", description: "Request for proposals for employees." };
    assert.equal(classifyResult(input).profileSource, "unavailable");
    assert.equal(decideRelevance(classifyResult(input)).verdict, "review");
    await refreshRelevanceProfile(neonTransport(ROWS));
    assert.equal(getRelevanceProfile().source, "neon");
  });

  const groups = [...new Set(CASES.map((c) => c.group))];
  for (const g of groups) {
    describe(`group: ${g}`, () => {
      for (const c of CASES.filter((x) => x.group === g)) {
        it(`${c.id} (expect ${c.expect}): ${c.title}`, () => {
          const v = verdictOf(record(c));
          assert.ok(meets(c.expect, v), `${c.id} expected ${c.expect}, got ${v}: ${JSON.stringify(decideOpportunityQuality(record(c)).reason)}`);
        });
      }
    });
  }

  describe("same decision regardless of provider", () => {
    for (const c of CASES) {
      it(`${c.id}: identical decision from every provider`, () => {
        const results = PROVIDERS.map((p) => {
          const d = decideOpportunityQuality(record(c, p));
          return { provider: p.source, status: d.status, code: d.reason?.split("|")[0] ?? null };
        });
        const first = results[0];
        for (const r of results) {
          assert.deepEqual({ status: r.status, code: r.code }, { status: first.status, code: first.code }, `${r.provider} differs from ${first.provider} for ${c.id}`);
        }
      });
    }
    it("the decision function never receives provider identity", () => {
      const c = CASES.find((x) => x.id === "good01")!;
      const a = decideRelevance(classifyResult({ title: c.title, snippet: c.description }));
      const b = decideRelevance(classifyResult({ title: c.title, snippet: c.description }));
      assert.deepEqual(a, b);
    });
  });
});
