-- 005: classifier wording rules (status=draft). 3 rows. Moves the classifier's last three relevance word lists
-- out of application code into Neon rules: the informational-wording penalty, the job-title-wording penalty
-- (both apply only when the notice carries no procurement signal), and the service-evidence list that managed
-- delivery/network scope must be accompanied by.
begin;
insert into occumed_core.rules (rule_key,category,title,rule_text,machine_action,hard_rule,priority,scope,authority_level,status,source_id,source_locator,notes,search_triggers)
select e->>0, e->>1, e->>2, e->>3, e->>4, (e->>5)::boolean, (e->>6)::int, e->7, 'internal_research', 'draft',
       (select id from occumed_core.source_documents where source_key='insight_hub_relevance_vocabulary_20261003'), e->>9, nullif(e->>10,''),
       array(select jsonb_array_elements_text(e->8))
from jsonb_array_elements($j$[["rv_soft_informational_wording","notice_type","Informational wording without a procurement signal","Articles, blogs, webinars, definitions and how-to pages are informational content. When the notice also carries no procurement signal, lower its relevance (soft penalty, not a rejection).","penalize_informational_notice",false,60,{"applies_to":["opportunity_research","rfp_search"],"match":"any_trigger","unless":"procurement_signal_present","penalty":12},["news","press release","blog","article","webinar","podcast","definition","what is","how to","guide to","overview of"],"relevance.ts.SOFT_PENALTY_TERMS","Carried from code unchanged (terms and penalty 12)."],["rv_soft_job_title_wording","notice_type","Job-title wording in the title without a procurement signal","A title that reads like a job title (nurse, technician, coordinator, assistant, director, manager) with no procurement signal is more likely a posting than a solicitation. Soft penalty, not a rejection.","penalize_job_title_wording",false,60,{"applies_to":["opportunity_research","rfp_search"],"match":"title_any_trigger","unless":"procurement_signal_present","penalty":30},["nurse","technician","coordinator","assistant","director","manager"],"relevance.ts job-title regex","Carried from code unchanged (terms and penalty 30)."],["rv_network_service_evidence","service_scope","Network/managed-delivery scope needs service evidence","A provider-network or program-management notice counts as Occu-Med scope only when it also contains evidence of an actual occupational-health service (and a medical title).","network_requires_service_evidence",false,60,{"applies_to":["opportunity_research","rfp_search"],"requires_one_of":["medical examination","surveillance","testing","occupational health","deployment","drug testing","physical"]},[],"relevance.ts pathD service-evidence list","Carried from code unchanged."]]$j$::jsonb) e;
commit;
