-- 006: commodity/raw-material rule redesign (DRAFT PROPOSAL, not approved). Updates the draft rule
-- rv_commodity_raw_material_supply in place (same rule_key, status unchanged): bare commodity words no longer reject;
-- the rule needs the commodity to be the PURCHASED SCOPE (purchase frame / unit / commodity wording with no workforce
-- or medical context), and a title that names an Occu-Med service is held for review, never hard-rejected.
begin;
update occumed_core.rules r
set title = e->>2, rule_text = e->>3, machine_action = e->>4, hard_rule = (e->>5)::boolean, priority = (e->>6)::int,
    scope = e->7, search_triggers = array(select jsonb_array_elements_text(e->8)), source_locator = e->>9, notes = nullif(e->>10,'')
from jsonb_array_elements($j$[["rv_commodity_raw_material_supply","service_scope","Commodity and raw-material procurement is not Occu-Med scope","A notice whose purchased scope is a commodity or raw material (fuel, metals, aggregate, grain, spare parts and similar) is not an Occu-Med service. A material name alone does not trigger the rule: it applies only when the material is tied to a purchase frame or unit (\"supply of diesel fuel\", \"gravel delivery per ton\"), or when the title is commodity wording with no workforce or medical context. A material that merely names the workplace of the workforce being served (\"Fuel Handler Medical Surveillance\", \"Steel Mill Employee Audiometry\") is not commodity procurement. A title that names an Occu-Med service is never hard-rejected; if it also buys a commodity (a purchase frame is present) it is held for review. Equipment-only purchases are covered by rv_cond_supplies_only.","reject_commodity_purchased_scope",true,88,{"applies_to":["opportunity_research","rfp_search"],"match":"title_commodity_scope","window_words":3,"purchase_frames":["supply","supplies","purchase","purchases","procurement","delivery","delivered","bulk","furnish","wholesale","fuel card","card program","fob","annual contract"],"unit_terms":["ton","tons","gallon","gallons","barrel","barrels","pound","pounds","cubic yard","cubic yards","bushel","bushels"],"context_terms":["handler","handlers","worker","workers","operator","operators"],"mixed_scope_penalty":40,"rescued_by":"title_contains_service_term (held for review when a purchase frame is also present)"},["raw material","raw materials","bulk commodity","commodity purchase","steel","aluminum","copper","lumber","fuel","diesel","gasoline","asphalt","gravel","aggregate","cement","fertilizer","grain","resin","scrap metal","spare parts","replacement parts","pipe and fittings","jet fuel","propane","natural gas","concrete","rebar","sand","road salt","coal"],"relevance.ts commodity rule redesign","Replaces the title-only bare-word trigger list of the draft rule (22 terms). NOT FINAL: trigger terms, frames, units, context terms and the mixed-scope penalty await owner approval. The last 8 triggers (jet fuel .. coal) are proposed additions."]]$j$::jsonb) e
where r.rule_key = e->>0 and r.rule_key like 'rv\_%';
-- expected: exactly 1 row updated
commit;
