-- 009: agency targeting restored as SEARCH-PRIORITY metadata (approved 2026-10-04).
-- Not relevance: the classifier and the accept/review/reject decision never read these facts. They are used only for
-- provider request filters and result ordering. (agencies_forecast_focus from 004 already holds the Tango agency codes.)
begin;
insert into occumed_core.facts (fact_key,subject_entity_id,category,predicate,value_text,value_json,value_numeric,authority_level,status,confidence,source_id,source_locator,notes)
select e->>0, 1, e->>1, e->>2, e->>3, nullif(e->4,'null'::jsonb), nullif(e->>5,'')::numeric, 'internal_research', 'draft', 0.8,
       (select id from occumed_core.source_documents where source_key='insight_hub_relevance_vocabulary_20261003'), e->>6, nullif(e->>7,'')
from jsonb_array_elements($j$[["agency_usaspending_awarding_filter","target_agency","usaspending_awarding_filter","USAspending awarding-agency request filter",{"names":["Department of Defense","Department of Homeland Security","Department of State","Department of Justice","Department of Health and Human Services"],"effect":"request_filter_only","relevance_effect":"none"},null,"federal-intel.ts USAspending request (legacy)","Search/request filter only. Not a relevance input."],["agency_search_priority_terms","target_agency","search_priority_terms","Agencies to prefer when ordering search work and results",{"terms":["department of defense","department of the army","department of the navy","department of the air force","defense health agency","department of veterans affairs","veterans affairs","department of homeland security","homeland security","department of labor","occupational safety and health administration","occupational safety","centers for disease control","health resources and services administration","department of state","department of justice","department of health and human services","cdc","hrsa","osha","dhs","dod","hhs","opm","bop","cbp","uscis","fmcsa","faa"],"effect":"search_priority_only","relevance_effect":"none","match":"whole_word"},null,"usaJobsIntelligence PRIORITY_AGENCY_PATTERN; intelligence-feed priorityAgency; federal-intel agency tokens (legacy)","Search-priority metadata. Replaces the legacy agency score boosts: it orders results, it never changes a relevance score or verdict."]]$j$::jsonb) e
where not exists (select 1 from occumed_core.facts f where f.fact_key = e->>0);
-- expected: 2 rows inserted (0 if re-run)
commit;
