/**
 * TEST FIXTURE ONLY. Publishes the Neon profile reconstructed from the checksum-verified migration files
 * (docs/neon-profile/regression/rows.json, generated by build_rows.py) as the relevance profile, so classifier
 * tests run against the same rows Neon holds after activation. Nothing outside tests imports this; the application
 * has no embedded profile (it loads from Neon, then the verified cache, else fails closed).
 *
 * Importing this module installs the fixture profile for the importing test process.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildProfile, setRelevanceProfile, type ProfileRows } from "../../relevanceProfile";

const here = path.dirname(fileURLToPath(import.meta.url));
export const FIXTURE_ROWS_PATH = path.resolve(here, "../../../../../../docs/neon-profile/regression/rows.json");

export function loadFixtureRows(): ProfileRows {
  return JSON.parse(fs.readFileSync(FIXTURE_ROWS_PATH, "utf8")) as ProfileRows;
}

export function installFixtureProfile(): void {
  const result = setRelevanceProfile(buildProfile(loadFixtureRows(), "neon"));
  if (!result.applied) throw new Error(`Fixture profile incomplete: ${result.missing.join(", ")}`);
}

/** A fresh fixture profile object (not published). */
export function fixtureProfile() {
  return buildProfile(loadFixtureRows(), "neon");
}

installFixtureProfile();
