import { Router, type IRouter } from "express";
import { resolveCredential } from "../lib/config/providerConfig";
import { keenableProvider } from "../lib/providers/keenable";
const router: IRouter = Router();
type Article = { id:string; title:string; url:string; snippet:string; publisher:string|null; publishedAt:string|null; provider:"tinyfish"|"keenable" };
function validUrl(value: unknown): string | null { try { const u=new URL(String(value)); return /^https?:$/.test(u.protocol) ? u.href : null; } catch { return null; } }
function normalize(value: unknown, provider: Article["provider"]): Article|null { const r=(value&&typeof value==='object'?value:{}) as Record<string,unknown>; const url=validUrl(r.url); const title=typeof r.title==='string'?r.title.trim():''; if(!url||!title)return null; return {id:`${provider}:${url}`,title,url,snippet:typeof r.snippet==='string'?r.snippet:(typeof r.description==='string'?r.description:''),publisher:typeof r.publisher==='string'?r.publisher:(typeof r.site_name==='string'?r.site_name:null),publishedAt:typeof r.date==='string'?r.date:(typeof r.publishedAt==='string'?r.publishedAt:null),provider}; }
async function tinyfish(query:string):Promise<Article[]> { const key=await resolveCredential('tinyfishApiKey','TINYFISH_API_KEY'); if(!key)return []; const u=new URL('https://api.search.tinyfish.ai'); u.searchParams.set('query',query); u.searchParams.set('domain_type','news'); u.searchParams.set('language','en'); u.searchParams.set('location','US'); u.searchParams.set('recency_minutes','10080'); const response=await fetch(u,{headers:{'X-API-Key':key,'Accept':'application/json'}}); if(!response.ok)throw new Error(`TinyFish returned HTTP ${response.status}`); const data=await response.json() as {results?:unknown[]}; return (data.results??[]).map(v=>normalize(v,'tinyfish')).filter((v):v is Article=>Boolean(v)); }
async function keen(query:string):Promise<Article[]> { const rows=await keenableProvider.search(`${query} latest news contracts spending acquisition workforce`,{publishedAfter:new Date(Date.now()-7*86400000).toISOString()}); return rows.map(v=>normalize(v,'keenable')).filter((v):v is Article=>Boolean(v)); }
router.post('/company-watch/search',async(req,res)=>{ const companies=Array.isArray(req.body?.companies)?req.body.companies.filter((v:unknown)=>typeof v==='string').map((v:string)=>v.trim()).filter(Boolean).slice(0,100):[]; if(!companies.length)return res.status(400).json({error:'Add at least one company.'}); const query=companies.map((v:string)=>`"${v.replace(/"/g,'')}"`).join(' OR ')+' (contract OR award OR spending OR acquisition OR expansion OR workforce OR facility OR aerospace OR defense)'; const settled=await Promise.allSettled([tinyfish(query),keen(query)]); const articles=settled.flatMap(r=>r.status==='fulfilled'?r.value:[]); const warnings=settled.filter((r):r is PromiseRejectedResult=>r.status==='rejected').map(()=> 'Company news provider temporarily unavailable.'); const unique=[...new Map(articles.map(a=>[a.url,a])).values()].sort((a,b)=>(Date.parse(b.publishedAt??'')||0)-(Date.parse(a.publishedAt??'')||0)); res.json({articles:unique.slice(0,100),companies,updatedAt:new Date().toISOString(),warnings}); });
export default router;
