import { Router, type IRouter } from "express";
import healthRouter from "./health";
import opportunitySummaryRouter from "./opportunity-summary-v2";
import ingestionDiagnosticsRouter from "./ingestion-diagnostics";
import opportunitySafetyBoundaryRouter from "./opportunity-safety-boundary";
import opportunitiesRouter from "./opportunities";
import opportunityFeedbackRouter from "./opportunity-feedback";
import settingsRouter from "./settings";
import providersRouter from "./providers";
import rfpSourcesRouter from "./rfp-sources";
import crawlerAdminRouter from "./crawler-admin";
import competitorsRouter from "./competitors";
import prospectsRouter from "./prospects";
import prospectLocationsRouter from "./prospect-locations";
import prospectContactsRouter from "./prospect-contacts";
import clientsRouter from "./clients";
import clientContactsRouter from "./client-contacts";
import federalIntelRouter from "./federal-intel";
import stateAgenciesRouter from "./state-agencies";
import intelligenceFeedRouter from "./intelligence-feed";
import searchRouter from "./search";
import rfpProviderBoundaryRouter from "../middleware/rfp-provider-boundary";
import manualOnlyPortalHealthBoundaryRouter from "../middleware/manual-only-portal-health-boundary";

const router: IRouter = Router();

router.use(healthRouter);
router.use(opportunitySummaryRouter);
router.use(rfpProviderBoundaryRouter);
router.use(ingestionDiagnosticsRouter);
router.use(opportunitySafetyBoundaryRouter);
router.use(opportunitiesRouter);
router.use(opportunityFeedbackRouter);
router.use(settingsRouter);
router.use(providersRouter);
router.use(manualOnlyPortalHealthBoundaryRouter);
router.use(rfpSourcesRouter);
router.use(crawlerAdminRouter);
router.use(competitorsRouter);
router.use(prospectsRouter);
router.use(prospectLocationsRouter);
router.use(prospectContactsRouter);
router.use(clientsRouter);
router.use(clientContactsRouter);
router.use(federalIntelRouter);
router.use(stateAgenciesRouter);
router.use(intelligenceFeedRouter);
router.use(searchRouter);

export default router;
