import { useEffect, useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Clock3, ExternalLink, Minus, Plus, RefreshCcw, Search, X } from "lucide-react";

type Company={name:string; logo?:string}; type Article={id:string;title:string;url:string;snippet:string;publisher:string|null;publishedAt:string|null;provider:string};
const SEED=['Leidos','IAP Worldwide Services','MAG Aerospace','Camber Corporation','Trace Systems','KBR','BAE Systems','Weatherford International','Versar','Constellis','C3EL','Fluor Corporation','Clovehitch','V2X','Sierra Nevada Corporation','Valiant Integrated Services','AC Transit','Freeport-McMoRan','California Department of Corrections and Rehabilitation','Alutiiq','ManTech International','GDC','CACI International','IDS International','SOS International','ITC Defense','DataPath','SkyBridge Tactical','Amentum','American International Contractors','Anduril','APVI','ASRC Federal','Astrapi Advisors','Atlas Advisors','Bell Textron','BL Harbert International','CDAS','Dynamic Aviation','Fathom 4','GardaWorld','General Dynamics Information Technology','Group SSI','IAP','International SOS','Jacobs Technology','Leidos','Navmar Applied Science Corporation','Noblis','Olgoonik Solutions','Patriot Group International','Peraton','Platform Aerospace','Prüst Holding','S3 International','Strategic Solutions Unlimited','University of Maryland Global Campus','Vectrus','Versar Global Solutions','Westinghouse Electric Company'];
const key='insight-hub.company-watch.companies'; const timesKey='insight-hub.company-watch.times';
function unique(names:string[]){return [...new Map(names.map(n=>[n.trim().toLowerCase(),n.trim()])).values()].filter(Boolean)}
function ago(v:string|null){if(!v)return 'Date unavailable'; const d=new Date(v); return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(d)}
export default function CompanyWatchPage(){
 const [companies,setCompanies]=useState<Company[]>(()=>{try{return unique(JSON.parse(localStorage.getItem(key)||'[]')).map(name=>({name})).length?unique(JSON.parse(localStorage.getItem(key)||'[]')).map(name=>({name})):unique(SEED).map(name=>({name}))}catch{return SEED.map(name=>({name}))}});
 const [add,setAdd]=useState(''); const [selected,setSelected]=useState<Company|null>(null); const [articles,setArticles]=useState<Article[]>([]); const [updated,setUpdated]=useState<string|null>(null); const [times,setTimes]=useState(()=>{try{return JSON.parse(localStorage.getItem(timesKey)||'["08:00","16:00"]')}catch{return ['08:00','16:00']}}); const [auto,setAuto]=useState(true);
 useEffect(()=>localStorage.setItem(key,JSON.stringify(companies.map(c=>c.name))),[companies]); useEffect(()=>localStorage.setItem(timesKey,JSON.stringify(times)),[times]);
 const mutation=useMutation({mutationFn:async()=>{const r=await fetch('/api/company-watch/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companies:companies.map(c=>c.name)})}); const j=await r.json(); if(!r.ok)throw new Error(j.error||'Search failed'); return j as {articles:Article[];updatedAt:string}},onSuccess:j=>{setArticles(j.articles);setUpdated(j.updatedAt)}});
 useEffect(()=>{if(!auto)return; const tick=()=>{const now=new Date(); const t=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`; if(times.includes(t)&&now.getSeconds()<10&&!mutation.isPending)mutation.mutate()}; const id=window.setInterval(tick,10000); return()=>clearInterval(id)},[auto,times,mutation]);
 const addCompany=()=>{const names=unique([...companies.map(c=>c.name),add]); if(add.trim())setCompanies(names.map(name=>({name})));setAdd('')}; const remove=(name:string)=>setCompanies(companies.filter(c=>c.name!==name));
 const matching=(name:string)=>articles.filter(a=>`${a.title} ${a.snippet}`.toLowerCase().includes(name.toLowerCase().split(' ')[0]));
 return <div className="space-y-7"><header><p className="mb-2 text-xs font-semibold uppercase tracking-[0.24em] text-primary/70">Company Intelligence</p><h1 className="text-4xl font-bold tracking-tight text-white md:text-5xl">Company Watch</h1><p className="mt-3 max-w-3xl text-base leading-relaxed text-white/50">Track contractor activity, awards, acquisitions, spending, facilities, and workforce news for the companies you choose.</p></header>
 <section className="glass-card rounded-2xl border border-white/10 p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row"><div className="flex min-w-0 flex-1 gap-2"><input aria-label="Add a company" value={add} onChange={e=>setAdd(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addCompany()} placeholder="Add a company to watch…" className="min-h-11 min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 text-sm text-white outline-none focus:border-primary/50"/><button onClick={addCompany} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Add</button></div><button onClick={()=>mutation.mutate()} disabled={mutation.isPending||!companies.length} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-primary/30 bg-primary/10 px-4 text-sm text-primary hover:bg-primary/20 disabled:opacity-50"><Search className="h-4 w-4"/>{mutation.isPending?'Searching…':'Search for Updates'}</button></div>
 <div className="mt-4 flex flex-wrap items-center gap-3 border-t border-white/10 pt-4 text-xs text-white/55"><Clock3 className="h-4 w-4 text-primary"/><span>Automatic searches</span>{times.map((t,i)=><label key={i} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-2 py-1.5">{i+1}<input type="time" value={t} onChange={e=>setTimes(times.map((x,j)=>j===i?e.target.value:x))} className="bg-transparent text-white"/></label>)}<label className="ml-auto inline-flex items-center gap-2"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> enabled</label></div></section>
 <div className="flex items-center justify-between gap-3 text-sm text-white/45"><span>{companies.length} companies watched{updated&&` · last search ${ago(updated)}`}</span><button onClick={()=>setCompanies([])} className="text-red-200/60 hover:text-red-100">Remove all</button></div>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{companies.map(c=>{const count=matching(c.name).length; return <article key={c.name} className="glass-card group relative overflow-hidden rounded-2xl border border-white/10 p-5 transition hover:border-primary/40"><button aria-label={`Remove ${c.name}`} onClick={()=>remove(c.name)} className="absolute right-3 top-3 rounded-full p-1 text-white/30 hover:bg-red-400/10 hover:text-red-200"><X className="h-4 w-4"/></button><button onClick={()=>setSelected(c)} className="block w-full text-left"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-xl border border-white/10 bg-white/10 text-sm font-bold text-primary">{c.name.slice(0,2).toUpperCase()}</div><div className="min-w-0 pr-6"><h2 className="ui-break-anywhere text-lg font-semibold text-white">{c.name}</h2><p className="mt-1 text-xs text-white/40">{updated?'Updated '+ago(updated):'Ready to search'}</p></div></div><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-3 text-xs"><span className={count?'text-primary':'text-white/45'}>{count?`${count} relevant update${count===1?'':'s'}`:'No updates loaded'}</span><span className="text-primary/70">Open window →</span></div></button></article>})}</section>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="max-h-[85dvh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/20 bg-[#102c59]/90 p-6 shadow-2xl backdrop-blur-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-primary/80">Company update window</p><h2 className="mt-2 text-3xl font-bold text-white">{selected.name}</h2><p className="mt-2 text-sm text-white/45">{updated?`Last updated ${ago(updated)}`:'Run Search for Updates to load current coverage.'}</p></div><button onClick={()=>setSelected(null)} className="rounded-full border border-white/10 p-2 text-white/60 hover:text-white"><X className="h-5 w-5"/></button></div><div className="mt-6 space-y-3">{matching(selected.name).map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer" className="block rounded-2xl border border-white/10 bg-black/15 p-4 transition hover:border-primary/40"><div className="flex items-center justify-between gap-3 text-xs uppercase tracking-wider text-white/35"><span>{a.publisher||a.provider}</span><span>{ago(a.publishedAt)}</span></div><h3 className="mt-2 text-lg font-semibold text-white">{a.title}</h3>{a.snippet&&<p className="mt-2 text-sm leading-relaxed text-white/55">{a.snippet}</p>}<span className="mt-3 inline-flex items-center gap-1 text-xs text-primary">Read source <ExternalLink className="h-3 w-3"/></span></a>)}{!matching(selected.name).length&&<div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-white/45">No relevant updates loaded for this company yet.</div>}</div></div></div>}
 </div>
}
