import { cloudflareWorkersAi } from "../providers/cloudflareWorkersAi";
import { geminiEmbeddingProvider } from "../providers/geminiEmbeddings";
import { jinaProvider } from "../providers/jina";
import { voyageProvider } from "../providers/voyage";
import { huggingFaceProvider } from "../providers/huggingFace";

export type EmbeddingInputType = "query" | "document";
export type EmbeddingProviderName =
  | "cloudflare"
  | "gemini"
  | "jina"
  | "voyage"
  | "huggingFace";

export interface EmbeddingResult {
  provider: EmbeddingProviderName;
  vectors: number[][];
  /** Errors from providers that were tried but failed (for diagnostics). */
  errors?: string[];
}

function validVectors(
  vectors: number[][] | null,
  expectedLength: number,
): vectors is number[][] {
  return (
    !!vectors &&
    vectors.length === expectedLength &&
    vectors.every(
      (vector) =>
        Array.isArray(vector) &&
        vector.length > 0 &&
        vector.every((value) => Number.isFinite(value)),
    )
  );
}

async function tryProvider(
  provider: EmbeddingProviderName,
  texts: string[],
  inputType: EmbeddingInputType,
): Promise<number[][] | null> {
  switch (provider) {
    case "cloudflare":
      return (await cloudflareWorkersAi.isConfigured())
        ? cloudflareWorkersAi.embed(texts)
        : null;
    case "gemini":
      return (await geminiEmbeddingProvider.isConfigured())
        ? geminiEmbeddingProvider.embed(texts, inputType)
        : null;
    case "jina": {
      if (!(await jinaProvider.isConfigured())) return null;
      const task =
        inputType === "query" ? "retrieval.query" : "retrieval.passage";
      return jinaProvider.embed(texts, task);
    }
    case "voyage":
      return (await voyageProvider.isConfigured())
        ? voyageProvider.embed(texts, inputType)
        : null;
    case "huggingFace":
      return (await huggingFaceProvider.isConfigured())
        ? huggingFaceProvider.embed(texts)
        : null;
  }
}

/**
 * Semantic provider order:
 *   1. Cloudflare Workers AI — primary high-volume embedding layer.
 *   2. Gemini — semantic fallback using the already configured Gemini key.
 *   3. Existing Jina/Voyage/Hugging Face providers — tertiary continuity.
 *
 * `preferredProvider` pins query and document embeddings to the same model
 * space. Vectors generated by different providers are never compared.
 */
export async function embedTexts(
  texts: string[],
  inputType: EmbeddingInputType = "document",
  preferredProvider?: EmbeddingProviderName,
): Promise<EmbeddingResult | null> {
  if (texts.length === 0) return null;
  const normalized = texts.map((text) => text.slice(0, 16_000));
  const errors: string[] = [];
  const order: EmbeddingProviderName[] = preferredProvider
    ? [preferredProvider]
    : ["cloudflare", "gemini", "jina", "voyage", "huggingFace"];

  for (const provider of order) {
    try {
      const vectors = await tryProvider(provider, normalized, inputType);
      if (validVectors(vectors, texts.length)) {
        return { provider, vectors, errors };
      }
      errors.push(`${provider}: unavailable or returned invalid vectors`);
    } catch (error) {
      errors.push(
        `${provider}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  console.warn(`[embedTexts] All embedding providers failed: ${errors.join("; ")}`);
  return null;
}
