export type MatchMode = "phrase" | "word" | "acronym";

export interface ProcurementTermGroup {
  id: string;
  label: string;
  phrases: string[];
  aliases?: string[];
  weight: number;
  matchMode?: MatchMode;
}
export interface OccuMedServiceCategory {
  id: string;
  label: string;
  explicitPhrases: string[];
  componentTerms: string[];
  supportingTerms?: string[];
  regulatoryTerms?: string[];
  highIntentPhrases?: string[];
  adjacentOnly?: boolean;
}
export interface SearchQueryBundle {
  id: string;
  label: string;
  serviceTerms: string[];
  workforceTerms?: string[];
  procurementTerms: string[];
  exclusions?: string[];
}
export interface BuyerSectorSignal {
  id: string;
  label: string;
  phrases: string[];
  propensity: "high" | "medium";
}

export const PROCUREMENT_TERM_GROUPS: ProcurementTermGroup[] = [
  {
    id: "procurement_stage",
    label: "Procurement-stage language",
    weight: 18,
    phrases: [
      "request for proposal",
      "RFP",
      "request for proposals",
      "request for quote",
      "RFQ",
      "request for quotation",
      "request for information",
      "RFI",
      "invitation to bid",
      "ITB",
      "invitation for bid",
      "IFB",
      "invitation to quote",
      "ITQ",
      "sources sought",
      "sources sought notice",
      "presolicitation",
      "presolicitation notice",
      "pre-solicitation",
      "special notice",
      "combined synopsis/solicitation",
      "solicitation",
      "bid solicitation",
      "open bid",
      "competitive bid",
      "request for responses",
      "professional services solicitation",
      "tender",
      "contract opportunity",
      "subcontracting opportunity",
      "teaming opportunity",
      "procurement forecast",
      "acquisition forecast",
      "recompetition",
      "recompete",
      "renewal solicitation",
      "blanket purchase agreement",
      "BPA",
      "indefinite delivery indefinite quantity",
      "IDIQ",
      "task order",
      "multiple-award contract",
      "framework agreement",
      "multi-supplier framework",
      "statement of work",
      "SOW",
      "performance work statement",
      "PWS",
      "scope of work",
      "scope of services",
      "technical specifications",
      "proposals due",
      "quotes due",
      "responses due",
      "bid opening",
      "closing date",
      "due date",
      "procurement",
      "bid opportunity",
      "vendor onboarding",
      "provider agreement",
      "supplier registration",
    ],
  },
];

export const SERVICE_CATEGORIES: OccuMedServiceCategory[] = [
  {
    id: "occupational_employee_medical",
    label: "Occupational / employee medical services",
    explicitPhrases: [
      "occupational health services",
      "employee occupational health services",
      "employee health services",
      "occupational medicine services",
      "occupational medical services",
      "occupational health and medical services",
      "occupational health examinations",
      "occupational medical examinations",
      "occupational medical examination services",
      "employment medical evaluation services",
      "employment medical examination services",
      "medical evaluations and services",
      "medical examination services",
      "workforce medical services",
      "occupational health program",
      "employee medical services",
      "health screening services",
      "medical screening services",
      "clinical and occupational health services",
      "occupational health physician services",
      "physician clinical laboratory services",
      "onsite occupational health services",
      "on-site occupational health services",
      "onsite medical services",
      "enterprise health unit services",
      "comprehensive occupational health services",
    ],
    componentTerms: [
      "occupational health",
      "occupational medicine",
      "occupational medical",
      "employee health",
      "workforce health",
      "onsite clinic",
      "onsite medical",
      "clinical services",
    ],
  },
  {
    id: "pre_employment_exams",
    label: "Pre-employment / post-offer / pre-placement examinations",
    explicitPhrases: [
      "pre-employment physical",
      "pre-employment physical examination",
      "pre employment physical",
      "pre employment medical examination",
      "pre-employment medical evaluation",
      "employment physical examination",
      "employment physicals",
      "post-offer physical",
      "post offer physical",
      "post-offer medical examination",
      "post employment offer physical",
      "pre-placement physical",
      "pre placement physical",
      "pre-placement medical examination",
      "pre-placement medical evaluation",
      "pre-hire physical",
      "new-hire physical",
      "applicant medical examination",
      "applicant medical evaluation",
      "candidate medical examination",
      "candidate medical evaluation",
      "prospective employee examination",
      "continued-employment physical",
      "annual employee physical",
      "biennial employee physical",
      "periodic employee physical",
      "job-specific medical examination",
      "position-specific medical examination",
      "role-specific medical examination",
      "job-related medical examination",
    ],
    componentTerms: [
      "physical examination",
      "physicals",
      "medical evaluation",
      "medical examination",
      "health assessment",
      "TB testing",
      "tuberculosis screening",
    ],
  },
  {
    id: "medical_suitability",
    label: "Medical suitability / job compatibility / exam review",
    explicitPhrases: [
      "medical suitability",
      "medical suitability determination",
      "medical qualification",
      "medical fitness",
      "fitness determination",
      "medical fitness determination",
      "placement determination",
      "medical placement recommendation",
      "ability to perform required duties",
      "ability to safely perform",
      "ability to physically perform required duties",
      "essential job functions",
      "job-specific examination",
      "job-related assessment",
      "legally defensible medical evaluation",
      "defensible placement recommendation",
      "medical clearance determination",
      "exam quality review",
      "EXAMQA",
    ],
    componentTerms: [
      "medically capable",
      "physically capable",
      "essential training functions",
      "essential functions",
      "physical demands",
      "environmental conditions",
      "job description",
      "job classification",
      "job specification",
      "functional requirements",
      "work restrictions",
      "restriction determination",
      "reasonable accommodation",
      "accommodation assessment",
      "accommodation documentation",
      "examination protocol",
      "medical screening guidelines",
      "classification methodology",
      "physician review",
      "medical determination",
      "report of findings",
      "written results summary",
      "quality review",
      "quality assurance review",
    ],
  },
  {
    id: "fitness_return_work",
    label: "Fitness-for-duty / return-to-work / work capacity",
    explicitPhrases: [
      "fitness for duty",
      "fitness-for-duty",
      "fit for duty",
      "fit-for-duty",
      "return to work",
      "return-to-work",
      "return to duty",
      "return-to-duty",
      "medical clearance to return",
      "work capacity evaluation",
      "functional capacity evaluation",
      "physical capacity evaluation",
      "physical ability test",
      "physical abilities testing",
      "post-offer employment test",
      "job functional analysis",
      "job demands analysis",
    ],
    componentTerms: [
      "work readiness",
      "duty status",
      "duty-status determination",
      "release to work",
      "full-duty release",
      "modified-duty determination",
      "temporary restrictions",
      "permanent restrictions",
      "functional limitations",
      "existing-employee medical evaluation",
      "performance and safety concerns",
      "FCE",
      "POET",
      "ergonomic assessment",
      "ergonomic evaluation",
    ],
  },
  {
    id: "medical_surveillance",
    label: "Medical surveillance / exposure programs",
    explicitPhrases: [
      "medical surveillance",
      "occupational medical surveillance",
      "occupational health surveillance",
      "employee health surveillance",
      "medical monitoring",
      "periodic medical monitoring",
      "surveillance examination",
      "surveillance exams",
      "exposure-related examination",
      "exposure-specific examination",
      "regulated-exposure examination",
      "hazard-specific examination",
      "medical surveillance program",
      "OSHA medical surveillance",
      "Cal-OSHA medical surveillance",
    ],
    componentTerms: [
      "health monitoring",
      "baseline surveillance",
      "annual surveillance",
      "periodic surveillance",
      "surveillance screenings",
      "biological monitoring",
      "occupational exposure evaluation",
      "employee exposure monitoring",
      "regulated exposure",
      "hazardous exposure",
      "toxic and hazardous substances",
      "lead surveillance",
      "blood lead testing",
      "blood lead level",
      "asbestos medical surveillance",
      "asbestos examination",
      "cadmium surveillance",
      "benzene surveillance",
      "formaldehyde surveillance",
      "silica medical surveillance",
      "hexavalent chromium surveillance",
      "beryllium medical surveillance",
      "methylene chloride surveillance",
      "ethylene oxide surveillance",
      "cotton dust surveillance",
      "heavy metals testing",
      "hazardous materials worker examination",
      "HAZMAT examination",
      "HAZWOPER medical examination",
      "bloodborne pathogen exposure",
      "communicable-disease exposure",
      "radiation medical surveillance",
      "occupational noise exposure",
    ],
    regulatoryTerms: [
      "OSHA",
      "Cal-OSHA",
      "lead",
      "asbestos",
      "silica",
      "cadmium",
      "benzene",
      "hexavalent chromium",
      "HAZWOPER",
    ],
  },
  {
    id: "respiratory_fit_testing",
    label: "Respiratory protection / fit testing",
    explicitPhrases: [
      "respiratory protection program",
      "respirator medical evaluation",
      "respirator medical clearance",
      "respirator clearance examination",
      "respirator fit testing",
      "respiratory fit testing",
      "qualitative fit testing",
      "quantitative fit testing",
      "qualitative fit test",
      "quantitative fit test",
    ],
    componentTerms: [
      "respirator clearance",
      "respiratory clearance",
      "pulmonary clearance",
      "respirator questionnaire",
      "OSHA respirator questionnaire",
      "respirator medical questionnaire",
      "PLHCP review",
      "physician or other licensed health care professional",
      "QLFT",
      "QNFT",
      "fit factor",
      "tight-fitting respirator",
      "SCBA",
      "self-contained breathing apparatus",
      "PAPR",
      "powered air-purifying respirator",
      "supplied-air respirator",
      "pulmonary function testing",
      "spirometry",
      "PFT",
    ],
    regulatoryTerms: ["OSHA", "PLHCP", "SCBA", "PAPR"],
  },
  {
    id: "hearing_audiometry",
    label: "Hearing conservation / audiometry",
    explicitPhrases: [
      "hearing conservation program",
      "occupational hearing conservation",
      "audiometric testing program",
      "audiometric examination",
      "audiometric testing",
      "baseline audiogram",
      "annual audiogram",
      "periodic audiogram",
      "mobile audiometric testing",
    ],
    componentTerms: [
      "audiogram",
      "audiograms",
      "mobile audiograms",
      "mobile test van",
      "audiometer calibration",
      "problem audiogram",
      "audiological review",
      "standard threshold shift",
      "STS",
      "hearing threshold examination",
      "pure-tone audiometry",
      "CAOHC technician",
      "hearing testing",
      "hearing screening",
      "hearing acuity",
    ],
  },
  {
    id: "drug_alcohol",
    label: "Drug / alcohol testing and program administration",
    explicitPhrases: [
      "drug testing services",
      "drug screening services",
      "drug and alcohol testing services",
      "controlled-substance testing",
      "substance-abuse testing",
      "workplace drug testing",
      "employment drug screening",
      "pre-employment drug testing",
      "post-offer drug screening",
      "DOT drug testing",
      "non-DOT drug testing",
      "DOT/non-DOT testing",
      "random drug testing",
      "random alcohol testing",
      "post-accident testing",
      "reasonable-suspicion testing",
      "reasonable-cause testing",
      "return-to-duty testing",
      "follow-up testing",
      "pre-duty testing",
    ],
    componentTerms: [
      "specimen collection",
      "urine specimen collection",
      "oral-fluid collection",
      "oral fluid collection",
      "urine collection",
      "collection site",
      "collection-site services",
      "mobile collection",
      "onsite collection",
      "on-site collection",
      "after-hours collection",
      "observed collection",
      "split-specimen collection",
      "breath-alcohol testing",
      "breath alcohol testing",
      "alcohol screening test",
      "alcohol confirmation test",
      "saliva screening",
      "five-panel drug test",
      "5-panel drug screen",
      "nine-panel drug test",
      "10-panel drug test",
      "rapid drug screen",
      "non-rapid drug screen",
      "laboratory confirmation",
      "confirmation testing",
      "confirmation processing",
      "urinalysis",
      "Medical Review Officer",
      "MRO",
      "Medical Review Director",
      "Breath Alcohol Technician",
      "BAT",
      "Screening Test Technician",
      "STT",
      "Substance Abuse Professional",
      "SAP",
      "Designated Employer Representative",
      "DER",
      "Consortium/Third-Party Administrator",
      "C/TPA",
      "third-party administrator",
      "service agent",
      "urine collector",
      "oral-fluid collector",
      "SAMHSA-certified laboratory",
      "HHS-certified laboratory",
      "certified drug-testing laboratory",
      "chain of custody",
      "custody and control form",
      "CCF",
      "electronic CCF",
      "eCCF",
      "testing pool",
      "random selection",
      "MIS reporting",
      "result verification",
      "non-negative result",
      "dilute specimen",
      "refusal to test",
      "cancelled test",
      "DOT Part 40",
      "49 CFR Part 40",
    ],
    regulatoryTerms: ["DOT", "DOT Part 40", "49 CFR Part 40", "SAMHSA", "HHS"],
  },
  {
    id: "public_safety_medical",
    label: "Public-safety medical services",
    explicitPhrases: [
      "law enforcement medical screening",
      "law enforcement medical examination",
      "police officer medical examination",
      "police medical examination",
      "police medical screening",
      "P.O.S.T. medical examination",
      "POST medical",
      "peace officer medical examination",
      "sheriff medical examination",
      "sheriff medical screening",
      "deputy sheriff medical examination",
      "protective service medical examination",
      "public safety physical",
      "public safety medical services",
      "firefighter medical examination",
      "firefighter physical",
      "fire service medical examination",
      "fire and rescue occupational health services",
      "NFPA 1582 examination",
      "NFPA 1582 physical",
      "annual firefighter physical",
      "firefighter fitness-for-duty",
      "firefighter medical surveillance",
      "SCBA medical clearance",
      "firefighter respirator clearance",
      "firefighter cardiac stress testing",
      "EMS medical evaluation",
      "EMT medical evaluation",
      "paramedic medical evaluation",
      "emergency medical personnel evaluation",
      "first-responder medical evaluation",
      "first responder medical",
      "correctional officer medical examination",
      "juvenile justice officer examination",
      "commercial driver medical examination",
      "CDL medical examination",
      "DMV Class A driver examination",
      "DMV Class B driver examination",
      "DOT physical",
      "DOT medical examination",
      "FMCSA physical",
    ],
    componentTerms: [
      "criminal justice certified applicant",
      "protective service division",
      "safety and emergency personnel examination",
      "medical qualification standards",
      "medical screening guide",
      "NFPA medical guidelines",
      "safety-sensitive position",
      "safety-sensitive role",
      "safety-sensitive workforce",
    ],
  },
  {
    id: "lab_diagnostic_components",
    label: "Laboratory / diagnostic / exam components",
    explicitPhrases: [
      "clinical laboratory services",
      "laboratory testing",
      "infectious-disease testing",
      "communicable-disease testing",
      "TB testing",
      "tuberculosis screening",
      "cardiac stress test",
      "exercise treadmill stress test",
    ],
    componentTerms: [
      "general physical examination",
      "medical history review",
      "health questionnaire",
      "vital signs",
      "blood pressure",
      "pulse",
      "respiration",
      "height and weight",
      "body mass index",
      "BMI",
      "visual acuity",
      "corrected vision",
      "uncorrected vision",
      "color vision",
      "depth perception",
      "peripheral vision",
      "Snellen",
      "vision testing",
      "vision screening",
      "hearing testing",
      "audiogram",
      "spirometry",
      "pulmonary function testing",
      "electrocardiogram",
      "EKG",
      "ECG",
      "exercise treadmill test",
      "treadmill stress test",
      "cardiovascular testing",
      "cardiac clearance",
      "chest X-ray",
      "chest radiograph",
      "CXR",
      "laboratory services",
      "lab work",
      "blood work",
      "CBC",
      "CMP",
      "urinalysis",
      "serology",
      "titers",
      "proof of immunity",
      "PPD",
      "TST",
      "IGRA",
      "QuantiFERON",
      "QFT-GIT",
      "T-SPOT",
      "musculoskeletal screening",
      "back screening",
      "knee screening",
    ],
  },
  {
    id: "immunizations_travel",
    label: "Immunizations / travel health",
    explicitPhrases: [
      "immunization services",
      "vaccination services",
      "employee vaccination",
      "workforce vaccination",
      "travel-health services",
      "travel medicine",
      "travel medical clearance",
      "deployment immunizations",
      "overseas immunizations",
      "vaccine administration",
      "onsite vaccination clinic",
      "mobile vaccination clinic",
      "flu clinic",
    ],
    componentTerms: [
      "immunizations",
      "vaccinations",
      "travel questionnaire",
      "location-specific immunizations",
      "proof of immunity",
      "immunity testing",
      "vaccine declination",
      "hepatitis A",
      "hepatitis B",
      "Heplisav",
      "Twinrix",
      "MMR",
      "measles",
      "mumps",
      "rubella",
      "varicella",
      "tetanus",
      "Tdap",
      "typhoid",
      "yellow fever",
      "rabies",
      "meningococcal",
      "pneumococcal",
      "polio",
      "Japanese encephalitis",
      "anthrax vaccine",
      "malaria prophylaxis",
      "cholera",
      "chikungunya",
      "mpox",
    ],
  },
  {
    id: "deployment_readiness",
    label: "Deployment / military / overseas medical readiness",
    explicitPhrases: [
      "deployment medical readiness",
      "medical readiness services",
      "deployment medical screening",
      "deployment physical",
      "pre-deployment examination",
      "pre-deployment medical",
      "pre-deployment health assessment",
      "post-deployment health assessment",
      "military medical screening",
      "military medical examination",
      "contractor deployment physical",
      "contractor personnel medical screening",
      "contractor employee medical screening",
      "medical screening and vaccination requirements",
      "medical qualification for deployment",
      "fit for deployment",
      "medically fit for deployment",
      "overseas medical clearance",
      "OCONUS medical clearance",
      "local nationals occupational health examinations",
    ],
    componentTerms: [
      "deployment readiness",
      "mission readiness",
      "global readiness",
      "PDHA",
      "dentally fit for deployment",
      "psychologically fit for deployment",
      "theater-specific medical requirements",
      "theater medical requirements",
      "CONUS and OCONUS",
      "international assignment medical",
      "foreign assignment medical",
      "expeditionary workforce",
      "deployed personnel",
      "local national employees",
      "host-nation employees",
      "DoD deployment requirements",
      "Department of Defense deployment",
      "Department of State medical requirements",
      "CENTCOM",
      "COCOM",
      "AOR",
      "area of responsibility",
      "medical readiness documentation",
      "dental readiness",
      "travel clearance",
      "deployment-limiting condition",
      "theater clearance",
      "waiver processing",
      "CENTCOM MOD",
      "MOD 18",
      "DD2795",
      "DD 2795",
      "DD2796",
      "DD 2796",
      "DD2807-1",
      "DD 2807-1",
      "DD2808",
      "DD 2808",
      "DD2813",
      "DD 2813",
    ],
    regulatoryTerms: [
      "CENTCOM",
      "DoD",
      "Department of Defense",
      "OCONUS",
      "CONUS",
      "MOD 18",
    ],
  },
  {
    id: "post_deployment_support",
    label: "Post-deployment / reintegration / psychological support",
    explicitPhrases: [
      "post-deployment health assessment",
      "post deployment health assessment",
      "deployment-related health",
      "post-deployment diagnostic",
      "behavioral health screening",
    ],
    componentTerms: [
      "returning personnel",
      "bookend testing",
      "traumatic exposure",
      "traumatic stress",
      "psychological assessment",
      "psychological screening",
      "psychological support",
      "PTSD",
      "health incident review",
      "deployment health record",
      "Defense Base Act",
      "DBA benefits",
      "claims documentation",
      "duty of care",
    ],
  },
  {
    id: "network_program_management",
    label: "Provider network / program management / reporting",
    explicitPhrases: [
      "nationwide provider network",
      "nationwide clinic network",
      "private provider network",
      "patient physician network",
      "patient-physician network",
      "medical provider network",
      "occupational health network",
      "network of clinics",
      "network of medical providers",
      "network of clinics hospitals and urgent-care facilities",
      "multiple local medical providers",
      "mobile medical services",
      "medical program management",
    ],
    componentTerms: [
      "multiple locations",
      "multi-site workforce",
      "multisite workforce",
      "regional clinic coverage",
      "national coverage",
      "global coverage",
      "CONUS and OCONUS coverage",
      "fixed locations",
      "mobile services",
      "mobile testing",
      "mobile collection",
      "onsite services",
      "on-site services",
      "off-site services",
      "near-site clinic",
      "walk-in services",
      "appointment scheduling",
      "expedited scheduling",
      "timely appointments",
      "service availability",
      "after-hours response",
      "turnaround time",
      "results turnaround",
      "secure electronic transmission",
      "secure portal",
      "medical-record maintenance",
      "medical records management",
      "record retention",
      "program management",
      "project management",
      "medical oversight",
      "medical director",
      "contract administration",
      "utilization reporting",
      "service-volume reporting",
      "compliance tracking",
      "occupational health tracking system",
      "medical tracking system",
      "protocol development",
      "procedure manual",
      "quality assurance",
      "referral coordination",
      "provider coordination",
      "network coordination",
      "scheduling coordination",
      "exam coordination",
      "decision-ready reporting",
      "proposal writing",
      "on-site support",
      "onsite support",
    ],
  },
  {
    id: "adjacent_bundled",
    label: "Adjacent or bundled services",
    explicitPhrases: [],
    componentTerms: [
      "occupational injury care",
      "work-related injury treatment",
      "workers compensation",
      "workers’ compensation",
      "workers compensation case management",
      "nurse case management",
      "case management",
      "injury care",
      "injury triage",
      "wellness clinic",
      "employee wellness clinic",
      "clinical staffing",
      "health-unit staffing",
      "ergonomic assessment",
      "medical tracking software",
      "occupational health tracking system",
    ],
    adjacentOnly: true,
  },
];

export const WORKFORCE_SIGNALS = [
  "employee",
  "employees",
  "applicant",
  "applicants",
  "candidate",
  "candidates",
  "prospective employee",
  "new hire",
  "workforce",
  "personnel",
  "contractor personnel",
  "contractor employees",
  "local national employees",
  "safety-sensitive employees",
  "public safety employees",
  "police officers",
  "law enforcement officers",
  "deputy sheriffs",
  "firefighters",
  "emergency responders",
  "EMTs",
  "paramedics",
  "commercial drivers",
  "CDL drivers",
  "correctional officers",
  "juvenile justice employees",
  "healthcare workers",
  "public works employees",
  "utility workers",
  "field employees",
  "hazardous-materials workers",
  "respirator users",
  "noise-exposed employees",
  "regulated employees",
  "deployed personnel",
  "workplace",
  "employer",
];
export const DELIVERY_NETWORK_TERMS = SERVICE_CATEGORIES.find(
  (c) => c.id === "network_program_management",
)!.explicitPhrases.concat(
  SERVICE_CATEGORIES.find((c) => c.id === "network_program_management")!
    .componentTerms,
);
export const REGULATORY_STANDARDS_TERMS = Array.from(
  new Set(
    SERVICE_CATEGORIES.flatMap((c) => c.regulatoryTerms ?? []).concat([
      "NFPA 1582",
      "DOT Part 40",
      "49 CFR Part 40",
      "OSHA",
      "Cal-OSHA",
      "FMCSA",
      "SAMHSA",
      "HHS",
      "CENTCOM",
      "MOD 18",
    ]),
  ),
);
export const HARD_REJECT_TERMS = [
  "job posting",
  "job opening",
  "job opportunity",
  "jobs in",
  "now hiring",
  "we're hiring",
  "career opportunity",
  "careers at",
  "/careers",
  "employment opportunity",
  "apply now",
  "submit resume",
  "send resume",
  "salary",
  "hourly pay",
  "per hour",
  "full-time position",
  "part-time position",
  "position available",
  "open position",
  "staffing job",
  "travel nurse",
  "nurse job",
  "ambulance job",
  "emt job",
  "paramedic job",
  "rn job",
  "contract awarded",
  "award notice",
  "awarded to",
  "selected vendor",
  "notice of award",
  "intent to award",
  "sole source award",
  "bid tabulation",
  "executed contract",
  "purchase order",
  "meeting agenda",
  "generic contract list",
  "procurement commentary",
  "blog post",
  "unrelated news article",
  "pharmacy benefits",
  "health insurance",
  "health benefits",
  "claims administration",
  "electronic health record",
  "ehr implementation",
  "emr system",
  "telehealth platform",
  "telemedicine software",
  "veterinary",
  "animal health",
  "pest control",
  "janitorial",
  "landscaping",
  "food service",
  "meal delivery",
];
export const CONDITIONAL_NEGATIVE_GROUPS = [
  {
    id: "ohs_safety_only",
    label: "Safety consulting/training without clinical delivery",
    terms: [
      "safety consulting",
      "construction safety",
      "industrial hygiene only",
      "environmental health and safety consulting",
      "policy development",
      "safety training",
      "OHS management system",
    ],
    requiresOneOf: [
      "examination",
      "physical",
      "surveillance",
      "medical clearance",
      "audiometry",
      "spirometry",
      "drug testing",
      "vaccination",
      "clinical services",
    ],
  },
  {
    id: "background_only",
    label: "Background screening without medical/testing scope",
    terms: [
      "background checks",
      "fingerprinting",
      "criminal history",
      "employment verification",
      "credential verification",
      "education verification",
      "motor vehicle records",
      "I-9",
      "E-Verify",
    ],
    requiresOneOf: [
      "physical",
      "medical",
      "drug",
      "alcohol",
      "TB",
      "audiogram",
      "fitness",
      "health assessment",
      "laboratory",
    ],
  },
  {
    id: "drug_adjacent",
    label: "Drug testing adjacent non-workforce context",
    terms: [
      "probation testing",
      "court-ordered testing",
      "treatment monitoring",
      "drug-testing kits",
      "laboratory supplies",
      "forensic toxicology",
      "student-athlete testing",
      "pharmaceutical research",
      "preclinical drug screening",
    ],
    requiresOneOf: [
      "employee",
      "applicant",
      "candidate",
      "workforce",
      "workplace",
      "DOT",
      "safety-sensitive",
      "pre-employment",
      "post-accident",
      "MRO",
      "collection site",
      "employer",
      "personnel",
    ],
  },
  {
    id: "employee_benefits",
    label: "Benefits/insurance instead of clinical employee medical services",
    terms: [
      "health insurance",
      "benefits administration",
      "wellness incentives",
      "population-health platform",
      "EAP",
      "pharmacy benefits",
      "claims administration",
    ],
    requiresOneOf: [
      "examination",
      "clinical",
      "testing",
      "surveillance",
      "vaccination",
      "medical clearance",
      "occupational medicine",
    ],
  },
  {
    id: "medical_screening_nonworkforce",
    label: "Non-workforce medical screening",
    terms: [
      "patient screening",
      "cancer screening",
      "community-health screening",
      "research-subject screening",
      "pharmaceutical clinical-trial screening",
    ],
    requiresOneOf: [
      "workforce",
      "employment",
      "occupational",
      "deployment",
      "public-safety",
      "contractor personnel",
    ],
  },
  {
    id: "incidental_requirement",
    label: "Incidental contractor compliance requirement",
    terms: [
      "contractor must maintain",
      "drug-testing policy",
      "maintain a drug testing policy",
      "employees assigned to this contract must pass",
    ],
    requiresOneOf: [
      "purchased deliverable",
      "scope item",
      "line item",
      "vendor shall provide",
      "testing services",
      "collection services",
    ],
  },
  {
    id: "supplies_only",
    label: "Equipment/supplies rather than medical service delivery",
    terms: [
      "drug-testing kits",
      "laboratory supplies",
      "fit testing system",
      "equipment only",
      "purchase of equipment",
      "test kits",
    ],
    requiresOneOf: [
      "services",
      "vendor shall provide testing",
      "medical evaluation",
      "program administration",
    ],
  },
];
export const BUYER_SECTOR_SIGNALS: BuyerSectorSignal[] = [
  {
    id: "high_propensity",
    label: "High-propensity public/safety/regulatory buyer",
    propensity: "high",
    phrases: [
      "defense contractor",
      "military",
      "defense agency",
      "Department of Homeland Security",
      "law-enforcement",
      "police",
      "sheriff",
      "fire and rescue",
      "EMS",
      "corrections",
      "juvenile justice",
      "department of transportation",
      "transit authority",
      "airport authority",
      "port authority",
      "public works",
      "water utility",
      "wastewater utility",
      "electric utility",
      "energy utility",
      "hazardous-materials",
      "emergency management",
      "large state government",
      "large county",
      "centralized HR",
      "risk management",
      "federal agency",
      "commercial drivers",
      "safety-sensitive workers",
    ],
  },
  {
    id: "medium_propensity",
    label: "Possible medium-propensity public buyer",
    propensity: "medium",
    phrases: [
      "university",
      "community college",
      "school district",
      "housing authority",
      "hospital district",
      "public hospital",
      "park district",
      "library system",
      "regional authority",
      "special district",
    ],
  },
];
export const REASON_CODES = {
  explicit: "PATH_A_EXPLICIT_SERVICE_MATCH",
  component: "PATH_B_COMPONENT_COMBINATION",
  regulatory: "PATH_C_REGULATORY_PROGRAM",
  network: "PATH_D_NETWORK_MANAGED_DELIVERY",
  genericScope: "PATH_E_GENERIC_TITLE_SPECIFIC_SCOPE",
  negative: "CONDITIONAL_FALSE_POSITIVE_RULE",
  hardReject: "HARD_REJECT_NON_BIDDABLE_OR_JUNK",
  procurementOnly: "PROCUREMENT_SIGNAL_ONLY_NOT_RELEVANT",
  portalVerified: "PORTAL_DIRECT_RELEVANCE_EVIDENCE",
  portalLikely:
    "PORTAL_HIGH_PROPENSITY_BUYER_WITH_OFFICIAL_PROCUREMENT_EVIDENCE",
} as const;
export const SEARCH_QUERY_BUNDLES: SearchQueryBundle[] = [
  {
    id: "general_occupational_medical",
    label: "General occupational medical",
    serviceTerms: [
      '"occupational health services"',
      '"employee occupational health services"',
      '"occupational medicine services"',
      '"occupational medical services"',
      '"medical examination services" employee',
      '"occupational health examinations"',
    ],
    procurementTerms: ["RFP", "solicitation", "request for proposal", "bid"],
  },
  {
    id: "employment_exams",
    label: "Employment exams",
    serviceTerms: [
      '"pre-employment physical"',
      '"employment physical examinations"',
      '"post-offer physical"',
      '"pre-placement medical examination"',
      '"applicant medical examination"',
      '"continued employment physical"',
    ],
    procurementTerms: ["RFP", "solicitation", "request for proposal", "bid"],
  },
  {
    id: "medical_suitability",
    label: "Medical suitability",
    serviceTerms: [
      '"essential job functions" medical',
      '"medical suitability" employee',
      '"ability to perform required duties" medical',
      '"job-specific medical examination"',
      '"fitness determination" employee',
    ],
    procurementTerms: ["RFP", "solicitation", "statement of work"],
  },
  {
    id: "surveillance",
    label: "Surveillance",
    serviceTerms: [
      '"medical surveillance"',
      '"occupational medical surveillance"',
      '"regulated exposure" examination',
      '"HAZWOPER medical examination"',
      '"respirator medical clearance"',
      '"hearing conservation" audiometric',
      '"blood lead testing" employee',
    ],
    procurementTerms: ["RFP", "solicitation", "bid"],
  },
  {
    id: "drug_alcohol",
    label: "Drug / alcohol",
    serviceTerms: [
      '"drug and alcohol testing services"',
      '"DOT drug testing"',
      '"urine specimen collection" DOT',
      '"breath alcohol testing" employee',
      '"Medical Review Officer" solicitation',
      '"random drug testing" workforce',
      '"post-accident testing" employee',
    ],
    procurementTerms: ["RFP", "solicitation", "request for proposal"],
  },
  {
    id: "public_safety",
    label: "Public safety",
    serviceTerms: [
      '"NFPA 1582" medical',
      '"firefighter physical"',
      '"fire and rescue occupational health"',
      '"P.O.S.T. medical examination"',
      '"law enforcement medical screening"',
      '"protective service" medical examination',
      '"public safety physical"',
    ],
    procurementTerms: ["RFP", "solicitation", "bid"],
  },
  {
    id: "deployment",
    label: "Deployment",
    serviceTerms: [
      '"deployment medical screening"',
      '"medical screening and vaccination requirements" contractor',
      '"local nationals occupational health"',
      '"contractor personnel" medical screening',
      '"OCONUS" medical clearance',
      '"CENTCOM" medical screening',
      '"fit for deployment"',
    ],
    procurementTerms: ["RFP", "solicitation", "sources sought"],
  },
  {
    id: "network_multi_site",
    label: "Network / multi-site",
    serviceTerms: [
      '"nationwide occupational health"',
      '"private provider network" medical',
      '"network of clinics" occupational',
      '"mobile medical services" employee',
      '"onsite occupational health services"',
      '"multiple local medical providers" physical examinations',
    ],
    procurementTerms: ["RFP", "solicitation", "request for proposal"],
  },
];
export function buildOccuMedSearchQueries(
  year = new Date().getFullYear(),
): string[] {
  return SEARCH_QUERY_BUNDLES.flatMap((b) =>
    b.serviceTerms.map(
      (t) =>
        `${t} (${b.procurementTerms.join(" OR ")}) ${year} -awarded -\"award notice\"`,
    ),
  );
}
export const ALL_SERVICE_TERMS = SERVICE_CATEGORIES.flatMap((c) => [
  ...c.explicitPhrases,
  ...(c.highIntentPhrases ?? []),
  ...c.componentTerms,
  ...(c.supportingTerms ?? []),
  ...(c.regulatoryTerms ?? []),
]);
export const PROCUREMENT_SIGNALS = PROCUREMENT_TERM_GROUPS.flatMap((g) =>
  g.phrases.concat(g.aliases ?? []),
);
