import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_005: DirectRfpPortal[] = [
  {
    id: "ca-riverside-county",
    name: "Riverside County Purchasing",
    jurisdiction: "Riverside County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://purchasing.co.riverside.ca.us/",
    searchUrl: "https://purchasing.co.riverside.ca.us/",
    domain: "purchasing.co.riverside.ca.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Riverside County purchasing page.",
  },
  {
    id: "ca-alameda-county",
    name: "Alameda County General Services Agency Procurement",
    jurisdiction: "Alameda County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://gsa.acgov.org/do-business-with-us/contracting-opportunities/",
    searchUrl:
      "https://gsa.acgov.org/do-business-with-us/contracting-opportunities/",
    domain: "gsa.acgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Alameda County contracting opportunities page.",
  },
  {
    id: "ca-contra-costa-county",
    name: "Contra Costa County Purchasing",
    jurisdiction: "Contra Costa County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.contracosta.ca.gov/4786/Purchasing",
    searchUrl: "https://www.contracosta.ca.gov/4786/Purchasing",
    domain: "contracosta.ca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Contra Costa County purchasing page.",
  },
  {
    id: "ca-santa-clara-county",
    name: "Santa Clara County Procurement Department",
    jurisdiction: "Santa Clara County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.sccgov.org/",
    searchUrl: "https://procurement.sccgov.org/",
    domain: "procurement.sccgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Santa Clara County procurement department page.",
  },
  {
    id: "ca-san-mateo-county",
    name: "San Mateo County Procurement",
    jurisdiction: "San Mateo County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.smcgov.org/procurement",
    searchUrl: "https://www.smcgov.org/procurement",
    domain: "smcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official San Mateo County procurement page.",
  },
  {
    id: "ca-ventura-county",
    name: "Ventura County Purchasing",
    jurisdiction: "Ventura County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.ventura.org/general-services-agency/procurement-services/",
    searchUrl:
      "https://www.ventura.org/general-services-agency/procurement-services/",
    domain: "ventura.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ventura County procurement services page.",
  },
  {
    id: "ca-long-beach",
    name: "City of Long Beach Purchasing",
    jurisdiction: "City of Long Beach",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.longbeach.gov/finance/business-info/purchasing-division/",
    searchUrl:
      "https://www.longbeach.gov/finance/business-info/purchasing-division/",
    domain: "longbeach.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Long Beach purchasing division page.",
  },
  {
    id: "ca-oakland",
    name: "City of Oakland Contracting Opportunities",
    jurisdiction: "City of Oakland",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.oaklandca.gov/services/contracting-opportunities",
    searchUrl: "https://www.oaklandca.gov/services/contracting-opportunities",
    domain: "oaklandca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official City of Oakland contracting opportunities page.",
  },
  {
    id: "ca-anaheim",
    name: "City of Anaheim Purchasing",
    jurisdiction: "City of Anaheim",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.anaheim.net/140/Purchasing",
    searchUrl: "https://www.anaheim.net/140/Purchasing",
    domain: "anaheim.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Anaheim purchasing page.",
  },
  {
    id: "ca-irvine",
    name: "City of Irvine Purchasing",
    jurisdiction: "City of Irvine",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.cityofirvine.org/purchasing",
    searchUrl: "https://www.cityofirvine.org/purchasing",
    domain: "cityofirvine.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Irvine purchasing page.",
  },
  {
    id: "ca-santa-ana",
    name: "City of Santa Ana Bid Opportunities",
    jurisdiction: "City of Santa Ana",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.santa-ana.org/bid-opportunities/",
    searchUrl: "https://www.santa-ana.org/bid-opportunities/",
    domain: "santa-ana.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official City of Santa Ana bid opportunities page.",
  },
  {
    id: "ca-berkeley",
    name: "City of Berkeley Procurement",
    jurisdiction: "City of Berkeley",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://berkeleyca.gov/doing-business/doing-business-city/procurement",
    searchUrl:
      "https://berkeleyca.gov/doing-business/doing-business-city/procurement",
    domain: "berkeleyca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Berkeley procurement page.",
  },
  {
    id: "ca-pasadena",
    name: "City of Pasadena Purchasing",
    jurisdiction: "City of Pasadena",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.cityofpasadena.net/finance/purchasing/",
    searchUrl: "https://www.cityofpasadena.net/finance/purchasing/",
    domain: "cityofpasadena.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Pasadena purchasing page.",
  },
  {
    id: "ca-glendale",
    name: "City of Glendale Purchasing",
    jurisdiction: "City of Glendale",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.glendaleca.gov/government/departments/finance/purchasing",
    searchUrl:
      "https://www.glendaleca.gov/government/departments/finance/purchasing",
    domain: "glendaleca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Glendale purchasing page.",
  },
  {
    id: "ca-burbank",
    name: "City of Burbank Purchasing",
    jurisdiction: "City of Burbank",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.burbankca.gov/web/financial-services/purchasing",
    searchUrl: "https://www.burbankca.gov/web/financial-services/purchasing",
    domain: "burbankca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Burbank purchasing page.",
  },
  {
    id: "ca-santa-monica",
    name: "City of Santa Monica Vendor Resources",
    jurisdiction: "City of Santa Monica",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.santamonica.gov/vendor-resources",
    searchUrl: "https://www.santamonica.gov/vendor-resources",
    domain: "santamonica.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Santa Monica vendor resources page.",
  },
  {
    id: "ca-uc-system",
    name: "University of California Procurement",
    jurisdiction: "University of California",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.ucop.edu/procurement-services/",
    searchUrl: "https://www.ucop.edu/procurement-services/",
    domain: "ucop.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of California procurement services page.",
  },
  {
    id: "ca-csu",
    name: "California State University Contract Services and Procurement",
    jurisdiction: "California State University",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.calstate.edu/csu-system/doing-business-with-the-csu/contract-services-and-procurement",
    searchUrl:
      "https://www.calstate.edu/csu-system/doing-business-with-the-csu/contract-services-and-procurement",
    domain: "calstate.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CSU contract services and procurement page.",
  },
  {
    id: "ca-lawa",
    name: "Los Angeles World Airports Business Opportunities",
    jurisdiction: "Los Angeles World Airports",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lawa.org/lawa-businesses/lawa-business-opportunities",
    searchUrl:
      "https://www.lawa.org/lawa-businesses/lawa-business-opportunities",
    domain: "lawa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Los Angeles World Airports business opportunities page.",
  },
  {
    id: "ca-port-la",
    name: "Port of Los Angeles Contracts and Bids",
    jurisdiction: "Port of Los Angeles",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.portoflosangeles.org/business/contracting-opportunities",
    searchUrl:
      "https://www.portoflosangeles.org/business/contracting-opportunities",
    domain: "portoflosangeles.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Port of Los Angeles contracting opportunities page.",
  },
  {
    id: "ca-mwd",
    name: "Metropolitan Water District Business Opportunities",
    jurisdiction: "Metropolitan Water District of Southern California",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.mwdh2o.com/doing-business-with-mwd/business-opportunities/",
    searchUrl:
      "https://www.mwdh2o.com/doing-business-with-mwd/business-opportunities/",
    domain: "mwdh2o.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Metropolitan Water District business opportunities page.",
  },
];
