import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_013: DirectRfpPortal[] = [
  {
    id: "mi-detroit",
    name: "City of Detroit Office of Contracting and Procurement",
    jurisdiction: "City of Detroit",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://detroitmi.gov/departments/office-chief-financial-officer/ocfo-divisions/office-contracting-and-procurement",
    searchUrl:
      "https://detroitmi.gov/departments/office-chief-financial-officer/ocfo-divisions/office-contracting-and-procurement",
    domain: "detroitmi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Detroit procurement page.",
  },
  {
    id: "oh-columbus",
    name: "City of Columbus Vendor Services",
    jurisdiction: "City of Columbus",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.columbus.gov/finance/financial-management-group/purchasing-office/vendor-services",
    searchUrl:
      "https://www.columbus.gov/finance/financial-management-group/purchasing-office/vendor-services",
    domain: "columbus.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Columbus procurement page.",
  },
  {
    id: "nc-winston-salem",
    name: "City of Winston-Salem Purchasing",
    jurisdiction: "City of Winston-Salem",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.cityofws.org/1020/Purchasing",
    searchUrl: "https://www.cityofws.org/1020/Purchasing",
    domain: "cityofws.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Winston-Salem procurement page.",
  },
  {
    id: "nc-mecklenburg-county",
    name: "Mecklenburg County Procurement",
    jurisdiction: "Mecklenburg County",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.mecknc.gov/CountyManagersOffice/Procurement/Pages/Home.aspx",
    searchUrl:
      "https://www.mecknc.gov/CountyManagersOffice/Procurement/Pages/Home.aspx",
    domain: "mecknc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Mecklenburg County procurement page.",
  },
  {
    id: "co-denver-airport",
    name: "Denver International Airport Business Opportunities",
    jurisdiction: "Denver International Airport",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.flydenver.com/business-and-community/business-opportunities/",
    searchUrl:
      "https://www.flydenver.com/business-and-community/business-opportunities/",
    domain: "flydenver.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Denver International Airport procurement page.",
  },
  {
    id: "or-washington-county",
    name: "Washington County Purchasing",
    jurisdiction: "Washington County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.washingtoncountyor.gov/purchasing",
    searchUrl: "https://www.washingtoncountyor.gov/purchasing",
    domain: "washingtoncountyor.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Washington County procurement page.",
  },
];
