import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_030: DirectRfpPortal[] = [
  {
    id: "fl-cape-coral-procurement",
    name: "City of Cape Coral Procurement",
    jurisdiction: "City of Cape Coral",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.capecoral.gov/department/financial_services/procurement.php",
    searchUrl:
      "https://www.capecoral.gov/department/financial_services/procurement.php",
    domain: "www.capecoral.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Cape Coral procurement or business opportunities page.",
  },
  {
    id: "ny-mta-procurement",
    name: "Metropolitan Transportation Authority Procurement",
    jurisdiction: "Metropolitan Transportation Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://new.mta.info/doing-business-with-us/procurement",
    searchUrl: "https://new.mta.info/doing-business-with-us/procurement",
    domain: "new.mta.info",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Metropolitan Transportation Authority procurement or business opportunities page.",
  },
  {
    id: "ca-metro-vendor",
    name: "Los Angeles Metro Vendor Portal",
    jurisdiction: "Los Angeles County Metropolitan Transportation Authority",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.metro.net/about/business/",
    searchUrl: "https://www.metro.net/about/business/",
    domain: "www.metro.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Los Angeles County Metropolitan Transportation Authority procurement or business opportunities page.",
  },
  {
    id: "ca-sfmta-procurement",
    name: "SFMTA Procurement",
    jurisdiction: "San Francisco Municipal Transportation Agency",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sfmta.com/business/procurement",
    searchUrl: "https://www.sfmta.com/business/procurement",
    domain: "www.sfmta.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official San Francisco Municipal Transportation Agency procurement or business opportunities page.",
  },
  {
    id: "ca-vta-procurement",
    name: "VTA Procurement",
    jurisdiction: "Santa Clara Valley Transportation Authority",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.vta.org/business-center/procurement",
    searchUrl: "https://www.vta.org/business-center/procurement",
    domain: "www.vta.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Santa Clara Valley Transportation Authority procurement or business opportunities page.",
  },
];
