import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_045: DirectRfpPortal[] = [
  {
    id: "wa-adams-county",
    name: "Adams County Bid Postings",
    jurisdiction: "Adams County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.adams.wa.gov/Bids.aspx",
    searchUrl: "https://www.co.adams.wa.gov/Bids.aspx",
    domain: "www.co.adams.wa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Adams County bid-postings page for current county contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-asotin-county",
    name: "Asotin County Bid Postings",
    jurisdiction: "Asotin County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.asotincountywa.gov/bids.aspx",
    searchUrl: "https://www.asotincountywa.gov/bids.aspx",
    domain: "www.asotincountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Asotin County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-benton-county",
    name: "Benton County Bid Opportunities",
    jurisdiction: "Benton County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.bentoncountywa.gov/departments/purchasing/bid_opportunities.php",
    searchUrl:
      "https://www.bentoncountywa.gov/departments/purchasing/bid_opportunities.php",
    domain: "www.bentoncountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Benton County Purchasing listing for bids, RFPs, RFQs, and related county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-chelan-county",
    name: "Chelan County Public Works Bidding Opportunities",
    jurisdiction: "Chelan County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.chelan.wa.us/public-works/pages/bidding-opportunities",
    searchUrl:
      "https://www.co.chelan.wa.us/public-works/pages/bidding-opportunities",
    domain: "www.co.chelan.wa.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Chelan County Public Works source for current bidding opportunities and project documents. Other county departments may maintain additional listings. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-clallam-county",
    name: "Clallam County Bid Postings",
    jurisdiction: "Clallam County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.clallamcountywa.gov/Bids.aspx",
    searchUrl: "https://www.clallamcountywa.gov/Bids.aspx",
    domain: "www.clallamcountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Clallam County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-clark-county",
    name: "Clark County Requests for Proposals",
    jurisdiction: "Clark County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://clark.wa.gov/internal-services/request-proposal-1",
    searchUrl: "https://clark.wa.gov/internal-services/request-proposal-1",
    domain: "clark.wa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Clark County listing for current requests for proposals across county departments. The county maintains a separate official bids listing for construction bids. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-columbia-county",
    name: "Columbia County Bid Postings",
    jurisdiction: "Columbia County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.columbiaco.com/Bids.aspx",
    searchUrl: "https://www.columbiaco.com/Bids.aspx",
    domain: "www.columbiaco.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Columbia County bid-postings source containing open and historical county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-cowlitz-county",
    name: "Cowlitz County Bid Postings",
    jurisdiction: "Cowlitz County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.cowlitz.wa.us/Bids.aspx",
    searchUrl:
      "https://www.co.cowlitz.wa.us/Bids.aspx?CatID=All&Status=&showAllBids=on&txtSort=Date",
    domain: "www.co.cowlitz.wa.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Cowlitz County all-category bid-postings listing for county departments. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-douglas-county",
    name: "Douglas County Bid Postings",
    jurisdiction: "Douglas County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.douglascountywa.gov/bids.aspx",
    searchUrl: "https://www.douglascountywa.gov/bids.aspx",
    domain: "www.douglascountywa.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Douglas County bid-postings page. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-ferry-county",
    name: "Ferry County Bids",
    jurisdiction: "Ferry County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://ferry-county.com/revize_training_2022/bids.php",
    searchUrl: "https://ferry-county.com/revize_training_2022/bids.php",
    domain: "ferry-county.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Ferry County bids page. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-franklin-county",
    name: "Franklin County RFP and RFQ Postings",
    jurisdiction: "Franklin County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.franklincountywa.gov/447/Bid-Opportunities",
    searchUrl: "https://franklincountywa.gov/Bids.aspx?CatID=19",
    domain: "franklincountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Franklin County RFP and RFQ category listing for county contract opportunities. The county's bid-opportunities hub links additional Public Works categories. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-garfield-county",
    name: "Garfield County Bids and RFPs",
    jurisdiction: "Garfield County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.garfieldcountywa.gov/rfps",
    searchUrl: "https://www.garfieldcountywa.gov/rfps",
    domain: "www.garfieldcountywa.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Garfield County open bids and RFPs listing. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-grant-county",
    name: "Grant County Bids, Proposals, and Qualifications",
    jurisdiction: "Grant County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.grantcountywa.gov/163/Bids-Proposals-Qualifications",
    searchUrl:
      "https://www.grantcountywa.gov/163/Bids-Proposals-Qualifications",
    domain: "www.grantcountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Grant County hub for current bids, RFPs, RFQs, and department-specific postings. Some roster opportunities are distributed through MRSC. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-grays-harbor-county",
    name: "Grays Harbor County Bids and RFPs",
    jurisdiction: "Grays Harbor County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.graysharbor.us/howdoi/bids_and_rfp_s.php",
    searchUrl: "https://www.graysharbor.us/howdoi/bids_and_rfp_s.php",
    domain: "www.graysharbor.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Grays Harbor County listing for bids, RFPs, RFQs, and related documents. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-island-county",
    name: "Island County Bid Postings",
    jurisdiction: "Island County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.islandcountywa.gov/Bids.aspx",
    searchUrl: "https://www.islandcountywa.gov/Bids.aspx",
    domain: "www.islandcountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Island County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-jefferson-county",
    name: "Jefferson County Bid Postings",
    jurisdiction: "Jefferson County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.jefferson.wa.us/Bids.aspx",
    searchUrl: "https://www.co.jefferson.wa.us/Bids.aspx",
    domain: "www.co.jefferson.wa.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Jefferson County all-category bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-kitsap-county",
    name: "Kitsap County Online Bids",
    jurisdiction: "Kitsap County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.kitsap.gov/das/pages/online-bids.aspx",
    searchUrl: "https://www.kitsap.gov/das/pages/online-bids.aspx",
    domain: "www.kitsap.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Kitsap County online-bids hub linking current Purchasing and Public Works bid and proposal listings. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-kittitas-county",
    name: "Kittitas County Public Works Project Bids",
    jurisdiction: "Kittitas County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.kittitas.wa.us/public-works/engineering/bids.aspx",
    searchUrl:
      "https://www.co.kittitas.wa.us/public-works/engineering/bids.aspx",
    domain: "www.co.kittitas.wa.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Kittitas County Public Works source for project bids, with project documents distributed through QuestCDN. Browser-compatible access may be required. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-klickitat-county",
    name: "Klickitat County Bid Postings",
    jurisdiction: "Klickitat County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.klickitatcounty.org/Bids.aspx",
    searchUrl: "https://www.klickitatcounty.org/Bids.aspx",
    domain: "www.klickitatcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Klickitat County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-lewis-county",
    name: "Lewis County Procurement Resources",
    jurisdiction: "Lewis County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://lewiscountywa.gov/departments/information-technology/procurement-resources/",
    searchUrl:
      "https://lewiscountywa.gov/departments/information-technology/procurement-resources/",
    domain: "lewiscountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Lewis County procurement hub linking current and upcoming solicitations plus pending and awarded contracts. Opportunity details may route to the county's buyer-specific OpenGov portal. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-lincoln-county",
    name: "Lincoln County Calls for Bids, RFQs, and RFPs",
    jurisdiction: "Lincoln County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://co.lincoln.wa.us/378/Call-For-Bids-RFQS-RFPs",
    searchUrl: "https://co.lincoln.wa.us/378/Call-For-Bids-RFQS-RFPs",
    domain: "co.lincoln.wa.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Lincoln County Public Works listing for calls for bids, RFQs, and RFPs. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-mason-county",
    name: "Mason County Bid Opportunities",
    jurisdiction: "Mason County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.masoncountywa.gov/services/bids.php",
    searchUrl: "https://www.masoncountywa.gov/services/bids.php",
    domain: "www.masoncountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Mason County bid-opportunities page for active county RFPs and related solicitations. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-okanogan-county",
    name: "Okanogan County Bid Postings",
    jurisdiction: "Okanogan County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.okanogancounty.gov/bids.aspx",
    searchUrl: "https://www.okanogancounty.gov/bids.aspx",
    domain: "www.okanogancounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Okanogan County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-pacific-county",
    name: "Pacific County RFA, RFP, RFQ, and Bid Notices",
    jurisdiction: "Pacific County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.pacific.wa.us/rfa-rfp-rfq/index.htm",
    searchUrl: "https://www.co.pacific.wa.us/rfa-rfp-rfq/index.htm",
    domain: "www.co.pacific.wa.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Pacific County source for requests for applications, proposals, qualifications, and calls for bids. Browser-compatible access may be required. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-pend-oreille-county",
    name: "Pend Oreille County RFP, RFQ, and Bid Opportunities",
    jurisdiction: "Pend Oreille County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.pendoreille.gov/rfp-rfq-bid-opportunities",
    searchUrl: "https://www.pendoreille.gov/rfp-rfq-bid-opportunities",
    domain: "www.pendoreille.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Pend Oreille County hub for department-specific RFP, RFQ, and bid opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-pierce-county",
    name: "Pierce County Current Solicitations",
    jurisdiction: "Pierce County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.piercecountywa.gov/7829/Current-Solicitations",
    searchUrl: "https://www.piercecountywa.gov/7829/Current-Solicitations",
    domain: "www.piercecountywa.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Pierce County current-solicitations source, which integrates the county's buyer-specific OpenGov e-procurement portal. Registration may be required to submit responses, but public opportunity browsing is available. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-san-juan-county",
    name: "San Juan County Current RFPs",
    jurisdiction: "San Juan County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.sanjuancountywa.gov/1557/Current-RFPs",
    searchUrl: "https://www.sanjuancountywa.gov/1557/Current-RFPs",
    domain: "www.sanjuancountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official San Juan County listing for current county RFPs and supporting documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-skagit-county",
    name: "Skagit County RFPs and Calls for Bids",
    jurisdiction: "Skagit County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.skagitcounty.net/Departments/Rfp/",
    searchUrl: "https://www.skagitcounty.net/Departments/Rfp/",
    domain: "www.skagitcounty.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Skagit County index for current RFPs, RFQs, calls for bids, vendor opportunities, and roster information. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-skamania-county",
    name: "Skamania County Public Works Bid Notices",
    jurisdiction: "Skamania County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.skamaniacounty.org/departments-offices/public-works/bid-notices",
    searchUrl:
      "https://www.skamaniacounty.org/departments-offices/public-works/bid-notices",
    domain: "www.skamaniacounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Skamania County Public Works bid-notices source for county projects and documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-stevens-county",
    name: "Stevens County RFPs, RFQs, and Bids",
    jurisdiction: "Stevens County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.stevenscountywa.gov/21234/rfp-rfq-bids",
    searchUrl: "https://www.stevenscountywa.gov/21234/rfp-rfq-bids",
    domain: "www.stevenscountywa.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Stevens County source for RFP, RFQ, and bid opportunities. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-thurston-county",
    name: "Thurston County Contract Opportunities",
    jurisdiction: "Thurston County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.thurstoncountywa.gov/ContractOpportunities",
    searchUrl: "https://www.thurstoncountywa.gov/ContractOpportunities",
    domain: "www.thurstoncountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Thurston County contract-opportunities source. Public Works project plans and specifications are distributed through Builders Exchange of Washington, where registration may be required. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-wahkiakum-county",
    name: "Wahkiakum County Bids and Proposals",
    jurisdiction: "Wahkiakum County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.wahkiakum.wa.us/417/County-Bids-and-Proposals",
    searchUrl: "https://www.co.wahkiakum.wa.us/417/County-Bids-and-Proposals",
    domain: "www.co.wahkiakum.wa.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Wahkiakum County listing for open county bids and proposals. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-walla-walla-county",
    name: "Walla Walla County Bids, RFPs, and RFQs",
    jurisdiction: "Walla Walla County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.co.walla-walla.wa.us/government/commissioners/county_bid_rfp_rfq.php",
    searchUrl:
      "https://www.co.walla-walla.wa.us/government/commissioners/county_bid_rfp_rfq.php",
    domain: "www.co.walla-walla.wa.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Walla Walla County listing for county bids, RFPs, RFQs, RFAs, awards, and supporting documents. The public endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-whatcom-county",
    name: "Whatcom County Bid Postings",
    jurisdiction: "Whatcom County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.whatcomcounty.us/157/Purchasing",
    searchUrl: "https://www.whatcomcounty.us/Bids.aspx",
    domain: "www.whatcomcounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Whatcom County Purchasing bid-postings source for formally solicited bids, RFPs, and RFQs. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-whitman-county",
    name: "Whitman County Bid Postings",
    jurisdiction: "Whitman County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.whitmancounty.gov/Bids.aspx",
    searchUrl: "https://www.whitmancounty.gov/Bids.aspx",
    domain: "www.whitmancounty.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Whitman County bid-postings page for county solicitation and contract opportunities. Browser-compatible access may be required. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-yakima-county",
    name: "Yakima County Current Bid Openings",
    jurisdiction: "Yakima County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.yakimacounty.us/2540/Current-Bid-Openings",
    searchUrl: "https://www.yakimacounty.us/2540/Current-Bid-Openings",
    domain: "www.yakimacounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Yakima County Purchasing listing for current county bids and proposals. Public Services and County Roads also maintain an official bid-postings page. No Occu-Med-specific solicitation is claimed.",
  },
];
