import type { DirectRfpPortal } from "./directRfpPortals";

const COUNTY_NAMES =
  "Anderson,Bedford,Benton,Bledsoe,Blount,Bradley,Campbell,Cannon,Carroll,Carter,Cheatham,Chester,Claiborne,Clay,Cocke,Coffee,Crockett,Cumberland,Davidson,Decatur,DeKalb,Dickson,Dyer,Fayette,Fentress,Franklin,Gibson,Giles,Grainger,Greene,Grundy,Hamblen,Hamilton,Hancock,Hardeman,Hardin,Hawkins,Haywood,Henderson,Henry,Hickman,Houston,Humphreys,Jackson,Jefferson,Johnson,Knox,Lake,Lauderdale,Lawrence,Lewis,Lincoln,Loudon,Macon,Madison,Marion,Marshall,Maury,McMinn,McNairy,Meigs,Monroe,Montgomery,Moore,Morgan,Obion,Overton,Perry,Pickett,Polk,Putnam,Rhea,Roane,Robertson,Rutherford,Scott,Sequatchie,Sevier,Shelby,Smith,Stewart,Sullivan,Sumner,Tipton,Trousdale,Unicoi,Union,Van Buren,Warren,Washington,Wayne,Weakley,White,Williamson,Wilson".split(
    ",",
  );

type ReplacementSpec = readonly [
  name: string,
  url: string,
  searchUrl: string,
  domain: string,
  accessMode: DirectRfpPortal["accessMode"],
  parserStatus: DirectRfpPortal["parserStatus"],
  notes: string,
];

const REPLACEMENTS: Readonly<Record<string, ReplacementSpec>> = {
  Anderson: [
    "Anderson County Purchasing",
    "https://andersoncountytn.gov/purchasing/",
    "https://www.bidnetdirect.com/tennessee/andersoncounty",
    "www.bidnetdirect.com",
    "portal",
    "catalog_only",
    "Official Anderson County Purchasing page and its buyer-specific BidNet current-bids destination. The county purchasing office serves county departments and the school system.",
  ],
  Bledsoe: [
    "Bledsoe County Public Notices and Budget",
    "https://bledsoetn.com/",
    "https://bledsoetn.com/",
    "bledsoetn.com",
    "public_html",
    "ready_to_parse",
    "Official Bledsoe County source with a public-notice archive, county budget access, and notices that include bidding actions.",
  ],
  Blount: [
    "Blount County Purchasing",
    "https://www.blounttn.gov/1133/Purchasing-Home",
    "https://www.blounttn.gov/1256/Ionwave---Vendor-Bidding-Registration",
    "www.blounttn.gov",
    "public_html",
    "catalog_only",
    "Official Blount County Purchasing source with the county's IonWave vendor bidding and registration destination.",
  ],
  Bradley: [
    "Bradley County Schools Bids, RFPs and RFQs",
    "https://www.bradleyschools.org/district/bids-rfps-and-rfqs",
    "https://www.beaconbid.com/solicitations/bradley-county-schools/open",
    "www.beaconbid.com",
    "portal",
    "catalog_only",
    "Official Bradley County Schools procurement page linked to its buyer-scoped Beacon Bid open-solicitations listing.",
  ],
  Campbell: [
    "Campbell County Announcements and Public Notices",
    "https://campbellcountytn.gov/announcements-and-events/",
    "https://campbellcountytn.gov/announcements-and-events/",
    "campbellcountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Campbell County announcements and public-notices source for commission, department, budget, finance, and other county-government notices.",
  ],
  Cheatham: [
    "Cheatham County Public Notices and Bid Notices",
    "https://www.cheathamcountytn.gov/calendar.html",
    "https://www.cheathamcountytn.gov/calendar.html",
    "www.cheathamcountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Cheatham County public-notices page, including county budget notices and department-specific sealed-bid notices.",
  ],
  Cocke: [
    "Cocke County Bids",
    "https://www.cockecountytn.gov/bids",
    "https://www.cockecountytn.gov/bids",
    "www.cockecountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Cocke County bids page for county invitations to bid, requests for proposals, bid documents, and related notices.",
  ],
  Coffee: [
    "Coffee County Bid Postings",
    "https://www.coffeecountytn.gov/Bids.aspx",
    "https://www.coffeecountytn.gov/Bids.aspx",
    "www.coffeecountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Coffee County CivicEngage listing for current and historical bid and contract opportunities.",
  ],
  Cumberland: [
    "Cumberland County Finance and Procurement Notices",
    "https://cumberlandcountytn.gov/directory/finance/",
    "https://cumberlandcountytn.gov/directory/finance/",
    "cumberlandcountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Cumberland County Finance Department page publishing procurement documents, including RFP and RFQ files, alongside financial records.",
  ],
  Greene: [
    "Greene County Purchasing",
    "https://www.greenecountytngov.com/purchasing/",
    "https://www.greenecountytngov.com/purchasing/",
    "www.greenecountytngov.com",
    "public_html",
    "ready_to_parse",
    "Official Greene County Purchasing source for the county's central buying agency, current bid solicitations, bid documents, and buyer-specific public-purchase links.",
  ],
  Hamilton: [
    "Hamilton County Financial Reporting and Transparency",
    "https://www.hamiltontn.gov/Services_Transparency.aspx",
    "https://www.hamiltontn.gov/Services_Transparency.aspx",
    "www.hamiltontn.gov",
    "public_html",
    "catalog_only",
    "Official Hamilton County financial-reporting and transparency destination with budgets, financial reports, spending reports, policies, and related county records.",
  ],
  Johnson: [
    "Johnson County Purchasing Department",
    "https://www.johnsoncountytn.gov/purchasing-department",
    "https://www.johnsoncountytn.gov/purchasing-department",
    "www.johnsoncountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Johnson County Purchasing Department page with open RFQs, invitations to bid, vendor registration, and a buyer-specific open-solicitations link.",
  ],
  Knox: [
    "Knox County Procurement",
    "https://www.knoxcounty.org/purchasing/",
    "https://www.knoxcounty.org/apps/solicitations/solicitations.php",
    "www.knoxcounty.org",
    "public_html",
    "ready_to_parse",
    "Official Knox County Procurement page and direct current-solicitations listing.",
  ],
  Lawrence: [
    "Lawrence County News and Procurement Notices",
    "https://lawrencecountytn.gov/news/",
    "https://lawrencecountytn.gov/news/",
    "lawrencecountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Lawrence County news and notice archive publishing invitations to bid, annual-bid packets, requests, and county financial notices.",
  ],
  Loudon: [
    "Loudon County Announcements and Public Notices",
    "https://loudoncounty-tn.gov/announcements/",
    "https://loudoncounty-tn.gov/announcements/",
    "loudoncounty-tn.gov",
    "public_html",
    "ready_to_parse",
    "Official Loudon County announcements source for county commission, budget, capital-project, purchasing-committee, and other public notices.",
  ],
  Madison: [
    "Madison County Bid Postings",
    "https://www.madisoncountytn.gov/Bids.aspx",
    "https://www.madisoncountytn.gov/Bids.aspx",
    "www.madisoncountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Madison County bid-postings page for current, closed, awarded, and cancelled county solicitations and downloadable bid packages.",
  ],
  Marion: [
    "Marion County Budget",
    "https://marioncountytn.net/budget",
    "https://marioncountytn.net/budget",
    "marioncountytn.net",
    "public_html",
    "ready_to_parse",
    "Official Marion County budget source publishing current and prior local-government, education, highway, capital, bond, and appropriation records.",
  ],
  Maury: [
    "Maury County Bid Postings",
    "https://www.maurycounty-tn.gov/Bids.aspx",
    "https://www.maurycounty-tn.gov/Bids.aspx",
    "www.maurycounty-tn.gov",
    "public_html",
    "ready_to_parse",
    "Official Maury County CivicEngage listing for current and historical bid and contract opportunities.",
  ],
  Montgomery: [
    "Montgomery County Purchasing and Current Bids",
    "https://mcgtn.org/purchasing",
    "https://mcgtn.org/purchasing/bids",
    "mcgtn.org",
    "public_html",
    "ready_to_parse",
    "Official Montgomery County Purchasing page and direct current-bids listing; the county also links its Bonfire online bid portal.",
  ],
  Shelby: [
    "Shelby County Purchasing Office",
    "https://www.shelbycountytn.gov/189/Purchasing",
    "https://www.shelbycountytn.gov/201/Conducting-Business-with-Shelby-County",
    "www.shelbycountytn.gov",
    "public_html",
    "catalog_only",
    "Official Shelby County Purchasing Office and county vendor-facing procurement guidance covering bidding procedures, purchasing, and vendor registration.",
  ],
  Stewart: [
    "Stewart County Budgets and Audits",
    "https://www.stewartcogov.com/county_budgets_audits/county_budgets_audit.html",
    "https://www.stewartcogov.com/county_budgets_audits/county_budgets_audit.html",
    "www.stewartcogov.com",
    "public_html",
    "ready_to_parse",
    "Official Stewart County budgets-and-audits source with current and proposed county, school, highway, capital-project, appropriation, and audit records.",
  ],
  Sullivan: [
    "Sullivan County Purchasing",
    "https://sullivancountytn.gov/purchasing/",
    "https://www.bidnetdirect.com/tennessee/sullivancountytn",
    "www.bidnetdirect.com",
    "portal",
    "catalog_only",
    "Official Sullivan County Purchasing source and its buyer-specific BidNet current-solicitations destination for county departments, including education.",
  ],
  Sumner: [
    "Sumner County Finance Purchasing and Bid Notices",
    "https://sumnercountytn.gov/departments/finance/purchasing/",
    "https://sumnercountytn.gov/departments/finance/purchasing/",
    "sumnercountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Sumner County Finance purchasing page with current bid notices, requests for proposals and qualifications, and multi-year bid minutes and awards.",
  ],
  Union: [
    "Union County Accounts and Budgets",
    "https://www.unioncountytn.gov/accounts-and-budgets/",
    "https://www.unioncountytn.gov/accounts-and-budgets/",
    "www.unioncountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Union County accounts-and-budgets source linking the current county budget, audit, and related financial records.",
  ],
  Washington: [
    "Washington County Bid Postings",
    "https://www.washingtoncountytn.org/Bids.aspx",
    "https://www.washingtoncountytn.org/Bids.aspx",
    "www.washingtoncountytn.org",
    "public_html",
    "ready_to_parse",
    "Official Washington County CivicEngage listing for current, closed, awarded, and cancelled bid and contract opportunities.",
  ],
  Weakley: [
    "Weakley County Finance Bids and Purchasing",
    "https://www.weakleycountytn.gov/bids--purchasing.html",
    "https://www.weakleycountytn.gov/bids--purchasing.html",
    "www.weakleycountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Weakley County Department of Finance bids-and-purchasing page for current county bids, RFPs, bid specifications, awards, and purchasing information.",
  ],
  White: [
    "White County Bids and Purchasing",
    "https://whitecountytn.gov/business/bids-purchasing",
    "https://whitecountytn.gov/business/bids-purchasing",
    "whitecountytn.gov",
    "public_html",
    "catalog_only",
    "Official White County buyer-facing bids-and-purchasing destination. The page remains catalog-only because the live endpoint was not reliably retrievable during this correction pass.",
  ],
  Williamson: [
    "Williamson County Purchasing",
    "https://www.williamsoncounty-tn.gov/406/Purchasing",
    "https://www.bidnetdirect.com/williamsoncounty",
    "www.bidnetdirect.com",
    "portal",
    "catalog_only",
    "Official Williamson County Purchasing page and its buyer-specific BidNet current-bid-opportunities destination.",
  ],
  Wilson: [
    "Wilson County Bid Postings",
    "https://www.wilsoncountytn.gov/Bids.aspx",
    "https://www.wilsoncountytn.gov/Bids.aspx",
    "www.wilsoncountytn.gov",
    "public_html",
    "ready_to_parse",
    "Official Wilson County bid-postings page for current, closed, awarded, and cancelled county contract opportunities.",
  ],
};

const CTAS_FALLBACK_NOTE =
  "County-specific Tennessee County Technical Assistance Service page retained as a fallback because this correction pass did not verify a stable direct source-of-truth procurement, finance, bid, public-notice, school-procurement, or buyer-specific portal for this county. Follow the listed county offices for department-specific opportunities. No Occu-Med-specific solicitation is claimed.";

function countySlug(countyName: string): string {
  return countyName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function portalForCounty(countyName: string): DirectRfpPortal {
  const slug = countySlug(countyName);
  const replacement = REPLACEMENTS[countyName];
  if (!replacement) {
    const ctasUrl = `https://www.ctas.tennessee.edu/county/${slug}`;
    return {
      id: `tn-${slug}-county`,
      name: `${countyName} County CTAS County Information`,
      jurisdiction: `${countyName} County`,
      state: "TN",
      country: "US",
      level: "district",
      url: ctasUrl,
      searchUrl: ctasUrl,
      domain: "www.ctas.tennessee.edu",
      accessMode: "public_html",
      requiresKey: false,
      requiresLogin: false,
      tier: 3,
      parserStatus: "catalog_only",
      notes: CTAS_FALLBACK_NOTE,
    };
  }

  const [name, url, searchUrl, domain, accessMode, parserStatus, notes] =
    replacement;
  return {
    id: `tn-${slug}-county`,
    name,
    jurisdiction: `${countyName} County`,
    state: "TN",
    country: "US",
    level: "district",
    url,
    searchUrl,
    domain,
    accessMode,
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus,
    notes,
  };
}

export const GENERATED_DIRECT_RFP_PORTALS_046: DirectRfpPortal[] =
  COUNTY_NAMES.map(portalForCounty);
