import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_006: DirectRfpPortal[] = [
  {
    id: "tx-dallas-county",
    name: "Dallas County Purchasing",
    jurisdiction: "Dallas County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.dallascounty.org/departments/purchasing/",
    searchUrl: "https://www.dallascounty.org/departments/purchasing/",
    domain: "dallascounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Dallas County purchasing page.",
  },
  {
    id: "tx-tarrant-county",
    name: "Tarrant County Purchasing",
    jurisdiction: "Tarrant County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.tarrantcountytx.gov/en/purchasing.html",
    searchUrl: "https://www.tarrantcountytx.gov/en/purchasing.html",
    domain: "tarrantcountytx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tarrant County purchasing page.",
  },
  {
    id: "tx-travis-county",
    name: "Travis County Purchasing Office",
    jurisdiction: "Travis County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.traviscountytx.gov/purchasing",
    searchUrl: "https://www.traviscountytx.gov/purchasing",
    domain: "traviscountytx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Travis County purchasing office page.",
  },
  {
    id: "tx-el-paso",
    name: "City of El Paso Purchasing and Strategic Sourcing",
    jurisdiction: "City of El Paso",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.elpasotexas.gov/purchasing/",
    searchUrl: "https://www.elpasotexas.gov/purchasing/",
    domain: "elpasotexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of El Paso purchasing page.",
  },
  {
    id: "tx-frisco",
    name: "City of Frisco Purchasing",
    jurisdiction: "City of Frisco",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.friscotexas.gov/133/Purchasing",
    searchUrl: "https://www.friscotexas.gov/133/Purchasing",
    domain: "friscotexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Frisco purchasing page.",
  },
  {
    id: "tx-via",
    name: "VIA Metropolitan Transit Procurement",
    jurisdiction: "VIA Metropolitan Transit",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.viainfo.net/procurement/",
    searchUrl: "https://www.viainfo.net/procurement/",
    domain: "viainfo.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official VIA procurement page.",
  },
];
