import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_025: DirectRfpPortal[] = [
  {
    id: "ny-stonybrook-procurement",
    name: "Stony Brook University Procurement",
    jurisdiction: "Stony Brook University",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.stonybrook.edu/commcms/procurement/",
    searchUrl: "https://www.stonybrook.edu/commcms/procurement/",
    domain: "www.stonybrook.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Stony Brook University procurement or business opportunities page.",
  },
  {
    id: "ny-buffalo-procurement",
    name: "University at Buffalo Procurement Services",
    jurisdiction: "University at Buffalo",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.buffalo.edu/administrative-services/managing-procurement.html",
    searchUrl:
      "https://www.buffalo.edu/administrative-services/managing-procurement.html",
    domain: "www.buffalo.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University at Buffalo procurement or business opportunities page.",
  },
  {
    id: "ny-albany-procurement",
    name: "University at Albany Purchasing",
    jurisdiction: "University at Albany",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.albany.edu/purchasing",
    searchUrl: "https://www.albany.edu/purchasing",
    domain: "www.albany.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University at Albany procurement or business opportunities page.",
  },
  {
    id: "ny-binghamton-purchasing",
    name: "Binghamton University Purchasing",
    jurisdiction: "Binghamton University",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.binghamton.edu/offices/purchasing/",
    searchUrl: "https://www.binghamton.edu/offices/purchasing/",
    domain: "www.binghamton.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Binghamton University procurement or business opportunities page.",
  },
  {
    id: "ny-syracuse-purchasing",
    name: "Syracuse University Purchasing",
    jurisdiction: "Syracuse University",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://purchasing.syr.edu/",
    searchUrl: "https://purchasing.syr.edu/",
    domain: "purchasing.syr.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Syracuse University procurement or business opportunities page.",
  },
];
