import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_001: DirectRfpPortal[] = [
  {
    id: "ak-anchorage",
    name: "Municipality of Anchorage Purchasing",
    jurisdiction: "Municipality of Anchorage",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    searchUrl: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    domain: "muni.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official municipal purchasing page for Anchorage procurement resources and bid information.",
  },
  {
    id: "ak-university-of-alaska",
    name: "University of Alaska Procurement",
    jurisdiction: "University of Alaska",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.alaska.edu/procurement/",
    searchUrl: "https://www.alaska.edu/procurement/",
    domain: "alaska.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of Alaska procurement and contract services page.",
  },
  {
    id: "al-jefferson-county",
    name: "Jefferson County Purchasing",
    jurisdiction: "Jefferson County",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.jccal.org/Default.asp?ID=238&pg=Purchasing",
    searchUrl: "https://www.jccal.org/Default.asp?ID=238&pg=Purchasing",
    domain: "jccal.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Jefferson County purchasing page for vendor and bid information.",
  },
  {
    id: "ar-little-rock",
    name: "City of Little Rock Purchasing",
    jurisdiction: "City of Little Rock",
    state: "AR",
    country: "US",
    level: "district",
    url: "https://www.littlerock.gov/city-administration/city-departments/finance/purchasing/",
    searchUrl:
      "https://www.littlerock.gov/city-administration/city-departments/finance/purchasing/",
    domain: "littlerock.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official city purchasing page for Little Rock procurement information.",
  },
  {
    id: "ct-uconn",
    name: "University of Connecticut Procurement Services",
    jurisdiction: "University of Connecticut",
    state: "CT",
    country: "US",
    level: "district",
    url: "https://procurement.uconn.edu/",
    searchUrl: "https://procurement.uconn.edu/",
    domain: "procurement.uconn.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UConn procurement services site.",
  },
  {
    id: "de-wilmington",
    name: "City of Wilmington Procurement",
    jurisdiction: "City of Wilmington",
    state: "DE",
    country: "US",
    level: "district",
    url: "https://www.wilmingtonde.gov/government/city-departments/finance/purchasing",
    searchUrl:
      "https://www.wilmingtonde.gov/government/city-departments/finance/purchasing",
    domain: "wilmingtonde.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Wilmington purchasing page.",
  },
  {
    id: "fl-hillsborough-county",
    name: "Hillsborough County Procurement Services",
    jurisdiction: "Hillsborough County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.hillsboroughcounty.org/en/businesses/doing-business-with-hillsborough/vendors/procurement-services",
    searchUrl:
      "https://www.hillsboroughcounty.org/en/businesses/doing-business-with-hillsborough/vendors/procurement-services",
    domain: "hillsboroughcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Hillsborough County procurement services page.",
  },
  {
    id: "ga-fulton-county",
    name: "Fulton County Purchasing and Contract Compliance",
    jurisdiction: "Fulton County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/purchasing-contract-compliance",
    searchUrl:
      "https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/purchasing-contract-compliance",
    domain: "fultoncountyga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Fulton County purchasing and contract compliance page.",
  },
  {
    id: "gu-general-services-agency",
    name: "Guam General Services Agency Procurement",
    jurisdiction: "Guam",
    state: "GU",
    country: "US",
    level: "district",
    url: "https://gsa.doa.guam.gov/",
    searchUrl: "https://gsa.doa.guam.gov/",
    domain: "gsa.doa.guam.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Guam General Services Agency procurement site.",
  },
  {
    id: "hi-honolulu",
    name: "City and County of Honolulu Purchasing",
    jurisdiction: "City and County of Honolulu",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www8.honolulu.gov/bfs/purchasing/",
    searchUrl: "https://www8.honolulu.gov/bfs/purchasing/",
    domain: "honolulu.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Honolulu purchasing page.",
  },
  {
    id: "ia-des-moines",
    name: "City of Des Moines Procurement",
    jurisdiction: "City of Des Moines",
    state: "IA",
    country: "US",
    level: "district",
    url: "https://www.dsm.city/departments/finance/procurement.php",
    searchUrl: "https://www.dsm.city/departments/finance/procurement.php",
    domain: "dsm.city",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Des Moines procurement page.",
  },
  {
    id: "id-ada-county",
    name: "Ada County Procurement",
    jurisdiction: "Ada County",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://adacounty.id.gov/procurement/",
    searchUrl: "https://adacounty.id.gov/procurement/",
    domain: "adacounty.id.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ada County procurement page.",
  },
  {
    id: "in-indianapolis",
    name: "Indianapolis Purchasing Division",
    jurisdiction: "City of Indianapolis / Marion County",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.indy.gov/agency/purchasing-division",
    searchUrl: "https://www.indy.gov/agency/purchasing-division",
    domain: "indy.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Indianapolis purchasing division page.",
  },
  {
    id: "ks-wichita",
    name: "City of Wichita Purchasing",
    jurisdiction: "City of Wichita",
    state: "KS",
    country: "US",
    level: "district",
    url: "https://www.wichita.gov/Finance/Pages/Purchasing.aspx",
    searchUrl: "https://www.wichita.gov/Finance/Pages/Purchasing.aspx",
    domain: "wichita.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Wichita purchasing page.",
  },
  {
    id: "ma-massport",
    name: "Massport Business Opportunities",
    jurisdiction: "Massachusetts Port Authority",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.massport.com/business-with-massport",
    searchUrl: "https://www.massport.com/business-with-massport",
    domain: "massport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official Massport business opportunities page for airport and port authority procurement.",
  },
  {
    id: "me-portland",
    name: "City of Portland Purchasing",
    jurisdiction: "City of Portland",
    state: "ME",
    country: "US",
    level: "district",
    url: "https://www.portlandmaine.gov/1056/Purchasing",
    searchUrl: "https://www.portlandmaine.gov/1056/Purchasing",
    domain: "portlandmaine.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Portland, Maine purchasing page.",
  },
  {
    id: "mn-hennepin-county",
    name: "Hennepin County Supplier Portal",
    jurisdiction: "Hennepin County",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    searchUrl:
      "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    domain: "hennepin.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Hennepin County supplier portal entry page.",
  },
  {
    id: "mo-st-louis",
    name: "City of St. Louis Supply Division",
    jurisdiction: "City of St. Louis",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://www.stlouis-mo.gov/government/departments/supply/",
    searchUrl: "https://www.stlouis-mo.gov/government/departments/supply/",
    domain: "stlouis-mo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official St. Louis supply division procurement page.",
  },
  {
    id: "mp-procurement",
    name: "CNMI Procurement and Supply",
    jurisdiction: "Commonwealth of the Northern Mariana Islands",
    state: "MP",
    country: "US",
    level: "district",
    url: "https://www.finance.gov.mp/divisions/procurement-and-supply/",
    searchUrl: "https://www.finance.gov.mp/divisions/procurement-and-supply/",
    domain: "finance.gov.mp",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CNMI procurement and supply division page.",
  },
  {
    id: "ms-jackson",
    name: "City of Jackson Purchasing",
    jurisdiction: "City of Jackson",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.jacksonms.gov/purchasing/",
    searchUrl: "https://www.jacksonms.gov/purchasing/",
    domain: "jacksonms.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jackson purchasing page.",
  },
  {
    id: "mt-billings",
    name: "City of Billings Purchasing",
    jurisdiction: "City of Billings",
    state: "MT",
    country: "US",
    level: "district",
    url: "https://www.billingsmt.gov/107/Purchasing",
    searchUrl: "https://www.billingsmt.gov/107/Purchasing",
    domain: "billingsmt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Billings purchasing page.",
  },
  {
    id: "nd-fargo",
    name: "City of Fargo Purchasing",
    jurisdiction: "City of Fargo",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://fargond.gov/city-government/departments/finance/purchasing",
    searchUrl:
      "https://fargond.gov/city-government/departments/finance/purchasing",
    domain: "fargond.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fargo purchasing page.",
  },
  {
    id: "ne-omaha",
    name: "City of Omaha Purchasing",
    jurisdiction: "City of Omaha",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://finance.cityofomaha.org/purchasing",
    searchUrl: "https://finance.cityofomaha.org/purchasing",
    domain: "finance.cityofomaha.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Omaha purchasing page.",
  },
  {
    id: "nh-manchester",
    name: "City of Manchester Purchasing",
    jurisdiction: "City of Manchester",
    state: "NH",
    country: "US",
    level: "district",
    url: "https://www.manchesternh.gov/Departments/Purchasing",
    searchUrl: "https://www.manchesternh.gov/Departments/Purchasing",
    domain: "manchesternh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Manchester purchasing page.",
  },
  {
    id: "nj-essex-county",
    name: "Essex County Purchasing",
    jurisdiction: "Essex County",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://essexcountynj.org/purchasing/",
    searchUrl: "https://essexcountynj.org/purchasing/",
    domain: "essexcountynj.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Essex County purchasing page.",
  },
  {
    id: "nm-albuquerque",
    name: "City of Albuquerque Purchasing",
    jurisdiction: "City of Albuquerque",
    state: "NM",
    country: "US",
    level: "district",
    url: "https://www.cabq.gov/dfa/purchasing",
    searchUrl: "https://www.cabq.gov/dfa/purchasing",
    domain: "cabq.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Albuquerque purchasing page.",
  },
  {
    id: "nv-las-vegas",
    name: "City of Las Vegas Purchasing and Contracts",
    jurisdiction: "City of Las Vegas",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    searchUrl:
      "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    domain: "lasvegasnevada.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Las Vegas purchasing and contracts page.",
  },
  {
    id: "ny-nyc-dcas",
    name: "New York City DCAS Procurement",
    jurisdiction: "City of New York",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/site/dcas/business/procurement.page",
    searchUrl: "https://www.nyc.gov/site/dcas/business/procurement.page",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 1,
    parserStatus: "catalog_only",
    notes: "Official NYC DCAS procurement page for city contracting resources.",
  },
  {
    id: "oh-franklin-county",
    name: "Franklin County Purchasing",
    jurisdiction: "Franklin County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://purchasing.franklincountyohio.gov/",
    searchUrl: "https://purchasing.franklincountyohio.gov/",
    domain: "purchasing.franklincountyohio.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Franklin County purchasing site.",
  },
  {
    id: "ok-oklahoma-city",
    name: "Oklahoma City Bids and Proposals",
    jurisdiction: "City of Oklahoma City",
    state: "OK",
    country: "US",
    level: "district",
    url: "https://www.okc.gov/departments/finance/purchasing/bids-proposals",
    searchUrl:
      "https://www.okc.gov/departments/finance/purchasing/bids-proposals",
    domain: "okc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Oklahoma City bids and proposals page.",
  },
  {
    id: "pa-allegheny-county",
    name: "Allegheny County Purchasing and Supplies",
    jurisdiction: "Allegheny County",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.alleghenycounty.us/Services/Purchasing-and-Supplies",
    searchUrl:
      "https://www.alleghenycounty.us/Services/Purchasing-and-Supplies",
    domain: "alleghenycounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Allegheny County purchasing and supplies page.",
  },
  {
    id: "pr-general-services-administration",
    name: "Puerto Rico General Services Administration",
    jurisdiction: "Puerto Rico",
    state: "PR",
    country: "US",
    level: "district",
    url: "https://asg.pr.gov/",
    searchUrl: "https://asg.pr.gov/",
    domain: "asg.pr.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Puerto Rico General Services Administration procurement entry point.",
  },
  {
    id: "ri-providence",
    name: "City of Providence Purchasing",
    jurisdiction: "City of Providence",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://www.providenceri.gov/purchasing/",
    searchUrl: "https://www.providenceri.gov/purchasing/",
    domain: "providenceri.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Providence purchasing page.",
  },
  {
    id: "sc-richland-county",
    name: "Richland County Procurement",
    jurisdiction: "Richland County",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://www.richlandcountysc.gov/Government/Departments/Business-Operations/Procurement",
    searchUrl:
      "https://www.richlandcountysc.gov/Government/Departments/Business-Operations/Procurement",
    domain: "richlandcountysc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Richland County procurement page.",
  },
  {
    id: "sd-sioux-falls",
    name: "City of Sioux Falls Purchasing",
    jurisdiction: "City of Sioux Falls",
    state: "SD",
    country: "US",
    level: "district",
    url: "https://www.siouxfalls.gov/business-permits/business/purchasing",
    searchUrl:
      "https://www.siouxfalls.gov/business-permits/business/purchasing",
    domain: "siouxfalls.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Sioux Falls purchasing page.",
  },
  {
    id: "tx-houston",
    name: "City of Houston Strategic Procurement Division",
    jurisdiction: "City of Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.houstontx.gov/bizwithhou/",
    searchUrl: "https://www.houstontx.gov/bizwithhou/",
    domain: "houstontx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Houston strategic procurement page.",
  },
];
