import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_012: DirectRfpPortal[] = [
  {
    id: "pa-allentown",
    name: "City of Allentown Purchasing",
    jurisdiction: "City of Allentown",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.allentownpa.gov/Finance/Purchasing",
    searchUrl: "https://www.allentownpa.gov/Finance/Purchasing",
    domain: "allentownpa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Allentown procurement page.",
  },
  {
    id: "il-dupage-county",
    name: "DuPage County Procurement Services",
    jurisdiction: "DuPage County",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.dupagecounty.gov/government/departments/finance/procurement_services/",
    searchUrl:
      "https://www.dupagecounty.gov/government/departments/finance/procurement_services/",
    domain: "dupagecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official DuPage County procurement page.",
  },
  {
    id: "ga-augusta",
    name: "Augusta Procurement Department",
    jurisdiction: "Augusta-Richmond County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.augustaga.gov/685/Procurement-Department",
    searchUrl: "https://www.augustaga.gov/685/Procurement-Department",
    domain: "augustaga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Augusta-Richmond County procurement page.",
  },
  {
    id: "tx-collin-county",
    name: "Collin County Purchasing",
    jurisdiction: "Collin County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.collincountytx.gov/Purchasing",
    searchUrl: "https://www.collincountytx.gov/Purchasing",
    domain: "collincountytx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Collin County procurement page.",
  },
  {
    id: "mi-macomb-county",
    name: "Macomb County Purchasing",
    jurisdiction: "Macomb County",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://purchasing.macombgov.org/Purchasing-Home",
    searchUrl: "https://purchasing.macombgov.org/Purchasing-Home",
    domain: "purchasing.macombgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Macomb County procurement page.",
  },
  {
    id: "wa-seattle",
    name: "City of Seattle Purchasing and Contracting",
    jurisdiction: "City of Seattle",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.seattle.gov/purchasing-and-contracting",
    searchUrl: "https://www.seattle.gov/purchasing-and-contracting",
    domain: "seattle.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Seattle procurement page.",
  },
];
