import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_006: DirectRfpPortal[] = [
  {
    id: "tx-dallas-county",
    name: "Dallas County Purchasing",
    jurisdiction: "Dallas County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.dallascounty.org/departments/purchasing/",
    searchUrl: "https://www.dallascounty.org/departments/purchasing/",
    domain: "dallascounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Dallas County purchasing page.",
  },
  {
    id: "tx-tarrant-county",
    name: "Tarrant County Purchasing",
    jurisdiction: "Tarrant County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.tarrantcountytx.gov/en/purchasing.html",
    searchUrl: "https://www.tarrantcountytx.gov/en/purchasing.html",
    domain: "tarrantcountytx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tarrant County purchasing page.",
  },
  {
    id: "tx-bexar-county",
    name: "Bexar County Purchasing",
    jurisdiction: "Bexar County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.bexar.org/1435/Purchasing",
    searchUrl: "https://www.bexar.org/1435/Purchasing",
    domain: "bexar.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bexar County purchasing page.",
  },
  {
    id: "tx-travis-county",
    name: "Travis County Purchasing Office",
    jurisdiction: "Travis County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.traviscountytx.gov/purchasing",
    searchUrl: "https://www.traviscountytx.gov/purchasing",
    domain: "traviscountytx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Travis County purchasing office page.",
  },
  {
    id: "tx-san-antonio",
    name: "City of San Antonio Purchasing",
    jurisdiction: "City of San Antonio",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.sa.gov/Directory/Departments/Finance/Purchasing",
    searchUrl: "https://www.sa.gov/Directory/Departments/Finance/Purchasing",
    domain: "sa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of San Antonio purchasing page.",
  },
  {
    id: "tx-el-paso",
    name: "City of El Paso Purchasing and Strategic Sourcing",
    jurisdiction: "City of El Paso",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.elpasotexas.gov/purchasing/",
    searchUrl: "https://www.elpasotexas.gov/purchasing/",
    domain: "elpasotexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of El Paso purchasing page.",
  },
  {
    id: "tx-corpus-christi",
    name: "City of Corpus Christi Contracts and Procurement",
    jurisdiction: "City of Corpus Christi",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.cctexas.com/services/business/contracts-and-procurement",
    searchUrl:
      "https://www.cctexas.com/services/business/contracts-and-procurement",
    domain: "cctexas.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Corpus Christi contracts and procurement page.",
  },
  {
    id: "tx-frisco",
    name: "City of Frisco Purchasing",
    jurisdiction: "City of Frisco",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.friscotexas.gov/133/Purchasing",
    searchUrl: "https://www.friscotexas.gov/133/Purchasing",
    domain: "friscotexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Frisco purchasing page.",
  },
  {
    id: "tx-richardson",
    name: "City of Richardson Purchasing",
    jurisdiction: "City of Richardson",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.cor.net/departments/purchasing",
    searchUrl: "https://www.cor.net/departments/purchasing",
    domain: "cor.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Richardson purchasing page.",
  },
  {
    id: "tx-university-of-texas-system",
    name: "University of Texas System Supply Chain Alliance",
    jurisdiction: "University of Texas System",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.utsystem.edu/offices/supply-chain-alliance",
    searchUrl: "https://www.utsystem.edu/offices/supply-chain-alliance",
    domain: "utsystem.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UT System supply chain alliance page.",
  },
  {
    id: "tx-texas-am",
    name: "Texas A&M University Procurement Services",
    jurisdiction: "Texas A&M University",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://procurement.tamu.edu/",
    searchUrl: "https://procurement.tamu.edu/",
    domain: "procurement.tamu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Texas A&M procurement services page.",
  },
  {
    id: "tx-houston-airports",
    name: "Houston Airports Business Opportunities",
    jurisdiction: "Houston Airport System",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.fly2houston.com/biz/opportunities",
    searchUrl: "https://www.fly2houston.com/biz/opportunities",
    domain: "fly2houston.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Houston Airports business opportunities page.",
  },
  {
    id: "tx-port-houston",
    name: "Port Houston Procurement Services",
    jurisdiction: "Port Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://porthouston.com/business/procurement-services/",
    searchUrl: "https://porthouston.com/business/procurement-services/",
    domain: "porthouston.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Port Houston procurement services page.",
  },
  {
    id: "tx-capmetro",
    name: "CapMetro Procurement",
    jurisdiction: "Capital Metropolitan Transportation Authority",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.capmetro.org/procurement",
    searchUrl: "https://www.capmetro.org/procurement",
    domain: "capmetro.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CapMetro procurement page.",
  },
  {
    id: "tx-via",
    name: "VIA Metropolitan Transit Procurement",
    jurisdiction: "VIA Metropolitan Transit",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.viainfo.net/procurement/",
    searchUrl: "https://www.viainfo.net/procurement/",
    domain: "viainfo.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official VIA procurement page.",
  },
  {
    id: "tx-san-antonio-water",
    name: "San Antonio Water System Contracting",
    jurisdiction: "San Antonio Water System",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.saws.org/business-center/contracting/",
    searchUrl: "https://www.saws.org/business-center/contracting/",
    domain: "saws.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official SAWS contracting page.",
  },
];
