import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_034: DirectRfpPortal[] = [
  {
    id: "va-port-procurement",
    name: "Virginia Port Authority Procurement",
    jurisdiction: "Virginia Port Authority",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.portofvirginia.com/about/procurement/",
    searchUrl: "https://www.portofvirginia.com/about/procurement/",
    domain: "www.portofvirginia.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Virginia Port Authority procurement or business opportunities page.",
  },
  {
    id: "md-port-procurement",
    name: "Maryland Port Administration Procurement",
    jurisdiction: "Maryland Port Administration",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://mpa.maryland.gov/Pages/procurement.aspx",
    searchUrl: "https://mpa.maryland.gov/Pages/procurement.aspx",
    domain: "mpa.maryland.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Maryland Port Administration procurement or business opportunities page.",
  },
  {
    id: "ca-lawa-business",
    name: "Los Angeles World Airports Business Opportunities",
    jurisdiction: "Los Angeles World Airports",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lawa.org/lawa-businesses/lawa-procurement-services",
    searchUrl: "https://www.lawa.org/lawa-businesses/lawa-procurement-services",
    domain: "www.lawa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Los Angeles World Airports procurement or business opportunities page.",
  },
  {
    id: "ca-sfo-business",
    name: "San Francisco International Airport Business Opportunities",
    jurisdiction: "San Francisco International Airport",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.flysfo.com/business-at-sfo",
    searchUrl: "https://www.flysfo.com/business-at-sfo",
    domain: "www.flysfo.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official San Francisco International Airport procurement or business opportunities page.",
  },
  {
    id: "ca-san-diego-airport-procurement",
    name: "San Diego County Regional Airport Authority Procurement",
    jurisdiction: "San Diego County Regional Airport Authority",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.san.org/business-opportunities/procurement",
    searchUrl: "https://www.san.org/business-opportunities/procurement",
    domain: "www.san.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official San Diego County Regional Airport Authority procurement or business opportunities page.",
  },
];
