import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_002: DirectRfpPortal[] = [
  {
    id: "vi-property-and-procurement",
    name: "USVI Department of Property and Procurement",
    jurisdiction: "U.S. Virgin Islands",
    state: "VI",
    country: "US",
    level: "district",
    url: "https://dpp.vi.gov/",
    searchUrl: "https://dpp.vi.gov/",
    domain: "dpp.vi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official U.S. Virgin Islands Department of Property and Procurement site.",
  },
  {
    id: "vt-burlington",
    name: "City of Burlington RFPs and Bids",
    jurisdiction: "City of Burlington",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.burlingtonvt.gov/RFP",
    searchUrl: "https://www.burlingtonvt.gov/RFP",
    domain: "burlingtonvt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Burlington RFP and bid posting page.",
  },
  {
    id: "az-phoenix",
    name: "City of Phoenix Finance Procurement",
    jurisdiction: "City of Phoenix",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.phoenix.gov/finance/vendorsreg",
    searchUrl: "https://www.phoenix.gov/finance/vendorsreg",
    domain: "phoenix.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official City of Phoenix procurement and vendor registration page.",
  },
  {
    id: "co-colorado-springs",
    name: "City of Colorado Springs Procurement Services",
    jurisdiction: "City of Colorado Springs",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://coloradosprings.gov/procurement-services",
    searchUrl: "https://coloradosprings.gov/procurement-services",
    domain: "coloradosprings.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Colorado Springs procurement services page.",
  },
  {
    id: "dc-water",
    name: "DC Water Procurement",
    jurisdiction: "District of Columbia Water and Sewer Authority",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.dcwater.com/procurement",
    searchUrl: "https://www.dcwater.com/procurement",
    domain: "dcwater.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official DC Water procurement page for water utility solicitations and vendor resources.",
  },
  {
    id: "la-baton-rouge",
    name: "City-Parish of Baton Rouge Purchasing",
    jurisdiction: "City of Baton Rouge and Parish of East Baton Rouge",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.brla.gov/150/Purchasing",
    searchUrl: "https://www.brla.gov/150/Purchasing",
    domain: "brla.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City-Parish purchasing page.",
  },
  {
    id: "nc-raleigh",
    name: "City of Raleigh Procurement",
    jurisdiction: "City of Raleigh",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://raleighnc.gov/doing-business/services/procurement",
    searchUrl: "https://raleighnc.gov/doing-business/services/procurement",
    domain: "raleighnc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Raleigh procurement page.",
  },
  {
    id: "or-trimet",
    name: "TriMet Procurement",
    jurisdiction: "Tri-County Metropolitan Transportation District of Oregon",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://trimet.org/procurement/",
    searchUrl: "https://trimet.org/procurement/",
    domain: "trimet.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official TriMet procurement page for transit contracting.",
  },
  {
    id: "tn-knoxville",
    name: "City of Knoxville Purchasing",
    jurisdiction: "City of Knoxville",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    searchUrl:
      "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    domain: "knoxvilletn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Knoxville purchasing page.",
  },
  {
    id: "ak-fairbanks-north-star-borough",
    name: "Fairbanks North Star Borough Purchasing",
    jurisdiction: "Fairbanks North Star Borough",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.fnsb.gov/452/Purchasing",
    searchUrl: "https://www.fnsb.gov/452/Purchasing",
    domain: "fnsb.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fairbanks North Star Borough purchasing page.",
  },
  {
    id: "dc-udc-procurement",
    name: "University of the District of Columbia Procurement",
    jurisdiction: "University of the District of Columbia",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    searchUrl:
      "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    domain: "udc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UDC contracts and procurement page.",
  },
  {
    id: "hi-university-of-hawaii-procurement",
    name: "University of Hawaii Procurement and Real Property Management",
    jurisdiction: "University of Hawaii System",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www.hawaii.edu/procurement/",
    searchUrl: "https://www.hawaii.edu/procurement/",
    domain: "hawaii.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Hawaii procurement page.",
  },
  {
    id: "id-boise",
    name: "City of Boise Purchasing",
    jurisdiction: "City of Boise",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    searchUrl:
      "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    domain: "cityofboise.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Boise purchasing page.",
  },
  {
    id: "il-university-of-illinois-procurement",
    name: "University of Illinois System Procurement Services",
    jurisdiction: "University of Illinois System",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.procure.stateuniv.state.il.us/",
    searchUrl: "https://www.procure.stateuniv.state.il.us/",
    domain: "procure.stateuniv.state.il.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Illinois System procurement services site.",
  },
];
