import type { DirectRfpPortal } from "./directRfpPortals";

const COUNTY_NAMES = [
  "Anderson",
  "Bedford",
  "Benton",
  "Bledsoe",
  "Blount",
  "Bradley",
  "Campbell",
  "Cannon",
  "Carroll",
  "Carter",
  "Cheatham",
  "Chester",
  "Claiborne",
  "Clay",
  "Cocke",
  "Coffee",
  "Crockett",
  "Cumberland",
  "Davidson",
  "Decatur",
  "DeKalb",
  "Dickson",
  "Dyer",
  "Fayette",
  "Fentress",
  "Franklin",
  "Gibson",
  "Giles",
  "Grainger",
  "Greene",
  "Grundy",
  "Hamblen",
  "Hamilton",
  "Hancock",
  "Hardeman",
  "Hardin",
  "Hawkins",
  "Haywood",
  "Henderson",
  "Henry",
  "Hickman",
  "Houston",
  "Humphreys",
  "Jackson",
  "Jefferson",
  "Johnson",
  "Knox",
  "Lake",
  "Lauderdale",
  "Lawrence",
  "Lewis",
  "Lincoln",
  "Loudon",
  "Macon",
  "Madison",
  "Marion",
  "Marshall",
  "Maury",
  "McMinn",
  "McNairy",
  "Meigs",
  "Monroe",
  "Montgomery",
  "Moore",
  "Morgan",
  "Obion",
  "Overton",
  "Perry",
  "Pickett",
  "Polk",
  "Putnam",
  "Rhea",
  "Roane",
  "Robertson",
  "Rutherford",
  "Scott",
  "Sequatchie",
  "Sevier",
  "Shelby",
  "Smith",
  "Stewart",
  "Sullivan",
  "Sumner",
  "Tipton",
  "Trousdale",
  "Unicoi",
  "Union",
  "Van Buren",
  "Warren",
  "Washington",
  "Wayne",
  "Weakley",
  "White",
  "Williamson",
  "Wilson",
] as const;

const CTAS_FALLBACK_NOTE =
  "County-specific Tennessee County Technical Assistance Service page retained as a fallback because this correction pass did not verify a stable direct source-of-truth procurement, finance, bid, public-notice, school-procurement, or buyer-specific portal for this county. Follow the listed county offices for department-specific opportunities. No Occu-Med-specific solicitation is claimed.";

function countySlug(countyName: string): string {
  return countyName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function ctasFallback(countyName: string): DirectRfpPortal {
  const slug = countySlug(countyName);
  return {
    id: `tn-${slug}-county`,
    name: `${countyName} County CTAS County Information`,
    jurisdiction: `${countyName} County`,
    state: "TN",
    country: "US",
    level: "district",
    url: `https://www.ctas.tennessee.edu/county/${slug}`,
    searchUrl: `https://www.ctas.tennessee.edu/county/${slug}`,
    domain: "www.ctas.tennessee.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: CTAS_FALLBACK_NOTE,
  };
}

const VERIFIED_REPLACEMENTS: Readonly<Record<string, DirectRfpPortal>> = {
  Anderson: {
    id: "tn-anderson-county",
    name: "Anderson County Purchasing",
    jurisdiction: "Anderson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://andersoncountytn.gov/purchasing/",
    searchUrl: "https://www.bidnetdirect.com/tennessee/andersoncounty",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Anderson County Purchasing page and its buyer-specific BidNet current-bids destination. The county purchasing office serves county departments and the school system.",
  },
  Blount: {
    id: "tn-blount-county",
    name: "Blount County Purchasing",
    jurisdiction: "Blount County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.blounttn.gov/1133/Purchasing-Home",
    searchUrl:
      "https://www.blounttn.gov/1256/Ionwave---Vendor-Bidding-Registration",
    domain: "www.blounttn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Blount County Purchasing source with the county's IonWave vendor bidding and registration destination.",
  },
  Bradley: {
    id: "tn-bradley-county",
    name: "Bradley County Schools Bids, RFPs and RFQs",
    jurisdiction: "Bradley County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.bradleyschools.org/district/bids-rfps-and-rfqs",
    searchUrl:
      "https://www.beaconbid.com/solicitations/bradley-county-schools/open",
    domain: "www.beaconbid.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Bradley County Schools procurement page linked to its buyer-scoped Beacon Bid open-solicitations listing.",
  },
  Coffee: {
    id: "tn-coffee-county",
    name: "Coffee County Bid Postings",
    jurisdiction: "Coffee County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.coffeecountytn.gov/Bids.aspx",
    searchUrl: "https://www.coffeecountytn.gov/Bids.aspx",
    domain: "www.coffeecountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Coffee County CivicEngage listing for current and historical bid and contract opportunities.",
  },
  Hamilton: {
    id: "tn-hamilton-county",
    name: "Hamilton County Financial Reporting and Transparency",
    jurisdiction: "Hamilton County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.hamiltontn.gov/Services_Transparency.aspx",
    searchUrl: "https://www.hamiltontn.gov/Services_Transparency.aspx",
    domain: "www.hamiltontn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Hamilton County financial-reporting and transparency destination with budgets, financial reports, spending reports, policies, and related county records.",
  },
  Knox: {
    id: "tn-knox-county",
    name: "Knox County Procurement",
    jurisdiction: "Knox County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxcounty.org/purchasing/",
    searchUrl:
      "https://www.knoxcounty.org/apps/solicitations/solicitations.php",
    domain: "www.knoxcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Knox County Procurement page and direct current-solicitations listing.",
  },
  Maury: {
    id: "tn-maury-county",
    name: "Maury County Bid Postings",
    jurisdiction: "Maury County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.maurycounty-tn.gov/Bids.aspx",
    searchUrl: "https://www.maurycounty-tn.gov/Bids.aspx",
    domain: "www.maurycounty-tn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Maury County CivicEngage listing for current and historical bid and contract opportunities.",
  },
  Montgomery: {
    id: "tn-montgomery-county",
    name: "Montgomery County Purchasing and Current Bids",
    jurisdiction: "Montgomery County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://mcgtn.org/purchasing",
    searchUrl: "https://mcgtn.org/purchasing/bids",
    domain: "mcgtn.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Montgomery County Purchasing page and direct current-bids listing; the county also links its Bonfire online bid portal.",
  },
  Shelby: {
    id: "tn-shelby-county",
    name: "Shelby County Purchasing Office",
    jurisdiction: "Shelby County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.shelbycountytn.gov/189/Purchasing",
    searchUrl:
      "https://www.shelbycountytn.gov/201/Conducting-Business-with-Shelby-County",
    domain: "www.shelbycountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Shelby County Purchasing Office and county vendor-facing procurement guidance covering bidding procedures, purchasing, and vendor registration.",
  },
  Sullivan: {
    id: "tn-sullivan-county",
    name: "Sullivan County Purchasing",
    jurisdiction: "Sullivan County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://sullivancountytn.gov/purchasing/",
    searchUrl: "https://www.bidnetdirect.com/tennessee/sullivancountytn",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Sullivan County Purchasing source and its buyer-specific BidNet current-solicitations destination for county departments, including education.",
  },
  Sumner: {
    id: "tn-sumner-county",
    name: "Sumner County Finance Purchasing and Bid Notices",
    jurisdiction: "Sumner County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://sumnercountytn.gov/departments/finance/purchasing/",
    searchUrl: "https://sumnercountytn.gov/departments/finance/purchasing/",
    domain: "sumnercountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Sumner County Finance purchasing page with current bid notices, requests for proposals and qualifications, and multi-year bid minutes and awards.",
  },
  Washington: {
    id: "tn-washington-county",
    name: "Washington County Bid Postings",
    jurisdiction: "Washington County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.washingtoncountytn.org/Bids.aspx",
    searchUrl: "https://www.washingtoncountytn.org/Bids.aspx",
    domain: "www.washingtoncountytn.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Washington County CivicEngage listing for current, closed, awarded, and cancelled bid and contract opportunities.",
  },
  Williamson: {
    id: "tn-williamson-county",
    name: "Williamson County Purchasing",
    jurisdiction: "Williamson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.williamsoncounty-tn.gov/406/Purchasing",
    searchUrl: "https://www.bidnetdirect.com/williamsoncounty",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Williamson County Purchasing page and its buyer-specific BidNet current-bid-opportunities destination.",
  },
};

export const GENERATED_DIRECT_RFP_PORTALS_046: DirectRfpPortal[] =
  COUNTY_NAMES.map(
    (countyName) =>
      VERIFIED_REPLACEMENTS[countyName] ?? ctasFallback(countyName),
  );
