import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_005: DirectRfpPortal[] = [
  {
    id: "ca-alameda-county",
    name: "Alameda County General Services Agency Procurement",
    jurisdiction: "Alameda County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://gsa.acgov.org/do-business-with-us/contracting-opportunities/",
    searchUrl:
      "https://gsa.acgov.org/do-business-with-us/contracting-opportunities/",
    domain: "gsa.acgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Alameda County contracting opportunities page.",
  },
  {
    id: "ca-san-mateo-county",
    name: "San Mateo County Procurement",
    jurisdiction: "San Mateo County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.smcgov.org/procurement",
    searchUrl: "https://www.smcgov.org/procurement",
    domain: "smcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official San Mateo County procurement page.",
  },
  {
    id: "ca-ventura-county",
    name: "Ventura County Purchasing",
    jurisdiction: "Ventura County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.ventura.org/general-services-agency/procurement-services/",
    searchUrl:
      "https://www.ventura.org/general-services-agency/procurement-services/",
    domain: "ventura.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ventura County procurement services page.",
  },
  {
    id: "ca-anaheim",
    name: "City of Anaheim Purchasing",
    jurisdiction: "City of Anaheim",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.anaheim.net/140/Purchasing",
    searchUrl: "https://www.anaheim.net/140/Purchasing",
    domain: "anaheim.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Anaheim purchasing page.",
  },
  {
    id: "ca-irvine",
    name: "City of Irvine Purchasing",
    jurisdiction: "City of Irvine",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.cityofirvine.org/purchasing",
    searchUrl: "https://www.cityofirvine.org/purchasing",
    domain: "cityofirvine.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Irvine purchasing page.",
  },
  {
    id: "ca-uc-system",
    name: "University of California Procurement",
    jurisdiction: "University of California",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.ucop.edu/procurement-services/",
    searchUrl: "https://www.ucop.edu/procurement-services/",
    domain: "ucop.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of California procurement services page.",
  },
];
