import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_008: DirectRfpPortal[] = [
  {
    id: "ny-nyc-dot",
    name: "New York City DOT Bid Opportunities",
    jurisdiction: "New York City Department of Transportation",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/html/dot/html/about/doing-business.shtml",
    searchUrl: "https://www.nyc.gov/html/dot/html/about/doing-business.shtml",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NYC DOT doing business page.",
  },
  {
    id: "ny-erie-county",
    name: "Erie County Purchasing",
    jurisdiction: "Erie County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www3.erie.gov/purchasing/",
    searchUrl: "https://www3.erie.gov/purchasing/",
    domain: "www3.erie.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Erie County purchasing page.",
  },
  {
    id: "ny-rochester-genesee-regional-transportation",
    name: "RGRTA Procurement",
    jurisdiction: "Rochester Genesee Regional Transportation Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.myrts.com/About-RTS/Procurement",
    searchUrl: "https://www.myrts.com/About-RTS/Procurement",
    domain: "myrts.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official RTS procurement page.",
  },
  {
    id: "ny-nycha",
    name: "NYCHA Procurement Opportunities",
    jurisdiction: "New York City Housing Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/site/nycha/business/procurement-opportunities.page",
    searchUrl:
      "https://www.nyc.gov/site/nycha/business/procurement-opportunities.page",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NYCHA procurement opportunities page.",
  },
];
