import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_004: DirectRfpPortal[] = [
  {
    id: "az-mesa",
    name: "City of Mesa Purchasing",
    jurisdiction: "City of Mesa",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.mesaaz.gov/business/purchasing",
    searchUrl: "https://www.mesaaz.gov/business/purchasing",
    domain: "mesaaz.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Mesa purchasing page for bid and vendor resources.",
  },
  {
    id: "ca-fresno",
    name: "City of Fresno Purchasing",
    jurisdiction: "City of Fresno",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.fresno.gov/finance/purchasing/",
    searchUrl: "https://www.fresno.gov/finance/purchasing/",
    domain: "fresno.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Fresno purchasing page for solicitations and vendor information.",
  },
  {
    id: "ca-san-diego-city",
    name: "City of San Diego Purchasing and Contracting",
    jurisdiction: "City of San Diego",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sandiego.gov/purchasing/bids-contracts",
    searchUrl: "https://www.sandiego.gov/purchasing/bids-contracts",
    domain: "sandiego.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official City of San Diego bids and contracts page.",
  },
  {
    id: "fl-st-petersburg",
    name: "City of St. Petersburg Procurement",
    jurisdiction: "City of St. Petersburg",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.stpete.org/business/procurement/index.php",
    searchUrl: "https://www.stpete.org/business/procurement/index.php",
    domain: "stpete.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of St. Petersburg procurement page.",
  },
  {
    id: "fl-tampa",
    name: "City of Tampa Purchasing",
    jurisdiction: "City of Tampa",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.tampa.gov/purchasing",
    searchUrl: "https://www.tampa.gov/purchasing",
    domain: "tampa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Tampa purchasing page.",
  },
  {
    id: "tx-fort-worth",
    name: "City of Fort Worth Purchasing",
    jurisdiction: "City of Fort Worth",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.fortworthtexas.gov/departments/finance/purchasing",
    searchUrl: "https://www.fortworthtexas.gov/departments/finance/purchasing",
    domain: "fortworthtexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Fort Worth purchasing page.",
  },
  {
    id: "tx-plano",
    name: "City of Plano Purchasing",
    jurisdiction: "City of Plano",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.plano.gov/194/Purchasing",
    searchUrl: "https://www.plano.gov/194/Purchasing",
    domain: "plano.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Plano purchasing page.",
  },
];
