import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_015: DirectRfpPortal[] = [
  {
    id: "md-baltimore-city",
    name: "Baltimore City Bureau of Procurement",
    jurisdiction: "City of Baltimore",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://bbmr.baltimorecity.gov/bureau-procurement",
    searchUrl: "https://bbmr.baltimorecity.gov/bureau-procurement",
    domain: "bbmr.baltimorecity.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Baltimore procurement page.",
  },
  {
    id: "tx-laredo",
    name: "City of Laredo Purchasing",
    jurisdiction: "City of Laredo",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.cityoflaredo.com/departments/financial-services/purchasing",
    searchUrl:
      "https://www.cityoflaredo.com/departments/financial-services/purchasing",
    domain: "cityoflaredo.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Laredo procurement page.",
  },
  {
    id: "il-will-county",
    name: "Will County Purchasing",
    jurisdiction: "Will County",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.willcountyillinois.com/County-Offices/Finance/Purchasing",
    searchUrl:
      "https://www.willcountyillinois.com/County-Offices/Finance/Purchasing",
    domain: "willcountyillinois.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Will County procurement page.",
  },
  {
    id: "pa-bucks-county",
    name: "Bucks County Purchasing",
    jurisdiction: "Bucks County",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.buckscounty.gov/149/Purchasing",
    searchUrl: "https://www.buckscounty.gov/149/Purchasing",
    domain: "buckscounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bucks County procurement page.",
  },
  {
    id: "co-jefferson-county",
    name: "Jefferson County Purchasing",
    jurisdiction: "Jefferson County",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.jeffco.us/2155/Purchasing",
    searchUrl: "https://www.jeffco.us/2155/Purchasing",
    domain: "jeffco.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jefferson County procurement page.",
  },
];
