import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_044: DirectRfpPortal[] = [
  {
    id: "or-benton-county",
    name: "Benton County Requests for Proposals",
    jurisdiction: "Benton County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://finance.bentoncountyor.gov/requests-for-proposals-rfps/",
    searchUrl:
      "https://finance.bentoncountyor.gov/requests-for-proposals-rfps/",
    domain: "finance.bentoncountyor.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Benton County Financial Services RFP entry point. The county directs vendors to its buyer-specific DemandStar page but also permits vendors to request opportunities directly; the aggregator URL is intentionally not cataloged as the source URL. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-clackamas-county",
    name: "Clackamas County Procurement Opportunities",
    jurisdiction: "Clackamas County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.clackamas.us/finance/purchasing",
    searchUrl: "https://bidlocker.us/a/clackamascounty/BidLocker",
    domain: "bidlocker.us",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Clackamas County procurement entry point and county-specific BidLocker opportunity portal. Public opportunity browsing does not require a login; registration may be required to respond. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-clatsop-county",
    name: "Clatsop County Bid Postings",
    jurisdiction: "Clatsop County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.clatsopcounty.gov/1257/Job-Opportunities-BidsRFPs",
    searchUrl: "https://www.clatsopcounty.gov/bids.aspx",
    domain: "www.clatsopcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Clatsop County bid-postings page for county solicitations and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-coos-county",
    name: "Coos County Bid Notices",
    jurisdiction: "Coos County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://co.coos.or.us/roads",
    searchUrl: "https://co.coos.or.us/bid-notice",
    domain: "co.coos.or.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Coos County Road Department bid-notice listing. Other county departments may publish additional solicitations separately. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-crook-county",
    name: "Crook County Bid Postings",
    jurisdiction: "Crook County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://crookcountyor.gov/bids.aspx",
    searchUrl: "https://crookcountyor.gov/bids.aspx",
    domain: "crookcountyor.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Crook County bid-postings page for county solicitation and contracting opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-curry-county",
    name: "Curry County Requests for Proposals",
    jurisdiction: "Curry County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.currycountyor.gov/government/request_for_proposals.php",
    searchUrl:
      "https://www.currycountyor.gov/government/request_for_proposals.php",
    domain: "www.currycountyor.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Curry County request-for-proposals document listing. Browser-compatible access is required because the county site blocks direct automated requests. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-deschutes-county",
    name: "Deschutes County Procurement Opportunities",
    jurisdiction: "Deschutes County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.deschutescounty.gov/721/Procurement",
    searchUrl: "https://bidlocker.us/a/deschutescounty/BidLocker",
    domain: "bidlocker.us",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Deschutes County procurement entry point and county-specific BidLocker opportunity portal. Public opportunity browsing does not require a login; registration may be required to respond. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-grant-county",
    name: "Grant County Bid Postings",
    jurisdiction: "Grant County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://grantcountyoregon.net/Bids.aspx",
    searchUrl: "https://grantcountyoregon.net/Bids.aspx",
    domain: "grantcountyoregon.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Grant County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-hood-river-county",
    name: "Hood River County RFP and Bid Documents",
    jurisdiction: "Hood River County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.hoodrivercounty.gov/?SEC=3F86B7A7-6605-4973-9884-C29DA41C6166",
    searchUrl:
      "https://www.hoodrivercounty.gov/?SEC=3F86B7A7-6605-4973-9884-C29DA41C6166",
    domain: "www.hoodrivercounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Hood River County RFP and other bid-document listing. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-jackson-county",
    name: "Jackson County RFPs and Bids",
    jurisdiction: "Jackson County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.jacksoncountyor.gov/government/rfps___bids/index.php",
    searchUrl:
      "https://www.jacksoncountyor.gov/government/rfps___bids/index.php",
    domain: "www.jacksoncountyor.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Jackson County RFP and bid listing with current, closed, and addendum documents. Browser-compatible access is required because the county site blocks direct automated requests. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-josephine-county",
    name: "Josephine County Requests for Proposals",
    jurisdiction: "Josephine County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.josephinecounty.gov/residents/rfps.php",
    searchUrl: "https://www.josephinecounty.gov/residents/rfps.php",
    domain: "www.josephinecounty.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Josephine County RFP entry point; Public Works also maintains a department-specific RFP page. Browser-compatible access is required because the county site blocks direct automated requests. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-klamath-county",
    name: "Klamath County Bid Postings",
    jurisdiction: "Klamath County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.klamathcounty.org/150/Bid-Process",
    searchUrl: "https://www.klamathcounty.org/bids.aspx",
    domain: "www.klamathcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Klamath County bid-process and bid-postings source for county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-lake-county",
    name: "Lake County Open Bids and RFPs",
    jurisdiction: "Lake County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.lakecountyor.org/open_bids_rfps.php",
    searchUrl: "https://www.lakecountyor.org/open_bids_rfps.php",
    domain: "www.lakecountyor.org",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Lake County open-bids-and-RFPs listing. Browser-compatible access is required because the county site blocks direct automated requests. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-lane-county",
    name: "Lane County Procurement Opportunities",
    jurisdiction: "Lane County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.lanecountyor.gov/government/budget_and_finance/procurement_and_purchasing",
    searchUrl: "https://bidlocker.us/a/lanecounty/BidLocker",
    domain: "bidlocker.us",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Lane County procurement entry point and county-specific BidLocker opportunity portal used for county solicitations. Public opportunity browsing does not require a login; registration may be required to respond. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-lincoln-county",
    name: "Lincoln County Bids and RFPs",
    jurisdiction: "Lincoln County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.co.lincoln.or.us/966/Bids-RFPs",
    searchUrl: "https://www.co.lincoln.or.us/Bids.aspx",
    domain: "www.co.lincoln.or.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Lincoln County bids-and-RFPs entry point and bid-postings listing. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-malheur-county",
    name: "Malheur County Bid Process",
    jurisdiction: "Malheur County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.malheurco.org/county-court/bid-process/",
    searchUrl: "https://www.malheurco.org/county-court/bid-process/",
    domain: "www.malheurco.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Malheur County bid-process page that links available projects to their solicitation details. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-marion-county",
    name: "Marion County Contracting Opportunities",
    jurisdiction: "Marion County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.co.marion.or.us/FIN/pages/contracts.aspx",
    searchUrl: "https://contracts-marioncountygcc.msappproxy.net/gateway/",
    domain: "contracts-marioncountygcc.msappproxy.net",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Marion County contracting-opportunities entry point and county Procurement Collaboration Portal. Public portal access is available without a login; an account may be required to participate. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-morrow-county",
    name: "Morrow County Bids and RFPs",
    jurisdiction: "Morrow County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.morrowcountyor.gov/rfps",
    searchUrl: "https://www.morrowcountyor.gov/rfps",
    domain: "www.morrowcountyor.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Morrow County bids-and-RFPs listing for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-tillamook-county",
    name: "Tillamook County Bids and RFPs",
    jurisdiction: "Tillamook County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.tillamookcounty.gov/rfps",
    searchUrl: "https://www.tillamookcounty.gov/rfps",
    domain: "www.tillamookcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Tillamook County bids-and-RFPs listing for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-umatilla-county",
    name: "Umatilla County Public Notices and RFPs",
    jurisdiction: "Umatilla County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://umatillacounty.net/",
    searchUrl: "https://umatillacounty.net/public-notices",
    domain: "umatillacounty.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Umatilla County public-notices source covering announcements, public notices, and RFPs. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-union-county",
    name: "Union County RFP Notices",
    jurisdiction: "Union County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://unioncountyor.gov/category/public-notice/",
    searchUrl: "https://unioncountyor.gov/category/rfp/",
    domain: "unioncountyor.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Union County RFP category and public-notice archive for county solicitation opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-wasco-county",
    name: "Wasco County Bids and Contracts",
    jurisdiction: "Wasco County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.wascocountyor.gov/departments/public_works/",
    searchUrl:
      "https://www.wascocountyor.gov/departments/public_works/bids_and_contracts.php",
    domain: "www.wascocountyor.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Wasco County Public Works bids-and-contracts listing. Browser-compatible access is required because the county site blocks direct automated requests; other departments may advertise separately. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-yamhill-county",
    name: "Yamhill County Bid Postings",
    jurisdiction: "Yamhill County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.yamhillcounty.gov/Bids.aspx",
    searchUrl: "https://www.yamhillcounty.gov/Bids.aspx",
    domain: "www.yamhillcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Yamhill County bid-postings page for RFI, RFP, RFQ, ITB, and notice-of-intent opportunities. No Occu-Med-specific solicitation is claimed.",
  }
];
