import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_046: DirectRfpPortal[] = [
  {
    id: "tn-anderson-county",
    name: "Anderson County Purchasing",
    jurisdiction: "Anderson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://andersoncountytn.gov/purchasing/",
    searchUrl: "https://www.bidnetdirect.com/tennessee/andersoncounty",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Anderson County Purchasing page and its buyer-specific BidNet current-bids destination. The county purchasing office serves county departments and the school system.",
  },
  {
    id: "tn-bledsoe-county",
    name: "Bledsoe County Public Notices and Budget",
    jurisdiction: "Bledsoe County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://bledsoetn.com/",
    searchUrl: "https://bledsoetn.com/",
    domain: "bledsoetn.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Bledsoe County source with a public-notice archive, county budget access, and notices that include bidding actions.",
  },
  {
    id: "tn-blount-county",
    name: "Blount County Purchasing",
    jurisdiction: "Blount County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.blounttn.gov/1133/Purchasing-Home",
    searchUrl: "https://www.blounttn.gov/1256/Ionwave---Vendor-Bidding-Registration",
    domain: "www.blounttn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Blount County Purchasing source with the county's IonWave vendor bidding and registration destination.",
  },
  {
    id: "tn-campbell-county",
    name: "Campbell County Announcements and Public Notices",
    jurisdiction: "Campbell County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://campbellcountytn.gov/announcements-and-events/",
    searchUrl: "https://campbellcountytn.gov/announcements-and-events/",
    domain: "campbellcountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Campbell County announcements and public-notices source for commission, department, budget, finance, and other county-government notices.",
  },
  {
    id: "tn-cheatham-county",
    name: "Cheatham County Public Notices and Bid Notices",
    jurisdiction: "Cheatham County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.cheathamcountytn.gov/calendar.html",
    searchUrl: "https://www.cheathamcountytn.gov/calendar.html",
    domain: "www.cheathamcountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Cheatham County public-notices page, including county budget notices and department-specific sealed-bid notices.",
  },
  {
    id: "tn-coffee-county",
    name: "Coffee County Bid Postings",
    jurisdiction: "Coffee County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.coffeecountytn.gov/Bids.aspx",
    searchUrl: "https://www.coffeecountytn.gov/Bids.aspx",
    domain: "www.coffeecountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Coffee County CivicEngage listing for current and historical bid and contract opportunities.",
  },
  {
    id: "tn-cumberland-county",
    name: "Cumberland County Finance and Procurement Notices",
    jurisdiction: "Cumberland County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://cumberlandcountytn.gov/directory/finance/",
    searchUrl: "https://cumberlandcountytn.gov/directory/finance/",
    domain: "cumberlandcountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Cumberland County Finance Department page publishing procurement documents, including RFP and RFQ files, alongside financial records.",
  },
  {
    id: "tn-greene-county",
    name: "Greene County Purchasing",
    jurisdiction: "Greene County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.greenecountytngov.com/purchasing/",
    searchUrl: "https://www.greenecountytngov.com/purchasing/",
    domain: "www.greenecountytngov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Greene County Purchasing source for the county's central buying agency, current bid solicitations, bid documents, and buyer-specific public-purchase links.",
  },
  {
    id: "tn-johnson-county",
    name: "Johnson County Purchasing Department",
    jurisdiction: "Johnson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.johnsoncountytn.gov/purchasing-department",
    searchUrl: "https://www.johnsoncountytn.gov/purchasing-department",
    domain: "www.johnsoncountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Johnson County Purchasing Department page with open RFQs, invitations to bid, vendor registration, and a buyer-specific open-solicitations link.",
  },
  {
    id: "tn-knox-county",
    name: "Knox County Procurement",
    jurisdiction: "Knox County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxcounty.org/purchasing/",
    searchUrl: "https://www.knoxcounty.org/apps/solicitations/solicitations.php",
    domain: "www.knoxcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Knox County Procurement page and direct current-solicitations listing.",
  },
  {
    id: "tn-lawrence-county",
    name: "Lawrence County News and Procurement Notices",
    jurisdiction: "Lawrence County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://lawrencecountytn.gov/news/",
    searchUrl: "https://lawrencecountytn.gov/news/",
    domain: "lawrencecountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Lawrence County news and notice archive publishing invitations to bid, annual-bid packets, requests, and county financial notices.",
  },
  {
    id: "tn-loudon-county",
    name: "Loudon County Announcements and Public Notices",
    jurisdiction: "Loudon County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://loudoncounty-tn.gov/announcements/",
    searchUrl: "https://loudoncounty-tn.gov/announcements/",
    domain: "loudoncounty-tn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Loudon County announcements source for county commission, budget, capital-project, purchasing-committee, and other public notices.",
  },
  {
    id: "tn-madison-county",
    name: "Madison County Bid Postings",
    jurisdiction: "Madison County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.madisoncountytn.gov/Bids.aspx",
    searchUrl: "https://www.madisoncountytn.gov/Bids.aspx",
    domain: "www.madisoncountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Madison County bid-postings page for current, closed, awarded, and cancelled county solicitations and downloadable bid packages.",
  },
  {
    id: "tn-maury-county",
    name: "Maury County Bid Postings",
    jurisdiction: "Maury County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.maurycounty-tn.gov/Bids.aspx",
    searchUrl: "https://www.maurycounty-tn.gov/Bids.aspx",
    domain: "www.maurycounty-tn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Maury County CivicEngage listing for current and historical bid and contract opportunities.",
  },
  {
    id: "tn-montgomery-county",
    name: "Montgomery County Purchasing and Current Bids",
    jurisdiction: "Montgomery County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://mcgtn.org/purchasing",
    searchUrl: "https://mcgtn.org/purchasing/bids",
    domain: "mcgtn.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Montgomery County Purchasing page and direct current-bids listing; the county also links its Bonfire online bid portal.",
  },
  {
    id: "tn-shelby-county",
    name: "Shelby County Purchasing Office",
    jurisdiction: "Shelby County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.shelbycountytn.gov/189/Purchasing",
    searchUrl: "https://www.shelbycountytn.gov/201/Conducting-Business-with-Shelby-County",
    domain: "www.shelbycountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Shelby County Purchasing Office and county vendor-facing procurement guidance covering bidding procedures, purchasing, and vendor registration.",
  },
  {
    id: "tn-sullivan-county",
    name: "Sullivan County Purchasing",
    jurisdiction: "Sullivan County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://sullivancountytn.gov/purchasing/",
    searchUrl: "https://www.bidnetdirect.com/tennessee/sullivancountytn",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Sullivan County Purchasing source and its buyer-specific BidNet current-solicitations destination for county departments, including education.",
  },
  {
    id: "tn-union-county",
    name: "Union County Accounts and Budgets",
    jurisdiction: "Union County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.unioncountytn.gov/accounts-and-budgets/",
    searchUrl: "https://www.unioncountytn.gov/accounts-and-budgets/",
    domain: "www.unioncountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Union County accounts-and-budgets source linking the current county budget, audit, and related financial records.",
  },
  {
    id: "tn-washington-county",
    name: "Washington County Bid Postings",
    jurisdiction: "Washington County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.washingtoncountytn.org/Bids.aspx",
    searchUrl: "https://www.washingtoncountytn.org/Bids.aspx",
    domain: "www.washingtoncountytn.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Washington County CivicEngage listing for current, closed, awarded, and cancelled bid and contract opportunities.",
  },
  {
    id: "tn-weakley-county",
    name: "Weakley County Finance Bids and Purchasing",
    jurisdiction: "Weakley County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.weakleycountytn.gov/bids--purchasing.html",
    searchUrl: "https://www.weakleycountytn.gov/bids--purchasing.html",
    domain: "www.weakleycountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Weakley County Department of Finance bids-and-purchasing page for current county bids, RFPs, bid specifications, awards, and purchasing information.",
  },
  {
    id: "tn-williamson-county",
    name: "Williamson County Purchasing",
    jurisdiction: "Williamson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.williamsoncounty-tn.gov/406/Purchasing",
    searchUrl: "https://www.bidnetdirect.com/williamsoncounty",
    domain: "www.bidnetdirect.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Williamson County Purchasing page and its buyer-specific BidNet current-bid-opportunities destination.",
  },
  {
    id: "tn-wilson-county",
    name: "Wilson County Bid Postings",
    jurisdiction: "Wilson County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.wilsoncountytn.gov/Bids.aspx",
    searchUrl: "https://www.wilsoncountytn.gov/Bids.aspx",
    domain: "www.wilsoncountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official Wilson County bid-postings page for current, closed, awarded, and cancelled county contract opportunities.",
  }
];
