import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_003: DirectRfpPortal[] = [
  {
    id: "ky-lexington",
    name: "Lexington-Fayette Urban County Government Purchasing",
    jurisdiction: "Lexington-Fayette Urban County Government",
    state: "KY",
    country: "US",
    level: "district",
    url: "https://www.lexingtonky.gov/procurement",
    searchUrl: "https://www.lexingtonky.gov/procurement",
    domain: "lexingtonky.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lexington procurement page.",
  },
  {
    id: "la-jefferson-parish",
    name: "Jefferson Parish Purchasing",
    jurisdiction: "Jefferson Parish",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.jeffparish.gov/464/Purchasing",
    searchUrl: "https://www.jeffparish.gov/464/Purchasing",
    domain: "jeffparish.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jefferson Parish purchasing page.",
  },
  {
    id: "ms-hinds-county",
    name: "Hinds County Purchasing",
    jurisdiction: "Hinds County",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.hindscountyms.com/departments/purchasing",
    searchUrl: "https://www.hindscountyms.com/departments/purchasing",
    domain: "hindscountyms.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Hinds County purchasing page.",
  },
  {
    id: "ne-lincoln",
    name: "City of Lincoln Purchasing",
    jurisdiction: "City of Lincoln",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    searchUrl: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    domain: "lincoln.ne.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lincoln purchasing page.",
  },
  {
    id: "nc-guilford-county",
    name: "Guilford County Purchasing",
    jurisdiction: "Guilford County",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.guilfordcountync.gov/our-county/purchasing",
    searchUrl: "https://www.guilfordcountync.gov/our-county/purchasing",
    domain: "guilfordcountync.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Guilford County purchasing page.",
  },
  {
    id: "nd-bismarck",
    name: "City of Bismarck Purchasing",
    jurisdiction: "City of Bismarck",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://www.bismarcknd.gov/88/Purchasing",
    searchUrl: "https://www.bismarcknd.gov/88/Purchasing",
    domain: "bismarcknd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bismarck purchasing page.",
  },
  {
    id: "ok-tulsa",
    name: "City of Tulsa Purchasing",
    jurisdiction: "City of Tulsa",
    state: "OK",
    country: "US",
    level: "district",
    url: "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    searchUrl:
      "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    domain: "cityoftulsa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tulsa purchasing page.",
  },
  {
    id: "or-multnomah-county",
    name: "Multnomah County Purchasing",
    jurisdiction: "Multnomah County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.multco.us/purchasing",
    searchUrl: "https://www.multco.us/purchasing",
    domain: "multco.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Multnomah County purchasing page.",
  },
  {
    id: "pa-philadelphia",
    name: "City of Philadelphia Procurement Department",
    jurisdiction: "City of Philadelphia",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.phila.gov/departments/procurement-department/",
    searchUrl: "https://www.phila.gov/departments/procurement-department/",
    domain: "phila.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Philadelphia Procurement Department page.",
  },
  {
    id: "sc-greenville-county",
    name: "Greenville County Procurement Services",
    jurisdiction: "Greenville County",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://www.greenvillecounty.org/Procurement/",
    searchUrl: "https://www.greenvillecounty.org/Procurement/",
    domain: "greenvillecounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Greenville County procurement services page.",
  },
  {
    id: "ut-salt-lake-county",
    name: "Salt Lake County Contracts and Procurement",
    jurisdiction: "Salt Lake County",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.saltlakecounty.gov/contracts/",
    searchUrl: "https://www.saltlakecounty.gov/contracts/",
    domain: "saltlakecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Salt Lake County contracts and procurement page.",
  },
  {
    id: "wi-madison",
    name: "City of Madison Purchasing Services",
    jurisdiction: "City of Madison",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://www.cityofmadison.com/finance/purchasing/",
    searchUrl: "https://www.cityofmadison.com/finance/purchasing/",
    domain: "cityofmadison.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Madison purchasing services page.",
  },
];
