import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_027: DirectRfpPortal[] = [
  {
    id: "ca-stockton-purchasing",
    name: "City of Stockton Purchasing",
    jurisdiction: "City of Stockton",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.stocktonca.gov/government/departments/adminServices/purch.html",
    searchUrl:
      "https://www.stocktonca.gov/government/departments/adminServices/purch.html",
    domain: "www.stocktonca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Stockton procurement or business opportunities page.",
  },
  {
    id: "ca-fremont-purchasing",
    name: "City of Fremont Purchasing",
    jurisdiction: "City of Fremont",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.fremont.gov/government/departments/finance/purchasing",
    searchUrl:
      "https://www.fremont.gov/government/departments/finance/purchasing",
    domain: "www.fremont.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Fremont procurement or business opportunities page.",
  },
  {
    id: "ca-san-bernardino-purchasing",
    name: "City of San Bernardino Purchasing",
    jurisdiction: "City of San Bernardino",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sbcity.org/city_hall/finance/purchasing",
    searchUrl: "https://www.sbcity.org/city_hall/finance/purchasing",
    domain: "www.sbcity.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of San Bernardino procurement or business opportunities page.",
  },
  {
    id: "tx-houston-procurement",
    name: "City of Houston Strategic Procurement",
    jurisdiction: "City of Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.houstontx.gov/obo/procurement.html",
    searchUrl: "https://www.houstontx.gov/obo/procurement.html",
    domain: "www.houstontx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Houston procurement or business opportunities page.",
  },
  {
    id: "tx-san-antonio-purchasing",
    name: "City of San Antonio Purchasing",
    jurisdiction: "City of San Antonio",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.sa.gov/Directory/Departments/Finance/About/Divisions/Procurement",
    searchUrl:
      "https://www.sa.gov/Directory/Departments/Finance/About/Divisions/Procurement",
    domain: "www.sa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of San Antonio procurement or business opportunities page.",
  },
];
