import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_009: DirectRfpPortal[] = [
  {
    id: "ca-san-bernardino-county",
    name: "San Bernardino County Purchasing",
    jurisdiction: "San Bernardino County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://wp.sbcounty.gov/purchasing/",
    searchUrl: "https://wp.sbcounty.gov/purchasing/",
    domain: "wp.sbcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official San Bernardino County procurement page.",
  },
  {
    id: "ca-sacramento-city",
    name: "City of Sacramento Procurement Services",
    jurisdiction: "City of Sacramento",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.cityofsacramento.gov/finance/procurement",
    searchUrl: "https://www.cityofsacramento.gov/finance/procurement",
    domain: "cityofsacramento.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Sacramento procurement page.",
  },
];
