import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_008: DirectRfpPortal[] = [
  {
    id: "ny-nyc-ddc",
    name: "New York City DDC RFPs and RFQs",
    jurisdiction: "New York City Department of Design and Construction",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/site/ddc/contracts/rfps-rfqs.page",
    searchUrl: "https://www.nyc.gov/site/ddc/contracts/rfps-rfqs.page",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official NYC DDC RFP and RFQ page.",
  },
  {
    id: "ny-nyc-dot",
    name: "New York City DOT Bid Opportunities",
    jurisdiction: "New York City Department of Transportation",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/html/dot/html/about/doing-business.shtml",
    searchUrl: "https://www.nyc.gov/html/dot/html/about/doing-business.shtml",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NYC DOT doing business page.",
  },
  {
    id: "ny-albany-county",
    name: "Albany County Purchasing",
    jurisdiction: "Albany County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.albanycountyny.gov/departments/purchasing",
    searchUrl: "https://www.albanycountyny.gov/departments/purchasing",
    domain: "albanycountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Albany County purchasing page.",
  },
  {
    id: "ny-erie-county",
    name: "Erie County Purchasing",
    jurisdiction: "Erie County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www3.erie.gov/purchasing/",
    searchUrl: "https://www3.erie.gov/purchasing/",
    domain: "www3.erie.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Erie County purchasing page.",
  },
  {
    id: "ny-suffolk-county",
    name: "Suffolk County Purchasing",
    jurisdiction: "Suffolk County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.suffolkcountyny.gov/Departments/Purchasing",
    searchUrl: "https://www.suffolkcountyny.gov/Departments/Purchasing",
    domain: "suffolkcountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Suffolk County purchasing page.",
  },
  {
    id: "ny-nassau-county",
    name: "Nassau County Purchasing",
    jurisdiction: "Nassau County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nassaucountyny.gov/1559/Purchasing",
    searchUrl: "https://www.nassaucountyny.gov/1559/Purchasing",
    domain: "nassaucountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Nassau County purchasing page.",
  },
  {
    id: "ny-buffalo",
    name: "City of Buffalo Purchasing",
    jurisdiction: "City of Buffalo",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.buffalony.gov/313/Purchasing",
    searchUrl: "https://www.buffalony.gov/313/Purchasing",
    domain: "buffalony.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Buffalo purchasing page.",
  },
  {
    id: "ny-rochester",
    name: "City of Rochester Purchasing",
    jurisdiction: "City of Rochester",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.cityofrochester.gov/departments/purchasing",
    searchUrl: "https://www.cityofrochester.gov/departments/purchasing",
    domain: "cityofrochester.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Rochester purchasing page.",
  },
  {
    id: "ny-syracuse",
    name: "City of Syracuse Purchasing",
    jurisdiction: "City of Syracuse",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.syr.gov/Departments/Finance/Purchasing",
    searchUrl: "https://www.syr.gov/Departments/Finance/Purchasing",
    domain: "syr.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Syracuse purchasing page.",
  },
  {
    id: "ny-albany-city",
    name: "City of Albany Purchasing",
    jurisdiction: "City of Albany",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.albanyny.gov/331/Purchasing",
    searchUrl: "https://www.albanyny.gov/331/Purchasing",
    domain: "albanyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Albany purchasing page.",
  },
  {
    id: "ny-suny",
    name: "SUNY Procurement",
    jurisdiction: "State University of New York",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.suny.edu/meansbusiness/",
    searchUrl: "https://www.suny.edu/meansbusiness/",
    domain: "suny.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official SUNY business and procurement opportunities page.",
  },
  {
    id: "ny-cuny",
    name: "CUNY Procurement",
    jurisdiction: "City University of New York",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.cuny.edu/about/administration/offices/budget-and-finance/procurement/",
    searchUrl:
      "https://www.cuny.edu/about/administration/offices/budget-and-finance/procurement/",
    domain: "cuny.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CUNY procurement page.",
  },
  {
    id: "ny-buffalo-niagara-airport",
    name: "Buffalo Niagara International Airport Business Opportunities",
    jurisdiction: "Niagara Frontier Transportation Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nfta.com/business-center/procurement",
    searchUrl: "https://www.nfta.com/business-center/procurement",
    domain: "nfta.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NFTA procurement page.",
  },
  {
    id: "ny-nfta",
    name: "Niagara Frontier Transportation Authority Procurement",
    jurisdiction: "Niagara Frontier Transportation Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nfta.com/business-center/procurement",
    searchUrl: "https://www.nfta.com/business-center/procurement",
    domain: "nfta.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NFTA procurement page.",
  },
  {
    id: "ny-rochester-genesee-regional-transportation",
    name: "RGRTA Procurement",
    jurisdiction: "Rochester Genesee Regional Transportation Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.myrts.com/About-RTS/Procurement",
    searchUrl: "https://www.myrts.com/About-RTS/Procurement",
    domain: "myrts.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official RTS procurement page.",
  },
  {
    id: "ny-monroe-county-water-authority",
    name: "Monroe County Water Authority Purchasing",
    jurisdiction: "Monroe County Water Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.mcwa.com/about/purchasing/",
    searchUrl: "https://www.mcwa.com/about/purchasing/",
    domain: "mcwa.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official MCWA purchasing page.",
  },
  {
    id: "ny-nycha",
    name: "NYCHA Procurement Opportunities",
    jurisdiction: "New York City Housing Authority",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/site/nycha/business/procurement-opportunities.page",
    searchUrl:
      "https://www.nyc.gov/site/nycha/business/procurement-opportunities.page",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NYCHA procurement opportunities page.",
  },
  {
    id: "ny-buffalo-schools",
    name: "Buffalo Public Schools Purchasing",
    jurisdiction: "Buffalo Public Schools",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.buffaloschools.org/Page/360",
    searchUrl: "https://www.buffaloschools.org/Page/360",
    domain: "buffaloschools.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Buffalo Public Schools purchasing page.",
  },
  {
    id: "ny-rochester-schools",
    name: "Rochester City School District Purchasing",
    jurisdiction: "Rochester City School District",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.rcsdk12.org/Page/808",
    searchUrl: "https://www.rcsdk12.org/Page/808",
    domain: "rcsdk12.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official RCSD purchasing page.",
  },
  {
    id: "ny-syracuse-schools",
    name: "Syracuse City School District Purchasing",
    jurisdiction: "Syracuse City School District",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.syracusecityschools.com/districtpage.cfm?pageid=539",
    searchUrl:
      "https://www.syracusecityschools.com/districtpage.cfm?pageid=539",
    domain: "syracusecityschools.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Syracuse City School District purchasing page.",
  },
  {
    id: "ny-onondaga-county",
    name: "Onondaga County Purchasing",
    jurisdiction: "Onondaga County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.ongov.net/purchase/",
    searchUrl: "https://www.ongov.net/purchase/",
    domain: "ongov.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Onondaga County purchasing page.",
  },
];
