import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_041: DirectRfpPortal[] = [
  {
    id: "ca-city-of-santa-cruz-opengov",
    name: "City of Santa Cruz Procurement Portal",
    jurisdiction: "City of Santa Cruz",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/santacruzca",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/santacruzca/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for City of Santa Cruz public RFP, RFQ, RFI, and project opportunities; active project browsing is public. Broad official source; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-city-of-palm-desert-opengov",
    name: "City of Palm Desert Procurement Portal",
    jurisdiction: "City of Palm Desert",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/cityofpalmdesert",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/cityofpalmdesert/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for City of Palm Desert public RFP, RFQ, RFI, and project opportunities; active project browsing is public. Broad official source; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-city-of-west-sacramento-opengov",
    name: "City of West Sacramento Procurement Portal",
    jurisdiction: "City of West Sacramento",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/cityofwestsacramento",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/cityofwestsacramento/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for City of West Sacramento public RFP, RFQ, RFI, and project opportunities; active project browsing is public. Broad official source; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "pa-scranton-city-school-district-opengov",
    name: "Scranton City School District Procurement Portal",
    jurisdiction: "Scranton City School District",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/ssdedu",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/ssdedu/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Scranton City School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-monroe-county-school-district-opengov",
    name: "Monroe County School District, FL Procurement Portal",
    jurisdiction: "Monroe County School District",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/keyschools-mcsd",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/keyschools-mcsd/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Monroe County School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "nj-passaic-city-school-district-opengov",
    name: "Passaic City School District Procurement Portal",
    jurisdiction: "Passaic City School District",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/passaicschools",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/passaicschools/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Passaic City School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-volusia-county-opengov",
    name: "County of Volusia Procurement Portal",
    jurisdiction: "Volusia County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/volusia",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/volusia/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Volusia County public RFP, RFQ, RFI, and project opportunities; active project browsing is public. County public-safety and operational workforces provide a likely-fit basis, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-pinellas-county-school-district-opengov",
    name: "Pinellas County School District Procurement Portal",
    jurisdiction: "Pinellas County School District",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/pcsb",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/pcsb/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Pinellas County School District public RFP, RFQ, RFI, and project opportunities; active project browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "nj-jersey-city-public-schools-opengov",
    name: "Jersey City Public Schools Procurement Portal",
    jurisdiction: "Jersey City Public Schools",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/jcboe",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/jcboe/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Jersey City Public Schools public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-santa-rosa-county-opengov",
    name: "Santa Rosa County Procurement Portal",
    jurisdiction: "Santa Rosa County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/santarosafl",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/santarosafl/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Santa Rosa County public RFP, RFQ, RFI, and project opportunities; active project browsing is public. County public-safety and operational workforces provide a likely-fit basis, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "oh-cleveland-metropolitan-school-district-opengov",
    name: "Cleveland Metropolitan School District Procurement Portal",
    jurisdiction: "Cleveland Metropolitan School District",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/clevelandmetroschools",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/clevelandmetroschools/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov project-list portal for Cleveland Metropolitan School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "ca-san-bernardino-city-unified-school-district-opengov",
    name: "San Bernardino City Unified School District Procurement Portal",
    jurisdiction: "San Bernardino City Unified School District",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/sbcusd",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/sbcusd/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for San Bernardino City Unified School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-alachua-county-opengov",
    name: "Alachua County, Florida Procurement Portal",
    jurisdiction: "Alachua County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/alachuacounty",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/alachuacounty/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Alachua County public RFP, RFQ, RFI, and project opportunities; active project browsing is public. County public-safety and operational workforces provide a likely-fit basis, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "va-richmond-public-schools-opengov",
    name: "Richmond Public Schools Procurement Portal",
    jurisdiction: "Richmond Public Schools",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/rvaschools",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/rvaschools/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Richmond Public Schools public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "fl-clay-county-opengov",
    name: "Clay County Procurement Portal",
    jurisdiction: "Clay County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/claycounty",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/claycounty/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Clay County public RFP, RFQ, RFI, and project opportunities; active project browsing is public. County public-safety and operational workforces provide a likely-fit basis, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "az-chandler-unified-school-district-opengov",
    name: "Chandler Unified School District Procurement Portal",
    jurisdiction: "Chandler Unified School District",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/cusd80",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/cusd80/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Chandler Unified School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "md-wicomico-county-opengov",
    name: "Wicomico County Procurement Portal",
    jurisdiction: "Wicomico County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/wicomicocounty",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/wicomicocounty/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Wicomico County public RFP, RFQ, RFI, and project opportunities; active project browsing is public. County public-safety and operational workforces provide a likely-fit basis, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "sc-richland-school-district-two-opengov",
    name: "Richland School District Two Procurement Portal",
    jurisdiction: "Richland School District Two",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/richland2",
    searchUrl: "https://procurement.opengov.com/api/v2/portal/richland2/projects",
    domain: "procurement.opengov.com",
    accessMode: "api",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes: "Official buyer-specific OpenGov procurement portal for Richland School District Two public RFP, RFQ, RFI, and project opportunities; active project browsing is public. Large public-school workforce provides a documented likely-fit basis for employee-health procurement, but no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "va-metropolitan-washington-airports-authority",
    name: "Metropolitan Washington Airports Authority Current Contracting Opportunities",
    jurisdiction: "Metropolitan Washington Airports Authority",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.mwaa.com/business/current-contracting-opportunities",
    searchUrl: "https://www.mwaa.com/business/current-contracting-opportunities",
    domain: "mwaa.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct contracting-opportunity listing for the Metropolitan Washington Airports Authority. Airport operations, public safety, construction, maintenance, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "tn-metropolitan-nashville-airport-authority",
    name: "Metropolitan Nashville Airport Authority Business Opportunities",
    jurisdiction: "Metropolitan Nashville Airport Authority",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://flynashville.com/opportunity_category/business",
    searchUrl: "https://flynashville.com/opportunity_category/business",
    domain: "flynashville.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct business-opportunity archive for the Metropolitan Nashville Airport Authority. Airport operations, public safety, construction, maintenance, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "tn-memphis-shelby-county-airport-authority",
    name: "Memphis-Shelby County Airport Authority Bids, RFPs, and RFQs",
    jurisdiction: "Memphis-Shelby County Airport Authority",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://flymemphis.com/rfps-rfqs/",
    searchUrl: "https://flymemphis.com/rfps-rfqs/",
    domain: "flymemphis.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct open-bid, RFP, and RFQ listing for the Memphis-Shelby County Airport Authority. Airport police, ARFF, operations, construction, maintenance, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "pa-allegheny-county-airport-authority",
    name: "Allegheny County Airport Authority Business Opportunities",
    jurisdiction: "Allegheny County Airport Authority",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://flypittsburgh.com/acaa-corporate/partner-with-us/business-opportunities/",
    searchUrl: "https://flypittsburgh.com/acaa-corporate/partner-with-us/business-opportunities/",
    domain: "flypittsburgh.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes: "Official direct business-opportunity listing for the Allegheny County Airport Authority. Airport operations, badging, ARFF, construction, maintenance, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "ri-rhode-island-airport-corporation",
    name: "Rhode Island Airport Corporation Procurement",
    jurisdiction: "Rhode Island Airport Corporation",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://flyri.com/riac/procurement/",
    searchUrl: "https://flyri.com/riac/procurement/",
    domain: "flyri.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct procurement page for the Rhode Island Airport Corporation and its airport system. Airport police, ARFF, operations, construction, maintenance, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "nv-reno-tahoe-airport-authority",
    name: "Reno-Tahoe Airport Authority Solicitation Opportunities",
    jurisdiction: "Reno-Tahoe Airport Authority",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.renoairport.com/doing-business/solicitation-opportunities/",
    searchUrl: "https://www.renoairport.com/doing-business/solicitation-opportunities/",
    domain: "renoairport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct solicitation listing for the Reno-Tahoe Airport Authority. The authority operates airport police and fire departments and other safety-sensitive airport functions, providing a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "az-tucson-airport-authority",
    name: "Tucson Airport Authority Bids and RFPs",
    jurisdiction: "Tucson Airport Authority",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://flytucson.com/taa/business_development/doing_business_with_taa/bids_rfps.php",
    searchUrl: "https://flytucson.com/taa/business_development/doing_business_with_taa/bids_rfps.php",
    domain: "flytucson.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "ready_to_parse",
    notes: "Official direct bids, RFPs, RFQs, and SOQs listing for the Tucson Airport Authority. Airport police, fire, badging, operations, construction, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; no matching Occu-Med solicitation is claimed.",
  },
  {
    id: "in-indianapolis-airport-authority",
    name: "Indianapolis Airport Authority Business Opportunities",
    jurisdiction: "Indianapolis Airport Authority",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.ind.com/business/do-business-at-the-airport",
    searchUrl: "https://www.ind.com/business/do-business-at-the-airport",
    domain: "ind.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official buyer page for Indianapolis Airport Authority solicitations and its buyer-specific PlanetBids system. Airport operations, maintenance, construction, badging, and other safety-sensitive work provide a strong likely-fit basis for occupational-health-related services; public opportunity viewing is available, while registration is required to download documents. No matching Occu-Med solicitation is claimed.",
  }
];
