import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_042: DirectRfpPortal[] = [
  {
    id: "ga-gdot-letting",
    name: "Georgia DOT Construction Letting",
    jurisdiction: "Georgia Department of Transportation",
    state: "GA",
    country: "US",
    level: "state",
    url: "https://www.dot.ga.gov/GDOT/Pages/Letting.aspx",
    searchUrl: "https://www.dot.ga.gov/GDOT/Pages/Letting.aspx",
    domain: "www.dot.ga.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Georgia Department of Transportation construction letting source for advertised highway projects, proposal information, bid results, and letting resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ma-massdot-contract-opportunities",
    name: "MassDOT Contract Opportunities",
    jurisdiction: "Massachusetts Department of Transportation",
    state: "MA",
    country: "US",
    level: "state",
    url: "https://www.mass.gov/massdot-contract-opportunities",
    searchUrl: "https://www.mass.gov/massdot-contract-opportunities",
    domain: "www.mass.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official Massachusetts Department of Transportation contract-opportunity entry point covering highway and transportation contracting resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ms-mdot-letting",
    name: "Mississippi DOT Contractor Letting",
    jurisdiction: "Mississippi Department of Transportation",
    state: "MS",
    country: "US",
    level: "state",
    url: "https://mdot.ms.gov/portal/contractors/letting/",
    searchUrl: "https://mdot.ms.gov/portal/contractors/letting/",
    domain: "mdot.ms.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Mississippi Department of Transportation contractor letting source for advertised projects, proposals, plans, addenda, and bid information. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "mo-modot-bid-opening",
    name: "Missouri DOT Bid Opening Information",
    jurisdiction: "Missouri Department of Transportation",
    state: "MO",
    country: "US",
    level: "state",
    url: "https://www.modot.org/bid-opening-info",
    searchUrl: "https://www.modot.org/bid-opening-info",
    domain: "www.modot.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Missouri Department of Transportation bid-opening and highway-construction letting source, including plans-room and bidding resources. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ne-ndot-highway-bridge-lettings",
    name: "Nebraska DOT Highway and Bridge Lettings",
    jurisdiction: "Nebraska Department of Transportation",
    state: "NE",
    country: "US",
    level: "state",
    url: "https://dot.nebraska.gov/business-center/hwy-bridge-lp/",
    searchUrl: "https://dot.nebraska.gov/business-center/hwy-bridge-lp/",
    domain: "dot.nebraska.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Nebraska Department of Transportation highway and bridge letting source with current and historical lettings, plans, proposals, addenda, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "nh-nhdot-construction-advertisements",
    name: "New Hampshire DOT Construction Advertisements",
    jurisdiction: "New Hampshire Department of Transportation",
    state: "NH",
    country: "US",
    level: "state",
    url: "https://www.dot.nh.gov/doing-business-nhdot/contractors/construction-advertisements",
    searchUrl:
      "https://www.dot.nh.gov/doing-business-nhdot/contractors/construction-advertisements",
    domain: "www.dot.nh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official New Hampshire Department of Transportation construction-advertisement source for contractor opportunities and project documents. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "oh-odot-contract-sales",
    name: "Ohio DOT Contract Sales",
    jurisdiction: "Ohio Department of Transportation",
    state: "OH",
    country: "US",
    level: "state",
    url: "https://www.transportation.ohio.gov/working/contract-sales",
    searchUrl: "https://www.transportation.ohio.gov/working/contract-sales",
    domain: "www.transportation.ohio.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Ohio Department of Transportation contract-sales source for highway project advertisements, letting schedules, plans, addenda, and bid information. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ok-odot-contracts-proposals",
    name: "Oklahoma DOT Contracts and Proposals",
    jurisdiction: "Oklahoma Department of Transportation",
    state: "OK",
    country: "US",
    level: "state",
    url: "https://oklahoma.gov/odot/business-center/contracts-and-proposals.html",
    searchUrl:
      "https://oklahoma.gov/odot/business-center/contracts-and-proposals.html",
    domain: "oklahoma.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Oklahoma Department of Transportation contracts-and-proposals source for project lettings, proposal documents, addenda, and bid information. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-odot-procurement",
    name: "Oregon DOT Procurement and Contracting",
    jurisdiction: "Oregon Department of Transportation",
    state: "OR",
    country: "US",
    level: "state",
    url: "https://www.oregon.gov/odot/Business/Procurement/Pages/index.aspx",
    searchUrl:
      "https://www.oregon.gov/odot/Business/Procurement/Pages/index.aspx",
    domain: "www.oregon.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Oregon Department of Transportation procurement source linking contracting opportunities, letting schedules, notices to contractors, bid results, eBIDS, and OregonBuys resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "pa-penndot-ecms",
    name: "PennDOT Engineering and Construction Management System",
    jurisdiction: "Pennsylvania Department of Transportation",
    state: "PA",
    country: "US",
    level: "state",
    url: "https://www.ecms.penndot.gov/ECMS/",
    searchUrl: "https://www.ecms.penndot.gov/ECMS/",
    domain: "www.ecms.penndot.gov",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official PennDOT Engineering and Construction Management System for advertised transportation projects, project details, bid packages, and construction contracting. Public information is available without supplier authentication; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ri-ridot-bidding-opportunities",
    name: "Rhode Island DOT Bidding Opportunities",
    jurisdiction: "Rhode Island Department of Transportation",
    state: "RI",
    country: "US",
    level: "state",
    url: "https://www.dot.ri.gov/ridotbidding/",
    searchUrl: "https://www.dot.ri.gov/ridotbidding/",
    domain: "www.dot.ri.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Rhode Island Department of Transportation bidding-opportunities and bid-board entry point. Opportunities are publicly discoverable, while some bidder functions require authentication. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ut-udot-contracting",
    name: "Utah DOT Contracting",
    jurisdiction: "Utah Department of Transportation",
    state: "UT",
    country: "US",
    level: "state",
    url: "https://udot.utah.gov/connect/business/contracting/",
    searchUrl: "https://udot.utah.gov/connect/business/contracting/",
    domain: "udot.utah.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official Utah Department of Transportation contracting entry point for advertised projects, consultant services, construction contracting, and related bidder resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "vt-vtrans-bids-requests",
    name: "Vermont Agency of Transportation Bids and Requests",
    jurisdiction: "Vermont Agency of Transportation",
    state: "VT",
    country: "US",
    level: "state",
    url: "https://vtrans.vermont.gov/contract-admin/bids-requests",
    searchUrl: "https://vtrans.vermont.gov/contract-admin/bids-requests",
    domain: "vtrans.vermont.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Vermont Agency of Transportation Contract Administration source for construction bids, requests, advertisements, proposal documents, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "va-vdot-construction-advertisements",
    name: "Virginia DOT Construction Advertisements",
    jurisdiction: "Virginia Department of Transportation",
    state: "VA",
    country: "US",
    level: "state",
    url: "https://www.vdot.virginia.gov/doing-business/technical-guidance-and-support/construction/advertisements/",
    searchUrl:
      "https://www.vdot.virginia.gov/doing-business/technical-guidance-and-support/construction/advertisements/",
    domain: "www.vdot.virginia.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Virginia Department of Transportation construction-advertisement source for highway contract opportunities, proposal documents, addenda, and letting information. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wa-wsdot-construction-advertisement-award",
    name: "Washington State DOT Construction Advertisement and Award",
    jurisdiction: "Washington State Department of Transportation",
    state: "WA",
    country: "US",
    level: "state",
    url: "https://wsdot.wa.gov/business-wsdot/contracting-opportunities/construction-contracts/advertisement-award",
    searchUrl:
      "https://wsdot.wa.gov/business-wsdot/contracting-opportunities/construction-contracts/advertisement-award",
    domain: "wsdot.wa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Washington State Department of Transportation construction-contract advertisement and award source for active projects, plans, specifications, addenda, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wv-wvdoh-contract-lettings",
    name: "West Virginia Division of Highways Contract Lettings",
    jurisdiction: "West Virginia Division of Highways",
    state: "WV",
    country: "US",
    level: "state",
    url: "https://transportation.wv.gov/highways/contractadmin/lettings/Pages/default.aspx",
    searchUrl:
      "https://transportation.wv.gov/highways/contractadmin/lettings/Pages/default.aspx",
    domain: "transportation.wv.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official West Virginia Division of Highways Contract Administration letting source for advertised projects, proposals, plans, addenda, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wi-wisdot-highway-bid-lettings",
    name: "Wisconsin DOT Highway Construction Bid Lettings",
    jurisdiction: "Wisconsin Department of Transportation",
    state: "WI",
    country: "US",
    level: "state",
    url: "https://wisconsindot.gov/Pages/doing-bus/contractors/hcci/bid-let.aspx",
    searchUrl:
      "https://wisconsindot.gov/Pages/doing-bus/contractors/hcci/bid-let.aspx",
    domain: "wisconsindot.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Wisconsin Department of Transportation highway-construction bid-letting source for advertisements, proposals, plans, addenda, and letting results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wy-wydot-project-letting",
    name: "Wyoming DOT Project Letting",
    jurisdiction: "Wyoming Department of Transportation",
    state: "WY",
    country: "US",
    level: "state",
    url: "https://www.dot.state.wy.us/home/business_with_wydot/contractors/project-letting.html",
    searchUrl:
      "https://www.dot.state.wy.us/home/business_with_wydot/contractors/project-letting.html",
    domain: "www.dot.state.wy.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Wyoming Department of Transportation project-letting source for advertised highway projects, plans, proposals, addenda, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
];
