import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS: DirectRfpPortal[] = [
  {
    id: "ak-anchorage",
    name: "Municipality of Anchorage Purchasing",
    jurisdiction: "Municipality of Anchorage",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    searchUrl: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    domain: "muni.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official municipal purchasing page for Anchorage procurement resources and bid information.",
  },
  {
    id: "ak-university-of-alaska",
    name: "University of Alaska Procurement",
    jurisdiction: "University of Alaska",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.alaska.edu/procurement/",
    searchUrl: "https://www.alaska.edu/procurement/",
    domain: "alaska.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of Alaska procurement and contract services page.",
  },
  {
    id: "al-jefferson-county",
    name: "Jefferson County Purchasing",
    jurisdiction: "Jefferson County",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.jccal.org/Default.asp?ID=238&pg=Purchasing",
    searchUrl: "https://www.jccal.org/Default.asp?ID=238&pg=Purchasing",
    domain: "jccal.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Jefferson County purchasing page for vendor and bid information.",
  },
  {
    id: "ar-little-rock",
    name: "City of Little Rock Purchasing",
    jurisdiction: "City of Little Rock",
    state: "AR",
    country: "US",
    level: "district",
    url: "https://www.littlerock.gov/city-administration/city-departments/finance/purchasing/",
    searchUrl:
      "https://www.littlerock.gov/city-administration/city-departments/finance/purchasing/",
    domain: "littlerock.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official city purchasing page for Little Rock procurement information.",
  },
  {
    id: "ct-uconn",
    name: "University of Connecticut Procurement Services",
    jurisdiction: "University of Connecticut",
    state: "CT",
    country: "US",
    level: "district",
    url: "https://procurement.uconn.edu/",
    searchUrl: "https://procurement.uconn.edu/",
    domain: "procurement.uconn.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UConn procurement services site.",
  },
  {
    id: "de-wilmington",
    name: "City of Wilmington Procurement",
    jurisdiction: "City of Wilmington",
    state: "DE",
    country: "US",
    level: "district",
    url: "https://www.wilmingtonde.gov/government/city-departments/finance/purchasing",
    searchUrl:
      "https://www.wilmingtonde.gov/government/city-departments/finance/purchasing",
    domain: "wilmingtonde.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Wilmington purchasing page.",
  },
  {
    id: "fl-hillsborough-county",
    name: "Hillsborough County Procurement Services",
    jurisdiction: "Hillsborough County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.hillsboroughcounty.org/en/businesses/doing-business-with-hillsborough/vendors/procurement-services",
    searchUrl:
      "https://www.hillsboroughcounty.org/en/businesses/doing-business-with-hillsborough/vendors/procurement-services",
    domain: "hillsboroughcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Hillsborough County procurement services page.",
  },
  {
    id: "ga-fulton-county",
    name: "Fulton County Purchasing and Contract Compliance",
    jurisdiction: "Fulton County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/purchasing-contract-compliance",
    searchUrl:
      "https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/purchasing-contract-compliance",
    domain: "fultoncountyga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Fulton County purchasing and contract compliance page.",
  },
  {
    id: "gu-general-services-agency",
    name: "Guam General Services Agency Procurement",
    jurisdiction: "Guam",
    state: "GU",
    country: "US",
    level: "district",
    url: "https://gsa.doa.guam.gov/",
    searchUrl: "https://gsa.doa.guam.gov/",
    domain: "gsa.doa.guam.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Guam General Services Agency procurement site.",
  },
  {
    id: "hi-honolulu",
    name: "City and County of Honolulu Purchasing",
    jurisdiction: "City and County of Honolulu",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www8.honolulu.gov/bfs/purchasing/",
    searchUrl: "https://www8.honolulu.gov/bfs/purchasing/",
    domain: "honolulu.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Honolulu purchasing page.",
  },
  {
    id: "ia-des-moines",
    name: "City of Des Moines Procurement",
    jurisdiction: "City of Des Moines",
    state: "IA",
    country: "US",
    level: "district",
    url: "https://www.dsm.city/departments/finance/procurement.php",
    searchUrl: "https://www.dsm.city/departments/finance/procurement.php",
    domain: "dsm.city",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Des Moines procurement page.",
  },
  {
    id: "id-ada-county",
    name: "Ada County Procurement",
    jurisdiction: "Ada County",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://adacounty.id.gov/procurement/",
    searchUrl: "https://adacounty.id.gov/procurement/",
    domain: "adacounty.id.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ada County procurement page.",
  },
  {
    id: "in-indianapolis",
    name: "Indianapolis Purchasing Division",
    jurisdiction: "City of Indianapolis / Marion County",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.indy.gov/agency/purchasing-division",
    searchUrl: "https://www.indy.gov/agency/purchasing-division",
    domain: "indy.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Indianapolis purchasing division page.",
  },
  {
    id: "ks-wichita",
    name: "City of Wichita Purchasing",
    jurisdiction: "City of Wichita",
    state: "KS",
    country: "US",
    level: "district",
    url: "https://www.wichita.gov/Finance/Pages/Purchasing.aspx",
    searchUrl: "https://www.wichita.gov/Finance/Pages/Purchasing.aspx",
    domain: "wichita.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Wichita purchasing page.",
  },
  {
    id: "ma-massport",
    name: "Massport Business Opportunities",
    jurisdiction: "Massachusetts Port Authority",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.massport.com/business-with-massport",
    searchUrl: "https://www.massport.com/business-with-massport",
    domain: "massport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official Massport business opportunities page for airport and port authority procurement.",
  },
  {
    id: "me-portland",
    name: "City of Portland Purchasing",
    jurisdiction: "City of Portland",
    state: "ME",
    country: "US",
    level: "district",
    url: "https://www.portlandmaine.gov/1056/Purchasing",
    searchUrl: "https://www.portlandmaine.gov/1056/Purchasing",
    domain: "portlandmaine.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Portland, Maine purchasing page.",
  },
  {
    id: "mn-hennepin-county",
    name: "Hennepin County Supplier Portal",
    jurisdiction: "Hennepin County",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    searchUrl:
      "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    domain: "hennepin.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Hennepin County supplier portal entry page.",
  },
  {
    id: "mo-st-louis",
    name: "City of St. Louis Supply Division",
    jurisdiction: "City of St. Louis",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://www.stlouis-mo.gov/government/departments/supply/",
    searchUrl: "https://www.stlouis-mo.gov/government/departments/supply/",
    domain: "stlouis-mo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official St. Louis supply division procurement page.",
  },
  {
    id: "mp-procurement",
    name: "CNMI Procurement and Supply",
    jurisdiction: "Commonwealth of the Northern Mariana Islands",
    state: "MP",
    country: "US",
    level: "district",
    url: "https://www.finance.gov.mp/divisions/procurement-and-supply/",
    searchUrl: "https://www.finance.gov.mp/divisions/procurement-and-supply/",
    domain: "finance.gov.mp",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CNMI procurement and supply division page.",
  },
  {
    id: "ms-jackson",
    name: "City of Jackson Purchasing",
    jurisdiction: "City of Jackson",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.jacksonms.gov/purchasing/",
    searchUrl: "https://www.jacksonms.gov/purchasing/",
    domain: "jacksonms.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jackson purchasing page.",
  },
  {
    id: "mt-billings",
    name: "City of Billings Purchasing",
    jurisdiction: "City of Billings",
    state: "MT",
    country: "US",
    level: "district",
    url: "https://www.billingsmt.gov/107/Purchasing",
    searchUrl: "https://www.billingsmt.gov/107/Purchasing",
    domain: "billingsmt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Billings purchasing page.",
  },
  {
    id: "nd-fargo",
    name: "City of Fargo Purchasing",
    jurisdiction: "City of Fargo",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://fargond.gov/city-government/departments/finance/purchasing",
    searchUrl:
      "https://fargond.gov/city-government/departments/finance/purchasing",
    domain: "fargond.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fargo purchasing page.",
  },
  {
    id: "ne-omaha",
    name: "City of Omaha Purchasing",
    jurisdiction: "City of Omaha",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://finance.cityofomaha.org/purchasing",
    searchUrl: "https://finance.cityofomaha.org/purchasing",
    domain: "finance.cityofomaha.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Omaha purchasing page.",
  },
  {
    id: "nh-manchester",
    name: "City of Manchester Purchasing",
    jurisdiction: "City of Manchester",
    state: "NH",
    country: "US",
    level: "district",
    url: "https://www.manchesternh.gov/Departments/Purchasing",
    searchUrl: "https://www.manchesternh.gov/Departments/Purchasing",
    domain: "manchesternh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Manchester purchasing page.",
  },
  {
    id: "nj-essex-county",
    name: "Essex County Purchasing",
    jurisdiction: "Essex County",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://essexcountynj.org/purchasing/",
    searchUrl: "https://essexcountynj.org/purchasing/",
    domain: "essexcountynj.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Essex County purchasing page.",
  },
  {
    id: "nm-albuquerque",
    name: "City of Albuquerque Purchasing",
    jurisdiction: "City of Albuquerque",
    state: "NM",
    country: "US",
    level: "district",
    url: "https://www.cabq.gov/dfa/purchasing",
    searchUrl: "https://www.cabq.gov/dfa/purchasing",
    domain: "cabq.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Albuquerque purchasing page.",
  },
  {
    id: "nv-las-vegas",
    name: "City of Las Vegas Purchasing and Contracts",
    jurisdiction: "City of Las Vegas",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    searchUrl:
      "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    domain: "lasvegasnevada.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Las Vegas purchasing and contracts page.",
  },
  {
    id: "ny-nyc-dcas",
    name: "New York City DCAS Procurement",
    jurisdiction: "City of New York",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.nyc.gov/site/dcas/business/procurement.page",
    searchUrl: "https://www.nyc.gov/site/dcas/business/procurement.page",
    domain: "nyc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 1,
    parserStatus: "catalog_only",
    notes: "Official NYC DCAS procurement page for city contracting resources.",
  },
  {
    id: "oh-franklin-county",
    name: "Franklin County Purchasing",
    jurisdiction: "Franklin County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://purchasing.franklincountyohio.gov/",
    searchUrl: "https://purchasing.franklincountyohio.gov/",
    domain: "purchasing.franklincountyohio.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Franklin County purchasing site.",
  },
  {
    id: "ok-oklahoma-city",
    name: "Oklahoma City Bids and Proposals",
    jurisdiction: "City of Oklahoma City",
    state: "OK",
    country: "US",
    level: "district",
    url: "https://www.okc.gov/departments/finance/purchasing/bids-proposals",
    searchUrl:
      "https://www.okc.gov/departments/finance/purchasing/bids-proposals",
    domain: "okc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Oklahoma City bids and proposals page.",
  },
  {
    id: "pa-allegheny-county",
    name: "Allegheny County Purchasing and Supplies",
    jurisdiction: "Allegheny County",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.alleghenycounty.us/Services/Purchasing-and-Supplies",
    searchUrl:
      "https://www.alleghenycounty.us/Services/Purchasing-and-Supplies",
    domain: "alleghenycounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Allegheny County purchasing and supplies page.",
  },
  {
    id: "pr-general-services-administration",
    name: "Puerto Rico General Services Administration",
    jurisdiction: "Puerto Rico",
    state: "PR",
    country: "US",
    level: "district",
    url: "https://asg.pr.gov/",
    searchUrl: "https://asg.pr.gov/",
    domain: "asg.pr.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Puerto Rico General Services Administration procurement entry point.",
  },
  {
    id: "ri-providence",
    name: "City of Providence Purchasing",
    jurisdiction: "City of Providence",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://www.providenceri.gov/purchasing/",
    searchUrl: "https://www.providenceri.gov/purchasing/",
    domain: "providenceri.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Providence purchasing page.",
  },
  {
    id: "sc-richland-county",
    name: "Richland County Procurement",
    jurisdiction: "Richland County",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://www.richlandcountysc.gov/Government/Departments/Business-Operations/Procurement",
    searchUrl:
      "https://www.richlandcountysc.gov/Government/Departments/Business-Operations/Procurement",
    domain: "richlandcountysc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Richland County procurement page.",
  },
  {
    id: "sd-sioux-falls",
    name: "City of Sioux Falls Purchasing",
    jurisdiction: "City of Sioux Falls",
    state: "SD",
    country: "US",
    level: "district",
    url: "https://www.siouxfalls.gov/business-permits/business/purchasing",
    searchUrl:
      "https://www.siouxfalls.gov/business-permits/business/purchasing",
    domain: "siouxfalls.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Sioux Falls purchasing page.",
  },
  {
    id: "tx-houston",
    name: "City of Houston Strategic Procurement Division",
    jurisdiction: "City of Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.houstontx.gov/bizwithhou/",
    searchUrl: "https://www.houstontx.gov/bizwithhou/",
    domain: "houstontx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Houston strategic procurement page.",
  },
  {
    id: "ut-salt-lake-city",
    name: "Salt Lake City Purchasing",
    jurisdiction: "Salt Lake City",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.slc.gov/purchasing/",
    searchUrl: "https://www.slc.gov/purchasing/",
    domain: "slc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Salt Lake City purchasing page.",
  },
  {
    id: "vi-property-and-procurement",
    name: "USVI Department of Property and Procurement",
    jurisdiction: "U.S. Virgin Islands",
    state: "VI",
    country: "US",
    level: "district",
    url: "https://dpp.vi.gov/",
    searchUrl: "https://dpp.vi.gov/",
    domain: "dpp.vi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official U.S. Virgin Islands Department of Property and Procurement site.",
  },
  {
    id: "vt-burlington",
    name: "City of Burlington RFPs and Bids",
    jurisdiction: "City of Burlington",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.burlingtonvt.gov/RFP",
    searchUrl: "https://www.burlingtonvt.gov/RFP",
    domain: "burlingtonvt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Burlington RFP and bid posting page.",
  },
  {
    id: "wi-milwaukee",
    name: "City of Milwaukee Purchasing",
    jurisdiction: "City of Milwaukee",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://city.milwaukee.gov/Purchasing",
    searchUrl: "https://city.milwaukee.gov/Purchasing",
    domain: "city.milwaukee.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Milwaukee purchasing page.",
  },
  {
    id: "wv-charleston",
    name: "City of Charleston Purchasing",
    jurisdiction: "City of Charleston",
    state: "WV",
    country: "US",
    level: "district",
    url: "https://www.charlestonwv.gov/government/city-departments/finance/purchasing",
    searchUrl:
      "https://www.charlestonwv.gov/government/city-departments/finance/purchasing",
    domain: "charlestonwv.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Charleston, West Virginia purchasing page.",
  },
  {
    id: "wy-cheyenne",
    name: "City of Cheyenne Purchasing",
    jurisdiction: "City of Cheyenne",
    state: "WY",
    country: "US",
    level: "district",
    url: "https://www.cheyennecity.org/Your-Government/Departments/Finance/Purchasing",
    searchUrl:
      "https://www.cheyennecity.org/Your-Government/Departments/Finance/Purchasing",
    domain: "cheyennecity.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cheyenne purchasing page.",
  },
  {
    id: "az-phoenix",
    name: "City of Phoenix Finance Procurement",
    jurisdiction: "City of Phoenix",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.phoenix.gov/finance/vendorsreg",
    searchUrl: "https://www.phoenix.gov/finance/vendorsreg",
    domain: "phoenix.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official City of Phoenix procurement and vendor registration page.",
  },
  {
    id: "ca-los-angeles-world-airports",
    name: "Los Angeles World Airports Business Opportunities",
    jurisdiction: "Los Angeles World Airports",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lawa.org/businesses/lawa-business-opportunities",
    searchUrl: "https://www.lawa.org/businesses/lawa-business-opportunities",
    domain: "lawa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official LAWA business opportunities page for airport authority procurement.",
  },
  {
    id: "co-colorado-springs",
    name: "City of Colorado Springs Procurement Services",
    jurisdiction: "City of Colorado Springs",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://coloradosprings.gov/procurement-services",
    searchUrl: "https://coloradosprings.gov/procurement-services",
    domain: "coloradosprings.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Colorado Springs procurement services page.",
  },
  {
    id: "dc-water",
    name: "DC Water Procurement",
    jurisdiction: "District of Columbia Water and Sewer Authority",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.dcwater.com/procurement",
    searchUrl: "https://www.dcwater.com/procurement",
    domain: "dcwater.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official DC Water procurement page for water utility solicitations and vendor resources.",
  },
  {
    id: "il-metropolitan-water-reclamation-district",
    name: "MWRD Procurement and Materials Management",
    jurisdiction: "Metropolitan Water Reclamation District of Greater Chicago",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://mwrd.org/procurement-and-materials-management",
    searchUrl: "https://mwrd.org/procurement-and-materials-management",
    domain: "mwrd.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official MWRD procurement and materials management page.",
  },
  {
    id: "la-baton-rouge",
    name: "City-Parish of Baton Rouge Purchasing",
    jurisdiction: "City of Baton Rouge and Parish of East Baton Rouge",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.brla.gov/150/Purchasing",
    searchUrl: "https://www.brla.gov/150/Purchasing",
    domain: "brla.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City-Parish purchasing page.",
  },
  {
    id: "md-maryland-transportation-authority",
    name: "Maryland Transportation Authority Procurement",
    jurisdiction: "Maryland Transportation Authority",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://mdta.maryland.gov/Business/Procurement",
    searchUrl: "https://mdta.maryland.gov/Business/Procurement",
    domain: "mdta.maryland.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official MDTA procurement page for transportation authority contracting.",
  },
  {
    id: "mi-oakland-county",
    name: "Oakland County Purchasing",
    jurisdiction: "Oakland County",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.oakgov.com/government/purchasing",
    searchUrl: "https://www.oakgov.com/government/purchasing",
    domain: "oakgov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Oakland County purchasing page.",
  },
  {
    id: "nc-raleigh",
    name: "City of Raleigh Procurement",
    jurisdiction: "City of Raleigh",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://raleighnc.gov/doing-business/services/procurement",
    searchUrl: "https://raleighnc.gov/doing-business/services/procurement",
    domain: "raleighnc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Raleigh procurement page.",
  },
  {
    id: "or-trimet",
    name: "TriMet Procurement",
    jurisdiction: "Tri-County Metropolitan Transportation District of Oregon",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://trimet.org/procurement/",
    searchUrl: "https://trimet.org/procurement/",
    domain: "trimet.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official TriMet procurement page for transit contracting.",
  },
  {
    id: "tn-knoxville",
    name: "City of Knoxville Purchasing",
    jurisdiction: "City of Knoxville",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    searchUrl:
      "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    domain: "knoxvilletn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Knoxville purchasing page.",
  },
  {
    id: "va-virginia-beach",
    name: "City of Virginia Beach Purchasing",
    jurisdiction: "City of Virginia Beach",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.vbgov.com/government/departments/finance/Pages/purchasing.aspx",
    searchUrl:
      "https://www.vbgov.com/government/departments/finance/Pages/purchasing.aspx",
    domain: "vbgov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Virginia Beach purchasing page.",
  },
  {
    id: "wa-sound-transit",
    name: "Sound Transit Procurement and Contracts",
    jurisdiction: "Central Puget Sound Regional Transit Authority",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.soundtransit.org/get-to-know-us/doing-business/procurement-contracts",
    searchUrl:
      "https://www.soundtransit.org/get-to-know-us/doing-business/procurement-contracts",
    domain: "soundtransit.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Sound Transit procurement and contracts page.",
  },
  {
    id: "al-mobile-county-public-schools",
    name: "Mobile County Public Schools Purchasing",
    jurisdiction: "Mobile County Public Schools",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.mcpss.com/purchasing",
    searchUrl: "https://www.mcpss.com/purchasing",
    domain: "mcpss.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Mobile County Public Schools purchasing page.",
  },
  {
    id: "ak-fairbanks-north-star-borough",
    name: "Fairbanks North Star Borough Purchasing",
    jurisdiction: "Fairbanks North Star Borough",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.fnsb.gov/452/Purchasing",
    searchUrl: "https://www.fnsb.gov/452/Purchasing",
    domain: "fnsb.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fairbanks North Star Borough purchasing page.",
  },
  {
    id: "az-tucson",
    name: "City of Tucson Procurement",
    jurisdiction: "City of Tucson",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.tucsonprocurement.com/",
    searchUrl: "https://www.tucsonprocurement.com/",
    domain: "tucsonprocurement.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Tucson procurement site.",
  },
  {
    id: "ar-fayetteville",
    name: "City of Fayetteville Purchasing",
    jurisdiction: "City of Fayetteville",
    state: "AR",
    country: "US",
    level: "district",
    url: "https://www.fayetteville-ar.gov/384/Purchasing",
    searchUrl: "https://www.fayetteville-ar.gov/384/Purchasing",
    domain: "fayetteville-ar.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fayetteville purchasing page.",
  },
  {
    id: "ca-sacramento-county",
    name: "Sacramento County Contract and Purchasing Services",
    jurisdiction: "Sacramento County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://contractservices.saccounty.gov/Pages/default.aspx",
    searchUrl: "https://contractservices.saccounty.gov/Pages/default.aspx",
    domain: "contractservices.saccounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Sacramento County contract and purchasing services page.",
  },
  {
    id: "co-aurora",
    name: "City of Aurora Purchasing Services",
    jurisdiction: "City of Aurora",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.auroragov.org/cms/One.aspx?portalId=1881221&pageId=2031063",
    searchUrl:
      "https://www.auroragov.org/cms/One.aspx?portalId=1881221&pageId=2031063",
    domain: "auroragov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Aurora purchasing services page.",
  },
  {
    id: "ct-new-haven",
    name: "City of New Haven Purchasing",
    jurisdiction: "City of New Haven",
    state: "CT",
    country: "US",
    level: "district",
    url: "https://www.newhavenct.gov/government/departments-divisions/purchasing",
    searchUrl:
      "https://www.newhavenct.gov/government/departments-divisions/purchasing",
    domain: "newhavenct.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official New Haven purchasing page.",
  },
  {
    id: "de-new-castle-county",
    name: "New Castle County Purchasing",
    jurisdiction: "New Castle County",
    state: "DE",
    country: "US",
    level: "district",
    url: "https://www.newcastlede.gov/249/Purchasing",
    searchUrl: "https://www.newcastlede.gov/249/Purchasing",
    domain: "newcastlede.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official New Castle County purchasing page.",
  },
  {
    id: "dc-udc-procurement",
    name: "University of the District of Columbia Procurement",
    jurisdiction: "University of the District of Columbia",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    searchUrl:
      "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    domain: "udc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UDC contracts and procurement page.",
  },
  {
    id: "fl-palm-beach-county",
    name: "Palm Beach County Purchasing",
    jurisdiction: "Palm Beach County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://discover.pbcgov.org/purchasing/Pages/default.aspx",
    searchUrl: "https://discover.pbcgov.org/purchasing/Pages/default.aspx",
    domain: "discover.pbcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Palm Beach County purchasing page.",
  },
  {
    id: "ga-dekalb-county",
    name: "DeKalb County Purchasing and Contracting",
    jurisdiction: "DeKalb County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.dekalbcountyga.gov/purchasing-contracting/purchasing-contracting",
    searchUrl:
      "https://www.dekalbcountyga.gov/purchasing-contracting/purchasing-contracting",
    domain: "dekalbcountyga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official DeKalb County purchasing and contracting page.",
  },
  {
    id: "hi-university-of-hawaii-procurement",
    name: "University of Hawaii Procurement and Real Property Management",
    jurisdiction: "University of Hawaii System",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www.hawaii.edu/procurement/",
    searchUrl: "https://www.hawaii.edu/procurement/",
    domain: "hawaii.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Hawaii procurement page.",
  },
  {
    id: "id-boise",
    name: "City of Boise Purchasing",
    jurisdiction: "City of Boise",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    searchUrl:
      "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    domain: "cityofboise.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Boise purchasing page.",
  },
  {
    id: "il-university-of-illinois-procurement",
    name: "University of Illinois System Procurement Services",
    jurisdiction: "University of Illinois System",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.procure.stateuniv.state.il.us/",
    searchUrl: "https://www.procure.stateuniv.state.il.us/",
    domain: "procure.stateuniv.state.il.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Illinois System procurement services site.",
  },
  {
    id: "in-fort-wayne",
    name: "City of Fort Wayne Purchasing",
    jurisdiction: "City of Fort Wayne",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.cityoffortwayne.org/purchasing.html",
    searchUrl: "https://www.cityoffortwayne.org/purchasing.html",
    domain: "cityoffortwayne.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fort Wayne purchasing page.",
  },
  {
    id: "ia-linn-county",
    name: "Linn County Purchasing",
    jurisdiction: "Linn County",
    state: "IA",
    country: "US",
    level: "district",
    url: "https://www.linncountyiowa.gov/149/Purchasing",
    searchUrl: "https://www.linncountyiowa.gov/149/Purchasing",
    domain: "linncountyiowa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Linn County purchasing page.",
  },
  {
    id: "ks-johnson-county",
    name: "Johnson County Purchasing",
    jurisdiction: "Johnson County",
    state: "KS",
    country: "US",
    level: "district",
    url: "https://www.jocogov.org/department/financial-management-administration/purchasing",
    searchUrl:
      "https://www.jocogov.org/department/financial-management-administration/purchasing",
    domain: "jocogov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Johnson County purchasing page.",
  },
  {
    id: "ky-lexington",
    name: "Lexington-Fayette Urban County Government Purchasing",
    jurisdiction: "Lexington-Fayette Urban County Government",
    state: "KY",
    country: "US",
    level: "district",
    url: "https://www.lexingtonky.gov/procurement",
    searchUrl: "https://www.lexingtonky.gov/procurement",
    domain: "lexingtonky.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lexington procurement page.",
  },
  {
    id: "la-jefferson-parish",
    name: "Jefferson Parish Purchasing",
    jurisdiction: "Jefferson Parish",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.jeffparish.gov/464/Purchasing",
    searchUrl: "https://www.jeffparish.gov/464/Purchasing",
    domain: "jeffparish.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jefferson Parish purchasing page.",
  },
  {
    id: "me-bangor",
    name: "City of Bangor Purchasing",
    jurisdiction: "City of Bangor",
    state: "ME",
    country: "US",
    level: "district",
    url: "https://www.bangormaine.gov/purchasing",
    searchUrl: "https://www.bangormaine.gov/purchasing",
    domain: "bangormaine.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bangor purchasing page.",
  },
  {
    id: "md-prince-georges-county",
    name: "Prince George's County Contract Administration and Procurement",
    jurisdiction: "Prince George's County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://www.princegeorgescountymd.gov/departments-offices/central-services/contract-administration-procurement",
    searchUrl:
      "https://www.princegeorgescountymd.gov/departments-offices/central-services/contract-administration-procurement",
    domain: "princegeorgescountymd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Prince George's County procurement page.",
  },
  {
    id: "ma-boston-public-schools-procurement",
    name: "Boston Public Schools Procurement",
    jurisdiction: "Boston Public Schools",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.bostonpublicschools.org/Page/331",
    searchUrl: "https://www.bostonpublicschools.org/Page/331",
    domain: "bostonpublicschools.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Boston Public Schools procurement page.",
  },
  {
    id: "mi-grand-rapids",
    name: "City of Grand Rapids Purchasing",
    jurisdiction: "City of Grand Rapids",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.grandrapidsmi.gov/Government/Departments/Fiscal-Services/Purchasing",
    searchUrl:
      "https://www.grandrapidsmi.gov/Government/Departments/Fiscal-Services/Purchasing",
    domain: "grandrapidsmi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Grand Rapids purchasing page.",
  },
  {
    id: "mn-ramsey-county",
    name: "Ramsey County Procurement",
    jurisdiction: "Ramsey County",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.ramseycounty.us/businesses/doing-business-ramsey-county/procurement",
    searchUrl:
      "https://www.ramseycounty.us/businesses/doing-business-ramsey-county/procurement",
    domain: "ramseycounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ramsey County procurement page.",
  },
  {
    id: "ms-hinds-county",
    name: "Hinds County Purchasing",
    jurisdiction: "Hinds County",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.hindscountyms.com/departments/purchasing",
    searchUrl: "https://www.hindscountyms.com/departments/purchasing",
    domain: "hindscountyms.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Hinds County purchasing page.",
  },
  {
    id: "mo-st-louis-county",
    name: "St. Louis County Procurement",
    jurisdiction: "St. Louis County",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://stlouiscountymo.gov/st-louis-county-departments/administration/procurement/",
    searchUrl:
      "https://stlouiscountymo.gov/st-louis-county-departments/administration/procurement/",
    domain: "stlouiscountymo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official St. Louis County procurement page.",
  },
  {
    id: "mt-missoula",
    name: "City of Missoula Purchasing",
    jurisdiction: "City of Missoula",
    state: "MT",
    country: "US",
    level: "district",
    url: "https://www.ci.missoula.mt.us/276/Purchasing",
    searchUrl: "https://www.ci.missoula.mt.us/276/Purchasing",
    domain: "ci.missoula.mt.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Missoula purchasing page.",
  },
  {
    id: "ne-lincoln",
    name: "City of Lincoln Purchasing",
    jurisdiction: "City of Lincoln",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    searchUrl: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    domain: "lincoln.ne.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lincoln purchasing page.",
  },
  {
    id: "nv-washoe-county",
    name: "Washoe County Purchasing",
    jurisdiction: "Washoe County",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.washoecounty.gov/clerks/cco/purchasing.php",
    searchUrl: "https://www.washoecounty.gov/clerks/cco/purchasing.php",
    domain: "washoecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Washoe County purchasing page.",
  },
  {
    id: "nh-nashua",
    name: "City of Nashua Purchasing",
    jurisdiction: "City of Nashua",
    state: "NH",
    country: "US",
    level: "district",
    url: "https://www.nashuanh.gov/390/Purchasing",
    searchUrl: "https://www.nashuanh.gov/390/Purchasing",
    domain: "nashuanh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Nashua purchasing page.",
  },
  {
    id: "nm-bernalillo-county",
    name: "Bernalillo County Purchasing",
    jurisdiction: "Bernalillo County",
    state: "NM",
    country: "US",
    level: "district",
    url: "https://www.bernco.gov/finance/purchasing/",
    searchUrl: "https://www.bernco.gov/finance/purchasing/",
    domain: "bernco.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bernalillo County purchasing page.",
  },
  {
    id: "ny-westchester-county",
    name: "Westchester County Purchasing",
    jurisdiction: "Westchester County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.westchestergov.com/purchasing",
    searchUrl: "https://www.westchestergov.com/purchasing",
    domain: "westchestergov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Westchester County purchasing page.",
  },
  {
    id: "nc-guilford-county",
    name: "Guilford County Purchasing",
    jurisdiction: "Guilford County",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.guilfordcountync.gov/our-county/purchasing",
    searchUrl: "https://www.guilfordcountync.gov/our-county/purchasing",
    domain: "guilfordcountync.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Guilford County purchasing page.",
  },
  {
    id: "nd-bismarck",
    name: "City of Bismarck Purchasing",
    jurisdiction: "City of Bismarck",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://www.bismarcknd.gov/88/Purchasing",
    searchUrl: "https://www.bismarcknd.gov/88/Purchasing",
    domain: "bismarcknd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bismarck purchasing page.",
  },
  {
    id: "oh-cuyahoga-county",
    name: "Cuyahoga County Procurement and Diversity",
    jurisdiction: "Cuyahoga County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://cuyahogacounty.gov/procurement",
    searchUrl: "https://cuyahogacounty.gov/procurement",
    domain: "cuyahogacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Cuyahoga County procurement page.",
  },
  {
    id: "ok-tulsa",
    name: "City of Tulsa Purchasing",
    jurisdiction: "City of Tulsa",
    state: "OK",
    country: "US",
    level: "district",
    url: "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    searchUrl:
      "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    domain: "cityoftulsa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tulsa purchasing page.",
  },
  {
    id: "or-multnomah-county",
    name: "Multnomah County Purchasing",
    jurisdiction: "Multnomah County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.multco.us/purchasing",
    searchUrl: "https://www.multco.us/purchasing",
    domain: "multco.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Multnomah County purchasing page.",
  },
  {
    id: "pa-philadelphia",
    name: "City of Philadelphia Procurement Department",
    jurisdiction: "City of Philadelphia",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.phila.gov/departments/procurement-department/",
    searchUrl: "https://www.phila.gov/departments/procurement-department/",
    domain: "phila.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Philadelphia Procurement Department page.",
  },
  {
    id: "ri-warwick",
    name: "City of Warwick Purchasing",
    jurisdiction: "City of Warwick",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://www.warwickri.gov/purchasing-department",
    searchUrl: "https://www.warwickri.gov/purchasing-department",
    domain: "warwickri.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Warwick purchasing department page.",
  },
  {
    id: "sc-greenville-county",
    name: "Greenville County Procurement Services",
    jurisdiction: "Greenville County",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://www.greenvillecounty.org/Procurement/",
    searchUrl: "https://www.greenvillecounty.org/Procurement/",
    domain: "greenvillecounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Greenville County procurement services page.",
  },
  {
    id: "sd-rapid-city",
    name: "City of Rapid City Purchasing",
    jurisdiction: "City of Rapid City",
    state: "SD",
    country: "US",
    level: "district",
    url: "https://www.rcgov.org/departments/finance/purchasing.html",
    searchUrl: "https://www.rcgov.org/departments/finance/purchasing.html",
    domain: "rcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Rapid City purchasing page.",
  },
  {
    id: "tn-chattanooga",
    name: "City of Chattanooga Purchasing",
    jurisdiction: "City of Chattanooga",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://chattanooga.gov/finance/purchasing",
    searchUrl: "https://chattanooga.gov/finance/purchasing",
    domain: "chattanooga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Chattanooga purchasing page.",
  },
  {
    id: "tx-austin",
    name: "City of Austin Financial Services Purchasing",
    jurisdiction: "City of Austin",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.austintexas.gov/department/purchasing",
    searchUrl: "https://www.austintexas.gov/department/purchasing",
    domain: "austintexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Austin purchasing page.",
  },
  {
    id: "ut-salt-lake-county",
    name: "Salt Lake County Contracts and Procurement",
    jurisdiction: "Salt Lake County",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.saltlakecounty.gov/contracts/",
    searchUrl: "https://www.saltlakecounty.gov/contracts/",
    domain: "saltlakecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Salt Lake County contracts and procurement page.",
  },
  {
    id: "vt-south-burlington",
    name: "City of South Burlington Purchasing",
    jurisdiction: "City of South Burlington",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.southburlingtonvt.gov/business/purchasing.php",
    searchUrl: "https://www.southburlingtonvt.gov/business/purchasing.php",
    domain: "southburlingtonvt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official South Burlington purchasing page.",
  },
  {
    id: "va-norfolk",
    name: "City of Norfolk Purchasing",
    jurisdiction: "City of Norfolk",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.norfolk.gov/291/Purchasing",
    searchUrl: "https://www.norfolk.gov/291/Purchasing",
    domain: "norfolk.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Norfolk purchasing page.",
  },
  {
    id: "wa-spokane",
    name: "City of Spokane Purchasing",
    jurisdiction: "City of Spokane",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://my.spokanecity.org/business/purchasing/",
    searchUrl: "https://my.spokanecity.org/business/purchasing/",
    domain: "my.spokanecity.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Spokane purchasing page.",
  },
  {
    id: "wv-huntington",
    name: "City of Huntington Purchasing",
    jurisdiction: "City of Huntington",
    state: "WV",
    country: "US",
    level: "district",
    url: "https://www.cityofhuntington.com/city-government/departments/finance/purchasing/",
    searchUrl:
      "https://www.cityofhuntington.com/city-government/departments/finance/purchasing/",
    domain: "cityofhuntington.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Huntington purchasing page.",
  },
  {
    id: "wi-madison",
    name: "City of Madison Purchasing Services",
    jurisdiction: "City of Madison",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://www.cityofmadison.com/finance/purchasing/",
    searchUrl: "https://www.cityofmadison.com/finance/purchasing/",
    domain: "cityofmadison.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Madison purchasing services page.",
  },
  {
    id: "wy-casper",
    name: "City of Casper Purchasing",
    jurisdiction: "City of Casper",
    state: "WY",
    country: "US",
    level: "district",
    url: "https://www.casperwy.gov/government/city_manager/purchasing",
    searchUrl: "https://www.casperwy.gov/government/city_manager/purchasing",
    domain: "casperwy.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Casper purchasing page.",
  },
  {
    id: "pr-university-of-puerto-rico",
    name: "University of Puerto Rico Purchasing",
    jurisdiction: "University of Puerto Rico",
    state: "PR",
    country: "US",
    level: "district",
    url: "https://www.upr.edu/procurement/",
    searchUrl: "https://www.upr.edu/procurement/",
    domain: "upr.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Puerto Rico procurement page.",
  },
  {
    id: "vi-water-and-power-authority-procurement",
    name: "Virgin Islands Water and Power Authority Procurement",
    jurisdiction: "Virgin Islands Water and Power Authority",
    state: "VI",
    country: "US",
    level: "district",
    url: "https://www.viwapa.vi/about/procurement/",
    searchUrl: "https://www.viwapa.vi/about/procurement/",
    domain: "viwapa.vi",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official VIWAPA procurement page.",
  },
];
