import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_032: DirectRfpPortal[] = [
  {
    id: "fl-lynx-procurement",
    name: "LYNX Procurement",
    jurisdiction: "Central Florida Regional Transportation Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.golynx.com/corporate-info/doing-business-with-lynx/procurement.stml",
    searchUrl:
      "https://www.golynx.com/corporate-info/doing-business-with-lynx/procurement.stml",
    domain: "www.golynx.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Central Florida Regional Transportation Authority procurement or business opportunities page.",
  },
  {
    id: "il-cta-procurement",
    name: "Chicago Transit Authority Procurement",
    jurisdiction: "Chicago Transit Authority",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.transitchicago.com/procurement/",
    searchUrl: "https://www.transitchicago.com/procurement/",
    domain: "www.transitchicago.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Chicago Transit Authority procurement or business opportunities page.",
  },
  {
    id: "il-rta-procurement",
    name: "Regional Transportation Authority Procurement",
    jurisdiction: "Regional Transportation Authority Northeastern Illinois",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.rtachicago.org/doing-business/procurement",
    searchUrl: "https://www.rtachicago.org/doing-business/procurement",
    domain: "www.rtachicago.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Regional Transportation Authority Northeastern Illinois procurement or business opportunities page.",
  },
  {
    id: "ma-mbta-procurement",
    name: "MBTA Procurement",
    jurisdiction: "Massachusetts Bay Transportation Authority",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.mbta.com/business-center/procurement",
    searchUrl: "https://www.mbta.com/business-center/procurement",
    domain: "www.mbta.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Massachusetts Bay Transportation Authority procurement or business opportunities page.",
  },
  {
    id: "pa-septa-procurement",
    name: "SEPTA Procurement",
    jurisdiction: "Southeastern Pennsylvania Transportation Authority",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.septa.org/business/procurement/",
    searchUrl: "https://www.septa.org/business/procurement/",
    domain: "www.septa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Southeastern Pennsylvania Transportation Authority procurement or business opportunities page.",
  },
];
