import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_014: DirectRfpPortal[] = [
  {
    id: "tx-lubbock",
    name: "City of Lubbock Purchasing and Contract Management",
    jurisdiction: "City of Lubbock",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://ci.lubbock.tx.us/departments/purchasing-contract-management",
    searchUrl:
      "https://ci.lubbock.tx.us/departments/purchasing-contract-management",
    domain: "ci.lubbock.tx.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Lubbock procurement page.",
  },
  {
    id: "va-alexandria",
    name: "City of Alexandria Purchasing",
    jurisdiction: "City of Alexandria",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.alexandriava.gov/Purchasing",
    searchUrl: "https://www.alexandriava.gov/Purchasing",
    domain: "alexandriava.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Alexandria procurement page.",
  },
  {
    id: "mn-minneapolis",
    name: "City of Minneapolis Procurement",
    jurisdiction: "City of Minneapolis",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www2.minneapolismn.gov/business-services/doing-business-with-the-city/procurement/",
    searchUrl:
      "https://www2.minneapolismn.gov/business-services/doing-business-with-the-city/procurement/",
    domain: "www2.minneapolismn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Minneapolis procurement page.",
  }
];
