import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_003: DirectRfpPortal[] = [
  {
    id: "ky-lexington",
    name: "Lexington-Fayette Urban County Government Purchasing",
    jurisdiction: "Lexington-Fayette Urban County Government",
    state: "KY",
    country: "US",
    level: "district",
    url: "https://www.lexingtonky.gov/procurement",
    searchUrl: "https://www.lexingtonky.gov/procurement",
    domain: "lexingtonky.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lexington procurement page.",
  },
  {
    id: "la-jefferson-parish",
    name: "Jefferson Parish Purchasing",
    jurisdiction: "Jefferson Parish",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.jeffparish.gov/464/Purchasing",
    searchUrl: "https://www.jeffparish.gov/464/Purchasing",
    domain: "jeffparish.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jefferson Parish purchasing page.",
  },
  {
    id: "me-bangor",
    name: "City of Bangor Purchasing",
    jurisdiction: "City of Bangor",
    state: "ME",
    country: "US",
    level: "district",
    url: "https://www.bangormaine.gov/purchasing",
    searchUrl: "https://www.bangormaine.gov/purchasing",
    domain: "bangormaine.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bangor purchasing page.",
  },
  {
    id: "md-prince-georges-county",
    name: "Prince George's County Contract Administration and Procurement",
    jurisdiction: "Prince George's County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://www.princegeorgescountymd.gov/departments-offices/central-services/contract-administration-procurement",
    searchUrl:
      "https://www.princegeorgescountymd.gov/departments-offices/central-services/contract-administration-procurement",
    domain: "princegeorgescountymd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Prince George's County procurement page.",
  },
  {
    id: "ma-boston-public-schools-procurement",
    name: "Boston Public Schools Procurement",
    jurisdiction: "Boston Public Schools",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.bostonpublicschools.org/Page/331",
    searchUrl: "https://www.bostonpublicschools.org/Page/331",
    domain: "bostonpublicschools.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Boston Public Schools procurement page.",
  },
  {
    id: "mi-grand-rapids",
    name: "City of Grand Rapids Purchasing",
    jurisdiction: "City of Grand Rapids",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.grandrapidsmi.gov/Government/Departments/Fiscal-Services/Purchasing",
    searchUrl:
      "https://www.grandrapidsmi.gov/Government/Departments/Fiscal-Services/Purchasing",
    domain: "grandrapidsmi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Grand Rapids purchasing page.",
  },
  {
    id: "mn-ramsey-county",
    name: "Ramsey County Procurement",
    jurisdiction: "Ramsey County",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.ramseycounty.us/businesses/doing-business-ramsey-county/procurement",
    searchUrl:
      "https://www.ramseycounty.us/businesses/doing-business-ramsey-county/procurement",
    domain: "ramseycounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ramsey County procurement page.",
  },
  {
    id: "ms-hinds-county",
    name: "Hinds County Purchasing",
    jurisdiction: "Hinds County",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.hindscountyms.com/departments/purchasing",
    searchUrl: "https://www.hindscountyms.com/departments/purchasing",
    domain: "hindscountyms.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Hinds County purchasing page.",
  },
  {
    id: "mo-st-louis-county",
    name: "St. Louis County Procurement",
    jurisdiction: "St. Louis County",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://stlouiscountymo.gov/st-louis-county-departments/administration/procurement/",
    searchUrl:
      "https://stlouiscountymo.gov/st-louis-county-departments/administration/procurement/",
    domain: "stlouiscountymo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official St. Louis County procurement page.",
  },
  {
    id: "mt-missoula",
    name: "City of Missoula Purchasing",
    jurisdiction: "City of Missoula",
    state: "MT",
    country: "US",
    level: "district",
    url: "https://www.ci.missoula.mt.us/276/Purchasing",
    searchUrl: "https://www.ci.missoula.mt.us/276/Purchasing",
    domain: "ci.missoula.mt.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Missoula purchasing page.",
  },
  {
    id: "ne-lincoln",
    name: "City of Lincoln Purchasing",
    jurisdiction: "City of Lincoln",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    searchUrl: "https://www.lincoln.ne.gov/City/Departments/Finance/Purchasing",
    domain: "lincoln.ne.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lincoln purchasing page.",
  },
  {
    id: "nv-washoe-county",
    name: "Washoe County Purchasing",
    jurisdiction: "Washoe County",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.washoecounty.gov/clerks/cco/purchasing.php",
    searchUrl: "https://www.washoecounty.gov/clerks/cco/purchasing.php",
    domain: "washoecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Washoe County purchasing page.",
  },
  {
    id: "nh-nashua",
    name: "City of Nashua Purchasing",
    jurisdiction: "City of Nashua",
    state: "NH",
    country: "US",
    level: "district",
    url: "https://www.nashuanh.gov/390/Purchasing",
    searchUrl: "https://www.nashuanh.gov/390/Purchasing",
    domain: "nashuanh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Nashua purchasing page.",
  },
  {
    id: "nm-bernalillo-county",
    name: "Bernalillo County Purchasing",
    jurisdiction: "Bernalillo County",
    state: "NM",
    country: "US",
    level: "district",
    url: "https://www.bernco.gov/finance/purchasing/",
    searchUrl: "https://www.bernco.gov/finance/purchasing/",
    domain: "bernco.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bernalillo County purchasing page.",
  },
  {
    id: "ny-westchester-county",
    name: "Westchester County Purchasing",
    jurisdiction: "Westchester County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.westchestergov.com/purchasing",
    searchUrl: "https://www.westchestergov.com/purchasing",
    domain: "westchestergov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Westchester County purchasing page.",
  },
  {
    id: "nc-guilford-county",
    name: "Guilford County Purchasing",
    jurisdiction: "Guilford County",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.guilfordcountync.gov/our-county/purchasing",
    searchUrl: "https://www.guilfordcountync.gov/our-county/purchasing",
    domain: "guilfordcountync.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Guilford County purchasing page.",
  },
  {
    id: "nd-bismarck",
    name: "City of Bismarck Purchasing",
    jurisdiction: "City of Bismarck",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://www.bismarcknd.gov/88/Purchasing",
    searchUrl: "https://www.bismarcknd.gov/88/Purchasing",
    domain: "bismarcknd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Bismarck purchasing page.",
  },
  {
    id: "oh-cuyahoga-county",
    name: "Cuyahoga County Procurement and Diversity",
    jurisdiction: "Cuyahoga County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://cuyahogacounty.gov/procurement",
    searchUrl: "https://cuyahogacounty.gov/procurement",
    domain: "cuyahogacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Cuyahoga County procurement page.",
  },
  {
    id: "ok-tulsa",
    name: "City of Tulsa Purchasing",
    jurisdiction: "City of Tulsa",
    state: "OK",
    country: "US",
    level: "district",
    url: "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    searchUrl:
      "https://www.cityoftulsa.org/government/departments/finance/purchasing/",
    domain: "cityoftulsa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tulsa purchasing page.",
  },
  {
    id: "or-multnomah-county",
    name: "Multnomah County Purchasing",
    jurisdiction: "Multnomah County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.multco.us/purchasing",
    searchUrl: "https://www.multco.us/purchasing",
    domain: "multco.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Multnomah County purchasing page.",
  },
  {
    id: "pa-philadelphia",
    name: "City of Philadelphia Procurement Department",
    jurisdiction: "City of Philadelphia",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.phila.gov/departments/procurement-department/",
    searchUrl: "https://www.phila.gov/departments/procurement-department/",
    domain: "phila.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Philadelphia Procurement Department page.",
  },
  {
    id: "ri-warwick",
    name: "City of Warwick Purchasing",
    jurisdiction: "City of Warwick",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://www.warwickri.gov/purchasing-department",
    searchUrl: "https://www.warwickri.gov/purchasing-department",
    domain: "warwickri.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Warwick purchasing department page.",
  },
  {
    id: "sc-greenville-county",
    name: "Greenville County Procurement Services",
    jurisdiction: "Greenville County",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://www.greenvillecounty.org/Procurement/",
    searchUrl: "https://www.greenvillecounty.org/Procurement/",
    domain: "greenvillecounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Greenville County procurement services page.",
  },
  {
    id: "sd-rapid-city",
    name: "City of Rapid City Purchasing",
    jurisdiction: "City of Rapid City",
    state: "SD",
    country: "US",
    level: "district",
    url: "https://www.rcgov.org/departments/finance/purchasing.html",
    searchUrl: "https://www.rcgov.org/departments/finance/purchasing.html",
    domain: "rcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Rapid City purchasing page.",
  },
  {
    id: "tn-chattanooga",
    name: "City of Chattanooga Purchasing",
    jurisdiction: "City of Chattanooga",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://chattanooga.gov/finance/purchasing",
    searchUrl: "https://chattanooga.gov/finance/purchasing",
    domain: "chattanooga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Chattanooga purchasing page.",
  },
  {
    id: "tx-austin",
    name: "City of Austin Financial Services Purchasing",
    jurisdiction: "City of Austin",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.austintexas.gov/department/purchasing",
    searchUrl: "https://www.austintexas.gov/department/purchasing",
    domain: "austintexas.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Austin purchasing page.",
  },
  {
    id: "ut-salt-lake-county",
    name: "Salt Lake County Contracts and Procurement",
    jurisdiction: "Salt Lake County",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.saltlakecounty.gov/contracts/",
    searchUrl: "https://www.saltlakecounty.gov/contracts/",
    domain: "saltlakecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Salt Lake County contracts and procurement page.",
  },
  {
    id: "vt-south-burlington",
    name: "City of South Burlington Purchasing",
    jurisdiction: "City of South Burlington",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.southburlingtonvt.gov/business/purchasing.php",
    searchUrl: "https://www.southburlingtonvt.gov/business/purchasing.php",
    domain: "southburlingtonvt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official South Burlington purchasing page.",
  },
  {
    id: "va-norfolk",
    name: "City of Norfolk Purchasing",
    jurisdiction: "City of Norfolk",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.norfolk.gov/291/Purchasing",
    searchUrl: "https://www.norfolk.gov/291/Purchasing",
    domain: "norfolk.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Norfolk purchasing page.",
  },
  {
    id: "wa-spokane",
    name: "City of Spokane Purchasing",
    jurisdiction: "City of Spokane",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://my.spokanecity.org/business/purchasing/",
    searchUrl: "https://my.spokanecity.org/business/purchasing/",
    domain: "my.spokanecity.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Spokane purchasing page.",
  },
  {
    id: "wv-huntington",
    name: "City of Huntington Purchasing",
    jurisdiction: "City of Huntington",
    state: "WV",
    country: "US",
    level: "district",
    url: "https://www.cityofhuntington.com/city-government/departments/finance/purchasing/",
    searchUrl:
      "https://www.cityofhuntington.com/city-government/departments/finance/purchasing/",
    domain: "cityofhuntington.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Huntington purchasing page.",
  },
  {
    id: "wi-madison",
    name: "City of Madison Purchasing Services",
    jurisdiction: "City of Madison",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://www.cityofmadison.com/finance/purchasing/",
    searchUrl: "https://www.cityofmadison.com/finance/purchasing/",
    domain: "cityofmadison.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Madison purchasing services page.",
  },
  {
    id: "wy-casper",
    name: "City of Casper Purchasing",
    jurisdiction: "City of Casper",
    state: "WY",
    country: "US",
    level: "district",
    url: "https://www.casperwy.gov/government/city_manager/purchasing",
    searchUrl: "https://www.casperwy.gov/government/city_manager/purchasing",
    domain: "casperwy.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Casper purchasing page.",
  },
  {
    id: "pr-university-of-puerto-rico",
    name: "University of Puerto Rico Purchasing",
    jurisdiction: "University of Puerto Rico",
    state: "PR",
    country: "US",
    level: "district",
    url: "https://www.upr.edu/procurement/",
    searchUrl: "https://www.upr.edu/procurement/",
    domain: "upr.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Puerto Rico procurement page.",
  },
  {
    id: "vi-water-and-power-authority-procurement",
    name: "Virgin Islands Water and Power Authority Procurement",
    jurisdiction: "Virgin Islands Water and Power Authority",
    state: "VI",
    country: "US",
    level: "district",
    url: "https://www.viwapa.vi/about/procurement/",
    searchUrl: "https://www.viwapa.vi/about/procurement/",
    domain: "viwapa.vi",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official VIWAPA procurement page.",
  },
];
