import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_007: DirectRfpPortal[] = [
  {
    id: "fl-orange-county",
    name: "Orange County Procurement",
    jurisdiction: "Orange County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orangecountyfl.net/VendorServices.aspx",
    searchUrl: "https://www.orangecountyfl.net/VendorServices.aspx",
    domain: "orangecountyfl.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Orange County vendor services/procurement page.",
  },
  {
    id: "fl-jacksonville",
    name: "City of Jacksonville Procurement",
    jurisdiction: "City of Jacksonville",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.jacksonville.gov/departments/finance/procurement",
    searchUrl: "https://www.jacksonville.gov/departments/finance/procurement",
    domain: "jacksonville.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Jacksonville procurement page.",
  },
  {
    id: "fl-miami",
    name: "City of Miami Procurement",
    jurisdiction: "City of Miami",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.miami.gov/Services/Doing-Business/Procurement",
    searchUrl: "https://www.miami.gov/Services/Doing-Business/Procurement",
    domain: "miami.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Miami procurement page.",
  },
  {
    id: "fl-orlando",
    name: "City of Orlando Procurement and Contracts",
    jurisdiction: "City of Orlando",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orlando.gov/Our-Government/Departments-Offices/Executive-Offices/Procurement-and-Contracts",
    searchUrl:
      "https://www.orlando.gov/Our-Government/Departments-Offices/Executive-Offices/Procurement-and-Contracts",
    domain: "orlando.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Orlando procurement and contracts page.",
  },
  {
    id: "fl-tallahassee",
    name: "City of Tallahassee Procurement Services",
    jurisdiction: "City of Tallahassee",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.talgov.com/doingbusiness/procurementservices",
    searchUrl: "https://www.talgov.com/doingbusiness/procurementservices",
    domain: "talgov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Tallahassee procurement services page.",
  },
  {
    id: "fl-gainesville",
    name: "City of Gainesville Procurement",
    jurisdiction: "City of Gainesville",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.gainesvillefl.gov/Government-Pages/Government/Departments/Financial-Services/Procurement",
    searchUrl:
      "https://www.gainesvillefl.gov/Government-Pages/Government/Departments/Financial-Services/Procurement",
    domain: "gainesvillefl.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Gainesville procurement page.",
  },
  {
    id: "fl-ucf",
    name: "University of Central Florida Procurement Services",
    jurisdiction: "University of Central Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.ucf.edu/",
    searchUrl: "https://procurement.ucf.edu/",
    domain: "procurement.ucf.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UCF procurement services page.",
  },
  {
    id: "fl-uf",
    name: "University of Florida Procurement Services",
    jurisdiction: "University of Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.ufl.edu/",
    searchUrl: "https://procurement.ufl.edu/",
    domain: "procurement.ufl.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UF procurement services page.",
  },
  {
    id: "fl-fiu",
    name: "Florida International University Purchasing Services",
    jurisdiction: "Florida International University",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://controller.fiu.edu/departments/purchasing/",
    searchUrl: "https://controller.fiu.edu/departments/purchasing/",
    domain: "controller.fiu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official FIU purchasing services page.",
  },
  {
    id: "fl-miami-airport",
    name: "Miami International Airport Business Opportunities",
    jurisdiction: "Miami International Airport",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.miami-airport.com/business_opportunities.asp",
    searchUrl: "https://www.miami-airport.com/business_opportunities.asp",
    domain: "miami-airport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official MIA business opportunities page.",
  },
  {
    id: "fl-greater-orlando-aviation",
    name: "Greater Orlando Aviation Authority Purchasing",
    jurisdiction: "Greater Orlando Aviation Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orlandoairports.net/getting-around-mco/business-opportunities/purchasing/",
    searchUrl:
      "https://www.orlandoairports.net/getting-around-mco/business-opportunities/purchasing/",
    domain: "orlandoairports.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official GOAA purchasing page.",
  },
  {
    id: "fl-jacksonville-port",
    name: "Jacksonville Port Authority Procurement",
    jurisdiction: "Jacksonville Port Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.jaxport.com/procurement/",
    searchUrl: "https://www.jaxport.com/procurement/",
    domain: "jaxport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official JAXPORT procurement page.",
  },
  {
    id: "fl-port-everglades",
    name: "Port Everglades Business Opportunities",
    jurisdiction: "Port Everglades",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.porteverglades.net/business/business-opportunities/",
    searchUrl:
      "https://www.porteverglades.net/business/business-opportunities/",
    domain: "porteverglades.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Port Everglades business opportunities page.",
  },
  {
    id: "fl-hart",
    name: "Hillsborough Area Regional Transit Procurement",
    jurisdiction: "Hillsborough Transit Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.gohart.org/Pages/AboutUS-Procurement.aspx",
    searchUrl: "https://www.gohart.org/Pages/AboutUS-Procurement.aspx",
    domain: "gohart.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official HART procurement page.",
  },
  {
    id: "fl-lynx",
    name: "LYNX Procurement",
    jurisdiction: "Central Florida Regional Transportation Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.golynx.com/corporate-info/procurement.stml",
    searchUrl: "https://www.golynx.com/corporate-info/procurement.stml",
    domain: "golynx.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official LYNX procurement page.",
  },
  {
    id: "fl-tampa-bay-water",
    name: "Tampa Bay Water Procurement",
    jurisdiction: "Tampa Bay Water",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.tampabaywater.org/business/procurement",
    searchUrl: "https://www.tampabaywater.org/business/procurement",
    domain: "tampabaywater.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tampa Bay Water procurement page.",
  },
  {
    id: "fl-miami-dade-schools",
    name: "Miami-Dade County Public Schools Procurement",
    jurisdiction: "Miami-Dade County Public Schools",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.dadeschools.net/",
    searchUrl: "https://procurement.dadeschools.net/",
    domain: "procurement.dadeschools.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official M-DCPS procurement page.",
  },
  {
    id: "fl-broward-schools",
    name: "Broward County Public Schools Procurement",
    jurisdiction: "Broward County Public Schools",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.browardschools.com/procurement",
    searchUrl: "https://www.browardschools.com/procurement",
    domain: "browardschools.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official BCPS procurement page.",
  },
];
