import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_009: DirectRfpPortal[] = [
  {
    id: "tx-irving",
    name: "City of Irving Purchasing",
    jurisdiction: "City of Irving",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.cityofirving.org/89/Purchasing",
    searchUrl: "https://www.cityofirving.org/89/Purchasing",
    domain: "cityofirving.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Irving procurement page.",
  },
  {
    id: "ca-san-bernardino-county",
    name: "San Bernardino County Purchasing",
    jurisdiction: "San Bernardino County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://wp.sbcounty.gov/purchasing/",
    searchUrl: "https://wp.sbcounty.gov/purchasing/",
    domain: "wp.sbcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official San Bernardino County procurement page.",
  },
  {
    id: "il-lake-county",
    name: "Lake County Purchasing",
    jurisdiction: "Lake County",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.lakecountyil.gov/344/Purchasing",
    searchUrl: "https://www.lakecountyil.gov/344/Purchasing",
    domain: "lakecountyil.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lake County procurement page.",
  },
  {
    id: "ca-kern-county",
    name: "Kern County Purchasing",
    jurisdiction: "Kern County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.kerncounty.com/government/purchasing",
    searchUrl: "https://www.kerncounty.com/government/purchasing",
    domain: "kerncounty.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Kern County procurement page.",
  },
  {
    id: "ca-sacramento-city",
    name: "City of Sacramento Procurement Services",
    jurisdiction: "City of Sacramento",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.cityofsacramento.gov/finance/procurement",
    searchUrl: "https://www.cityofsacramento.gov/finance/procurement",
    domain: "cityofsacramento.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Sacramento procurement page.",
  },
  {
    id: "az-chandler",
    name: "City of Chandler Purchasing",
    jurisdiction: "City of Chandler",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.chandleraz.gov/government/departments/management-services/purchasing",
    searchUrl:
      "https://www.chandleraz.gov/government/departments/management-services/purchasing",
    domain: "chandleraz.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Chandler procurement page.",
  },
];
