import { GENERATED_DIRECT_RFP_PORTALS } from "./directRfpPortals.generated";
import { ADDITIONAL_DIRECTORY_PORTALS } from "./portalDirectory";

export type DirectRfpPortalLevel = "federal" | "state" | "district" | "international";
export type DirectRfpPortalAccessMode = "api" | "csv" | "public_html" | "dynamic_html" | "portal";
export type DirectRfpPortalParserStatus = "ready_to_parse" | "needs_parser" | "catalog_only";
export type OccuMedPortalFit = "verified_high" | "likely" | "broad" | "insufficient_evidence";

export interface DirectRfpPortal {
  id: string;
  name: string;
  jurisdiction: string;
  state?: string;
  country: string;
  level: DirectRfpPortalLevel;
  url: string;
  searchUrl?: string;
  domain: string;
  accessMode: DirectRfpPortalAccessMode;
  requiresKey: boolean;
  requiresLogin: boolean;
  tier: 1 | 2 | 3;
  parserStatus: DirectRfpPortalParserStatus;
  notes: string;
  occumedFit?: OccuMedPortalFit;
  occumedServiceCategories?: string[];
  relevanceReasonCodes?: string[];
  relevanceEvidence?: string[];
  relevanceEvidenceUrls?: string[];
  lastRelevanceVerified?: string;
  buyerSector?: string;
}

/**
 * Direct official RFP/opportunity portals.
 *
 * This catalog intentionally excludes paid/public aggregators such as BidNet,
 * DemandStar, GovWin, PlanetBids, OpenGov network pages, Periscope/S2G, and
 * generic search engines. Those may be useful for discovery, but they are not
 * the direct buyer/source-of-truth layer we want to build on.
 */
export const CORE_DIRECT_RFP_PORTALS: DirectRfpPortal[] = [
  {
    id: "us-sam-gov",
    name: "SAM.gov Contract Opportunities",
    jurisdiction: "United States Federal Government",
    country: "US",
    level: "federal",
    url: "https://sam.gov/content/opportunities",
    searchUrl: "https://sam.gov/content/opportunities",
    domain: "sam.gov",
    accessMode: "api",
    requiresKey: true,
    requiresLogin: false,
    tier: 1,
    parserStatus: "ready_to_parse",
    notes: "Primary official federal contract opportunity API/source.",
  },
  { id: "tx-esbd", name: "Texas ESBD / Texas SmartBuy", jurisdiction: "Texas", state: "TX", country: "US", level: "state", url: "https://www.txsmartbuy.gov/esbd", searchUrl: "https://www.txsmartbuy.gov/esbd", domain: "txsmartbuy.gov", accessMode: "csv", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Public official Texas bid portal; high priority because listings are structured and export-friendly." },
  { id: "ny-contract-reporter", name: "New York State Contract Reporter", jurisdiction: "New York", state: "NY", country: "US", level: "state", url: "https://www.nyscr.ny.gov/", searchUrl: "https://www.nyscr.ny.gov/contracts.cfm", domain: "nyscr.ny.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official New York contracting opportunity portal." },
  { id: "va-eva", name: "Virginia eVA / Business Opportunities", jurisdiction: "Virginia", state: "VA", country: "US", level: "state", url: "https://eva.virginia.gov/", searchUrl: "https://eva.virginia.gov/business-opportunities.html", domain: "eva.virginia.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Virginia procurement marketplace and business opportunities portal." },
  { id: "pa-emarketplace", name: "Pennsylvania eMarketplace", jurisdiction: "Pennsylvania", state: "PA", country: "US", level: "state", url: "https://www.emarketplace.state.pa.us/", searchUrl: "https://www.emarketplace.state.pa.us/Solicitations.aspx", domain: "emarketplace.state.pa.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Pennsylvania bid, award, and contract portal." },
  { id: "ca-caleprocure", name: "California Cal eProcure", jurisdiction: "California", state: "CA", country: "US", level: "state", url: "https://caleprocure.ca.gov/", searchUrl: "https://caleprocure.ca.gov/pages/Events-BS3/event-search.aspx", domain: "caleprocure.ca.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official California event search. Dynamic page; likely needs a dedicated parser/browser-safe fetch strategy." },
  { id: "fl-vbs", name: "Florida Vendor Bid System", jurisdiction: "Florida", state: "FL", country: "US", level: "state", url: "https://vendor.myfloridamarketplace.com/", searchUrl: "https://vendor.myfloridamarketplace.com/search/bids", domain: "vendor.myfloridamarketplace.com", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Florida public bid search." },
  { id: "oh-ohiobuys", name: "OhioBuys / Ohio Procurement", jurisdiction: "Ohio", state: "OH", country: "US", level: "state", url: "https://procure.ohio.gov/", searchUrl: "https://procure.ohio.gov/proc/view-procurement-opportunities", domain: "procure.ohio.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Ohio procurement opportunities portal." },
  { id: "md-emma", name: "eMaryland Marketplace Advantage", jurisdiction: "Maryland", state: "MD", country: "US", level: "state", url: "https://emma.maryland.gov/", searchUrl: "https://emma.maryland.gov/page.aspx/en/rfp/request_browse_public", domain: "emma.maryland.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Maryland public solicitations portal." },
  { id: "ar-arbuy", name: "Arkansas ARBuy", jurisdiction: "Arkansas", state: "AR", country: "US", level: "state", url: "https://arbuy.arkansas.gov/", searchUrl: "https://arbuy.arkansas.gov/", domain: "arbuy.arkansas.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Arkansas procurement portal." },
  { id: "ct-ctsource", name: "Connecticut CTsource Bid Board", jurisdiction: "Connecticut", state: "CT", country: "US", level: "state", url: "https://portal.ct.gov/DAS/CTSource/BidBoard", searchUrl: "https://portal.ct.gov/DAS/CTSource/BidBoard", domain: "portal.ct.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Connecticut DAS/CTsource bid board." },
  { id: "ga-gpr", name: "Georgia Procurement Registry", jurisdiction: "Georgia", state: "GA", country: "US", level: "state", url: "https://ssl.doas.state.ga.us/gpr/", searchUrl: "https://ssl.doas.state.ga.us/gpr/", domain: "ssl.doas.state.ga.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Georgia Procurement Registry." },
  { id: "id-purchasing", name: "Idaho Division of Purchasing", jurisdiction: "Idaho", state: "ID", country: "US", level: "state", url: "https://purchasing.idaho.gov/", searchUrl: "https://purchasing.idaho.gov/", domain: "purchasing.idaho.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Idaho purchasing portal." },
  { id: "il-bidbuy", name: "Illinois BidBuy", jurisdiction: "Illinois", state: "IL", country: "US", level: "state", url: "https://bidbuy.illinois.gov/", searchUrl: "https://bidbuy.illinois.gov/", domain: "bidbuy.illinois.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Illinois BidBuy portal." },
  { id: "in-idoa", name: "Indiana Current Business Opportunities", jurisdiction: "Indiana", state: "IN", country: "US", level: "state", url: "https://www.in.gov/idoa/procurement/current-business-opportunities/", searchUrl: "https://www.in.gov/idoa/procurement/current-business-opportunities/", domain: "in.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Indiana Department of Administration procurement opportunities." },
  { id: "ia-das", name: "Iowa DAS Bid Opportunities", jurisdiction: "Iowa", state: "IA", country: "US", level: "state", url: "https://das.iowa.gov/procurement", searchUrl: "https://bids.sciquest.com/apps/Router/PublicEvent?CustomerOrg=DASIowa", domain: "bids.sciquest.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Iowa DAS public bid event portal." },
  { id: "la-lapac", name: "Louisiana LaPAC", jurisdiction: "Louisiana", state: "LA", country: "US", level: "state", url: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", searchUrl: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", domain: "wwwcfprd.doa.louisiana.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Louisiana Procurement and Contract Network." },
  { id: "me-rfps", name: "Maine Division of Procurement Services RFPs", jurisdiction: "Maine", state: "ME", country: "US", level: "state", url: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", searchUrl: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", domain: "maine.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Maine RFP listing page." },
  { id: "ma-commbuys", name: "Massachusetts COMMBUYS", jurisdiction: "Massachusetts", state: "MA", country: "US", level: "state", url: "https://www.commbuys.com/bso/", searchUrl: "https://www.commbuys.com/bso/", domain: "commbuys.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Massachusetts COMMBUYS portal." },
  { id: "mi-sigma", name: "Michigan SIGMA VSS", jurisdiction: "Michigan", state: "MI", country: "US", level: "state", url: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", searchUrl: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", domain: "sigma.michigan.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Michigan SIGMA VSS public portal." },
  { id: "ms-magic", name: "Mississippi MAGIC Contract/Bid Search", jurisdiction: "Mississippi", state: "MS", country: "US", level: "state", url: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", searchUrl: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", domain: "ms.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Mississippi DFA bid search." },
  { id: "mo-missouribuys", name: "MissouriBUYS", jurisdiction: "Missouri", state: "MO", country: "US", level: "state", url: "https://missouribuys.mo.gov/", searchUrl: "https://missouribuys.mo.gov/", domain: "missouribuys.mo.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Missouri procurement portal." },
  { id: "nv-epro", name: "NevadaEPro", jurisdiction: "Nevada", state: "NV", country: "US", level: "state", url: "https://nevadaepro.com/bso/", searchUrl: "https://nevadaepro.com/bso/", domain: "nevadaepro.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official Nevada electronic procurement portal." },
  { id: "nj-start", name: "New Jersey START", jurisdiction: "New Jersey", state: "NJ", country: "US", level: "state", url: "https://www.njstart.gov/bso/", searchUrl: "https://www.njstart.gov/bso/", domain: "njstart.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official New Jersey START procurement portal." },
  { id: "nm-active-procurements", name: "New Mexico Active Procurements", jurisdiction: "New Mexico", state: "NM", country: "US", level: "state", url: "https://www.generalservices.state.nm.us/state-purchasing/", searchUrl: "https://www.generalservices.state.nm.us/state-purchasing/active-procurements/", domain: "generalservices.state.nm.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official New Mexico state purchasing active procurements." },
  { id: "nc-evp", name: "North Carolina eVP Solicitations", jurisdiction: "North Carolina", state: "NC", country: "US", level: "state", url: "https://evp.nc.gov/", searchUrl: "https://evp.nc.gov/solicitations/", domain: "evp.nc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official North Carolina electronic Vendor Portal solicitations." },
  { id: "nd-spo", name: "North Dakota Current Solicitations", jurisdiction: "North Dakota", state: "ND", country: "US", level: "state", url: "https://www.omb.nd.gov/doing-business-state/procurement", searchUrl: "https://apps.nd.gov/csd/spo/services/bidder/listCurrentSolicitations.htm", domain: "apps.nd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official North Dakota current solicitations page." },
  { id: "ri-bids", name: "Rhode Island Division of Purchases Bidding Opportunities", jurisdiction: "Rhode Island", state: "RI", country: "US", level: "state", url: "https://ridop.ri.gov/", searchUrl: "https://ridop.ri.gov/vendors/bidding-opportunities", domain: "ridop.ri.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Rhode Island bidding opportunities page." },
  { id: "sd-solicitations", name: "South Dakota Procurement Solicitations", jurisdiction: "South Dakota", state: "SD", country: "US", level: "state", url: "https://boa.sd.gov/central-services/procurement-management/", searchUrl: "https://boa.sd.gov/central-services/procurement-management/solicitations.aspx", domain: "boa.sd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official South Dakota procurement solicitations page." },
  { id: "ca-los-angeles-county", name: "Los Angeles County Open Solicitations", jurisdiction: "Los Angeles County", state: "CA", country: "US", level: "district", url: "https://doingbusiness.lacounty.gov/", searchUrl: "https://doingbusiness.lacounty.gov/open-solicitations/", domain: "doingbusiness.lacounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Los Angeles County Doing Business portal with open solicitation listings." },
  { id: "ca-orange-county", name: "Orange County Open Bids", jurisdiction: "Orange County", state: "CA", country: "US", level: "district", url: "https://cpo.ocgov.com/", searchUrl: "https://cpo.ocgov.com/open-bids", domain: "cpo.ocgov.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official County Procurement Office page for active County bid solicitations." },
  { id: "ca-san-francisco", name: "City and County of San Francisco Bid Opportunities", jurisdiction: "San Francisco", state: "CA", country: "US", level: "district", url: "https://www.sf.gov/topics--contracting-city-and-county-san-francisco", searchUrl: "https://www.sf.gov/information--bid-opportunities", domain: "sf.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official SF.gov bid opportunities page for City and County contracting." },
  { id: "ca-city-of-long-beach", name: "City of Long Beach Purchasing", jurisdiction: "City of Long Beach", state: "CA", country: "US", level: "district", url: "https://longbeach.gov/finance/business-info/purchasing-division/", searchUrl: "https://longbeach.gov/finance/business-info/purchasing-division/", domain: "longbeach.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official purchasing division page linking to Long Beach Buys opportunities and vendor resources." },
  { id: "ca-orange-county-fire-authority", name: "Orange County Fire Authority Purchasing", jurisdiction: "Orange County Fire Authority", state: "CA", country: "US", level: "district", url: "https://ocfa.org/about-us/departments/business-services/purchasing/", searchUrl: "https://ocfa.org/about-us/departments/business-services/purchasing/", domain: "ocfa.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official OCFA purchasing page for supplier registration, current bids, RFPs, and bid results." },
  { id: "ca-port-of-los-angeles", name: "Port of Los Angeles Contracting Opportunities", jurisdiction: "Port of Los Angeles", state: "CA", country: "US", level: "district", url: "https://portoflosangeles.org/business/contracting-opportunities", searchUrl: "https://portoflosangeles.org/business/contracting-opportunities/purchasing-bids", domain: "portoflosangeles.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Port of Los Angeles contracting opportunities and purchasing bids pages." },
  { id: "ca-la-metro", name: "LA Metro Contracting Opportunities", jurisdiction: "Los Angeles County Metropolitan Transportation Authority", state: "CA", country: "US", level: "district", url: "https://www.metro.net/about/doing-business-with-metro/", searchUrl: "https://www.metro.net/about/doing-business-with-metro/", domain: "metro.net", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official LA Metro doing-business page for procurement and contracting opportunity access." },
  { id: "tx-harris-county", name: "Harris County Online Solicitation Opportunities", jurisdiction: "Harris County", state: "TX", country: "US", level: "district", url: "https://purchasing.harriscountytx.gov/", searchUrl: "https://purchasing.harriscountytx.gov/Services/Online-Solicitation-Opportunities", domain: "purchasing.harriscountytx.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Harris County Purchasing page for online solicitation opportunities." },
  { id: "tx-city-of-austin", name: "City of Austin Active Solicitations", jurisdiction: "City of Austin", state: "TX", country: "US", level: "district", url: "https://www.austintexas.gov/financial-services/solicitations", searchUrl: "https://financeonline.austintexas.gov/afo/account_services/solicitation/solicitations.cfm", domain: "financeonline.austintexas.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official City of Austin active solicitations table." },
  { id: "tx-city-of-san-antonio", name: "City of San Antonio Bidding and Contracting", jurisdiction: "City of San Antonio", state: "TX", country: "US", level: "district", url: "https://www.sanantonio.gov/purchasing", searchUrl: "https://webapp1.sanantonio.gov/BidContractOpps/Default.aspx", domain: "webapp1.sanantonio.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official City of San Antonio bid and contract opportunities listing." },
  { id: "ny-city-of-new-york", name: "New York City PASSPort Public", jurisdiction: "New York City", state: "NY", country: "US", level: "district", url: "https://www.nyc.gov/site/mocs/passport/about-passport.page", searchUrl: "https://a0333-passportpublic.nyc.gov/", domain: "a0333-passportpublic.nyc.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official NYC PASSPort public procurement navigator; public opportunities are browsable without an account." },
  { id: "fl-miami-dade-county", name: "Miami-Dade County Solicitations", jurisdiction: "Miami-Dade County", state: "FL", country: "US", level: "district", url: "https://www.miamidade.gov/global/strategic-procurement/solicitations.page", searchUrl: "https://www.miamidade.gov/apps/ISD/stratproc/Home/CurrentSolicitations", domain: "miamidade.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Miami-Dade County Strategic Procurement current solicitations list." },
  { id: "va-fairfax-county", name: "Fairfax County Current Solicitations", jurisdiction: "Fairfax County", state: "VA", country: "US", level: "district", url: "https://www.fairfaxcounty.gov/procurement/contracting-opportunities", searchUrl: "https://www.fairfaxcounty.gov/solicitation/", domain: "fairfaxcounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Fairfax County procurement opportunities and current solicitations pages." },
  { id: "wa-king-county", name: "King County Solicitations", jurisdiction: "King County", state: "WA", country: "US", level: "district", url: "https://kingcounty.gov/en/dept/executive-services/about-king-county/business-operations/finance-business-operations/procurement-payables", searchUrl: "https://kingcounty.gov/en/dept/executive-services/about-king-county/business-operations/finance-business-operations/procurement-payables", domain: "kingcounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official King County Procurement and Payables page linking current solicitation abstracts and the E-Procurement Supplier Portal." },
  { id: "tn-nashville", name: "Metropolitan Government of Nashville Procurement", jurisdiction: "Metropolitan Government of Nashville and Davidson County", state: "TN", country: "US", level: "district", url: "https://www.nashville.gov/departments/finance/procurement", searchUrl: "https://www.nashville.gov/departments/finance/procurement", domain: "nashville.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Metro Nashville procurement page for solicitation and vendor resources." },
  { id: "la-new-orleans", name: "City of New Orleans Purchasing", jurisdiction: "City of New Orleans", state: "LA", country: "US", level: "district", url: "https://nola.gov/purchasing/", searchUrl: "https://nola.gov/purchasing/", domain: "nola.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of New Orleans purchasing page for bid and vendor information." },
  { id: "ca-sandag", name: "SANDAG Contracts and Procurement", jurisdiction: "San Diego Association of Governments", state: "CA", country: "US", level: "district", url: "https://www.sandag.org/contracts", searchUrl: "https://www.sandag.org/contracts", domain: "sandag.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official SANDAG contracts page for procurement opportunities and vendor resources." },
  { id: "ca-bart", name: "BART Procurement Opportunities", jurisdiction: "San Francisco Bay Area Rapid Transit District", state: "CA", country: "US", level: "district", url: "https://www.bart.gov/about/business/procurement", searchUrl: "https://www.bart.gov/about/business/procurement", domain: "bart.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official BART procurement page for contracting opportunities and vendor information." },
  { id: "ca-port-of-oakland", name: "Port of Oakland Bids and RFPs", jurisdiction: "Port of Oakland", state: "CA", country: "US", level: "district", url: "https://www.portofoakland.com/business/bids-rfps/", searchUrl: "https://www.portofoakland.com/business/bids-rfps/", domain: "portofoakland.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Port of Oakland bids and RFPs page." },
  { id: "tx-dallas-isd", name: "Dallas ISD Procurement Services", jurisdiction: "Dallas Independent School District", state: "TX", country: "US", level: "district", url: "https://www.dallasisd.org/procurement", searchUrl: "https://www.dallasisd.org/procurement", domain: "dallasisd.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Dallas ISD procurement services page for bid and vendor information." },
  { id: "ny-mta", name: "MTA Doing Business With Us", jurisdiction: "Metropolitan Transportation Authority", state: "NY", country: "US", level: "district", url: "https://new.mta.info/doing-business-with-us", searchUrl: "https://new.mta.info/doing-business-with-us", domain: "new.mta.info", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official MTA procurement and contracting entry point for public transit opportunities." },
  { id: "ny-port-authority", name: "Port Authority of New York and New Jersey Procurement", jurisdiction: "Port Authority of New York and New Jersey", state: "NY", country: "US", level: "district", url: "https://www.panynj.gov/port-authority/en/business-opportunities.html", searchUrl: "https://www.panynj.gov/port-authority/en/business-opportunities.html", domain: "panynj.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official PANYNJ business opportunities page for port and airport authority procurement." },
  { id: "nj-njtransit", name: "NJ TRANSIT Procurement", jurisdiction: "New Jersey Transit", state: "NJ", country: "US", level: "district", url: "https://www.njtransit.com/procurement", searchUrl: "https://www.njtransit.com/procurement", domain: "njtransit.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official NJ TRANSIT procurement page for transit solicitations and vendor resources." },
  { id: "fl-orange-county-public-schools", name: "Orange County Public Schools Procurement Services", jurisdiction: "Orange County Public Schools", state: "FL", country: "US", level: "district", url: "https://www.ocps.net/departments/procurement_services", searchUrl: "https://www.ocps.net/departments/procurement_services", domain: "ocps.net", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official OCPS procurement services page for school district purchasing opportunities." },
  { id: "fl-jtafla", name: "Jacksonville Transportation Authority Procurement", jurisdiction: "Jacksonville Transportation Authority", state: "FL", country: "US", level: "district", url: "https://www.jtafla.com/procurement/", searchUrl: "https://www.jtafla.com/procurement/", domain: "jtafla.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official JTA procurement page for transit solicitations and vendor information." },
  { id: "va-henrico-county", name: "Henrico County Purchasing", jurisdiction: "Henrico County", state: "VA", country: "US", level: "district", url: "https://henrico.us/purchasing/", searchUrl: "https://henrico.us/purchasing/", domain: "henrico.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Henrico County purchasing page for solicitations and vendor information." },
  { id: "md-baltimore-county", name: "Baltimore County Purchasing", jurisdiction: "Baltimore County", state: "MD", country: "US", level: "district", url: "https://www.baltimorecountymd.gov/departments/budfin/purchasing/", searchUrl: "https://www.baltimorecountymd.gov/departments/budfin/purchasing/", domain: "baltimorecountymd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Baltimore County purchasing page for bids and vendor resources." },
  { id: "wa-port-of-seattle", name: "Port of Seattle Bid Opportunities", jurisdiction: "Port of Seattle", state: "WA", country: "US", level: "district", url: "https://www.portseattle.org/business/bid-opportunities", searchUrl: "https://www.portseattle.org/business/bid-opportunities", domain: "portseattle.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Port of Seattle bid opportunities page for port and airport procurement." },
  { id: "il-cook-county", name: "Cook County Procurement", jurisdiction: "Cook County", state: "IL", country: "US", level: "district", url: "https://www.cookcountyil.gov/service/doing-business-cook-county", searchUrl: "https://www.cookcountyil.gov/service/doing-business-cook-county", domain: "cookcountyil.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Cook County doing-business page for procurement opportunities and vendor resources." },
  { id: "ut-uta", name: "Utah Transit Authority Procurement", jurisdiction: "Utah Transit Authority", state: "UT", country: "US", level: "district", url: "https://www.rideuta.com/Doing-Business/Procurement", searchUrl: "https://www.rideuta.com/Doing-Business/Procurement", domain: "rideuta.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official UTA procurement page for transit contracting opportunities." },
  { id: "ca-canadabuys", name: "CanadaBuys Tender Opportunities", jurisdiction: "Canada", country: "CA", level: "international", url: "https://canadabuys.canada.ca/en/tender-opportunities", searchUrl: "https://canadabuys.canada.ca/en/tender-opportunities", domain: "canadabuys.canada.ca", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Canadian tender opportunities portal." },
  { id: "uk-contracts-finder", name: "UK Contracts Finder", jurisdiction: "United Kingdom", country: "GB", level: "international", url: "https://www.contractsfinder.service.gov.uk/", searchUrl: "https://www.contractsfinder.service.gov.uk/Search", domain: "contractsfinder.service.gov.uk", accessMode: "api", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "UK public contracts portal with documented API/OCDS access patterns." },
  { id: "worldbank-procurement", name: "World Bank Procurement Notices", jurisdiction: "World Bank", country: "INTL", level: "international", url: "https://projects.worldbank.org/en/projects-operations/procurement", searchUrl: "https://projects.worldbank.org/en/projects-operations/procurement", domain: "projects.worldbank.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "International procurement notices; not a US RFP source but useful for later global coverage." }
];

export const DIRECT_RFP_PORTALS: DirectRfpPortal[] = [
  ...CORE_DIRECT_RFP_PORTALS,
  ...ADDITIONAL_DIRECTORY_PORTALS,
  ...GENERATED_DIRECT_RFP_PORTALS,
];

export const OFFICIAL_DIRECT_RFP_DOMAINS = new Set(DIRECT_RFP_PORTALS.map((portal) => portal.domain));

export function directRfpPortalsForSearch(includeTier3 = false): DirectRfpPortal[] {
  return DIRECT_RFP_PORTALS.filter((portal) => portal.level !== "federal" && (includeTier3 || portal.tier !== 3));
}

export function directRfpPortalByDomain(hostname: string): DirectRfpPortal | undefined {
  const normalized = hostname.toLowerCase().replace(/^www\./, "");
  return DIRECT_RFP_PORTALS.find((portal) => normalized.includes(portal.domain.toLowerCase().replace(/^www\./, "")));
}


const OCCUMED_FIT_ORDER: Record<OccuMedPortalFit | "unclassified", number> = { verified_high: 0, likely: 1, broad: 2, insufficient_evidence: 3, unclassified: 4 };

export function directRfpPortalsForOccuMedSearch(options: { includeTier3?: boolean; minimumFit?: OccuMedPortalFit } = {}): DirectRfpPortal[] {
  const minimum = options.minimumFit ? OCCUMED_FIT_ORDER[options.minimumFit] : null;
  return directRfpPortalsForSearch(options.includeTier3 ?? true)
    .filter((portal) => minimum == null || OCCUMED_FIT_ORDER[portal.occumedFit ?? "unclassified"] <= minimum)
    .sort((a, b) => OCCUMED_FIT_ORDER[a.occumedFit ?? "unclassified"] - OCCUMED_FIT_ORDER[b.occumedFit ?? "unclassified"] || a.tier - b.tier || a.name.localeCompare(b.name));
}
