import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_042: DirectRfpPortal[] = [
  {
    id: "mo-modot-bid-opening",
    name: "Missouri DOT Bid Opening Information",
    jurisdiction: "Missouri Department of Transportation",
    state: "MO",
    country: "US",
    level: "state",
    url: "https://www.modot.org/bid-opening-info",
    searchUrl: "https://www.modot.org/bid-opening-info",
    domain: "www.modot.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Missouri Department of Transportation bid-opening and highway-construction letting source, including plans-room and bidding resources. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ne-ndot-highway-bridge-lettings",
    name: "Nebraska DOT Highway and Bridge Lettings",
    jurisdiction: "Nebraska Department of Transportation",
    state: "NE",
    country: "US",
    level: "state",
    url: "https://dot.nebraska.gov/business-center/hwy-bridge-lp/",
    searchUrl: "https://dot.nebraska.gov/business-center/hwy-bridge-lp/",
    domain: "dot.nebraska.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Nebraska Department of Transportation highway and bridge letting source with current and historical lettings, plans, proposals, addenda, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "or-odot-procurement",
    name: "Oregon DOT Procurement and Contracting",
    jurisdiction: "Oregon Department of Transportation",
    state: "OR",
    country: "US",
    level: "state",
    url: "https://www.oregon.gov/odot/Business/Procurement/Pages/index.aspx",
    searchUrl:
      "https://www.oregon.gov/odot/Business/Procurement/Pages/index.aspx",
    domain: "www.oregon.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Oregon Department of Transportation procurement source linking contracting opportunities, letting schedules, notices to contractors, bid results, eBIDS, and OregonBuys resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ri-ridot-bidding-opportunities",
    name: "Rhode Island DOT Bidding Opportunities",
    jurisdiction: "Rhode Island Department of Transportation",
    state: "RI",
    country: "US",
    level: "state",
    url: "https://www.dot.ri.gov/ridotbidding/",
    searchUrl: "https://www.dot.ri.gov/ridotbidding/",
    domain: "www.dot.ri.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Rhode Island Department of Transportation bidding-opportunities and bid-board entry point. Opportunities are publicly discoverable, while some bidder functions require authentication. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ut-udot-contracting",
    name: "Utah DOT Contracting",
    jurisdiction: "Utah Department of Transportation",
    state: "UT",
    country: "US",
    level: "state",
    url: "https://udot.utah.gov/connect/business/contracting/",
    searchUrl: "https://udot.utah.gov/connect/business/contracting/",
    domain: "udot.utah.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official Utah Department of Transportation contracting entry point for advertised projects, consultant services, construction contracting, and related bidder resources. Public entry point; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "vt-vtrans-bids-requests",
    name: "Vermont Agency of Transportation Bids and Requests",
    jurisdiction: "Vermont Agency of Transportation",
    state: "VT",
    country: "US",
    level: "state",
    url: "https://vtrans.vermont.gov/contract-admin/bids-requests",
    searchUrl: "https://vtrans.vermont.gov/contract-admin/bids-requests",
    domain: "vtrans.vermont.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Vermont Agency of Transportation Contract Administration source for construction bids, requests, advertisements, proposal documents, and bid results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "wi-wisdot-highway-bid-lettings",
    name: "Wisconsin DOT Highway Construction Bid Lettings",
    jurisdiction: "Wisconsin Department of Transportation",
    state: "WI",
    country: "US",
    level: "state",
    url: "https://wisconsindot.gov/Pages/doing-bus/contractors/hcci/bid-let.aspx",
    searchUrl:
      "https://wisconsindot.gov/Pages/doing-bus/contractors/hcci/bid-let.aspx",
    domain: "wisconsindot.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official Wisconsin Department of Transportation highway-construction bid-letting source for advertisements, proposals, plans, addenda, and letting results. Public browsing is available; no Occu-Med-specific solicitation is claimed.",
  }
];
