import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_001: DirectRfpPortal[] = [
  {
    id: "ak-anchorage",
    name: "Municipality of Anchorage Purchasing",
    jurisdiction: "Municipality of Anchorage",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    searchUrl: "https://www.muni.org/Departments/purchasing/Pages/default.aspx",
    domain: "muni.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official municipal purchasing page for Anchorage procurement resources and bid information.",
  },
  {
    id: "ct-uconn",
    name: "University of Connecticut Procurement Services",
    jurisdiction: "University of Connecticut",
    state: "CT",
    country: "US",
    level: "district",
    url: "https://procurement.uconn.edu/",
    searchUrl: "https://procurement.uconn.edu/",
    domain: "procurement.uconn.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UConn procurement services site.",
  },
  {
    id: "id-ada-county",
    name: "Ada County Procurement",
    jurisdiction: "Ada County",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://adacounty.id.gov/procurement/",
    searchUrl: "https://adacounty.id.gov/procurement/",
    domain: "adacounty.id.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ada County procurement page.",
  },
  {
    id: "mn-hennepin-county",
    name: "Hennepin County Supplier Portal",
    jurisdiction: "Hennepin County",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    searchUrl:
      "https://www.hennepin.us/business/work-with-henn-co/supplier-portal",
    domain: "hennepin.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Hennepin County supplier portal entry page.",
  },
  {
    id: "mo-st-louis",
    name: "City of St. Louis Supply Division",
    jurisdiction: "City of St. Louis",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://www.stlouis-mo.gov/government/departments/supply/",
    searchUrl: "https://www.stlouis-mo.gov/government/departments/supply/",
    domain: "stlouis-mo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official St. Louis supply division procurement page.",
  },
  {
    id: "ms-jackson",
    name: "City of Jackson Purchasing",
    jurisdiction: "City of Jackson",
    state: "MS",
    country: "US",
    level: "district",
    url: "https://www.jacksonms.gov/purchasing/",
    searchUrl: "https://www.jacksonms.gov/purchasing/",
    domain: "jacksonms.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jackson purchasing page.",
  },
  {
    id: "mt-billings",
    name: "City of Billings Purchasing",
    jurisdiction: "City of Billings",
    state: "MT",
    country: "US",
    level: "district",
    url: "https://www.billingsmt.gov/107/Purchasing",
    searchUrl: "https://www.billingsmt.gov/107/Purchasing",
    domain: "billingsmt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Billings purchasing page.",
  },
  {
    id: "nh-manchester",
    name: "City of Manchester Purchasing",
    jurisdiction: "City of Manchester",
    state: "NH",
    country: "US",
    level: "district",
    url: "https://www.manchesternh.gov/Departments/Purchasing",
    searchUrl: "https://www.manchesternh.gov/Departments/Purchasing",
    domain: "manchesternh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Manchester purchasing page.",
  },
  {
    id: "nm-albuquerque",
    name: "City of Albuquerque Purchasing",
    jurisdiction: "City of Albuquerque",
    state: "NM",
    country: "US",
    level: "district",
    url: "https://www.cabq.gov/dfa/purchasing",
    searchUrl: "https://www.cabq.gov/dfa/purchasing",
    domain: "cabq.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Albuquerque purchasing page.",
  },
  {
    id: "nv-las-vegas",
    name: "City of Las Vegas Purchasing and Contracts",
    jurisdiction: "City of Las Vegas",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    searchUrl:
      "https://www.lasvegasnevada.gov/Government/Departments/Finance/Purchasing-Contracts",
    domain: "lasvegasnevada.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Las Vegas purchasing and contracts page.",
  },
  {
    id: "oh-franklin-county",
    name: "Franklin County Purchasing",
    jurisdiction: "Franklin County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://purchasing.franklincountyohio.gov/",
    searchUrl: "https://purchasing.franklincountyohio.gov/",
    domain: "purchasing.franklincountyohio.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Franklin County purchasing site.",
  },
  {
    id: "pr-general-services-administration",
    name: "Puerto Rico General Services Administration",
    jurisdiction: "Puerto Rico",
    state: "PR",
    country: "US",
    level: "district",
    url: "https://asg.pr.gov/",
    searchUrl: "https://asg.pr.gov/",
    domain: "asg.pr.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Puerto Rico General Services Administration procurement entry point.",
  },
  {
    id: "ri-providence",
    name: "City of Providence Purchasing",
    jurisdiction: "City of Providence",
    state: "RI",
    country: "US",
    level: "district",
    url: "https://www.providenceri.gov/purchasing/",
    searchUrl: "https://www.providenceri.gov/purchasing/",
    domain: "providenceri.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Providence purchasing page.",
  },
  {
    id: "tx-houston",
    name: "City of Houston Strategic Procurement Division",
    jurisdiction: "City of Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.houstontx.gov/bizwithhou/",
    searchUrl: "https://www.houstontx.gov/bizwithhou/",
    domain: "houstontx.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Houston strategic procurement page.",
  },
];
