import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_047: DirectRfpPortal[] = [
  {
    id: "ny-bronx-county",
    name: "Bronx County City Record Procurement Notices",
    jurisdiction: "Bronx County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://a856-cityrecord.nyc.gov/",
    searchUrl: "https://a856-cityrecord.nyc.gov/",
    domain: "a856-cityrecord.nyc.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Bronx is served by New York City's centralized procurement system rather than a separate county portal. The official City Record Online source provides searchable citywide procurement notices. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-broome-county",
    name: "Broome County Open Solicitations",
    jurisdiction: "Broome County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://broomecountyny.gov/purchasing/open-solicitations",
    searchUrl: "https://broomecountyny.gov/purchasing/open-solicitations",
    domain: "broomecountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Broome County Purchasing listing for open solicitations and related documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-cattaraugus-county",
    name: "Cattaraugus County Bid Requests",
    jurisdiction: "Cattaraugus County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.cattco.gov/bid-request",
    searchUrl: "https://www.cattco.gov/bid-request",
    domain: "www.cattco.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Cattaraugus County listing for current requests for bids, proposals, and information. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-cayuga-county",
    name: "Cayuga County Bid Postings",
    jurisdiction: "Cayuga County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.cayugacounty.gov/Bids.aspx",
    searchUrl: "https://www.cayugacounty.gov/Bids.aspx",
    domain: "www.cayugacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Cayuga County bid-postings page for county solicitation opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-chemung-county",
    name: "Chemung County Bid Postings",
    jurisdiction: "Chemung County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.chemungcountyny.gov/Bids.aspx",
    searchUrl: "https://www.chemungcountyny.gov/Bids.aspx",
    domain: "www.chemungcountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Chemung County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-clinton-county",
    name: "Clinton County Purchasing Bids",
    jurisdiction: "Clinton County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.clintoncountyny.gov/purchasing/bids",
    searchUrl: "https://www.clintoncountyny.gov/purchasing/bids",
    domain: "www.clintoncountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Clinton County Purchasing source for county bids and associated documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-columbia-county",
    name: "Columbia County Bid Postings",
    jurisdiction: "Columbia County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.columbiacountyny.gov/Bids.aspx",
    searchUrl: "https://www.columbiacountyny.gov/Bids.aspx",
    domain: "www.columbiacountyny.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Columbia County bid-postings page. The endpoint uses browser-protection controls and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-cortland-county",
    name: "Cortland County Bid Postings",
    jurisdiction: "Cortland County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.cortlandcountyny.gov/Bids.aspx",
    searchUrl: "https://www.cortlandcountyny.gov/Bids.aspx",
    domain: "www.cortlandcountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Cortland County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-delaware-county",
    name: "Delaware County RFP Notices",
    jurisdiction: "Delaware County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.delcony.gov/blog/category/rfp/",
    searchUrl: "https://www.delcony.gov/blog/category/rfp/",
    domain: "www.delcony.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Delaware County RFP archive containing current and historical county solicitation notices. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-dutchess-county",
    name: "Dutchess County Bidding Opportunities",
    jurisdiction: "Dutchess County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.dutchessny.gov/Departments/Central-Services-Purchasing/Bidding-Opportunities-and-Vendor-Registration.htm",
    searchUrl:
      "https://www.dutchessny.gov/Departments/Central-Services-Purchasing/Bidding-Opportunities-and-Vendor-Registration.htm",
    domain: "www.dutchessny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Dutchess County Central Services page for bidding opportunities and vendor registration; opportunity documents are routed through the county's procurement services. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-franklin-county",
    name: "Franklin County Purchasing Bids",
    jurisdiction: "Franklin County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.franklincountyny.gov/business/purchasing_bids.php",
    searchUrl: "https://www.franklincountyny.gov/business/purchasing_bids.php",
    domain: "www.franklincountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Franklin County Purchasing page directing vendors to current county bid documents and purchasing contacts. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-fulton-county",
    name: "Fulton County Purchasing",
    jurisdiction: "Fulton County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.fultoncountyny.gov/purchasing",
    searchUrl: "https://www.fultoncountyny.gov/purchasing",
    domain: "www.fultoncountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Fulton County Purchasing page. The county states that current bid specifications are obtained from the Purchasing Office rather than posted as a consolidated online list. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-genesee-county",
    name: "Genesee County Current Bids and RFPs",
    jurisdiction: "Genesee County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.geneseeny.gov/Department-Content/Central-Services-and-Purchasing/Current-Bids-RFPs-Quotes-and-Addenda",
    searchUrl:
      "https://www.geneseeny.gov/Department-Content/Central-Services-and-Purchasing/Current-Bids-RFPs-Quotes-and-Addenda",
    domain: "www.geneseeny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Genesee County Central Services page for bids, RFPs, quotes, and addenda; the county routes active opportunities to its external bidding service. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-greene-county",
    name: "Greene County RFP and Bid Notices",
    jurisdiction: "Greene County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://greenecountyny.gov/category/rfp/",
    searchUrl: "https://greenecountyny.gov/category/rfp/",
    domain: "greenecountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Greene County public listing for RFPs, RFQs, bids, and related notices. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-herkimer-county",
    name: "Herkimer County Budget and Purchasing",
    jurisdiction: "Herkimer County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.herkimercountyny.gov/government/budget-and-purchasing/",
    searchUrl:
      "https://www.herkimercountyny.gov/government/budget-and-purchasing/",
    domain: "www.herkimercountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Herkimer County Budget and Purchasing page for procurement contacts, resources, and county opportunity access. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-jefferson-county",
    name: "Jefferson County Open Solicitations",
    jurisdiction: "Jefferson County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.jeffersoncountyny.gov/departments/Purchasing",
    searchUrl:
      "https://www.jeffersoncountyny.gov/departments/Purchasing/opensolicitationsandbidopportunities",
    domain: "www.jeffersoncountyny.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Jefferson County Purchasing listing for open solicitations and bid opportunities. The direct endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-kings-county",
    name: "Kings County PASSPort Public RFx",
    jurisdiction: "Kings County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://passport.cityofnewyork.us/page.aspx/en/rfp/request_browse_public",
    searchUrl:
      "https://passport.cityofnewyork.us/page.aspx/en/rfp/request_browse_public",
    domain: "passport.cityofnewyork.us",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Kings County, coterminous with Brooklyn, is served by New York City's centralized procurement system rather than a separate county portal. This official PASSPort page provides public citywide RFx browsing. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-lewis-county",
    name: "Lewis County Purchasing Opportunities",
    jurisdiction: "Lewis County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://lewiscountyny.gov/departments/purchasing/",
    searchUrl: "https://lewiscountyny.gov/departments/purchasing/",
    domain: "lewiscountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Lewis County Purchasing page listing current requests and supporting procurement documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-livingston-county",
    name: "Livingston County Bid Postings",
    jurisdiction: "Livingston County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.livingstoncountyny.gov/Bids.aspx",
    searchUrl: "https://www.livingstoncountyny.gov/Bids.aspx",
    domain: "www.livingstoncountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Livingston County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-madison-county",
    name: "Madison County Bid Postings",
    jurisdiction: "Madison County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.madisoncounty.ny.gov/Bids.aspx",
    searchUrl: "https://www.madisoncounty.ny.gov/Bids.aspx",
    domain: "www.madisoncounty.ny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Madison County bid-postings page for current county solicitations. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-montgomery-county",
    name: "Montgomery County Current Bids",
    jurisdiction: "Montgomery County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.montgomerycountyny.gov/web/sites/departments/purchasing/default.asp",
    searchUrl:
      "https://www.montgomerycountyny.gov/web/sites/departments/purchasing/list.asp?exp=0&type=35",
    domain: "www.montgomerycountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Montgomery County Purchasing listing for current bids, including a public empty-state when no opportunities are open. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-ontario-county",
    name: "Ontario County Bid Postings",
    jurisdiction: "Ontario County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.ontariocountyny.gov/Bids.aspx",
    searchUrl: "https://www.ontariocountyny.gov/Bids.aspx",
    domain: "www.ontariocountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Ontario County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-orange-county",
    name: "Orange County Bid Postings",
    jurisdiction: "Orange County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.orangecountygov.com/Bids.aspx",
    searchUrl: "https://www.orangecountygov.com/Bids.aspx",
    domain: "www.orangecountygov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Orange County bid-postings page for current county solicitations and awards. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-rensselaer-county",
    name: "Rensselaer County Bid Postings",
    jurisdiction: "Rensselaer County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.rensco.com/Bids.aspx",
    searchUrl: "https://www.rensco.com/Bids.aspx",
    domain: "www.rensco.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Rensselaer County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-st-lawrence-county",
    name: "St. Lawrence County Vendor Opportunities",
    jurisdiction: "St. Lawrence County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.stlawco.gov/Departments/Purchasing/VendorOpportunities",
    searchUrl:
      "https://www.stlawco.gov/Departments/Purchasing/VendorOpportunities",
    domain: "www.stlawco.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official St. Lawrence County Purchasing page listing current vendor opportunities and RFP documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-schuyler-county",
    name: "Schuyler County Bid Postings",
    jurisdiction: "Schuyler County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.schuylercountyny.gov/Bids.aspx",
    searchUrl: "https://www.schuylercountyny.gov/Bids.aspx",
    domain: "www.schuylercountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Schuyler County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-steuben-county",
    name: "Steuben County Bid Postings",
    jurisdiction: "Steuben County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.steubencountyny.gov/Bids.aspx",
    searchUrl: "https://www.steubencountyny.gov/Bids.aspx",
    domain: "www.steubencountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Steuben County bid-postings page for current county solicitations. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-sullivan-county",
    name: "Sullivan County Current Bids",
    jurisdiction: "Sullivan County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.sullivanny.gov/Departments/Purchasing/Bids",
    searchUrl: "https://www.sullivanny.gov/Departments/Purchasing/Bids",
    domain: "www.sullivanny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Sullivan County Purchasing listing for current bids and proposal documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-tompkins-county",
    name: "Tompkins County Purchasing Division",
    jurisdiction: "Tompkins County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.tompkinscountyny.gov/All-Departments/Finance-Department/Purchasing-Division",
    searchUrl:
      "https://www.tompkinscountyny.gov/All-Departments/Finance-Department/Purchasing-Division",
    domain: "www.tompkinscountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Tompkins County Purchasing Division page linking open solicitations and providing bid-and-tender search access through the county's procurement service. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-ulster-county",
    name: "Ulster County Current Bid Opportunities",
    jurisdiction: "Ulster County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.ulstercountyny.gov/Departments/General-Services",
    searchUrl:
      "https://www.ulstercountyny.gov/Departments/General-Services/Current-Bid-Opportunities",
    domain: "www.ulstercountyny.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Ulster County General Services listing for current bid opportunities. The direct endpoint blocks some automated requests and requires browser-compatible collection. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-warren-county",
    name: "Warren County Active Bids",
    jurisdiction: "Warren County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.warrencountyny.gov/purchasing/active",
    searchUrl: "https://www.warrencountyny.gov/purchasing/active",
    domain: "www.warrencountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Warren County Purchasing listing for active bids and county-hosted solicitation documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-washington-county",
    name: "Washington County Bid Postings",
    jurisdiction: "Washington County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.washingtoncountyny.gov/Bids.aspx",
    searchUrl: "https://www.washingtoncountyny.gov/Bids.aspx",
    domain: "www.washingtoncountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Washington County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-wayne-county",
    name: "Wayne County Solicitations",
    jurisdiction: "Wayne County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.waynecountyny.gov/922/Solicitations-After-192026",
    searchUrl: "https://www.waynecountyny.gov/922/Solicitations-After-192026",
    domain: "www.waynecountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Wayne County listing for solicitations issued after January 9, 2026, replacing the county's legacy purchasing listing. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-wyoming-county",
    name: "Wyoming County Bid Postings",
    jurisdiction: "Wyoming County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.wyomingcountyny.gov/Bids.aspx",
    searchUrl: "https://www.wyomingcountyny.gov/Bids.aspx",
    domain: "www.wyomingcountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Wyoming County bid-postings page for current county solicitations. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ny-yates-county",
    name: "Yates County Bid Postings",
    jurisdiction: "Yates County",
    state: "NY",
    country: "US",
    level: "district",
    url: "https://www.yatescountyny.gov/Bids.aspx",
    searchUrl: "https://www.yatescountyny.gov/Bids.aspx",
    domain: "www.yatescountyny.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Yates County bid-postings page for current county opportunities. No Occu-Med-specific solicitation is claimed.",
  }
];
