import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_043: DirectRfpPortal[] = [
  {
    id: "ca-alpine-county",
    name: "Alpine County Bid Postings",
    jurisdiction: "Alpine County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.alpinecountyca.gov/bids.aspx",
    searchUrl: "https://www.alpinecountyca.gov/bids.aspx",
    domain: "www.alpinecountyca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Alpine County bid-postings page for public solicitations and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-amador-county",
    name: "Amador County General Services Administration Open Bids",
    jurisdiction: "Amador County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.amadorcounty.gov/departments/general-services-admin",
    searchUrl:
      "https://www.amadorcounty.gov/departments/general-services-admin/goods-services/list-of-open-bids",
    domain: "www.amadorcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Amador County General Services Administration source for open goods, services, construction, and repair bids. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-butte-county",
    name: "Butte County Procurement",
    jurisdiction: "Butte County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.buttecounty.net/463/Procurement",
    searchUrl: "https://www.buttecounty.net/465/Competitive-Solicitations",
    domain: "www.buttecounty.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Butte County procurement and competitive-solicitation entry point. The county may route opportunity details through its buyer-specific Public Purchase system. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-calaveras-county",
    name: "County of Calaveras Public Purchase",
    jurisdiction: "Calaveras County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://administration.calaverasgov.us/RFP-RFQ-SOQ/Invitation-to-Bid",
    searchUrl:
      "https://www.publicpurchase.com/gems/calaverasco%2Cca/buyer/public/home",
    domain: "www.publicpurchase.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: true,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Calaveras County source directs vendors to this buyer-specific Public Purchase portal for RFP, RFQ, SOQ, bid, and contracting opportunities. Authentication may be required for complete documents or participation. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-colusa-county",
    name: "Colusa County Bid Postings",
    jurisdiction: "Colusa County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofcolusaca.gov/bids.aspx",
    searchUrl: "https://www.countyofcolusaca.gov/bids.aspx",
    domain: "www.countyofcolusaca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Colusa County bid-postings page for county solicitation and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-el-dorado-county",
    name: "El Dorado County Procurement and Contracts",
    jurisdiction: "El Dorado County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.eldoradocounty.ca.gov/County-Government/Procurement-and-Contracts",
    searchUrl:
      "https://www.eldoradocounty.ca.gov/County-Government/Procurement-and-Contracts/Open-Solicitations",
    domain: "www.eldoradocounty.ca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official El Dorado County Procurement and Contracts source with an open-solicitations destination. The listing may require browser-compatible dynamic access. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-glenn-county",
    name: "Glenn County Project and Service Bids",
    jurisdiction: "Glenn County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofglenn.net/government/bids",
    searchUrl: "https://www.countyofglenn.net/government/bids",
    domain: "www.countyofglenn.net",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Glenn County project and service bid listing. Some public-works documents may route to project-specific document services. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-humboldt-county",
    name: "Humboldt County Bid Opportunities",
    jurisdiction: "Humboldt County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://humboldtgov.org/bids.aspx",
    searchUrl: "https://humboldtgov.org/bids.aspx",
    domain: "humboldtgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Humboldt County bid-opportunities listing for consultants, contractors, service providers, vendors, and suppliers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-imperial-county",
    name: "Imperial County Purchasing",
    jurisdiction: "Imperial County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://purchasing.imperialcounty.org/",
    searchUrl: "https://purchasing.imperialcounty.org/",
    domain: "purchasing.imperialcounty.org",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Imperial County Purchasing source directs vendors to this buyer-specific PlanetBids portal for county bid and contracting opportunities. Registration may be required for document downloads or response submission. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-inyo-county",
    name: "Inyo County Bid Requests and RFPs",
    jurisdiction: "Inyo County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.inyocounty.us/services/county-administrators-office/bid-request-rfp",
    searchUrl:
      "https://www.inyocounty.us/services/county-administrators-office/bid-request-rfp",
    domain: "www.inyocounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Inyo County Administrator source for county bid requests, RFPs, RFQs, and related contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-kings-county",
    name: "Kings County Bids, Quotes, and Proposals",
    jurisdiction: "Kings County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofkingsca.gov/departments/administration/purchasing",
    searchUrl: "https://www.countyofkingsca.gov/i-want-to-/rfb",
    domain: "www.countyofkingsca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Kings County Purchasing and bid-listing source for requests for bids, quotes, proposals, and county contracting opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-lake-county",
    name: "Lake County Bid Postings",
    jurisdiction: "Lake County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lakecountyca.gov/bids.aspx",
    searchUrl: "https://www.lakecountyca.gov/bids.aspx",
    domain: "www.lakecountyca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Lake County bid-postings page for consultants, service providers, contractors, vendors, and suppliers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-lassen-county",
    name: "Lassen County Bids and RFPs",
    jurisdiction: "Lassen County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lassencounty.gov/bids.aspx",
    searchUrl: "https://www.lassencounty.gov/bids.aspx",
    domain: "www.lassencounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Lassen County bid and RFP listing for county contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-madera-county",
    name: "Madera County Bid Opportunities",
    jurisdiction: "Madera County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.maderacounty.com/government/public-works/divisions/engineering-services/bid-opportunities",
    searchUrl:
      "https://www.maderacounty.com/government/public-works/divisions/engineering-services/bid-opportunities",
    domain: "www.maderacounty.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Madera County bid-opportunities source covering county Public Works and related General Services solicitations. Some documents may use project-specific external hosting. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-marin-county",
    name: "Marin County Contracting Opportunities",
    jurisdiction: "Marin County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.marincounty.gov/contracting-opportunities",
    searchUrl: "https://www.marincounty.gov/contracting-opportunities",
    domain: "www.marincounty.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Marin County contracting-opportunities listing. Individual construction opportunities may use Bid Express for documents or submissions. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-mariposa-county",
    name: "Mariposa County Bid and Contract Opportunities",
    jurisdiction: "Mariposa County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.mariposacounty.gov/bids.aspx",
    searchUrl: "https://www.mariposacounty.gov/bids.aspx",
    domain: "www.mariposacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Mariposa County bid-postings page for consultants, service providers, contractors, vendors, and suppliers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-mendocino-county",
    name: "Mendocino County Open RFPs, Quotes, and Bids",
    jurisdiction: "Mendocino County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.mendocinocounty.gov/departments/general-services/central-services/open-rfp-quotes-bids",
    searchUrl:
      "https://www.mendocinocounty.gov/departments/general-services/central-services/open-rfp-quotes-bids",
    domain: "www.mendocinocounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Mendocino County General Services source for open RFPs, quotes, bids, and county contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-merced-county",
    name: "Merced County Bid Postings",
    jurisdiction: "Merced County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofmerced.com/bids.aspx",
    searchUrl: "https://www.countyofmerced.com/bids.aspx",
    domain: "www.countyofmerced.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Merced County bid-postings page for public county procurement and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-modoc-county",
    name: "Modoc County Bids and RFPs",
    jurisdiction: "Modoc County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofmodoc.gov/Bids.aspx",
    searchUrl: "https://www.countyofmodoc.gov/Bids.aspx",
    domain: "www.countyofmodoc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Modoc County bid-postings source for consultants, contractors, vendors, suppliers, and service providers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-mono-county",
    name: "Mono County Bids and RFPs",
    jurisdiction: "Mono County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.monocounty.ca.gov/rfps",
    searchUrl: "https://www.monocounty.ca.gov/rfps",
    domain: "www.monocounty.ca.gov",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Mono County Bids and RFPs destination. The county page redirects to its dedicated county bid site, so it is cataloged for browser-compatible access. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-monterey-county",
    name: "County of Monterey Solicitation Center",
    jurisdiction: "Monterey County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofmonterey.gov/government/departments-a-h/administrative-office/contracts-purchasing",
    searchUrl:
      "https://www.countyofmonterey.gov/government/departments-a-h/administrative-office/contracts-purchasing/solicitation-center",
    domain: "www.countyofmonterey.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official County of Monterey Contracts and Purchasing source with a solicitation center for active RFPs, RFQs, RFIs, bids, and related opportunities. The listing is dynamically rendered. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-napa-county",
    name: "Napa County Procurement",
    jurisdiction: "Napa County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.napacounty.gov/bids.aspx",
    searchUrl: "https://www.napacounty.gov/bids.aspx",
    domain: "www.napacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Napa County bid-postings source for county procurement and contract opportunities. The county may route newer electronic opportunities to a buyer-specific hosted platform. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-nevada-county",
    name: "Nevada County Bid Postings",
    jurisdiction: "Nevada County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.nevadacountyca.gov/bids.aspx",
    searchUrl: "https://www.nevadacountyca.gov/bids.aspx",
    domain: "www.nevadacountyca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Nevada County bid-postings entry point. The county may direct complete opportunity documents and participation to its buyer-specific Public Purchase source. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-placer-county",
    name: "Placer County Procurement Services",
    jurisdiction: "Placer County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.placer.ca.gov/1402/Procurement-Services",
    searchUrl: "https://www.placer.ca.gov/1406/Open-Bids-RFPs",
    domain: "www.placer.ca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Placer County Procurement Services and open-bids/RFP entry point. Complete electronic solicitation access may route to the county's hosted bidding system. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-plumas-county",
    name: "Plumas County Bids and RFPs",
    jurisdiction: "Plumas County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.plumascounty.us/bids.aspx",
    searchUrl: "https://www.plumascounty.us/bids.aspx",
    domain: "www.plumascounty.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Plumas County bid-postings source for bids, RFPs, consultants, contractors, vendors, and suppliers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-san-benito-county",
    name: "San Benito County Solicitation Center",
    jurisdiction: "San Benito County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sanbenitocountyca.gov/government/request-for-proposals-solicitation-center",
    searchUrl:
      "https://www.sanbenitocountyca.gov/government/request-for-proposals-solicitation-center",
    domain: "www.sanbenitocountyca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official San Benito County solicitation center for county RFPs, bids, RFQs, and related projects. Some electronic participation may use the county's buyer-specific hosted portal. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-san-joaquin-county",
    name: "San Joaquin County Open Bid Opportunities",
    jurisdiction: "San Joaquin County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sjgov.org/department/pss/bids",
    searchUrl: "https://www.sjgov.org/department/pss/bids",
    domain: "www.sjgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official San Joaquin County Purchasing and Support Services source for open bid opportunities. Full documents or participation may route to the county's buyer-specific Public Purchase system. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-san-luis-obispo-county",
    name: "San Luis Obispo County Bid and RFP Opportunities",
    jurisdiction: "San Luis Obispo County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.slocounty.ca.gov/departments/central-services",
    searchUrl:
      "https://www.slocounty.ca.gov/departments/central-services/purchasing-services/services/bid-rfp-opportunities",
    domain: "www.slocounty.ca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: true,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official San Luis Obispo County Central Services and Purchasing Services source for bid and RFP opportunities. Vendor registration with the county's hosted purchasing system may be required for documents or responses. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-santa-barbara-county",
    name: "Santa Barbara County Bid Opportunities",
    jurisdiction: "Santa Barbara County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.countyofsb.org/bid-opportunities-2",
    searchUrl: "https://www.countyofsb.org/bid-opportunities-2",
    domain: "www.countyofsb.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Santa Barbara County business source for bid and contract opportunities available to consultants, service providers, contractors, vendors, and suppliers. Individual departments may host detailed documents separately. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-santa-cruz-county",
    name: "Santa Cruz County Solicitations",
    jurisdiction: "Santa Cruz County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.santacruzcountyca.gov/Departments/GeneralServices/Purchasing/Solicitations.aspx",
    searchUrl:
      "https://www.santacruzcountyca.gov/Departments/GeneralServices/Purchasing/Solicitations.aspx",
    domain: "www.santacruzcountyca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Santa Cruz County General Services solicitation source. Current opportunities may route to the county's buyer-specific OpenGov portal, while historical listings remain available through the county page. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-shasta-county",
    name: "Shasta County Competitive Procurements",
    jurisdiction: "Shasta County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.shastacounty.gov/purchasing/page/competitive-procurements",
    searchUrl:
      "https://www.shastacounty.gov/purchasing/page/competitive-procurements",
    domain: "www.shastacounty.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Shasta County Purchasing source for competitive procurements. The county directs vendors to its buyer-specific OpenGov system as the centralized bid-opportunity location. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-sierra-county",
    name: "Sierra County Bids and RFPs",
    jurisdiction: "Sierra County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sierracounty.ca.gov/bids.aspx",
    searchUrl: "https://www.sierracounty.ca.gov/bids.aspx",
    domain: "www.sierracounty.ca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Sierra County bid-postings source for bids, RFPs, consultants, service providers, contractors, vendors, and suppliers. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-siskiyou-county",
    name: "Siskiyou County Bids and RFPs",
    jurisdiction: "Siskiyou County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.siskiyoucounty.gov/rfps",
    searchUrl: "https://www.siskiyoucounty.gov/rfps",
    domain: "www.siskiyoucounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Siskiyou County bids and RFPs source with opportunity status and attached solicitation documents. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-solano-county",
    name: "Solano County Bids and RFPs",
    jurisdiction: "Solano County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.solanocounty.gov/government/general-services/bidsrfps",
    searchUrl:
      "https://www.solanocounty.gov/government/general-services/bidsrfps",
    domain: "www.solanocounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Solano County General Services source for bids and RFPs. The page links the county's buyer-specific OpenGov source and separate Public Works opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-sonoma-county",
    name: "Sonoma County Purchasing",
    jurisdiction: "Sonoma County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://sonomacounty.gov/development-services/sonoma-public-infrastructure/divisions/purchasing-working-with-the-county",
    searchUrl: "https://esupplier.sonomacounty.ca.gov/",
    domain: "esupplier.sonomacounty.ca.gov",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: true,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Sonoma County Purchasing entry point and county supplier portal for county procurement and solicitation activity. Authentication may be required for complete opportunity details or participation. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-stanislaus-county",
    name: "Stanislaus County Active Bid Postings",
    jurisdiction: "Stanislaus County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.stancounty.com/purchasing/",
    searchUrl: "https://www.stancounty.com/purchasing/county-bids.shtm",
    domain: "www.stancounty.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Stanislaus County Purchasing division and active county bid listing. Public Works opportunities may additionally route to a county-specific hosted system. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-sutter-county",
    name: "Sutter County RFP and IFB Portal",
    jurisdiction: "Sutter County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.sutter.gov/business/doing-business-with-sutter-county",
    searchUrl: "https://sutter.bonfirehub.com/",
    domain: "sutter.bonfirehub.com",
    accessMode: "portal",
    requiresKey: false,
    requiresLogin: true,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Sutter County doing-business source links this buyer-specific Bonfire portal for RFP and IFB opportunities. Authentication may be required for complete documents or response submission. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-tehama-county",
    name: "Tehama County Bidding Opportunities",
    jurisdiction: "Tehama County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.tehama.gov/government/bidding-opportunities/",
    searchUrl: "https://www.tehama.gov/government/bidding-opportunities/",
    domain: "www.tehama.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Tehama County bidding-opportunities source for county bids, RFPs, contracts, and related solicitations. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-trinity-county",
    name: "Trinity County Bids and Proposals",
    jurisdiction: "Trinity County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.trinitycounty.org/Bids.aspx",
    searchUrl: "https://www.trinitycounty.org/Bids.aspx",
    domain: "www.trinitycounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "ready_to_parse",
    notes:
      "Official Trinity County bids-and-proposals listing for county procurement and contract opportunities. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-tulare-county",
    name: "Tulare County Current Bids and Proposals",
    jurisdiction: "Tulare County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://tularecounty.ca.gov/purchasing",
    searchUrl:
      "https://tularecounty.ca.gov/purchasing/current-bids-and-proposals",
    domain: "tularecounty.ca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Tulare County Purchasing and current-bids-and-proposals source. The county currently routes electronic solicitations through its buyer-specific BidNet Direct destination. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-tuolumne-county",
    name: "Tuolumne County Bid Postings",
    jurisdiction: "Tuolumne County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.tuolumnecounty.ca.gov/Bids.aspx",
    searchUrl: "https://www.tuolumnecounty.ca.gov/Bids.aspx",
    domain: "www.tuolumnecounty.ca.gov",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official Tuolumne County bid-postings source with public categories and individual opportunity listings. The county is transitioning newer solicitations to its buyer-specific OpenGov portal. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-yolo-county",
    name: "Yolo County Purchasing",
    jurisdiction: "Yolo County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.yolocounty.gov/government/general-government-departments/financial-services/procurement/current-advertised-bids",
    searchUrl:
      "https://www.yolocounty.gov/government/general-government-departments/financial-services/procurement/current-advertised-bids",
    domain: "www.yolocounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Yolo County Financial Services purchasing entry point for county bid, solicitation, vendor, and procurement information. No Occu-Med-specific solicitation is claimed.",
  },
  {
    id: "ca-yuba-county",
    name: "Yuba County Purchasing",
    jurisdiction: "Yuba County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.yuba.gov/departments/administrative_services/purchasing/",
    searchUrl:
      "https://www.yuba.gov/departments/administrative_services/purchasing/",
    domain: "www.yuba.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Yuba County Administrative Services purchasing entry point for county vendor, bid, and procurement opportunities. No Occu-Med-specific solicitation is claimed.",
  },
];
