import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_035: DirectRfpPortal[] = [
  {
    id: "fl-mco-procurement",
    name: "Greater Orlando Aviation Authority Procurement",
    jurisdiction: "Greater Orlando Aviation Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orlandoairports.net/getting-around-mco/business-opportunities/procurement-services/",
    searchUrl:
      "https://www.orlandoairports.net/getting-around-mco/business-opportunities/procurement-services/",
    domain: "www.orlandoairports.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Greater Orlando Aviation Authority procurement or business opportunities page.",
  },
  {
    id: "fl-broward-airport-purchasing",
    name: "Broward County Aviation Department Purchasing",
    jurisdiction: "Broward County Aviation Department",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.broward.org/Airport/Business/Pages/Purchasing.aspx",
    searchUrl: "https://www.broward.org/Airport/Business/Pages/Purchasing.aspx",
    domain: "www.broward.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Broward County Aviation Department procurement or business opportunities page.",
  },
  {
    id: "ga-atl-airport-procurement",
    name: "Hartsfield-Jackson Atlanta International Airport Procurement",
    jurisdiction: "Hartsfield-Jackson Atlanta International Airport",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.atl.com/business-information/procurement/",
    searchUrl: "https://www.atl.com/business-information/procurement/",
    domain: "www.atl.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Hartsfield-Jackson Atlanta International Airport procurement or business opportunities page.",
  },
  {
    id: "il-flychicago-contracts",
    name: "Chicago Department of Aviation Contracts",
    jurisdiction: "Chicago Department of Aviation",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.flychicago.com/business/CDA/Pages/ContractOpportunities.aspx",
    searchUrl:
      "https://www.flychicago.com/business/CDA/Pages/ContractOpportunities.aspx",
    domain: "www.flychicago.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Chicago Department of Aviation procurement or business opportunities page.",
  },
];
