import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_017: DirectRfpPortal[] = [
  {
    id: "ca-uc-berkeley",
    name: "UC Berkeley Supply Chain Management",
    jurisdiction: "UC Berkeley",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://supplychain.berkeley.edu/",
    searchUrl: "https://supplychain.berkeley.edu/",
    domain: "supplychain.berkeley.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Berkeley procurement or business opportunities page.",
  },
  {
    id: "ca-ucla-purchasing",
    name: "UCLA Purchasing",
    jurisdiction: "UCLA",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://purchasing.ucla.edu/",
    searchUrl: "https://purchasing.ucla.edu/",
    domain: "purchasing.ucla.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UCLA procurement or business opportunities page.",
  },
  {
    id: "ca-ucsd-procurement",
    name: "UC San Diego Procurement",
    jurisdiction: "UC San Diego",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://blink.ucsd.edu/buy-pay/",
    searchUrl: "https://blink.ucsd.edu/buy-pay/",
    domain: "blink.ucsd.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC San Diego procurement or business opportunities page.",
  },
  {
    id: "ca-ucsf-supply-chain",
    name: "UCSF Supply Chain Management",
    jurisdiction: "UCSF",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://supplychain.ucsf.edu/",
    searchUrl: "https://supplychain.ucsf.edu/",
    domain: "supplychain.ucsf.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UCSF procurement or business opportunities page.",
  },
  {
    id: "ca-uci-procurement",
    name: "UC Irvine Procurement Services",
    jurisdiction: "UC Irvine",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.uci.edu/",
    searchUrl: "https://procurement.uci.edu/",
    domain: "procurement.uci.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Irvine procurement or business opportunities page.",
  }
];
