import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_007: DirectRfpPortal[] = [
  {
    id: "fl-orange-county",
    name: "Orange County Procurement",
    jurisdiction: "Orange County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orangecountyfl.net/VendorServices.aspx",
    searchUrl: "https://www.orangecountyfl.net/VendorServices.aspx",
    domain: "orangecountyfl.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Orange County vendor services/procurement page.",
  },
  {
    id: "fl-jacksonville",
    name: "City of Jacksonville Procurement",
    jurisdiction: "City of Jacksonville",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.jacksonville.gov/departments/finance/procurement",
    searchUrl: "https://www.jacksonville.gov/departments/finance/procurement",
    domain: "jacksonville.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Jacksonville procurement page.",
  },
  {
    id: "fl-ucf",
    name: "University of Central Florida Procurement Services",
    jurisdiction: "University of Central Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.ucf.edu/",
    searchUrl: "https://procurement.ucf.edu/",
    domain: "procurement.ucf.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UCF procurement services page.",
  },
  {
    id: "fl-uf",
    name: "University of Florida Procurement Services",
    jurisdiction: "University of Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.ufl.edu/",
    searchUrl: "https://procurement.ufl.edu/",
    domain: "procurement.ufl.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UF procurement services page.",
  },
  {
    id: "fl-miami-airport",
    name: "Miami International Airport Business Opportunities",
    jurisdiction: "Miami International Airport",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.miami-airport.com/business_opportunities.asp",
    searchUrl: "https://www.miami-airport.com/business_opportunities.asp",
    domain: "miami-airport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official MIA business opportunities page.",
  },
  {
    id: "fl-greater-orlando-aviation",
    name: "Greater Orlando Aviation Authority Purchasing",
    jurisdiction: "Greater Orlando Aviation Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.orlandoairports.net/getting-around-mco/business-opportunities/purchasing/",
    searchUrl:
      "https://www.orlandoairports.net/getting-around-mco/business-opportunities/purchasing/",
    domain: "orlandoairports.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official GOAA purchasing page.",
  },
  {
    id: "fl-jacksonville-port",
    name: "Jacksonville Port Authority Procurement",
    jurisdiction: "Jacksonville Port Authority",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.jaxport.com/procurement/",
    searchUrl: "https://www.jaxport.com/procurement/",
    domain: "jaxport.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official JAXPORT procurement page.",
  },
  {
    id: "fl-tampa-bay-water",
    name: "Tampa Bay Water Procurement",
    jurisdiction: "Tampa Bay Water",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.tampabaywater.org/business/procurement",
    searchUrl: "https://www.tampabaywater.org/business/procurement",
    domain: "tampabaywater.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Tampa Bay Water procurement page.",
  },
  {
    id: "fl-broward-schools",
    name: "Broward County Public Schools Procurement",
    jurisdiction: "Broward County Public Schools",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.browardschools.com/procurement",
    searchUrl: "https://www.browardschools.com/procurement",
    domain: "browardschools.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official BCPS procurement page.",
  },
];
