import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_033: DirectRfpPortal[] = [
  {
    id: "ca-port-long-beach-contracts",
    name: "Port of Long Beach Contracting Opportunities",
    jurisdiction: "Port of Long Beach",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://polb.com/business/contracting-opportunities/",
    searchUrl: "https://polb.com/business/contracting-opportunities/",
    domain: "polb.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Port of Long Beach procurement or business opportunities page.",
  },
  {
    id: "wa-port-seattle-procurement",
    name: "Port of Seattle Procurement",
    jurisdiction: "Port of Seattle",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.portseattle.org/business/procurement",
    searchUrl: "https://www.portseattle.org/business/procurement",
    domain: "www.portseattle.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Port of Seattle procurement or business opportunities page.",
  },
  {
    id: "tx-port-houston-procurement",
    name: "Port Houston Procurement Services",
    jurisdiction: "Port Houston",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://porthouston.com/procurement-services/",
    searchUrl: "https://porthouston.com/procurement-services/",
    domain: "porthouston.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Port Houston procurement or business opportunities page.",
  },
  {
    id: "ga-port-authority-procurement",
    name: "Georgia Ports Authority Procurement",
    jurisdiction: "Georgia Ports Authority",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://gaports.com/procurement/",
    searchUrl: "https://gaports.com/procurement/",
    domain: "gaports.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Georgia Ports Authority procurement or business opportunities page.",
  },
  {
    id: "sc-ports-procurement",
    name: "South Carolina Ports Procurement",
    jurisdiction: "South Carolina Ports Authority",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://scspa.com/about/procurement/",
    searchUrl: "https://scspa.com/about/procurement/",
    domain: "scspa.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official South Carolina Ports Authority procurement or business opportunities page.",
  },
];
