import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_022: DirectRfpPortal[] = [
  {
    id: "tx-unt-procurement",
    name: "University of North Texas Procurement Services",
    jurisdiction: "University of North Texas",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://finance.untsystem.edu/procurement",
    searchUrl: "https://finance.untsystem.edu/procurement",
    domain: "finance.untsystem.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of North Texas procurement or business opportunities page.",
  },
  {
    id: "tx-rice-procurement",
    name: "Rice University Procurement",
    jurisdiction: "Rice University",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://procurement.rice.edu/",
    searchUrl: "https://procurement.rice.edu/",
    domain: "procurement.rice.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Rice University procurement or business opportunities page.",
  },
  {
    id: "fl-fsu-procurement",
    name: "Florida State University Procurement Services",
    jurisdiction: "Florida State University",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.fsu.edu/",
    searchUrl: "https://procurement.fsu.edu/",
    domain: "procurement.fsu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Florida State University procurement or business opportunities page.",
  },
  {
    id: "fl-usf-purchasing",
    name: "University of South Florida Purchasing Services",
    jurisdiction: "University of South Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://www.usf.edu/business-finance/purchasing/",
    searchUrl: "https://www.usf.edu/business-finance/purchasing/",
    domain: "www.usf.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of South Florida procurement or business opportunities page.",
  }
];
