import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_011: DirectRfpPortal[] = [
  {
    id: "md-anne-arundel-county",
    name: "Anne Arundel County Purchasing",
    jurisdiction: "Anne Arundel County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://www.aacounty.org/departments/central-services/purchasing/",
    searchUrl:
      "https://www.aacounty.org/departments/central-services/purchasing/",
    domain: "aacounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Anne Arundel County procurement page.",
  },
  {
    id: "md-rockville",
    name: "City of Rockville Procurement",
    jurisdiction: "City of Rockville",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://www.rockvillemd.gov/1112/Procurement",
    searchUrl: "https://www.rockvillemd.gov/1112/Procurement",
    domain: "rockvillemd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Rockville procurement page.",
  },
  {
    id: "ca-fresno-county",
    name: "Fresno County Purchasing",
    jurisdiction: "Fresno County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.fresnocountyca.gov/Departments/General-Services/Purchasing",
    searchUrl:
      "https://www.fresnocountyca.gov/Departments/General-Services/Purchasing",
    domain: "fresnocountyca.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fresno County procurement page.",
  },
  {
    id: "pa-montgomery-county",
    name: "Montgomery County Purchasing",
    jurisdiction: "Montgomery County",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.montgomerycountypa.gov/94/Purchasing",
    searchUrl: "https://www.montgomerycountypa.gov/94/Purchasing",
    domain: "montgomerycountypa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Montgomery County procurement page.",
  },
  {
    id: "va-loudoun-county",
    name: "Loudoun County Procurement",
    jurisdiction: "Loudoun County",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.loudoun.gov/1153/Procurement",
    searchUrl: "https://www.loudoun.gov/1153/Procurement",
    domain: "loudoun.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Loudoun County procurement page.",
  },
  {
    id: "wa-spokane-county",
    name: "Spokane County Purchasing",
    jurisdiction: "Spokane County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.spokanecounty.org/459/Purchasing",
    searchUrl: "https://www.spokanecounty.org/459/Purchasing",
    domain: "spokanecounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Spokane County procurement page.",
  },
];
