import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_016: DirectRfpPortal[] = [
  {
    id: "oh-hamilton-county",
    name: "Hamilton County Purchasing",
    jurisdiction: "Hamilton County",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.hamiltoncountyohio.gov/government/departments/purchasing",
    searchUrl:
      "https://www.hamiltoncountyohio.gov/government/departments/purchasing",
    domain: "hamiltoncountyohio.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Hamilton County procurement page.",
  },
  {
    id: "va-richmond",
    name: "City of Richmond Procurement Services",
    jurisdiction: "City of Richmond",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.rva.gov/procurement-services",
    searchUrl: "https://www.rva.gov/procurement-services",
    domain: "rva.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Richmond procurement page.",
  },
  {
    id: "oh-cincinnati",
    name: "City of Cincinnati Purchasing",
    jurisdiction: "City of Cincinnati",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.cincinnati-oh.gov/purchasing/",
    searchUrl: "https://www.cincinnati-oh.gov/purchasing/",
    domain: "cincinnati-oh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Cincinnati procurement page.",
  }
];
