import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_004: DirectRfpPortal[] = [
  {
    id: "az-mesa",
    name: "City of Mesa Purchasing",
    jurisdiction: "City of Mesa",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.mesaaz.gov/business/purchasing",
    searchUrl: "https://www.mesaaz.gov/business/purchasing",
    domain: "mesaaz.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official City of Mesa purchasing page for bids and vendor resources.",
  },
  {
    id: "az-pima-county",
    name: "Pima County Procurement",
    jurisdiction: "Pima County",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.pima.gov/697/Procurement",
    searchUrl: "https://www.pima.gov/697/Procurement",
    domain: "pima.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Pima County procurement page for solicitations and vendor information.",
  },
  {
    id: "co-jefferson-county",
    name: "Jefferson County Purchasing",
    jurisdiction: "Jefferson County",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.jeffco.us/2420/Purchasing",
    searchUrl: "https://www.jeffco.us/2420/Purchasing",
    domain: "jeffco.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jefferson County purchasing page.",
  },
  {
    id: "ga-cobb-county",
    name: "Cobb County Purchasing",
    jurisdiction: "Cobb County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.cobbcounty.org/purchasing",
    searchUrl: "https://www.cobbcounty.org/purchasing",
    domain: "cobbcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cobb County purchasing page.",
  },
  {
    id: "ga-savannah",
    name: "City of Savannah Purchasing",
    jurisdiction: "City of Savannah",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.savannahga.gov/437/Purchasing",
    searchUrl: "https://www.savannahga.gov/437/Purchasing",
    domain: "savannahga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Savannah purchasing page.",
  },
  {
    id: "il-dupage-county",
    name: "DuPage County Procurement Services",
    jurisdiction: "DuPage County",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.dupagecounty.gov/government/departments/procurement_services/",
    searchUrl:
      "https://www.dupagecounty.gov/government/departments/procurement_services/",
    domain: "dupagecounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official DuPage County procurement services page.",
  },
  {
    id: "il-lake-county",
    name: "Lake County Purchasing",
    jurisdiction: "Lake County",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.lakecountyil.gov/2178/Purchasing",
    searchUrl: "https://www.lakecountyil.gov/2178/Purchasing",
    domain: "lakecountyil.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Lake County purchasing page.",
  },
  {
    id: "in-hamilton-county",
    name: "Hamilton County Purchasing",
    jurisdiction: "Hamilton County",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.hamiltoncounty.in.gov/398/Purchasing",
    searchUrl: "https://www.hamiltoncounty.in.gov/398/Purchasing",
    domain: "hamiltoncounty.in.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Hamilton County purchasing page.",
  },
  {
    id: "in-south-bend",
    name: "City of South Bend Purchasing",
    jurisdiction: "City of South Bend",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://southbendin.gov/department/administration-finance/purchasing/",
    searchUrl:
      "https://southbendin.gov/department/administration-finance/purchasing/",
    domain: "southbendin.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of South Bend purchasing page.",
  },
  {
    id: "ma-worcester",
    name: "City of Worcester Purchasing",
    jurisdiction: "City of Worcester",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.worcesterma.gov/finance/purchasing-bids",
    searchUrl: "https://www.worcesterma.gov/finance/purchasing-bids",
    domain: "worcesterma.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Worcester purchasing and bids page.",
  },
  {
    id: "ma-cambridge",
    name: "City of Cambridge Purchasing",
    jurisdiction: "City of Cambridge",
    state: "MA",
    country: "US",
    level: "district",
    url: "https://www.cambridgema.gov/departments/purchasing",
    searchUrl: "https://www.cambridgema.gov/departments/purchasing",
    domain: "cambridgema.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cambridge purchasing department page.",
  },
  {
    id: "mi-ann-arbor",
    name: "City of Ann Arbor Purchasing",
    jurisdiction: "City of Ann Arbor",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.a2gov.org/departments/finance-admin-services/purchasing/",
    searchUrl:
      "https://www.a2gov.org/departments/finance-admin-services/purchasing/",
    domain: "a2gov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ann Arbor purchasing page.",
  },
  {
    id: "mn-minneapolis",
    name: "City of Minneapolis Procurement",
    jurisdiction: "City of Minneapolis",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.minneapolismn.gov/government/departments/finance/procurement/",
    searchUrl:
      "https://www.minneapolismn.gov/government/departments/finance/procurement/",
    domain: "minneapolismn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Minneapolis procurement page.",
  },
  {
    id: "mn-saint-paul",
    name: "City of Saint Paul Procurement",
    jurisdiction: "City of Saint Paul",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www.stpaul.gov/departments/financial-services/procurement",
    searchUrl:
      "https://www.stpaul.gov/departments/financial-services/procurement",
    domain: "stpaul.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Saint Paul procurement page.",
  },
  {
    id: "mo-springfield",
    name: "City of Springfield Purchasing",
    jurisdiction: "City of Springfield",
    state: "MO",
    country: "US",
    level: "district",
    url: "https://www.springfieldmo.gov/206/Purchasing",
    searchUrl: "https://www.springfieldmo.gov/206/Purchasing",
    domain: "springfieldmo.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Springfield purchasing page.",
  },
  {
    id: "nv-reno",
    name: "City of Reno Purchasing",
    jurisdiction: "City of Reno",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.reno.gov/government/departments/finance/purchasing",
    searchUrl: "https://www.reno.gov/government/departments/finance/purchasing",
    domain: "reno.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Reno purchasing page.",
  },
  {
    id: "nj-jersey-city",
    name: "Jersey City Purchasing",
    jurisdiction: "Jersey City",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://www.jerseycitynj.gov/cityhall/finance/purchasing",
    searchUrl: "https://www.jerseycitynj.gov/cityhall/finance/purchasing",
    domain: "jerseycitynj.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Jersey City purchasing page.",
  },
  {
    id: "nj-camden-county",
    name: "Camden County Purchasing",
    jurisdiction: "Camden County",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://www.camdencounty.com/service/purchasing/",
    searchUrl: "https://www.camdencounty.com/service/purchasing/",
    domain: "camdencounty.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Camden County purchasing page.",
  },
  {
    id: "nc-mecklenburg-county",
    name: "Mecklenburg County Procurement",
    jurisdiction: "Mecklenburg County",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://www.mecknc.gov/departments/procurement",
    searchUrl: "https://www.mecknc.gov/departments/procurement",
    domain: "mecknc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Mecklenburg County procurement page.",
  },
  {
    id: "oh-columbus",
    name: "City of Columbus Purchasing Office",
    jurisdiction: "City of Columbus",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.columbus.gov/finance/purchasing-office/",
    searchUrl: "https://www.columbus.gov/finance/purchasing-office/",
    domain: "columbus.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Columbus purchasing office page.",
  },
  {
    id: "oh-cincinnati",
    name: "City of Cincinnati Purchasing",
    jurisdiction: "City of Cincinnati",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.cincinnati-oh.gov/finance/purchasing/",
    searchUrl: "https://www.cincinnati-oh.gov/finance/purchasing/",
    domain: "cincinnati-oh.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cincinnati purchasing page.",
  },
  {
    id: "or-clackamas-county",
    name: "Clackamas County Procurement",
    jurisdiction: "Clackamas County",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://www.clackamas.us/procurement",
    searchUrl: "https://www.clackamas.us/procurement",
    domain: "clackamas.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Clackamas County procurement page.",
  },
  {
    id: "tn-shelby-county",
    name: "Shelby County Purchasing",
    jurisdiction: "Shelby County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.shelbycountytn.gov/577/Purchasing",
    searchUrl: "https://www.shelbycountytn.gov/577/Purchasing",
    domain: "shelbycountytn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Shelby County purchasing page.",
  },
  {
    id: "tn-knox-county",
    name: "Knox County Procurement",
    jurisdiction: "Knox County",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxcounty.org/procurement/",
    searchUrl: "https://www.knoxcounty.org/procurement/",
    domain: "knoxcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Knox County procurement page.",
  },
  {
    id: "tn-nashville-airport",
    name: "Nashville International Airport Business Opportunities",
    jurisdiction: "Metropolitan Nashville Airport Authority",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://flynashville.com/business-opportunities",
    searchUrl: "https://flynashville.com/business-opportunities",
    domain: "flynashville.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Nashville airport authority business opportunities page.",
  },
  {
    id: "ut-utah-county",
    name: "Utah County Purchasing",
    jurisdiction: "Utah County",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.utahcounty.gov/Dept/Purchasing/",
    searchUrl: "https://www.utahcounty.gov/Dept/Purchasing/",
    domain: "utahcounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Utah County purchasing page.",
  },
  {
    id: "ut-provo",
    name: "City of Provo Purchasing",
    jurisdiction: "City of Provo",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.provo.org/departments/finance/purchasing",
    searchUrl: "https://www.provo.org/departments/finance/purchasing",
    domain: "provo.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Provo purchasing page.",
  },
  {
    id: "ut-ogden",
    name: "Ogden City Purchasing",
    jurisdiction: "Ogden City",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.ogdencity.com/260/Purchasing",
    searchUrl: "https://www.ogdencity.com/260/Purchasing",
    domain: "ogdencity.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ogden City purchasing page.",
  },
  {
    id: "va-arlington-county",
    name: "Arlington County Purchasing",
    jurisdiction: "Arlington County",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.arlingtonva.us/Government/Programs/Business/Purchasing",
    searchUrl:
      "https://www.arlingtonva.us/Government/Programs/Business/Purchasing",
    domain: "arlingtonva.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Arlington County purchasing page.",
  },
  {
    id: "va-prince-william-county",
    name: "Prince William County Procurement Services",
    jurisdiction: "Prince William County",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.pwcva.gov/department/procurement-services",
    searchUrl: "https://www.pwcva.gov/department/procurement-services",
    domain: "pwcva.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Prince William County procurement services page.",
  },
  {
    id: "wa-seattle",
    name: "City of Seattle Purchasing and Contracting",
    jurisdiction: "City of Seattle",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.seattle.gov/purchasing-and-contracting",
    searchUrl: "https://www.seattle.gov/purchasing-and-contracting",
    domain: "seattle.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Seattle purchasing and contracting page.",
  },
  {
    id: "wa-snohomish-county",
    name: "Snohomish County Purchasing",
    jurisdiction: "Snohomish County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://snohomishcountywa.gov/1110/Purchasing",
    searchUrl: "https://snohomishcountywa.gov/1110/Purchasing",
    domain: "snohomishcountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Snohomish County purchasing page.",
  },
  {
    id: "wi-dane-county",
    name: "Dane County Purchasing",
    jurisdiction: "Dane County",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://admin.countyofdane.com/purchasing",
    searchUrl: "https://admin.countyofdane.com/purchasing",
    domain: "admin.countyofdane.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Dane County purchasing page.",
  },
  {
    id: "ak-juneau",
    name: "City and Borough of Juneau Purchasing",
    jurisdiction: "City and Borough of Juneau",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://juneau.org/finance/purchasing",
    searchUrl: "https://juneau.org/finance/purchasing",
    domain: "juneau.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Juneau purchasing page.",
  },
  {
    id: "al-huntsville",
    name: "City of Huntsville Procurement Services",
    jurisdiction: "City of Huntsville",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.huntsvilleal.gov/government/finance/procurement-services/",
    searchUrl:
      "https://www.huntsvilleal.gov/government/finance/procurement-services/",
    domain: "huntsvilleal.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Huntsville procurement services page.",
  },
  {
    id: "al-mobile",
    name: "City of Mobile Purchasing",
    jurisdiction: "City of Mobile",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.cityofmobile.org/government/departments/purchasing/",
    searchUrl:
      "https://www.cityofmobile.org/government/departments/purchasing/",
    domain: "cityofmobile.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Mobile purchasing department page.",
  },
  {
    id: "ar-pulaski-county",
    name: "Pulaski County Purchasing",
    jurisdiction: "Pulaski County",
    state: "AR",
    country: "US",
    level: "district",
    url: "https://www.pulaskicounty.net/purchasing/",
    searchUrl: "https://www.pulaskicounty.net/purchasing/",
    domain: "pulaskicounty.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Pulaski County purchasing page.",
  },
  {
    id: "hi-maui-county",
    name: "County of Maui Purchasing",
    jurisdiction: "County of Maui",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www.mauicounty.gov/123/Purchasing-Division",
    searchUrl: "https://www.mauicounty.gov/123/Purchasing-Division",
    domain: "mauicounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Maui County purchasing division page.",
  },
  {
    id: "ia-polk-county",
    name: "Polk County Purchasing",
    jurisdiction: "Polk County",
    state: "IA",
    country: "US",
    level: "district",
    url: "https://www.polkcountyiowa.gov/procurement/",
    searchUrl: "https://www.polkcountyiowa.gov/procurement/",
    domain: "polkcountyiowa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Polk County procurement page.",
  },
  {
    id: "ky-jefferson-county-public-schools",
    name: "Jefferson County Public Schools Purchasing",
    jurisdiction: "Jefferson County Public Schools",
    state: "KY",
    country: "US",
    level: "district",
    url: "https://www.jefferson.kyschools.us/page/purchasing",
    searchUrl: "https://www.jefferson.kyschools.us/page/purchasing",
    domain: "jefferson.kyschools.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official JCPS purchasing page.",
  },
  {
    id: "me-cumberland-county",
    name: "Cumberland County Purchasing",
    jurisdiction: "Cumberland County",
    state: "ME",
    country: "US",
    level: "district",
    url: "https://www.cumberlandcounty.org/363/Purchasing",
    searchUrl: "https://www.cumberlandcounty.org/363/Purchasing",
    domain: "cumberlandcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cumberland County purchasing page.",
  },
  {
    id: "nd-cass-county",
    name: "Cass County Finance Office",
    jurisdiction: "Cass County",
    state: "ND",
    country: "US",
    level: "district",
    url: "https://www.casscountynd.gov/our-county/finance-office",
    searchUrl: "https://www.casscountynd.gov/our-county/finance-office",
    domain: "casscountynd.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cass County finance office procurement resource page.",
  },
  {
    id: "ne-douglas-county",
    name: "Douglas County Purchasing",
    jurisdiction: "Douglas County",
    state: "NE",
    country: "US",
    level: "district",
    url: "https://www.douglascounty-ne.gov/purchasing",
    searchUrl: "https://www.douglascounty-ne.gov/purchasing",
    domain: "douglascounty-ne.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Douglas County purchasing page.",
  },
  {
    id: "sd-minnehaha-county",
    name: "Minnehaha County Auditor Purchasing",
    jurisdiction: "Minnehaha County",
    state: "SD",
    country: "US",
    level: "district",
    url: "https://www.minnehahacounty.gov/dept/au/auditor.php",
    searchUrl: "https://www.minnehahacounty.gov/dept/au/auditor.php",
    domain: "minnehahacounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Minnehaha County auditor purchasing resource page.",
  },
  {
    id: "vt-chittenden-county-regional-planning",
    name: "Chittenden County Regional Planning Commission RFPs",
    jurisdiction: "Chittenden County Regional Planning Commission",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.ccrpcvt.org/about-us/rfps/",
    searchUrl: "https://www.ccrpcvt.org/about-us/rfps/",
    domain: "ccrpcvt.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CCRPC RFP page.",
  },
  {
    id: "wv-kanawha-county-schools",
    name: "Kanawha County Schools Purchasing",
    jurisdiction: "Kanawha County Schools",
    state: "WV",
    country: "US",
    level: "district",
    url: "https://kcs.kana.k12.wv.us/departments/purchasing",
    searchUrl: "https://kcs.kana.k12.wv.us/departments/purchasing",
    domain: "kcs.kana.k12.wv.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Kanawha County Schools purchasing page.",
  },
  {
    id: "wy-laramie-county",
    name: "Laramie County Purchasing",
    jurisdiction: "Laramie County",
    state: "WY",
    country: "US",
    level: "district",
    url: "https://www.laramiecountywy.gov/_departments/finance/purchasing.aspx",
    searchUrl:
      "https://www.laramiecountywy.gov/_departments/finance/purchasing.aspx",
    domain: "laramiecountywy.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Laramie County purchasing page.",
  },
  {
    id: "edu-ucla-procurement",
    name: "UCLA Purchasing and Accounts Payable",
    jurisdiction: "University of California, Los Angeles",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://purchasing.ucla.edu/",
    searchUrl: "https://purchasing.ucla.edu/",
    domain: "purchasing.ucla.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UCLA purchasing page.",
  },
  {
    id: "edu-uc-berkeley-supply-chain",
    name: "UC Berkeley Supply Chain Management",
    jurisdiction: "University of California, Berkeley",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://supplychain.berkeley.edu/",
    searchUrl: "https://supplychain.berkeley.edu/",
    domain: "supplychain.berkeley.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Berkeley supply chain management page.",
  },
  {
    id: "edu-uc-davis-supply-chain",
    name: "UC Davis Supply Chain Management",
    jurisdiction: "University of California, Davis",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://supplychain.ucdavis.edu/",
    searchUrl: "https://supplychain.ucdavis.edu/",
    domain: "supplychain.ucdavis.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Davis supply chain management page.",
  },
  {
    id: "edu-uc-san-diego-procurement",
    name: "UC San Diego Procurement and Contracts",
    jurisdiction: "University of California, San Diego",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://blink.ucsd.edu/buy-pay/ways/procurement-contracts/",
    searchUrl: "https://blink.ucsd.edu/buy-pay/ways/procurement-contracts/",
    domain: "blink.ucsd.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC San Diego procurement and contracts page.",
  },
  {
    id: "edu-uw-procurement-services",
    name: "University of Washington Procurement Services",
    jurisdiction: "University of Washington",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://finance.uw.edu/ps/",
    searchUrl: "https://finance.uw.edu/ps/",
    domain: "finance.uw.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Washington procurement services page.",
  },
  {
    id: "edu-oregon-state-procurement",
    name: "Oregon State University Procurement",
    jurisdiction: "Oregon State University",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://fa.oregonstate.edu/pacs",
    searchUrl: "https://fa.oregonstate.edu/pacs",
    domain: "fa.oregonstate.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official Oregon State procurement, contracts, and materials management page.",
  },
  {
    id: "edu-university-of-oregon-purchasing",
    name: "University of Oregon Purchasing and Contracting Services",
    jurisdiction: "University of Oregon",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://pcs.uoregon.edu/",
    searchUrl: "https://pcs.uoregon.edu/",
    domain: "pcs.uoregon.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of Oregon purchasing and contracting services page.",
  },
  {
    id: "edu-university-of-arizona-procurement",
    name: "University of Arizona Procurement and Contracting Services",
    jurisdiction: "University of Arizona",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://pacs.arizona.edu/",
    searchUrl: "https://pacs.arizona.edu/",
    domain: "pacs.arizona.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of Arizona procurement and contracting services page.",
  },
  {
    id: "edu-arizona-state-procurement",
    name: "Arizona State University Supply Chain Management",
    jurisdiction: "Arizona State University",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://cfo.asu.edu/supply-chain",
    searchUrl: "https://cfo.asu.edu/supply-chain",
    domain: "cfo.asu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Arizona State University supply chain management page.",
  },
  {
    id: "edu-unlv-purchasing",
    name: "UNLV Purchasing and Contracts",
    jurisdiction: "University of Nevada, Las Vegas",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.unlv.edu/purchasing",
    searchUrl: "https://www.unlv.edu/purchasing",
    domain: "unlv.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UNLV purchasing and contracts page.",
  },
  {
    id: "edu-unr-purchasing",
    name: "University of Nevada, Reno Purchasing",
    jurisdiction: "University of Nevada, Reno",
    state: "NV",
    country: "US",
    level: "district",
    url: "https://www.unr.edu/bcn-nshe/departments/purchasing",
    searchUrl: "https://www.unr.edu/bcn-nshe/departments/purchasing",
    domain: "unr.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Nevada, Reno purchasing page.",
  },
  {
    id: "edu-university-of-utah-purchasing",
    name: "University of Utah Purchasing",
    jurisdiction: "University of Utah",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://purchasing.utah.edu/",
    searchUrl: "https://purchasing.utah.edu/",
    domain: "purchasing.utah.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Utah purchasing page.",
  },
  {
    id: "edu-byu-purchasing",
    name: "BYU Purchasing and Travel",
    jurisdiction: "Brigham Young University",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://purchasing.byu.edu/",
    searchUrl: "https://purchasing.byu.edu/",
    domain: "purchasing.byu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official BYU purchasing page.",
  },
  {
    id: "edu-colorado-boulder-procurement",
    name: "CU Boulder Procurement Service Center",
    jurisdiction: "University of Colorado Boulder",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.colorado.edu/psc/",
    searchUrl: "https://www.colorado.edu/psc/",
    domain: "colorado.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official CU Boulder procurement service center page.",
  },
  {
    id: "edu-colorado-state-procurement",
    name: "Colorado State University Procurement Services",
    jurisdiction: "Colorado State University",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://procurement.colostate.edu/",
    searchUrl: "https://procurement.colostate.edu/",
    domain: "procurement.colostate.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Colorado State University procurement services page.",
  },
  {
    id: "edu-university-of-minnesota-purchasing",
    name: "University of Minnesota Purchasing Services",
    jurisdiction: "University of Minnesota",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://purchasing.umn.edu/",
    searchUrl: "https://purchasing.umn.edu/",
    domain: "purchasing.umn.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Minnesota purchasing services page.",
  },
  {
    id: "edu-university-of-wisconsin-purchasing",
    name: "University of Wisconsin-Madison Purchasing Services",
    jurisdiction: "University of Wisconsin-Madison",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://purchasing.wisc.edu/",
    searchUrl: "https://purchasing.wisc.edu/",
    domain: "purchasing.wisc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UW-Madison purchasing services page.",
  },
  {
    id: "edu-university-of-michigan-procurement",
    name: "University of Michigan Procurement Services",
    jurisdiction: "University of Michigan",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://procurement.umich.edu/",
    searchUrl: "https://procurement.umich.edu/",
    domain: "procurement.umich.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Michigan procurement services page.",
  },
  {
    id: "edu-michigan-state-purchasing",
    name: "Michigan State University Purchasing",
    jurisdiction: "Michigan State University",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://upl.msu.edu/",
    searchUrl: "https://upl.msu.edu/",
    domain: "upl.msu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Michigan State University purchasing page.",
  },
  {
    id: "edu-ohio-state-purchasing",
    name: "Ohio State University Purchasing",
    jurisdiction: "Ohio State University",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://busfin.osu.edu/buy-schedule-travel/purchasing",
    searchUrl: "https://busfin.osu.edu/buy-schedule-travel/purchasing",
    domain: "busfin.osu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Ohio State University purchasing page.",
  },
  {
    id: "edu-university-of-cincinnati-purchasing",
    name: "University of Cincinnati Purchasing",
    jurisdiction: "University of Cincinnati",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.uc.edu/about/admin-finance/purchasing.html",
    searchUrl: "https://www.uc.edu/about/admin-finance/purchasing.html",
    domain: "uc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Cincinnati purchasing page.",
  },
  {
    id: "edu-purdue-procurement",
    name: "Purdue University Procurement Services",
    jurisdiction: "Purdue University",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.purdue.edu/procurement/",
    searchUrl: "https://www.purdue.edu/procurement/",
    domain: "purdue.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Purdue procurement services page.",
  },
  {
    id: "edu-indiana-university-purchasing",
    name: "Indiana University Purchasing",
    jurisdiction: "Indiana University",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://purchasing.iu.edu/",
    searchUrl: "https://purchasing.iu.edu/",
    domain: "purchasing.iu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Indiana University purchasing page.",
  },
  {
    id: "edu-uiuc-purchasing",
    name: "University of Illinois Purchasing and Contract Management",
    jurisdiction: "University of Illinois Urbana-Champaign",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.obfs.uillinois.edu/purchases/",
    searchUrl: "https://www.obfs.uillinois.edu/purchases/",
    domain: "obfs.uillinois.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official University of Illinois purchasing and contracting resource page.",
  },
  {
    id: "edu-northwestern-procurement",
    name: "Northwestern University Procurement and Payment Services",
    jurisdiction: "Northwestern University",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.northwestern.edu/procurement/",
    searchUrl: "https://www.northwestern.edu/procurement/",
    domain: "northwestern.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Northwestern procurement and payment services page.",
  },
  {
    id: "edu-georgia-tech-procurement",
    name: "Georgia Tech Procurement and Business Services",
    jurisdiction: "Georgia Institute of Technology",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://procurement.gatech.edu/",
    searchUrl: "https://procurement.gatech.edu/",
    domain: "procurement.gatech.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Georgia Tech procurement and business services page.",
  },
  {
    id: "edu-university-of-georgia-procurement",
    name: "University of Georgia Procurement",
    jurisdiction: "University of Georgia",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://busfin.uga.edu/procurement/",
    searchUrl: "https://busfin.uga.edu/procurement/",
    domain: "busfin.uga.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Georgia procurement page.",
  },
  {
    id: "edu-unc-purchasing",
    name: "UNC-Chapel Hill Purchasing Services",
    jurisdiction: "University of North Carolina at Chapel Hill",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://finance.unc.edu/services/purchasing/",
    searchUrl: "https://finance.unc.edu/services/purchasing/",
    domain: "finance.unc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UNC purchasing services page.",
  },
  {
    id: "edu-nc-state-procurement",
    name: "NC State Procurement and Business Services",
    jurisdiction: "North Carolina State University",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://procurement.ofa.ncsu.edu/",
    searchUrl: "https://procurement.ofa.ncsu.edu/",
    domain: "procurement.ofa.ncsu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official NC State procurement and business services page.",
  },
  {
    id: "edu-university-of-florida-procurement",
    name: "University of Florida Procurement Services",
    jurisdiction: "University of Florida",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.ufl.edu/",
    searchUrl: "https://procurement.ufl.edu/",
    domain: "procurement.ufl.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Florida procurement services page.",
  },
  {
    id: "edu-florida-state-procurement",
    name: "Florida State University Procurement Services",
    jurisdiction: "Florida State University",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.fsu.edu/",
    searchUrl: "https://procurement.fsu.edu/",
    domain: "procurement.fsu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Florida State University procurement services page.",
  },
  {
    id: "edu-utexas-purchasing",
    name: "University of Texas at Austin Purchasing Office",
    jurisdiction: "University of Texas at Austin",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://purchasing.utexas.edu/",
    searchUrl: "https://purchasing.utexas.edu/",
    domain: "purchasing.utexas.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UT Austin purchasing office page.",
  },
  {
    id: "edu-texas-am-procurement",
    name: "Texas A&M Procurement Services",
    jurisdiction: "Texas A&M University",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://procurement.tamu.edu/",
    searchUrl: "https://procurement.tamu.edu/",
    domain: "procurement.tamu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Texas A&M procurement services page.",
  },
  {
    id: "edu-virginia-procurement",
    name: "University of Virginia Procurement and Supplier Diversity Services",
    jurisdiction: "University of Virginia",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://uvafinance.virginia.edu/procurement",
    searchUrl: "https://uvafinance.virginia.edu/procurement",
    domain: "uvafinance.virginia.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Virginia procurement page.",
  },
  {
    id: "edu-virginia-tech-procurement",
    name: "Virginia Tech Procurement",
    jurisdiction: "Virginia Tech",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.procurement.vt.edu/",
    searchUrl: "https://www.procurement.vt.edu/",
    domain: "procurement.vt.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Virginia Tech procurement page.",
  },
  {
    id: "edu-rutgers-procurement",
    name: "Rutgers University Procurement Services",
    jurisdiction: "Rutgers University",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://procurementservices.rutgers.edu/",
    searchUrl: "https://procurementservices.rutgers.edu/",
    domain: "procurementservices.rutgers.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Rutgers procurement services page.",
  },
  {
    id: "edu-penn-state-procurement",
    name: "Penn State Procurement Services",
    jurisdiction: "Pennsylvania State University",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.procurement.psu.edu/",
    searchUrl: "https://www.procurement.psu.edu/",
    domain: "procurement.psu.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Penn State procurement services page.",
  },
  {
    id: "edu-university-of-pittsburgh-purchasing",
    name: "University of Pittsburgh Purchasing Services",
    jurisdiction: "University of Pittsburgh",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://www.ppt.pitt.edu/",
    searchUrl: "https://www.ppt.pitt.edu/",
    domain: "ppt.pitt.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Pittsburgh purchase, pay, and travel page.",
  },
  {
    id: "edu-university-of-tennessee-procurement",
    name: "University of Tennessee Procurement Services",
    jurisdiction: "University of Tennessee",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://procurement.tennessee.edu/",
    searchUrl: "https://procurement.tennessee.edu/",
    domain: "procurement.tennessee.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Tennessee procurement services page.",
  },
];
