import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_010: DirectRfpPortal[] = [
  {
    id: "ga-cobb-county",
    name: "Cobb County Purchasing",
    jurisdiction: "Cobb County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.cobbcounty.org/purchasing",
    searchUrl: "https://www.cobbcounty.org/purchasing",
    domain: "cobbcounty.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cobb County procurement page.",
  },
  {
    id: "va-chesapeake",
    name: "City of Chesapeake Purchasing",
    jurisdiction: "City of Chesapeake",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.cityofchesapeake.net/1062/Purchasing",
    searchUrl: "https://www.cityofchesapeake.net/1062/Purchasing",
    domain: "cityofchesapeake.net",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Chesapeake procurement page.",
  },
  {
    id: "oh-cleveland",
    name: "City of Cleveland Procurement",
    jurisdiction: "City of Cleveland",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://www.clevelandohio.gov/city-hall/departments/finance/divisions/procurement",
    searchUrl:
      "https://www.clevelandohio.gov/city-hall/departments/finance/divisions/procurement",
    domain: "clevelandohio.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Cleveland procurement page.",
  },
  {
    id: "tx-el-paso-county",
    name: "El Paso County Purchasing",
    jurisdiction: "El Paso County",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://www.epcounty.com/purchasing/",
    searchUrl: "https://www.epcounty.com/purchasing/",
    domain: "epcounty.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official El Paso County procurement page.",
  },
  {
    id: "ga-gwinnett-county",
    name: "Gwinnett County Purchasing",
    jurisdiction: "Gwinnett County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.gwinnettcounty.com/departments/financialservices/purchasing",
    searchUrl:
      "https://www.gwinnettcounty.com/departments/financialservices/purchasing",
    domain: "gwinnettcounty.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Gwinnett County procurement page.",
  },
  {
    id: "wa-snohomish-county",
    name: "Snohomish County Purchasing",
    jurisdiction: "Snohomish County",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://snohomishcountywa.gov/300/Purchasing",
    searchUrl: "https://snohomishcountywa.gov/300/Purchasing",
    domain: "snohomishcountywa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Snohomish County procurement page.",
  },
];
