import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_018: DirectRfpPortal[] = [
  {
    id: "ca-ucd-supply-chain",
    name: "UC Davis Supply Chain Management",
    jurisdiction: "UC Davis",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://supplychain.ucdavis.edu/",
    searchUrl: "https://supplychain.ucdavis.edu/",
    domain: "supplychain.ucdavis.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Davis procurement or business opportunities page.",
  },
  {
    id: "ca-ucsb-purchasing",
    name: "UC Santa Barbara Procurement Services",
    jurisdiction: "UC Santa Barbara",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.bfs.ucsb.edu/procurement",
    searchUrl: "https://www.bfs.ucsb.edu/procurement",
    domain: "www.bfs.ucsb.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official UC Santa Barbara procurement or business opportunities page.",
  },
  {
    id: "ca-ucr-procurement",
    name: "UC Riverside Procurement Services",
    jurisdiction: "UC Riverside",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.ucr.edu/",
    searchUrl: "https://procurement.ucr.edu/",
    domain: "procurement.ucr.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Riverside procurement or business opportunities page.",
  },
  {
    id: "ca-ucmerced-procurement",
    name: "UC Merced Procurement",
    jurisdiction: "UC Merced",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.ucmerced.edu/",
    searchUrl: "https://procurement.ucmerced.edu/",
    domain: "procurement.ucmerced.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Merced procurement or business opportunities page.",
  },
  {
    id: "ca-ucsc-procurement",
    name: "UC Santa Cruz Procurement Services",
    jurisdiction: "UC Santa Cruz",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://financial.ucsc.edu/Pages/Procurement_Services.aspx",
    searchUrl: "https://financial.ucsc.edu/Pages/Procurement_Services.aspx",
    domain: "financial.ucsc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UC Santa Cruz procurement or business opportunities page.",
  },
];
