export type DirectRfpPortalLevel = "federal" | "state" | "district" | "international";
export type DirectRfpPortalAccessMode = "api" | "csv" | "public_html" | "dynamic_html" | "portal";
export type DirectRfpPortalParserStatus = "ready_to_parse" | "needs_parser" | "catalog_only";

export interface DirectRfpPortal {
  id: string;
  name: string;
  jurisdiction: string;
  state?: string;
  country: string;
  level: DirectRfpPortalLevel;
  url: string;
  searchUrl?: string;
  domain: string;
  accessMode: DirectRfpPortalAccessMode;
  requiresKey: boolean;
  requiresLogin: boolean;
  tier: 1 | 2 | 3;
  parserStatus: DirectRfpPortalParserStatus;
  notes: string;
}

/**
 * Direct official RFP/opportunity portals.
 *
 * This catalog intentionally excludes paid/public aggregators such as BidNet,
 * DemandStar, GovWin, PlanetBids, OpenGov network pages, Periscope/S2G, and
 * generic search engines. Those may be useful for discovery, but they are not
 * the direct buyer/source-of-truth layer we want to build on.
 */
export const DIRECT_RFP_PORTALS: DirectRfpPortal[] = [
  {
    id: "us-sam-gov",
    name: "SAM.gov Contract Opportunities",
    jurisdiction: "United States Federal Government",
    country: "US",
    level: "federal",
    url: "https://sam.gov/content/opportunities",
    searchUrl: "https://sam.gov/content/opportunities",
    domain: "sam.gov",
    accessMode: "api",
    requiresKey: true,
    requiresLogin: false,
    tier: 1,
    parserStatus: "ready_to_parse",
    notes: "Primary official federal contract opportunity API/source.",
  },

  // Wave 1: high-value official state portals to implement first.
  { id: "tx-esbd", name: "Texas ESBD / Texas SmartBuy", jurisdiction: "Texas", state: "TX", country: "US", level: "state", url: "https://www.txsmartbuy.gov/esbd", searchUrl: "https://www.txsmartbuy.gov/esbd", domain: "txsmartbuy.gov", accessMode: "csv", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Public official Texas bid portal; high priority because listings are structured and export-friendly." },
  { id: "ny-contract-reporter", name: "New York State Contract Reporter", jurisdiction: "New York", state: "NY", country: "US", level: "state", url: "https://www.nyscr.ny.gov/", searchUrl: "https://www.nyscr.ny.gov/contracts.cfm", domain: "nyscr.ny.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official New York contracting opportunity portal." },
  { id: "va-eva", name: "Virginia eVA / Business Opportunities", jurisdiction: "Virginia", state: "VA", country: "US", level: "state", url: "https://eva.virginia.gov/", searchUrl: "https://eva.virginia.gov/business-opportunities.html", domain: "eva.virginia.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Virginia procurement marketplace and business opportunities portal." },
  { id: "pa-emarketplace", name: "Pennsylvania eMarketplace", jurisdiction: "Pennsylvania", state: "PA", country: "US", level: "state", url: "https://www.emarketplace.state.pa.us/", searchUrl: "https://www.emarketplace.state.pa.us/Solicitations.aspx", domain: "emarketplace.state.pa.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Pennsylvania bid, award, and contract portal." },
  { id: "ca-caleprocure", name: "California Cal eProcure", jurisdiction: "California", state: "CA", country: "US", level: "state", url: "https://caleprocure.ca.gov/", searchUrl: "https://caleprocure.ca.gov/pages/Events-BS3/event-search.aspx", domain: "caleprocure.ca.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official California event search. Dynamic page; likely needs a dedicated parser/browser-safe fetch strategy." },
  { id: "fl-vbs", name: "Florida Vendor Bid System", jurisdiction: "Florida", state: "FL", country: "US", level: "state", url: "https://vendor.myfloridamarketplace.com/", searchUrl: "https://vendor.myfloridamarketplace.com/search/bids", domain: "vendor.myfloridamarketplace.com", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Florida public bid search." },
  { id: "oh-ohiobuys", name: "OhioBuys / Ohio Procurement", jurisdiction: "Ohio", state: "OH", country: "US", level: "state", url: "https://procure.ohio.gov/", searchUrl: "https://procure.ohio.gov/proc/view-procurement-opportunities", domain: "procure.ohio.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Ohio procurement opportunities portal." },
  { id: "wa-webs", name: "Washington WEBS", jurisdiction: "Washington", state: "WA", country: "US", level: "state", url: "https://pr-webs-customer.des.wa.gov/", searchUrl: "https://pr-webs-customer.des.wa.gov/", domain: "pr-webs-customer.des.wa.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Washington Enterprise Bid System." },
  { id: "md-emma", name: "eMaryland Marketplace Advantage", jurisdiction: "Maryland", state: "MD", country: "US", level: "state", url: "https://emma.maryland.gov/", searchUrl: "https://emma.maryland.gov/page.aspx/en/rfp/request_browse_public", domain: "emma.maryland.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Maryland public solicitations portal." },

  // Remaining US state and district official portals.
  { id: "al-staars", name: "Alabama STAARS Vendor Self Service", jurisdiction: "Alabama", state: "AL", country: "US", level: "state", url: "https://procurement.staars.alabama.gov/", searchUrl: "https://procurement.staars.alabama.gov/", domain: "procurement.staars.alabama.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Alabama procurement portal." },
  { id: "ak-vss", name: "Alaska Vendor Self Service", jurisdiction: "Alaska", state: "AK", country: "US", level: "state", url: "https://vss.alaska.gov/", searchUrl: "https://vss.alaska.gov/", domain: "vss.alaska.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Alaska vendor self service portal; parser details need confirmation." },
  { id: "az-app", name: "Arizona Procurement Portal", jurisdiction: "Arizona", state: "AZ", country: "US", level: "state", url: "https://appstate.az.gov/", searchUrl: "https://appstate.az.gov/", domain: "appstate.az.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Arizona procurement portal." },
  { id: "ar-arbuy", name: "Arkansas ARBuy", jurisdiction: "Arkansas", state: "AR", country: "US", level: "state", url: "https://arbuy.arkansas.gov/", searchUrl: "https://arbuy.arkansas.gov/", domain: "arbuy.arkansas.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Arkansas procurement portal." },
  { id: "co-vss", name: "Colorado Vendor Self Service", jurisdiction: "Colorado", state: "CO", country: "US", level: "state", url: "https://codpa-vss.cloud.cgifederal.com/webapp/PRDVSS2X1/AltSelfService", searchUrl: "https://codpa-vss.cloud.cgifederal.com/webapp/PRDVSS2X1/AltSelfService", domain: "codpa-vss.cloud.cgifederal.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Colorado VSS public solicitation portal." },
  { id: "ct-ctsource", name: "Connecticut CTsource Bid Board", jurisdiction: "Connecticut", state: "CT", country: "US", level: "state", url: "https://portal.ct.gov/DAS/CTSource/BidBoard", searchUrl: "https://portal.ct.gov/DAS/CTSource/BidBoard", domain: "portal.ct.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Connecticut DAS/CTsource bid board." },
  { id: "de-mymarketplace", name: "Delaware MyMarketplace", jurisdiction: "Delaware", state: "DE", country: "US", level: "state", url: "https://mymarketplace.delaware.gov/", searchUrl: "https://mymarketplace.delaware.gov/", domain: "mymarketplace.delaware.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Delaware bid solicitation marketplace." },
  { id: "dc-ocp", name: "District of Columbia OCP Solicitations", jurisdiction: "District of Columbia", state: "DC", country: "US", level: "district", url: "https://ocp.dc.gov/", searchUrl: "https://ocp.dc.gov/page/ocp-solicitations", domain: "ocp.dc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official District of Columbia procurement solicitations page." },
  { id: "ga-gpr", name: "Georgia Procurement Registry", jurisdiction: "Georgia", state: "GA", country: "US", level: "state", url: "https://ssl.doas.state.ga.us/gpr/", searchUrl: "https://ssl.doas.state.ga.us/gpr/", domain: "ssl.doas.state.ga.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Georgia Procurement Registry." },
  { id: "hi-hiepro", name: "Hawaii HIePRO", jurisdiction: "Hawaii", state: "HI", country: "US", level: "state", url: "https://hiepro.ehawaii.gov/", searchUrl: "https://hiepro.ehawaii.gov/", domain: "hiepro.ehawaii.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Hawaii electronic procurement system." },
  { id: "id-purchasing", name: "Idaho Division of Purchasing", jurisdiction: "Idaho", state: "ID", country: "US", level: "state", url: "https://purchasing.idaho.gov/", searchUrl: "https://purchasing.idaho.gov/", domain: "purchasing.idaho.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Idaho purchasing portal." },
  { id: "il-bidbuy", name: "Illinois BidBuy", jurisdiction: "Illinois", state: "IL", country: "US", level: "state", url: "https://bidbuy.illinois.gov/", searchUrl: "https://bidbuy.illinois.gov/", domain: "bidbuy.illinois.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Illinois BidBuy portal." },
  { id: "in-idoa", name: "Indiana Current Business Opportunities", jurisdiction: "Indiana", state: "IN", country: "US", level: "state", url: "https://www.in.gov/idoa/procurement/current-business-opportunities/", searchUrl: "https://www.in.gov/idoa/procurement/current-business-opportunities/", domain: "in.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Indiana Department of Administration procurement opportunities." },
  { id: "ia-das", name: "Iowa DAS Bid Opportunities", jurisdiction: "Iowa", state: "IA", country: "US", level: "state", url: "https://das.iowa.gov/procurement", searchUrl: "https://bids.sciquest.com/apps/Router/PublicEvent?CustomerOrg=DASIowa", domain: "bids.sciquest.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Iowa DAS public bid event portal." },
  { id: "ks-procurement", name: "Kansas Procurement and Contracts", jurisdiction: "Kansas", state: "KS", country: "US", level: "state", url: "https://admin.ks.gov/offices/procurement-and-contracts", searchUrl: "https://admin.ks.gov/offices/procurement-and-contracts/bid-solicitations", domain: "admin.ks.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Kansas bid solicitation portal." },
  { id: "ky-vss", name: "Kentucky Vendor Self Service", jurisdiction: "Kentucky", state: "KY", country: "US", level: "state", url: "https://emars311.ky.gov/webapp/vssonline/AltSelfService", searchUrl: "https://emars311.ky.gov/webapp/vssonline/AltSelfService", domain: "emars311.ky.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Kentucky eMARS vendor self service portal." },
  { id: "la-lapac", name: "Louisiana LaPAC", jurisdiction: "Louisiana", state: "LA", country: "US", level: "state", url: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", searchUrl: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", domain: "wwwcfprd.doa.louisiana.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Louisiana Procurement and Contract Network." },
  { id: "me-rfps", name: "Maine Division of Procurement Services RFPs", jurisdiction: "Maine", state: "ME", country: "US", level: "state", url: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", searchUrl: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", domain: "maine.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Maine RFP listing page." },
  { id: "ma-commbuys", name: "Massachusetts COMMBUYS", jurisdiction: "Massachusetts", state: "MA", country: "US", level: "state", url: "https://www.commbuys.com/bso/", searchUrl: "https://www.commbuys.com/bso/", domain: "commbuys.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Massachusetts COMMBUYS portal." },
  { id: "mi-sigma", name: "Michigan SIGMA VSS", jurisdiction: "Michigan", state: "MI", country: "US", level: "state", url: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", searchUrl: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", domain: "sigma.michigan.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Michigan SIGMA VSS public portal." },
  { id: "mn-swift", name: "Minnesota SWIFT Supplier Portal", jurisdiction: "Minnesota", state: "MN", country: "US", level: "state", url: "https://supplier.swift.state.mn.us/", searchUrl: "https://supplier.swift.state.mn.us/psc/fmssupap/SUPPLIER/ERP/c/SCP_PUBLIC_MENU_FL.SCP_PUBLIC_MENU_FL.GBL", domain: "supplier.swift.state.mn.us", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Minnesota SWIFT public supplier portal." },
  { id: "ms-magic", name: "Mississippi MAGIC Contract/Bid Search", jurisdiction: "Mississippi", state: "MS", country: "US", level: "state", url: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", searchUrl: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", domain: "ms.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Mississippi DFA bid search." },
  { id: "mo-missouribuys", name: "MissouriBUYS", jurisdiction: "Missouri", state: "MO", country: "US", level: "state", url: "https://missouribuys.mo.gov/", searchUrl: "https://missouribuys.mo.gov/", domain: "missouribuys.mo.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Missouri procurement portal." },
  { id: "mt-emacs", name: "Montana eMACS", jurisdiction: "Montana", state: "MT", country: "US", level: "state", url: "https://spb.mt.gov/Vendor-Resources", searchUrl: "https://spb.mt.gov/Vendor-Resources", domain: "spb.mt.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Montana vendor resources and eMACS entry point." },
  { id: "ne-procurement", name: "Nebraska Materiel Division Bids", jurisdiction: "Nebraska", state: "NE", country: "US", level: "state", url: "https://das.nebraska.gov/materiel/", searchUrl: "https://das.nebraska.gov/materiel/purchasing/", domain: "das.nebraska.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Nebraska Materiel purchasing entry point." },
  { id: "nv-epro", name: "NevadaEPro", jurisdiction: "Nevada", state: "NV", country: "US", level: "state", url: "https://nevadaepro.com/bso/", searchUrl: "https://nevadaepro.com/bso/", domain: "nevadaepro.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official Nevada electronic procurement portal." },
  { id: "nh-purchasing", name: "New Hampshire Bureau of Purchase and Property", jurisdiction: "New Hampshire", state: "NH", country: "US", level: "state", url: "https://das.nh.gov/purchasing/", searchUrl: "https://das.nh.gov/purchasing/vendorresources.aspx", domain: "das.nh.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official New Hampshire purchasing portal." },
  { id: "nj-start", name: "New Jersey START", jurisdiction: "New Jersey", state: "NJ", country: "US", level: "state", url: "https://www.njstart.gov/bso/", searchUrl: "https://www.njstart.gov/bso/", domain: "njstart.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official New Jersey START procurement portal." },
  { id: "nm-active-procurements", name: "New Mexico Active Procurements", jurisdiction: "New Mexico", state: "NM", country: "US", level: "state", url: "https://www.generalservices.state.nm.us/state-purchasing/", searchUrl: "https://www.generalservices.state.nm.us/state-purchasing/active-procurements/", domain: "generalservices.state.nm.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official New Mexico state purchasing active procurements." },
  { id: "nc-evp", name: "North Carolina eVP Solicitations", jurisdiction: "North Carolina", state: "NC", country: "US", level: "state", url: "https://evp.nc.gov/", searchUrl: "https://evp.nc.gov/solicitations/", domain: "evp.nc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official North Carolina electronic Vendor Portal solicitations." },
  { id: "nd-spo", name: "North Dakota Current Solicitations", jurisdiction: "North Dakota", state: "ND", country: "US", level: "state", url: "https://www.omb.nd.gov/doing-business-state/procurement", searchUrl: "https://apps.nd.gov/csd/spo/services/bidder/listCurrentSolicitations.htm", domain: "apps.nd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official North Dakota current solicitations page." },
  { id: "ok-central-purchasing", name: "Oklahoma Central Purchasing", jurisdiction: "Oklahoma", state: "OK", country: "US", level: "state", url: "https://oklahoma.gov/omes/services/purchasing.html", searchUrl: "https://oklahoma.gov/omes/services/purchasing/solicitations.html", domain: "oklahoma.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Oklahoma purchasing solicitations entry point." },
  { id: "or-oregonbuys", name: "OregonBuys", jurisdiction: "Oregon", state: "OR", country: "US", level: "state", url: "https://oregonbuys.gov/bso/", searchUrl: "https://oregonbuys.gov/bso/", domain: "oregonbuys.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official OregonBuys portal." },
  { id: "ri-bids", name: "Rhode Island Division of Purchases Bidding Opportunities", jurisdiction: "Rhode Island", state: "RI", country: "US", level: "state", url: "https://ridop.ri.gov/", searchUrl: "https://ridop.ri.gov/vendors/bidding-opportunities", domain: "ridop.ri.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Rhode Island bidding opportunities page." },
  { id: "sc-bid-opps", name: "South Carolina Bid Opportunities", jurisdiction: "South Carolina", state: "SC", country: "US", level: "state", url: "https://procurement.sc.gov/", searchUrl: "https://procurement.sc.gov/doing-biz/bid-opps", domain: "procurement.sc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official South Carolina procurement bid opportunities." },
  { id: "sd-solicitations", name: "South Dakota Procurement Solicitations", jurisdiction: "South Dakota", state: "SD", country: "US", level: "state", url: "https://boa.sd.gov/central-services/procurement-management/", searchUrl: "https://boa.sd.gov/central-services/procurement-management/solicitations.aspx", domain: "boa.sd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official South Dakota procurement solicitations page." },
  { id: "tn-edison-rfps", name: "Tennessee Edison RFP Opportunities", jurisdiction: "Tennessee", state: "TN", country: "US", level: "state", url: "https://www.tn.gov/generalservices/procurement.html", searchUrl: "https://www.tn.gov/generalservices/procurement/central-procurement-office--cpo-/supplier-information/request-for-proposals--rfp--opportunities.html", domain: "tn.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Tennessee RFP opportunities page." },
  { id: "ut-current-bids", name: "Utah Current Bids", jurisdiction: "Utah", state: "UT", country: "US", level: "state", url: "https://purchasing.utah.gov/", searchUrl: "https://purchasing.utah.gov/for-vendors/current-bids/", domain: "purchasing.utah.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official Utah current bids page." },
  { id: "vt-bid-system", name: "Vermont Business Registry Bid System", jurisdiction: "Vermont", state: "VT", country: "US", level: "state", url: "https://www.vermontbusinessregistry.com/", searchUrl: "https://www.vermontbusinessregistry.com/BidSystem/", domain: "vermontbusinessregistry.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Vermont bid system entry point." },
  { id: "wv-purchasing-bulletin", name: "West Virginia Purchasing Bulletin", jurisdiction: "West Virginia", state: "WV", country: "US", level: "state", url: "https://www.state.wv.us/admin/purchase/", searchUrl: "https://www.state.wv.us/admin/purchase/bids.html", domain: "state.wv.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official West Virginia purchasing bulletin." },
  { id: "wi-esupplier", name: "Wisconsin eSupplier", jurisdiction: "Wisconsin", state: "WI", country: "US", level: "state", url: "https://esupplier.wi.gov/", searchUrl: "https://esupplier.wi.gov/psp/esupplier/SUPPLIER/ERP/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL", domain: "esupplier.wi.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Wisconsin eSupplier portal." },
  { id: "wy-bid-opportunities", name: "Wyoming Bid Opportunities", jurisdiction: "Wyoming", state: "WY", country: "US", level: "state", url: "https://ai.wyo.gov/divisions/procurement", searchUrl: "https://ai.wyo.gov/divisions/procurement/bid-opportunities", domain: "ai.wyo.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Wyoming procurement bid opportunities page." },

  // International direct public portals useful for later expansion.
  { id: "ca-canadabuys", name: "CanadaBuys Tender Opportunities", jurisdiction: "Canada", country: "CA", level: "international", url: "https://canadabuys.canada.ca/en/tender-opportunities", searchUrl: "https://canadabuys.canada.ca/en/tender-opportunities", domain: "canadabuys.canada.ca", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Canadian tender opportunities portal." },
  { id: "uk-contracts-finder", name: "UK Contracts Finder", jurisdiction: "United Kingdom", country: "GB", level: "international", url: "https://www.contractsfinder.service.gov.uk/", searchUrl: "https://www.contractsfinder.service.gov.uk/Search", domain: "contractsfinder.service.gov.uk", accessMode: "api", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "UK public contracts portal with documented API/OCDS access patterns." },
  { id: "worldbank-procurement", name: "World Bank Procurement Notices", jurisdiction: "World Bank", country: "INTL", level: "international", url: "https://projects.worldbank.org/en/projects-operations/procurement", searchUrl: "https://projects.worldbank.org/en/projects-operations/procurement", domain: "projects.worldbank.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "International procurement notices; not a US RFP source but useful for later global coverage." },
];

export const OFFICIAL_DIRECT_RFP_DOMAINS = new Set(DIRECT_RFP_PORTALS.map((portal) => portal.domain));

export function directRfpPortalsForSearch(includeTier3 = false): DirectRfpPortal[] {
  return DIRECT_RFP_PORTALS.filter((portal) => portal.level !== "federal" && (includeTier3 || portal.tier !== 3));
}

export function directRfpPortalByDomain(hostname: string): DirectRfpPortal | undefined {
  const normalized = hostname.toLowerCase().replace(/^www\./, "");
  return DIRECT_RFP_PORTALS.find((portal) => normalized.includes(portal.domain.toLowerCase().replace(/^www\./, "")));
}
