export type DirectRfpPortalLevel = "federal" | "state" | "district" | "international";
export type DirectRfpPortalAccessMode = "api" | "csv" | "public_html" | "dynamic_html" | "portal";
export type DirectRfpPortalParserStatus = "ready_to_parse" | "needs_parser" | "catalog_only";

export interface DirectRfpPortal {
  id: string;
  name: string;
  jurisdiction: string;
  state?: string;
  country: string;
  level: DirectRfpPortalLevel;
  url: string;
  searchUrl?: string;
  domain: string;
  accessMode: DirectRfpPortalAccessMode;
  requiresKey: boolean;
  requiresLogin: boolean;
  tier: 1 | 2 | 3;
  parserStatus: DirectRfpPortalParserStatus;
  notes: string;
}

/**
 * Direct official RFP/opportunity portals.
 *
 * This catalog intentionally excludes paid/public aggregators such as BidNet,
 * DemandStar, GovWin, PlanetBids, OpenGov network pages, Periscope/S2G, and
 * generic search engines. Those may be useful for discovery, but they are not
 * the direct buyer/source-of-truth layer we want to build on.
 */
export const DIRECT_RFP_PORTALS: DirectRfpPortal[] = [
  {
    id: "us-sam-gov",
    name: "SAM.gov Contract Opportunities",
    jurisdiction: "United States Federal Government",
    country: "US",
    level: "federal",
    url: "https://sam.gov/content/opportunities",
    searchUrl: "https://sam.gov/content/opportunities",
    domain: "sam.gov",
    accessMode: "api",
    requiresKey: true,
    requiresLogin: false,
    tier: 1,
    parserStatus: "ready_to_parse",
    notes: "Primary official federal contract opportunity API/source.",
  },

  // Wave 1: high-value official state portals to implement first.
  { id: "tx-esbd", name: "Texas ESBD / Texas SmartBuy", jurisdiction: "Texas", state: "TX", country: "US", level: "state", url: "https://www.txsmartbuy.gov/esbd", searchUrl: "https://www.txsmartbuy.gov/esbd", domain: "txsmartbuy.gov", accessMode: "csv", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Public official Texas bid portal; high priority because listings are structured and export-friendly." },
  { id: "ny-contract-reporter", name: "New York State Contract Reporter", jurisdiction: "New York", state: "NY", country: "US", level: "state", url: "https://www.nyscr.ny.gov/", searchUrl: "https://www.nyscr.ny.gov/contracts.cfm", domain: "nyscr.ny.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official New York contracting opportunity portal." },
  { id: "va-eva", name: "Virginia eVA / Business Opportunities", jurisdiction: "Virginia", state: "VA", country: "US", level: "state", url: "https://eva.virginia.gov/", searchUrl: "https://eva.virginia.gov/business-opportunities.html", domain: "eva.virginia.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Virginia procurement marketplace and business opportunities portal." },
  { id: "pa-emarketplace", name: "Pennsylvania eMarketplace", jurisdiction: "Pennsylvania", state: "PA", country: "US", level: "state", url: "https://www.emarketplace.state.pa.us/", searchUrl: "https://www.emarketplace.state.pa.us/Solicitations.aspx", domain: "emarketplace.state.pa.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Pennsylvania bid, award, and contract portal." },
  { id: "ca-caleprocure", name: "California Cal eProcure", jurisdiction: "California", state: "CA", country: "US", level: "state", url: "https://caleprocure.ca.gov/", searchUrl: "https://caleprocure.ca.gov/pages/Events-BS3/event-search.aspx", domain: "caleprocure.ca.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official California event search. Dynamic page; likely needs a dedicated parser/browser-safe fetch strategy." },
  { id: "fl-vbs", name: "Florida Vendor Bid System", jurisdiction: "Florida", state: "FL", country: "US", level: "state", url: "https://vendor.myfloridamarketplace.com/", searchUrl: "https://vendor.myfloridamarketplace.com/search/bids", domain: "vendor.myfloridamarketplace.com", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Florida public bid search." },
  { id: "oh-ohiobuys", name: "OhioBuys / Ohio Procurement", jurisdiction: "Ohio", state: "OH", country: "US", level: "state", url: "https://procure.ohio.gov/", searchUrl: "https://procure.ohio.gov/proc/view-procurement-opportunities", domain: "procure.ohio.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Ohio procurement opportunities portal." },
  { id: "wa-webs", name: "Washington WEBS", jurisdiction: "Washington", state: "WA", country: "US", level: "state", url: "https://pr-webs-customer.des.wa.gov/", searchUrl: "https://pr-webs-customer.des.wa.gov/", domain: "pr-webs-customer.des.wa.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official Washington Enterprise Bid System." },
  { id: "md-emma", name: "eMaryland Marketplace Advantage", jurisdiction: "Maryland", state: "MD", country: "US", level: "state", url: "https://emma.maryland.gov/", searchUrl: "https://emma.maryland.gov/page.aspx/en/rfp/request_browse_public", domain: "emma.maryland.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Maryland public solicitations portal." },

  // Remaining US state and district official portals.
  { id: "al-staars", name: "Alabama STAARS Vendor Self Service", jurisdiction: "Alabama", state: "AL", country: "US", level: "state", url: "https://procurement.staars.alabama.gov/", searchUrl: "https://procurement.staars.alabama.gov/", domain: "procurement.staars.alabama.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Alabama procurement portal." },
  { id: "ak-vss", name: "Alaska Vendor Self Service", jurisdiction: "Alaska", state: "AK", country: "US", level: "state", url: "https://vss.alaska.gov/", searchUrl: "https://vss.alaska.gov/", domain: "vss.alaska.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Alaska vendor self service portal; parser details need confirmation." },
  { id: "az-app", name: "Arizona Procurement Portal", jurisdiction: "Arizona", state: "AZ", country: "US", level: "state", url: "https://appstate.az.gov/", searchUrl: "https://appstate.az.gov/", domain: "appstate.az.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Arizona procurement portal." },
  { id: "ar-arbuy", name: "Arkansas ARBuy", jurisdiction: "Arkansas", state: "AR", country: "US", level: "state", url: "https://arbuy.arkansas.gov/", searchUrl: "https://arbuy.arkansas.gov/", domain: "arbuy.arkansas.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Arkansas procurement portal." },
  { id: "co-vss", name: "Colorado Vendor Self Service", jurisdiction: "Colorado", state: "CO", country: "US", level: "state", url: "https://codpa-vss.cloud.cgifederal.com/webapp/PRDVSS2X1/AltSelfService", searchUrl: "https://codpa-vss.cloud.cgifederal.com/webapp/PRDVSS2X1/AltSelfService", domain: "codpa-vss.cloud.cgifederal.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Colorado VSS public solicitation portal." },
  { id: "ct-ctsource", name: "Connecticut CTsource Bid Board", jurisdiction: "Connecticut", state: "CT", country: "US", level: "state", url: "https://portal.ct.gov/DAS/CTSource/BidBoard", searchUrl: "https://portal.ct.gov/DAS/CTSource/BidBoard", domain: "portal.ct.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Connecticut DAS/CTsource bid board." },
  { id: "de-mymarketplace", name: "Delaware MyMarketplace", jurisdiction: "Delaware", state: "DE", country: "US", level: "state", url: "https://mymarketplace.delaware.gov/", searchUrl: "https://mymarketplace.delaware.gov/", domain: "mymarketplace.delaware.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Delaware bid solicitation marketplace." },
  { id: "dc-ocp", name: "District of Columbia OCP Solicitations", jurisdiction: "District of Columbia", state: "DC", country: "US", level: "district", url: "https://ocp.dc.gov/", searchUrl: "https://ocp.dc.gov/page/ocp-solicitations", domain: "ocp.dc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official District of Columbia procurement solicitations page." },
  { id: "ga-gpr", name: "Georgia Procurement Registry", jurisdiction: "Georgia", state: "GA", country: "US", level: "state", url: "https://ssl.doas.state.ga.us/gpr/", searchUrl: "https://ssl.doas.state.ga.us/gpr/", domain: "ssl.doas.state.ga.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Georgia Procurement Registry." },
  { id: "hi-hiepro", name: "Hawaii HIePRO", jurisdiction: "Hawaii", state: "HI", country: "US", level: "state", url: "https://hiepro.ehawaii.gov/", searchUrl: "https://hiepro.ehawaii.gov/", domain: "hiepro.ehawaii.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Hawaii electronic procurement system." },
  { id: "id-purchasing", name: "Idaho Division of Purchasing", jurisdiction: "Idaho", state: "ID", country: "US", level: "state", url: "https://purchasing.idaho.gov/", searchUrl: "https://purchasing.idaho.gov/", domain: "purchasing.idaho.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Idaho purchasing portal." },
  { id: "il-bidbuy", name: "Illinois BidBuy", jurisdiction: "Illinois", state: "IL", country: "US", level: "state", url: "https://bidbuy.illinois.gov/", searchUrl: "https://bidbuy.illinois.gov/", domain: "bidbuy.illinois.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Illinois BidBuy portal." },
  { id: "in-idoa", name: "Indiana Current Business Opportunities", jurisdiction: "Indiana", state: "IN", country: "US", level: "state", url: "https://www.in.gov/idoa/procurement/current-business-opportunities/", searchUrl: "https://www.in.gov/idoa/procurement/current-business-opportunities/", domain: "in.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Indiana Department of Administration procurement opportunities." },
  { id: "ia-das", name: "Iowa DAS Bid Opportunities", jurisdiction: "Iowa", state: "IA", country: "US", level: "state", url: "https://das.iowa.gov/procurement", searchUrl: "https://bids.sciquest.com/apps/Router/PublicEvent?CustomerOrg=DASIowa", domain: "bids.sciquest.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Iowa DAS public bid event portal." },
  { id: "ks-procurement", name: "Kansas Procurement and Contracts", jurisdiction: "Kansas", state: "KS", country: "US", level: "state", url: "https://admin.ks.gov/offices/procurement-and-contracts", searchUrl: "https://admin.ks.gov/offices/procurement-and-contracts/bid-solicitations", domain: "admin.ks.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Kansas bid solicitation portal." },
  { id: "ky-vss", name: "Kentucky Vendor Self Service", jurisdiction: "Kentucky", state: "KY", country: "US", level: "state", url: "https://emars311.ky.gov/webapp/vssonline/AltSelfService", searchUrl: "https://emars311.ky.gov/webapp/vssonline/AltSelfService", domain: "emars311.ky.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Kentucky eMARS vendor self service portal." },
  { id: "la-lapac", name: "Louisiana LaPAC", jurisdiction: "Louisiana", state: "LA", country: "US", level: "state", url: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", searchUrl: "https://wwwcfprd.doa.louisiana.gov/OSP/LaPAC/pubMain.cfm", domain: "wwwcfprd.doa.louisiana.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Louisiana Procurement and Contract Network." },
  { id: "me-rfps", name: "Maine Division of Procurement Services RFPs", jurisdiction: "Maine", state: "ME", country: "US", level: "state", url: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", searchUrl: "https://www.maine.gov/dafs/bbm/procurementservices/vendors/rfps", domain: "maine.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Maine RFP listing page." },
  { id: "ma-commbuys", name: "Massachusetts COMMBUYS", jurisdiction: "Massachusetts", state: "MA", country: "US", level: "state", url: "https://www.commbuys.com/bso/", searchUrl: "https://www.commbuys.com/bso/", domain: "commbuys.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Massachusetts COMMBUYS portal." },
  { id: "mi-sigma", name: "Michigan SIGMA VSS", jurisdiction: "Michigan", state: "MI", country: "US", level: "state", url: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", searchUrl: "https://sigma.michigan.gov/webapp/PRDVSS2X1/AltSelfService", domain: "sigma.michigan.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Michigan SIGMA VSS public portal." },
  { id: "mn-swift", name: "Minnesota SWIFT Supplier Portal", jurisdiction: "Minnesota", state: "MN", country: "US", level: "state", url: "https://supplier.swift.state.mn.us/", searchUrl: "https://supplier.swift.state.mn.us/psc/fmssupap/SUPPLIER/ERP/c/SCP_PUBLIC_MENU_FL.SCP_PUBLIC_MENU_FL.GBL", domain: "supplier.swift.state.mn.us", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Minnesota SWIFT public supplier portal." },
  { id: "ms-magic", name: "Mississippi MAGIC Contract/Bid Search", jurisdiction: "Mississippi", state: "MS", country: "US", level: "state", url: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", searchUrl: "https://www.ms.gov/dfa/contract_bid_search/Home/Sell", domain: "ms.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Mississippi DFA bid search." },
  { id: "mo-missouribuys", name: "MissouriBUYS", jurisdiction: "Missouri", state: "MO", country: "US", level: "state", url: "https://missouribuys.mo.gov/", searchUrl: "https://missouribuys.mo.gov/", domain: "missouribuys.mo.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Missouri procurement portal." },
  { id: "mt-emacs", name: "Montana eMACS", jurisdiction: "Montana", state: "MT", country: "US", level: "state", url: "https://spb.mt.gov/Vendor-Resources", searchUrl: "https://spb.mt.gov/Vendor-Resources", domain: "spb.mt.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Montana vendor resources and eMACS entry point." },
  { id: "ne-procurement", name: "Nebraska Materiel Division Bids", jurisdiction: "Nebraska", state: "NE", country: "US", level: "state", url: "https://das.nebraska.gov/materiel/", searchUrl: "https://das.nebraska.gov/materiel/purchasing/", domain: "das.nebraska.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Nebraska Materiel purchasing entry point." },
  { id: "nv-epro", name: "NevadaEPro", jurisdiction: "Nevada", state: "NV", country: "US", level: "state", url: "https://nevadaepro.com/bso/", searchUrl: "https://nevadaepro.com/bso/", domain: "nevadaepro.com", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official Nevada electronic procurement portal." },
  { id: "nh-purchasing", name: "New Hampshire Bureau of Purchase and Property", jurisdiction: "New Hampshire", state: "NH", country: "US", level: "state", url: "https://das.nh.gov/purchasing/", searchUrl: "https://das.nh.gov/purchasing/vendorresources.aspx", domain: "das.nh.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official New Hampshire purchasing portal." },
  { id: "nj-start", name: "New Jersey START", jurisdiction: "New Jersey", state: "NJ", country: "US", level: "state", url: "https://www.njstart.gov/bso/", searchUrl: "https://www.njstart.gov/bso/", domain: "njstart.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official New Jersey START procurement portal." },
  { id: "nm-active-procurements", name: "New Mexico Active Procurements", jurisdiction: "New Mexico", state: "NM", country: "US", level: "state", url: "https://www.generalservices.state.nm.us/state-purchasing/", searchUrl: "https://www.generalservices.state.nm.us/state-purchasing/active-procurements/", domain: "generalservices.state.nm.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official New Mexico state purchasing active procurements." },
  { id: "nc-evp", name: "North Carolina eVP Solicitations", jurisdiction: "North Carolina", state: "NC", country: "US", level: "state", url: "https://evp.nc.gov/", searchUrl: "https://evp.nc.gov/solicitations/", domain: "evp.nc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official North Carolina electronic Vendor Portal solicitations." },
  { id: "nd-spo", name: "North Dakota Current Solicitations", jurisdiction: "North Dakota", state: "ND", country: "US", level: "state", url: "https://www.omb.nd.gov/doing-business-state/procurement", searchUrl: "https://apps.nd.gov/csd/spo/services/bidder/listCurrentSolicitations.htm", domain: "apps.nd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official North Dakota current solicitations page." },
  { id: "ok-central-purchasing", name: "Oklahoma Central Purchasing", jurisdiction: "Oklahoma", state: "OK", country: "US", level: "state", url: "https://oklahoma.gov/omes/services/purchasing.html", searchUrl: "https://oklahoma.gov/omes/services/purchasing/solicitations.html", domain: "oklahoma.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Oklahoma purchasing solicitations entry point." },
  { id: "or-oregonbuys", name: "OregonBuys", jurisdiction: "Oregon", state: "OR", country: "US", level: "state", url: "https://oregonbuys.gov/bso/", searchUrl: "https://oregonbuys.gov/bso/", domain: "oregonbuys.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official OregonBuys portal." },
  { id: "ri-bids", name: "Rhode Island Division of Purchases Bidding Opportunities", jurisdiction: "Rhode Island", state: "RI", country: "US", level: "state", url: "https://ridop.ri.gov/", searchUrl: "https://ridop.ri.gov/vendors/bidding-opportunities", domain: "ridop.ri.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Rhode Island bidding opportunities page." },
  { id: "sc-bid-opps", name: "South Carolina Bid Opportunities", jurisdiction: "South Carolina", state: "SC", country: "US", level: "state", url: "https://procurement.sc.gov/", searchUrl: "https://procurement.sc.gov/doing-biz/bid-opps", domain: "procurement.sc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official South Carolina procurement bid opportunities." },
  { id: "sd-solicitations", name: "South Dakota Procurement Solicitations", jurisdiction: "South Dakota", state: "SD", country: "US", level: "state", url: "https://boa.sd.gov/central-services/procurement-management/", searchUrl: "https://boa.sd.gov/central-services/procurement-management/solicitations.aspx", domain: "boa.sd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official South Dakota procurement solicitations page." },
  { id: "tn-edison-rfps", name: "Tennessee Edison RFP Opportunities", jurisdiction: "Tennessee", state: "TN", country: "US", level: "state", url: "https://www.tn.gov/generalservices/procurement.html", searchUrl: "https://www.tn.gov/generalservices/procurement/central-procurement-office--cpo-/supplier-information/request-for-proposals--rfp--opportunities.html", domain: "tn.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Tennessee RFP opportunities page." },
  { id: "ut-current-bids", name: "Utah Current Bids", jurisdiction: "Utah", state: "UT", country: "US", level: "state", url: "https://purchasing.utah.gov/", searchUrl: "https://purchasing.utah.gov/for-vendors/current-bids/", domain: "purchasing.utah.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "needs_parser", notes: "Official Utah current bids page." },
  { id: "vt-bid-system", name: "Vermont Business Registry Bid System", jurisdiction: "Vermont", state: "VT", country: "US", level: "state", url: "https://www.vermontbusinessregistry.com/", searchUrl: "https://www.vermontbusinessregistry.com/BidSystem/", domain: "vermontbusinessregistry.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Vermont bid system entry point." },
  { id: "wv-purchasing-bulletin", name: "West Virginia Purchasing Bulletin", jurisdiction: "West Virginia", state: "WV", country: "US", level: "state", url: "https://www.state.wv.us/admin/purchase/", searchUrl: "https://www.state.wv.us/admin/purchase/bids.html", domain: "state.wv.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official West Virginia purchasing bulletin." },
  { id: "wi-esupplier", name: "Wisconsin eSupplier", jurisdiction: "Wisconsin", state: "WI", country: "US", level: "state", url: "https://esupplier.wi.gov/", searchUrl: "https://esupplier.wi.gov/psp/esupplier/SUPPLIER/ERP/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL", domain: "esupplier.wi.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Wisconsin eSupplier portal." },
  { id: "wy-bid-opportunities", name: "Wyoming Bid Opportunities", jurisdiction: "Wyoming", state: "WY", country: "US", level: "state", url: "https://ai.wyo.gov/divisions/procurement", searchUrl: "https://ai.wyo.gov/divisions/procurement/bid-opportunities", domain: "ai.wyo.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Wyoming procurement bid opportunities page." },

  // California local government and public safety portals.
  { id: "ca-los-angeles-county", name: "Los Angeles County Open Solicitations", jurisdiction: "Los Angeles County", state: "CA", country: "US", level: "district", url: "https://doingbusiness.lacounty.gov/", searchUrl: "https://doingbusiness.lacounty.gov/open-solicitations/", domain: "doingbusiness.lacounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Los Angeles County Doing Business portal with open solicitation listings." },
  { id: "ca-city-of-los-angeles", name: "City of Los Angeles RAMPLA Contract Opportunities", jurisdiction: "City of Los Angeles", state: "CA", country: "US", level: "district", url: "https://lacity.gov/business/contract-city", searchUrl: "https://www.rampla.org/", domain: "rampla.org", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official City of Los Angeles contracting page points vendors to RAMPLA for public opportunities." },
  { id: "ca-orange-county", name: "Orange County Open Bids", jurisdiction: "Orange County", state: "CA", country: "US", level: "district", url: "https://cpo.ocgov.com/", searchUrl: "https://cpo.ocgov.com/open-bids", domain: "cpo.ocgov.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official County Procurement Office page for active County bid solicitations." },
  { id: "ca-san-diego-county", name: "County of San Diego Bid Opportunities", jurisdiction: "San Diego County", state: "CA", country: "US", level: "district", url: "https://www.sandiegocounty.gov/content/sdc/purchasing.html", searchUrl: "https://sdbuynet.sandiegocounty.gov/", domain: "sdbuynet.sandiegocounty.gov", accessMode: "portal", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official County of San Diego BuyNet procurement system; viewing and downloading solicitations is public." },
  { id: "ca-san-francisco", name: "City and County of San Francisco Bid Opportunities", jurisdiction: "San Francisco", state: "CA", country: "US", level: "district", url: "https://www.sf.gov/topics--contracting-city-and-county-san-francisco", searchUrl: "https://www.sf.gov/information--bid-opportunities", domain: "sf.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official SF.gov bid opportunities page for City and County contracting." },
  { id: "ca-city-of-long-beach", name: "City of Long Beach Purchasing", jurisdiction: "City of Long Beach", state: "CA", country: "US", level: "district", url: "https://longbeach.gov/finance/business-info/purchasing-division/", searchUrl: "https://longbeach.gov/finance/business-info/purchasing-division/", domain: "longbeach.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official purchasing division page linking to Long Beach Buys opportunities and vendor resources." },
  { id: "ca-orange-county-fire-authority", name: "Orange County Fire Authority Purchasing", jurisdiction: "Orange County Fire Authority", state: "CA", country: "US", level: "district", url: "https://ocfa.org/about-us/departments/business-services/purchasing/", searchUrl: "https://ocfa.org/about-us/departments/business-services/purchasing/", domain: "ocfa.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official OCFA purchasing page for supplier registration, current bids, RFPs, and bid results." },
  { id: "ca-port-of-los-angeles", name: "Port of Los Angeles Contracting Opportunities", jurisdiction: "Port of Los Angeles", state: "CA", country: "US", level: "district", url: "https://portoflosangeles.org/business/contracting-opportunities", searchUrl: "https://portoflosangeles.org/business/contracting-opportunities/purchasing-bids", domain: "portoflosangeles.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Port of Los Angeles contracting opportunities and purchasing bids pages." },
  { id: "ca-la-metro", name: "LA Metro Contracting Opportunities", jurisdiction: "Los Angeles County Metropolitan Transportation Authority", state: "CA", country: "US", level: "district", url: "https://www.metro.net/about/doing-business-with-metro/", searchUrl: "https://www.metro.net/about/doing-business-with-metro/", domain: "metro.net", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official LA Metro doing-business page for procurement and contracting opportunity access." },

  // Texas local government and public safety portals.
  { id: "tx-harris-county", name: "Harris County Online Solicitation Opportunities", jurisdiction: "Harris County", state: "TX", country: "US", level: "district", url: "https://purchasing.harriscountytx.gov/", searchUrl: "https://purchasing.harriscountytx.gov/Services/Online-Solicitation-Opportunities", domain: "purchasing.harriscountytx.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Harris County Purchasing page for online solicitation opportunities." },
  { id: "tx-city-of-austin", name: "City of Austin Active Solicitations", jurisdiction: "City of Austin", state: "TX", country: "US", level: "district", url: "https://www.austintexas.gov/financial-services/solicitations", searchUrl: "https://financeonline.austintexas.gov/afo/account_services/solicitation/solicitations.cfm", domain: "financeonline.austintexas.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official City of Austin active solicitations table." },
  { id: "tx-city-of-san-antonio", name: "City of San Antonio Bidding and Contracting", jurisdiction: "City of San Antonio", state: "TX", country: "US", level: "district", url: "https://www.sanantonio.gov/purchasing", searchUrl: "https://webapp1.sanantonio.gov/BidContractOpps/Default.aspx", domain: "webapp1.sanantonio.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official City of San Antonio bid and contract opportunities listing." },
  { id: "tx-city-of-dallas", name: "City of Dallas Procurement Services", jurisdiction: "City of Dallas", state: "TX", country: "US", level: "district", url: "https://dallascityhall.com/departments/procurement-services/", searchUrl: "https://dallascityhall.com/departments/procurement-services/Pages/default.aspx", domain: "dallascityhall.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Dallas procurement services pages for solicitations and vendor resources." },
  { id: "tx-city-of-houston", name: "City of Houston Strategic Procurement", jurisdiction: "City of Houston", state: "TX", country: "US", level: "district", url: "https://www.houstontx.gov/obo/strategic_procurement.html", searchUrl: "https://www.houstontx.gov/obo/strategic_procurement.html", domain: "houstontx.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Houston strategic procurement page for vendor and bid opportunity access." },

  // New York local government and public safety portals.
  { id: "ny-city-of-new-york", name: "New York City PASSPort Public", jurisdiction: "New York City", state: "NY", country: "US", level: "district", url: "https://www.nyc.gov/site/mocs/passport/about-passport.page", searchUrl: "https://a0333-passportpublic.nyc.gov/", domain: "a0333-passportpublic.nyc.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official NYC PASSPort public procurement navigator; public opportunities are browsable without an account." },

  // Florida local government and public safety portals.
  { id: "fl-miami-dade-county", name: "Miami-Dade County Solicitations", jurisdiction: "Miami-Dade County", state: "FL", country: "US", level: "district", url: "https://www.miamidade.gov/global/strategic-procurement/solicitations.page", searchUrl: "https://www.miamidade.gov/apps/ISD/stratproc/Home/CurrentSolicitations", domain: "miamidade.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Miami-Dade County Strategic Procurement current solicitations list." },

  // Pennsylvania local government and public safety portals.
  { id: "pa-city-of-philadelphia", name: "City of Philadelphia Contracts Hub", jurisdiction: "City of Philadelphia", state: "PA", country: "US", level: "district", url: "https://www.phila.gov/departments/procurement-department/contracts-information/available-contracts/", searchUrl: "https://contracts.phila.gov/", domain: "contracts.phila.gov", accessMode: "dynamic_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "needs_parser", notes: "Official City of Philadelphia Contracts Hub for contract opportunities across procurement websites." },

  // Virginia local government and public safety portals.
  { id: "va-fairfax-county", name: "Fairfax County Current Solicitations", jurisdiction: "Fairfax County", state: "VA", country: "US", level: "district", url: "https://www.fairfaxcounty.gov/procurement/contracting-opportunities", searchUrl: "https://www.fairfaxcounty.gov/solicitation/", domain: "fairfaxcounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "ready_to_parse", notes: "Official Fairfax County procurement opportunities and current solicitations pages." },

  // Maryland local government and public safety portals.
  { id: "md-montgomery-county", name: "Montgomery County Procurement", jurisdiction: "Montgomery County", state: "MD", country: "US", level: "district", url: "https://www.montgomerycountymd.gov/pro/", searchUrl: "https://www.montgomerycountymd.gov/PRO/solicitations.html", domain: "montgomerycountymd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Montgomery County procurement office and solicitations pages." },

  // North Carolina local government and public safety portals.
  { id: "nc-wake-county", name: "Wake County Vendor and Bid Opportunities", jurisdiction: "Wake County", state: "NC", country: "US", level: "district", url: "https://www.wake.gov/departments-government/finance/vendor-information", searchUrl: "https://www.wake.gov/departments-government/finance/vendor-information/bid-opportunities", domain: "wake.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Wake County vendor information and bid opportunities pages." },

  // Georgia local government and public safety portals.
  { id: "ga-city-of-atlanta", name: "City of Atlanta Procurement", jurisdiction: "City of Atlanta", state: "GA", country: "US", level: "district", url: "https://www.atlantaga.gov/government/departments/procurement", searchUrl: "https://www.atlantaga.gov/government/departments/procurement", domain: "atlantaga.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Atlanta procurement page for solicitations and vendor resources." },

  // Washington local government and public safety portals.
  { id: "wa-king-county", name: "King County Solicitations", jurisdiction: "King County", state: "WA", country: "US", level: "district", url: "https://kingcounty.gov/en/business/do-business-with-king-county", searchUrl: "https://kingcounty.gov/en/business/do-business-with-king-county/solicitations", domain: "kingcounty.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official King County doing-business and solicitations pages." },

  // Arizona local government and public safety portals.
  { id: "az-maricopa-county", name: "Maricopa County Procurement Services", jurisdiction: "Maricopa County", state: "AZ", country: "US", level: "district", url: "https://www.maricopa.gov/2085/Procurement-Services", searchUrl: "https://www.maricopa.gov/2085/Procurement-Services", domain: "maricopa.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Maricopa County Procurement Services page for bids and vendor resources." },

  // Colorado local government and public safety portals.
  { id: "co-denver", name: "City and County of Denver Purchasing", jurisdiction: "City and County of Denver", state: "CO", country: "US", level: "district", url: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/General-Services/Purchasing", searchUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/General-Services/Purchasing", domain: "denvergov.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Denver purchasing page for bid and procurement opportunity access." },

  // Illinois local government and public safety portals.
  { id: "il-city-of-chicago", name: "City of Chicago Procurement Services", jurisdiction: "City of Chicago", state: "IL", country: "US", level: "district", url: "https://www.chicago.gov/city/en/depts/dps.html", searchUrl: "https://www.chicago.gov/city/en/depts/dps/provdrs/contract/svcs/current_bid_opportunities.html", domain: "chicago.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Chicago Department of Procurement Services bid opportunities page." },

  // Michigan local government and public safety portals.
  { id: "mi-city-of-detroit", name: "City of Detroit Office of Contracting and Procurement", jurisdiction: "City of Detroit", state: "MI", country: "US", level: "district", url: "https://detroitmi.gov/departments/office-contracting-and-procurement", searchUrl: "https://detroitmi.gov/departments/office-contracting-and-procurement", domain: "detroitmi.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Detroit contracting and procurement office page for bid and vendor resources." },

  // New Jersey local government and public safety portals.
  { id: "nj-newark", name: "City of Newark Purchasing", jurisdiction: "City of Newark", state: "NJ", country: "US", level: "district", url: "https://www.newarknj.gov/departments/purchasing", searchUrl: "https://www.newarknj.gov/departments/purchasing", domain: "newarknj.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official City of Newark purchasing page for procurement notices and vendor information." },

  // Massachusetts local government and public safety portals.
  { id: "ma-city-of-boston", name: "City of Boston Procurement", jurisdiction: "City of Boston", state: "MA", country: "US", level: "district", url: "https://www.boston.gov/departments/procurement", searchUrl: "https://www.boston.gov/departments/procurement/bid-listings", domain: "boston.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Boston procurement department and bid listings pages." },

  // Tennessee local government and public safety portals.
  { id: "tn-nashville", name: "Metropolitan Government of Nashville Procurement", jurisdiction: "Metropolitan Government of Nashville and Davidson County", state: "TN", country: "US", level: "district", url: "https://www.nashville.gov/departments/finance/procurement", searchUrl: "https://www.nashville.gov/departments/finance/procurement", domain: "nashville.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official Metro Nashville procurement page for solicitation and vendor resources." },

  // Louisiana local government and public safety portals.
  { id: "la-new-orleans", name: "City of New Orleans Purchasing", jurisdiction: "City of New Orleans", state: "LA", country: "US", level: "district", url: "https://nola.gov/purchasing/", searchUrl: "https://nola.gov/purchasing/", domain: "nola.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of New Orleans purchasing page for bid and vendor information." },

  // Oregon local government and public safety portals.
  { id: "or-portland", name: "City of Portland Procurement Services", jurisdiction: "City of Portland", state: "OR", country: "US", level: "district", url: "https://www.portland.gov/omf/brfs/procurement", searchUrl: "https://www.portland.gov/omf/brfs/procurement/bids", domain: "portland.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official City of Portland procurement services and bids pages." },


  // California education, transit, airport, water, and port authority portals.
  { id: "ca-lausd", name: "Los Angeles Unified School District Procurement Services", jurisdiction: "Los Angeles Unified School District", state: "CA", country: "US", level: "district", url: "https://www.lausd.org/procurement", searchUrl: "https://www.lausd.org/procurement", domain: "lausd.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official LAUSD procurement services page for bids, vendor registration, and contracting resources." },
  { id: "ca-sandag", name: "SANDAG Contracts and Procurement", jurisdiction: "San Diego Association of Governments", state: "CA", country: "US", level: "district", url: "https://www.sandag.org/contracts", searchUrl: "https://www.sandag.org/contracts", domain: "sandag.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official SANDAG contracts page for procurement opportunities and vendor resources." },
  { id: "ca-bart", name: "BART Procurement Opportunities", jurisdiction: "San Francisco Bay Area Rapid Transit District", state: "CA", country: "US", level: "district", url: "https://www.bart.gov/about/business/procurement", searchUrl: "https://www.bart.gov/about/business/procurement", domain: "bart.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official BART procurement page for contracting opportunities and vendor information." },
  { id: "ca-port-of-oakland", name: "Port of Oakland Bids and RFPs", jurisdiction: "Port of Oakland", state: "CA", country: "US", level: "district", url: "https://www.portofoakland.com/business/bids-rfps/", searchUrl: "https://www.portofoakland.com/business/bids-rfps/", domain: "portofoakland.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Port of Oakland bids and RFPs page." },
  { id: "ca-east-bay-mud", name: "East Bay Municipal Utility District Purchasing", jurisdiction: "East Bay Municipal Utility District", state: "CA", country: "US", level: "district", url: "https://www.ebmud.com/business-center/purchasing", searchUrl: "https://www.ebmud.com/business-center/purchasing", domain: "ebmud.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official EBMUD purchasing page for bid opportunities and vendor guidance." },

  // Texas education, transit, airport, and utility authority portals.
  { id: "tx-houston-isd", name: "Houston ISD Procurement Services", jurisdiction: "Houston Independent School District", state: "TX", country: "US", level: "district", url: "https://www.houstonisd.org/procurement", searchUrl: "https://www.houstonisd.org/procurement", domain: "houstonisd.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Houston ISD procurement page for solicitations and vendor resources." },
  { id: "tx-dallas-isd", name: "Dallas ISD Procurement Services", jurisdiction: "Dallas Independent School District", state: "TX", country: "US", level: "district", url: "https://www.dallasisd.org/procurement", searchUrl: "https://www.dallasisd.org/procurement", domain: "dallasisd.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Dallas ISD procurement services page for bid and vendor information." },
  { id: "tx-dfw-airport", name: "DFW Airport Procurement", jurisdiction: "Dallas Fort Worth International Airport", state: "TX", country: "US", level: "district", url: "https://www.dfwairport.com/business/solicitations/", searchUrl: "https://www.dfwairport.com/business/solicitations/", domain: "dfwairport.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official DFW Airport solicitations page for airport procurement opportunities." },
  { id: "tx-dart", name: "DART Procurement", jurisdiction: "Dallas Area Rapid Transit", state: "TX", country: "US", level: "district", url: "https://www.dart.org/about/procurement", searchUrl: "https://www.dart.org/about/procurement", domain: "dart.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official DART procurement page for transit contracting opportunities." },
  { id: "tx-san-antonio-water-system", name: "San Antonio Water System Purchasing", jurisdiction: "San Antonio Water System", state: "TX", country: "US", level: "district", url: "https://www.saws.org/business-center/purchasing/", searchUrl: "https://www.saws.org/business-center/purchasing/", domain: "saws.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official SAWS purchasing page for water utility procurement and vendor resources." },

  // New York and New Jersey transit, port, and authority portals.
  { id: "ny-mta", name: "MTA Doing Business With Us", jurisdiction: "Metropolitan Transportation Authority", state: "NY", country: "US", level: "district", url: "https://new.mta.info/doing-business-with-us", searchUrl: "https://new.mta.info/doing-business-with-us", domain: "new.mta.info", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official MTA procurement and contracting entry point for public transit opportunities." },
  { id: "ny-port-authority", name: "Port Authority of New York and New Jersey Procurement", jurisdiction: "Port Authority of New York and New Jersey", state: "NY", country: "US", level: "district", url: "https://www.panynj.gov/port-authority/en/business-opportunities.html", searchUrl: "https://www.panynj.gov/port-authority/en/business-opportunities.html", domain: "panynj.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 1, parserStatus: "catalog_only", notes: "Official PANYNJ business opportunities page for port and airport authority procurement." },
  { id: "ny-buffalo-public-schools", name: "Buffalo Public Schools Purchasing", jurisdiction: "Buffalo Public Schools", state: "NY", country: "US", level: "district", url: "https://www.buffaloschools.org/Page/95165", searchUrl: "https://www.buffaloschools.org/Page/95165", domain: "buffaloschools.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Buffalo Public Schools purchasing page for school district procurement notices and resources." },
  { id: "nj-njtransit", name: "NJ TRANSIT Procurement", jurisdiction: "New Jersey Transit", state: "NJ", country: "US", level: "district", url: "https://www.njtransit.com/procurement", searchUrl: "https://www.njtransit.com/procurement", domain: "njtransit.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official NJ TRANSIT procurement page for transit solicitations and vendor resources." },

  // Florida education, airport, transit, and port authority portals.
  { id: "fl-broward-county", name: "Broward County Purchasing", jurisdiction: "Broward County", state: "FL", country: "US", level: "district", url: "https://www.broward.org/Purchasing/", searchUrl: "https://www.broward.org/Purchasing/", domain: "broward.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Broward County Purchasing Division page for solicitations and vendor resources." },
  { id: "fl-orange-county-public-schools", name: "Orange County Public Schools Procurement Services", jurisdiction: "Orange County Public Schools", state: "FL", country: "US", level: "district", url: "https://www.ocps.net/departments/procurement_services", searchUrl: "https://www.ocps.net/departments/procurement_services", domain: "ocps.net", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official OCPS procurement services page for school district purchasing opportunities." },
  { id: "fl-jacksonville-aviation-authority", name: "Jacksonville Aviation Authority Procurement", jurisdiction: "Jacksonville Aviation Authority", state: "FL", country: "US", level: "district", url: "https://www.flyjacksonville.com/Content2015.aspx?id=789", searchUrl: "https://www.flyjacksonville.com/Content2015.aspx?id=789", domain: "flyjacksonville.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Jacksonville Aviation Authority procurement page for airport contracting opportunities." },
  { id: "fl-jtafla", name: "Jacksonville Transportation Authority Procurement", jurisdiction: "Jacksonville Transportation Authority", state: "FL", country: "US", level: "district", url: "https://www.jtafla.com/procurement/", searchUrl: "https://www.jtafla.com/procurement/", domain: "jtafla.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official JTA procurement page for transit solicitations and vendor information." },

  // Pennsylvania, Virginia, Maryland, and District-area authority portals.
  { id: "pa-septa", name: "SEPTA Procurement", jurisdiction: "Southeastern Pennsylvania Transportation Authority", state: "PA", country: "US", level: "district", url: "https://www.septa.org/procurement/", searchUrl: "https://www.septa.org/procurement/", domain: "septa.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official SEPTA procurement page for transit contracting opportunities." },
  { id: "pa-pittsburgh", name: "City of Pittsburgh Procurement", jurisdiction: "City of Pittsburgh", state: "PA", country: "US", level: "district", url: "https://pittsburghpa.gov/finance/procurement", searchUrl: "https://pittsburghpa.gov/finance/procurement", domain: "pittsburghpa.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official City of Pittsburgh procurement page for bid opportunities and vendor guidance." },
  { id: "va-henrico-county", name: "Henrico County Purchasing", jurisdiction: "Henrico County", state: "VA", country: "US", level: "district", url: "https://henrico.us/purchasing/", searchUrl: "https://henrico.us/purchasing/", domain: "henrico.us", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Henrico County purchasing page for solicitations and vendor information." },
  { id: "md-baltimore-county", name: "Baltimore County Purchasing", jurisdiction: "Baltimore County", state: "MD", country: "US", level: "district", url: "https://www.baltimorecountymd.gov/departments/budfin/purchasing/", searchUrl: "https://www.baltimorecountymd.gov/departments/budfin/purchasing/", domain: "baltimorecountymd.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Baltimore County purchasing page for bids and vendor resources." },
  { id: "md-wmata", name: "WMATA Procurement and Contracting", jurisdiction: "Washington Metropolitan Area Transit Authority", state: "MD", country: "US", level: "district", url: "https://www.wmata.com/business/procurement/", searchUrl: "https://www.wmata.com/business/procurement/", domain: "wmata.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official WMATA procurement and contracting page for regional transit opportunities." },

  // North Carolina, Georgia, Washington, Arizona, and Colorado authority portals.
  { id: "nc-charlotte", name: "City of Charlotte Procurement", jurisdiction: "City of Charlotte", state: "NC", country: "US", level: "district", url: "https://www.charlottenc.gov/Growth-and-Development/Doing-Business-with-the-City", searchUrl: "https://www.charlottenc.gov/Growth-and-Development/Doing-Business-with-the-City", domain: "charlottenc.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official City of Charlotte doing-business page for procurement opportunities and vendor resources." },
  { id: "ga-marta", name: "MARTA Procurement", jurisdiction: "Metropolitan Atlanta Rapid Transit Authority", state: "GA", country: "US", level: "district", url: "https://www.itsmarta.com/Procurement.aspx", searchUrl: "https://www.itsmarta.com/Procurement.aspx", domain: "itsmarta.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official MARTA procurement page for transit contracting opportunities." },
  { id: "wa-port-of-seattle", name: "Port of Seattle Bid Opportunities", jurisdiction: "Port of Seattle", state: "WA", country: "US", level: "district", url: "https://www.portseattle.org/business/bid-opportunities", searchUrl: "https://www.portseattle.org/business/bid-opportunities", domain: "portseattle.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "ready_to_parse", notes: "Official Port of Seattle bid opportunities page for port and airport procurement." },
  { id: "az-valley-metro", name: "Valley Metro Procurement", jurisdiction: "Valley Metro Regional Public Transportation Authority", state: "AZ", country: "US", level: "district", url: "https://www.valleymetro.org/procurement", searchUrl: "https://www.valleymetro.org/procurement", domain: "valleymetro.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Valley Metro procurement page for regional transit opportunities." },
  { id: "co-rtd-denver", name: "RTD Denver Procurement", jurisdiction: "Regional Transportation District", state: "CO", country: "US", level: "district", url: "https://www.rtd-denver.com/doing-business-with-rtd/procurement", searchUrl: "https://www.rtd-denver.com/doing-business-with-rtd/procurement", domain: "rtd-denver.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official RTD procurement page for transit contracting opportunities." },

  // Midwest, Southeast, and Mountain West continuation portals.
  { id: "il-cook-county", name: "Cook County Procurement", jurisdiction: "Cook County", state: "IL", country: "US", level: "district", url: "https://www.cookcountyil.gov/service/doing-business-cook-county", searchUrl: "https://www.cookcountyil.gov/service/doing-business-cook-county", domain: "cookcountyil.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Cook County doing-business page for procurement opportunities and vendor resources." },
  { id: "mi-wayne-county", name: "Wayne County Procurement", jurisdiction: "Wayne County", state: "MI", country: "US", level: "district", url: "https://www.waynecounty.com/departments/procurement/home.aspx", searchUrl: "https://www.waynecounty.com/departments/procurement/home.aspx", domain: "waynecounty.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official Wayne County procurement page for bid and vendor resources." },
  { id: "tn-memphis", name: "City of Memphis Purchasing", jurisdiction: "City of Memphis", state: "TN", country: "US", level: "district", url: "https://www.memphistn.gov/government/finance/purchasing/", searchUrl: "https://www.memphistn.gov/government/finance/purchasing/", domain: "memphistn.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "catalog_only", notes: "Official City of Memphis purchasing page for solicitations and vendor information." },
  { id: "nv-clark-county", name: "Clark County Purchasing and Contracts", jurisdiction: "Clark County", state: "NV", country: "US", level: "district", url: "https://www.clarkcountynv.gov/government/departments/finance/purchasing_and_contracts/index.php", searchUrl: "https://www.clarkcountynv.gov/government/departments/finance/purchasing_and_contracts/index.php", domain: "clarkcountynv.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Clark County purchasing and contracts page for solicitations and vendor resources." },
  { id: "ut-uta", name: "Utah Transit Authority Procurement", jurisdiction: "Utah Transit Authority", state: "UT", country: "US", level: "district", url: "https://www.rideuta.com/Doing-Business/Procurement", searchUrl: "https://www.rideuta.com/Doing-Business/Procurement", domain: "rideuta.com", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official UTA procurement page for transit contracting opportunities." },
  { id: "sc-charleston-county", name: "Charleston County Procurement", jurisdiction: "Charleston County", state: "SC", country: "US", level: "district", url: "https://www.charlestoncounty.org/departments/procurement/", searchUrl: "https://www.charlestoncounty.org/departments/procurement/", domain: "charlestoncounty.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Charleston County procurement page for bids and vendor resources." },
  { id: "wi-milwaukee-county", name: "Milwaukee County Procurement", jurisdiction: "Milwaukee County", state: "WI", country: "US", level: "district", url: "https://county.milwaukee.gov/EN/Administrative-Services/Procurement", searchUrl: "https://county.milwaukee.gov/EN/Administrative-Services/Procurement", domain: "county.milwaukee.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Milwaukee County procurement page for solicitations and vendor resources." },
  { id: "mn-met-council", name: "Metropolitan Council Procurement", jurisdiction: "Metropolitan Council", state: "MN", country: "US", level: "district", url: "https://metrocouncil.org/About-Us/Doing-Business-with-the-Council.aspx", searchUrl: "https://metrocouncil.org/About-Us/Doing-Business-with-the-Council.aspx", domain: "metrocouncil.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Metropolitan Council doing-business page for regional transit and public agency procurement." },
  { id: "mo-kansas-city", name: "Kansas City Procurement Services", jurisdiction: "Kansas City", state: "MO", country: "US", level: "district", url: "https://www.kcmo.gov/city-hall/departments/finance/procurement-services", searchUrl: "https://www.kcmo.gov/city-hall/departments/finance/procurement-services", domain: "kcmo.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Kansas City procurement services page for bid opportunities and vendor resources." },
  { id: "al-birmingham", name: "City of Birmingham Purchasing", jurisdiction: "City of Birmingham", state: "AL", country: "US", level: "district", url: "https://www.birminghamal.gov/purchasing/", searchUrl: "https://www.birminghamal.gov/purchasing/", domain: "birminghamal.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official City of Birmingham purchasing page for vendor and bid opportunity information." },
  { id: "ky-louisville", name: "Louisville Metro Purchasing", jurisdiction: "Louisville Metro Government", state: "KY", country: "US", level: "district", url: "https://louisvilleky.gov/government/management-budget/purchasing", searchUrl: "https://louisvilleky.gov/government/management-budget/purchasing", domain: "louisvilleky.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official Louisville Metro purchasing page for solicitations and vendor resources." },
  { id: "ct-hartford", name: "City of Hartford Procurement", jurisdiction: "City of Hartford", state: "CT", country: "US", level: "district", url: "https://www.hartfordct.gov/Government/Departments/Finance/Procurement-Services", searchUrl: "https://www.hartfordct.gov/Government/Departments/Finance/Procurement-Services", domain: "hartfordct.gov", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "Official City of Hartford procurement services page for solicitations and vendor resources." },

  // International direct public portals useful for later expansion.
  { id: "ca-canadabuys", name: "CanadaBuys Tender Opportunities", jurisdiction: "Canada", country: "CA", level: "international", url: "https://canadabuys.canada.ca/en/tender-opportunities", searchUrl: "https://canadabuys.canada.ca/en/tender-opportunities", domain: "canadabuys.canada.ca", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "Official Canadian tender opportunities portal." },
  { id: "uk-contracts-finder", name: "UK Contracts Finder", jurisdiction: "United Kingdom", country: "GB", level: "international", url: "https://www.contractsfinder.service.gov.uk/", searchUrl: "https://www.contractsfinder.service.gov.uk/Search", domain: "contractsfinder.service.gov.uk", accessMode: "api", requiresKey: false, requiresLogin: false, tier: 2, parserStatus: "needs_parser", notes: "UK public contracts portal with documented API/OCDS access patterns." },
  { id: "worldbank-procurement", name: "World Bank Procurement Notices", jurisdiction: "World Bank", country: "INTL", level: "international", url: "https://projects.worldbank.org/en/projects-operations/procurement", searchUrl: "https://projects.worldbank.org/en/projects-operations/procurement", domain: "projects.worldbank.org", accessMode: "public_html", requiresKey: false, requiresLogin: false, tier: 3, parserStatus: "catalog_only", notes: "International procurement notices; not a US RFP source but useful for later global coverage." },
];

export const OFFICIAL_DIRECT_RFP_DOMAINS = new Set(DIRECT_RFP_PORTALS.map((portal) => portal.domain));

export function directRfpPortalsForSearch(includeTier3 = false): DirectRfpPortal[] {
  return DIRECT_RFP_PORTALS.filter((portal) => portal.level !== "federal" && (includeTier3 || portal.tier !== 3));
}

export function directRfpPortalByDomain(hostname: string): DirectRfpPortal | undefined {
  const normalized = hostname.toLowerCase().replace(/^www\./, "");
  return DIRECT_RFP_PORTALS.find((portal) => normalized.includes(portal.domain.toLowerCase().replace(/^www\./, "")));
}
