import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_002: DirectRfpPortal[] = [
  {
    id: "ut-salt-lake-city",
    name: "Salt Lake City Purchasing",
    jurisdiction: "Salt Lake City",
    state: "UT",
    country: "US",
    level: "district",
    url: "https://www.slc.gov/purchasing/",
    searchUrl: "https://www.slc.gov/purchasing/",
    domain: "slc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Salt Lake City purchasing page.",
  },
  {
    id: "vi-property-and-procurement",
    name: "USVI Department of Property and Procurement",
    jurisdiction: "U.S. Virgin Islands",
    state: "VI",
    country: "US",
    level: "district",
    url: "https://dpp.vi.gov/",
    searchUrl: "https://dpp.vi.gov/",
    domain: "dpp.vi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official U.S. Virgin Islands Department of Property and Procurement site.",
  },
  {
    id: "vt-burlington",
    name: "City of Burlington RFPs and Bids",
    jurisdiction: "City of Burlington",
    state: "VT",
    country: "US",
    level: "district",
    url: "https://www.burlingtonvt.gov/RFP",
    searchUrl: "https://www.burlingtonvt.gov/RFP",
    domain: "burlingtonvt.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Burlington RFP and bid posting page.",
  },
  {
    id: "wi-milwaukee",
    name: "City of Milwaukee Purchasing",
    jurisdiction: "City of Milwaukee",
    state: "WI",
    country: "US",
    level: "district",
    url: "https://city.milwaukee.gov/Purchasing",
    searchUrl: "https://city.milwaukee.gov/Purchasing",
    domain: "city.milwaukee.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Milwaukee purchasing page.",
  },
  {
    id: "wv-charleston",
    name: "City of Charleston Purchasing",
    jurisdiction: "City of Charleston",
    state: "WV",
    country: "US",
    level: "district",
    url: "https://www.charlestonwv.gov/government/city-departments/finance/purchasing",
    searchUrl:
      "https://www.charlestonwv.gov/government/city-departments/finance/purchasing",
    domain: "charlestonwv.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Charleston, West Virginia purchasing page.",
  },
  {
    id: "wy-cheyenne",
    name: "City of Cheyenne Purchasing",
    jurisdiction: "City of Cheyenne",
    state: "WY",
    country: "US",
    level: "district",
    url: "https://www.cheyennecity.org/Your-Government/Departments/Finance/Purchasing",
    searchUrl:
      "https://www.cheyennecity.org/Your-Government/Departments/Finance/Purchasing",
    domain: "cheyennecity.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Cheyenne purchasing page.",
  },
  {
    id: "az-phoenix",
    name: "City of Phoenix Finance Procurement",
    jurisdiction: "City of Phoenix",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.phoenix.gov/finance/vendorsreg",
    searchUrl: "https://www.phoenix.gov/finance/vendorsreg",
    domain: "phoenix.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official City of Phoenix procurement and vendor registration page.",
  },
  {
    id: "ca-los-angeles-world-airports",
    name: "Los Angeles World Airports Business Opportunities",
    jurisdiction: "Los Angeles World Airports",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://www.lawa.org/businesses/lawa-business-opportunities",
    searchUrl: "https://www.lawa.org/businesses/lawa-business-opportunities",
    domain: "lawa.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official LAWA business opportunities page for airport authority procurement.",
  },
  {
    id: "co-colorado-springs",
    name: "City of Colorado Springs Procurement Services",
    jurisdiction: "City of Colorado Springs",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://coloradosprings.gov/procurement-services",
    searchUrl: "https://coloradosprings.gov/procurement-services",
    domain: "coloradosprings.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Colorado Springs procurement services page.",
  },
  {
    id: "dc-water",
    name: "DC Water Procurement",
    jurisdiction: "District of Columbia Water and Sewer Authority",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.dcwater.com/procurement",
    searchUrl: "https://www.dcwater.com/procurement",
    domain: "dcwater.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes:
      "Official DC Water procurement page for water utility solicitations and vendor resources.",
  },
  {
    id: "il-metropolitan-water-reclamation-district",
    name: "MWRD Procurement and Materials Management",
    jurisdiction: "Metropolitan Water Reclamation District of Greater Chicago",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://mwrd.org/procurement-and-materials-management",
    searchUrl: "https://mwrd.org/procurement-and-materials-management",
    domain: "mwrd.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official MWRD procurement and materials management page.",
  },
  {
    id: "la-baton-rouge",
    name: "City-Parish of Baton Rouge Purchasing",
    jurisdiction: "City of Baton Rouge and Parish of East Baton Rouge",
    state: "LA",
    country: "US",
    level: "district",
    url: "https://www.brla.gov/150/Purchasing",
    searchUrl: "https://www.brla.gov/150/Purchasing",
    domain: "brla.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City-Parish purchasing page.",
  },
  {
    id: "md-maryland-transportation-authority",
    name: "Maryland Transportation Authority Procurement",
    jurisdiction: "Maryland Transportation Authority",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://mdta.maryland.gov/Business/Procurement",
    searchUrl: "https://mdta.maryland.gov/Business/Procurement",
    domain: "mdta.maryland.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes:
      "Official MDTA procurement page for transportation authority contracting.",
  },
  {
    id: "mi-oakland-county",
    name: "Oakland County Purchasing",
    jurisdiction: "Oakland County",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.oakgov.com/government/purchasing",
    searchUrl: "https://www.oakgov.com/government/purchasing",
    domain: "oakgov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Oakland County purchasing page.",
  },
  {
    id: "nc-raleigh",
    name: "City of Raleigh Procurement",
    jurisdiction: "City of Raleigh",
    state: "NC",
    country: "US",
    level: "district",
    url: "https://raleighnc.gov/doing-business/services/procurement",
    searchUrl: "https://raleighnc.gov/doing-business/services/procurement",
    domain: "raleighnc.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Raleigh procurement page.",
  },
  {
    id: "or-trimet",
    name: "TriMet Procurement",
    jurisdiction: "Tri-County Metropolitan Transportation District of Oregon",
    state: "OR",
    country: "US",
    level: "district",
    url: "https://trimet.org/procurement/",
    searchUrl: "https://trimet.org/procurement/",
    domain: "trimet.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official TriMet procurement page for transit contracting.",
  },
  {
    id: "tn-knoxville",
    name: "City of Knoxville Purchasing",
    jurisdiction: "City of Knoxville",
    state: "TN",
    country: "US",
    level: "district",
    url: "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    searchUrl:
      "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing",
    domain: "knoxvilletn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Knoxville purchasing page.",
  },
  {
    id: "va-virginia-beach",
    name: "City of Virginia Beach Purchasing",
    jurisdiction: "City of Virginia Beach",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.vbgov.com/government/departments/finance/Pages/purchasing.aspx",
    searchUrl:
      "https://www.vbgov.com/government/departments/finance/Pages/purchasing.aspx",
    domain: "vbgov.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Virginia Beach purchasing page.",
  },
  {
    id: "wa-sound-transit",
    name: "Sound Transit Procurement and Contracts",
    jurisdiction: "Central Puget Sound Regional Transit Authority",
    state: "WA",
    country: "US",
    level: "district",
    url: "https://www.soundtransit.org/get-to-know-us/doing-business/procurement-contracts",
    searchUrl:
      "https://www.soundtransit.org/get-to-know-us/doing-business/procurement-contracts",
    domain: "soundtransit.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Sound Transit procurement and contracts page.",
  },
  {
    id: "al-mobile-county-public-schools",
    name: "Mobile County Public Schools Purchasing",
    jurisdiction: "Mobile County Public Schools",
    state: "AL",
    country: "US",
    level: "district",
    url: "https://www.mcpss.com/purchasing",
    searchUrl: "https://www.mcpss.com/purchasing",
    domain: "mcpss.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Mobile County Public Schools purchasing page.",
  },
  {
    id: "ak-fairbanks-north-star-borough",
    name: "Fairbanks North Star Borough Purchasing",
    jurisdiction: "Fairbanks North Star Borough",
    state: "AK",
    country: "US",
    level: "district",
    url: "https://www.fnsb.gov/452/Purchasing",
    searchUrl: "https://www.fnsb.gov/452/Purchasing",
    domain: "fnsb.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fairbanks North Star Borough purchasing page.",
  },
  {
    id: "az-tucson",
    name: "City of Tucson Procurement",
    jurisdiction: "City of Tucson",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://www.tucsonprocurement.com/",
    searchUrl: "https://www.tucsonprocurement.com/",
    domain: "tucsonprocurement.com",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Tucson procurement site.",
  },
  {
    id: "ar-fayetteville",
    name: "City of Fayetteville Purchasing",
    jurisdiction: "City of Fayetteville",
    state: "AR",
    country: "US",
    level: "district",
    url: "https://www.fayetteville-ar.gov/384/Purchasing",
    searchUrl: "https://www.fayetteville-ar.gov/384/Purchasing",
    domain: "fayetteville-ar.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fayetteville purchasing page.",
  },
  {
    id: "ca-sacramento-county",
    name: "Sacramento County Contract and Purchasing Services",
    jurisdiction: "Sacramento County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://contractservices.saccounty.gov/Pages/default.aspx",
    searchUrl: "https://contractservices.saccounty.gov/Pages/default.aspx",
    domain: "contractservices.saccounty.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Sacramento County contract and purchasing services page.",
  },
  {
    id: "co-aurora",
    name: "City of Aurora Purchasing Services",
    jurisdiction: "City of Aurora",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://www.auroragov.org/cms/One.aspx?portalId=1881221&pageId=2031063",
    searchUrl:
      "https://www.auroragov.org/cms/One.aspx?portalId=1881221&pageId=2031063",
    domain: "auroragov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Aurora purchasing services page.",
  },
  {
    id: "ct-new-haven",
    name: "City of New Haven Purchasing",
    jurisdiction: "City of New Haven",
    state: "CT",
    country: "US",
    level: "district",
    url: "https://www.newhavenct.gov/government/departments-divisions/purchasing",
    searchUrl:
      "https://www.newhavenct.gov/government/departments-divisions/purchasing",
    domain: "newhavenct.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official New Haven purchasing page.",
  },
  {
    id: "de-new-castle-county",
    name: "New Castle County Purchasing",
    jurisdiction: "New Castle County",
    state: "DE",
    country: "US",
    level: "district",
    url: "https://www.newcastlede.gov/249/Purchasing",
    searchUrl: "https://www.newcastlede.gov/249/Purchasing",
    domain: "newcastlede.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official New Castle County purchasing page.",
  },
  {
    id: "dc-udc-procurement",
    name: "University of the District of Columbia Procurement",
    jurisdiction: "University of the District of Columbia",
    state: "DC",
    country: "US",
    level: "district",
    url: "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    searchUrl:
      "https://www.udc.edu/administration/office-of-contracts-and-procurement/",
    domain: "udc.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official UDC contracts and procurement page.",
  },
  {
    id: "fl-palm-beach-county",
    name: "Palm Beach County Purchasing",
    jurisdiction: "Palm Beach County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://discover.pbcgov.org/purchasing/Pages/default.aspx",
    searchUrl: "https://discover.pbcgov.org/purchasing/Pages/default.aspx",
    domain: "discover.pbcgov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "catalog_only",
    notes: "Official Palm Beach County purchasing page.",
  },
  {
    id: "ga-dekalb-county",
    name: "DeKalb County Purchasing and Contracting",
    jurisdiction: "DeKalb County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://www.dekalbcountyga.gov/purchasing-contracting/purchasing-contracting",
    searchUrl:
      "https://www.dekalbcountyga.gov/purchasing-contracting/purchasing-contracting",
    domain: "dekalbcountyga.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official DeKalb County purchasing and contracting page.",
  },
  {
    id: "hi-university-of-hawaii-procurement",
    name: "University of Hawaii Procurement and Real Property Management",
    jurisdiction: "University of Hawaii System",
    state: "HI",
    country: "US",
    level: "district",
    url: "https://www.hawaii.edu/procurement/",
    searchUrl: "https://www.hawaii.edu/procurement/",
    domain: "hawaii.edu",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Hawaii procurement page.",
  },
  {
    id: "id-boise",
    name: "City of Boise Purchasing",
    jurisdiction: "City of Boise",
    state: "ID",
    country: "US",
    level: "district",
    url: "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    searchUrl:
      "https://www.cityofboise.org/departments/finance-and-administration/purchasing/",
    domain: "cityofboise.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Boise purchasing page.",
  },
  {
    id: "il-university-of-illinois-procurement",
    name: "University of Illinois System Procurement Services",
    jurisdiction: "University of Illinois System",
    state: "IL",
    country: "US",
    level: "district",
    url: "https://www.procure.stateuniv.state.il.us/",
    searchUrl: "https://www.procure.stateuniv.state.il.us/",
    domain: "procure.stateuniv.state.il.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official University of Illinois System procurement services site.",
  },
  {
    id: "in-fort-wayne",
    name: "City of Fort Wayne Purchasing",
    jurisdiction: "City of Fort Wayne",
    state: "IN",
    country: "US",
    level: "district",
    url: "https://www.cityoffortwayne.org/purchasing.html",
    searchUrl: "https://www.cityoffortwayne.org/purchasing.html",
    domain: "cityoffortwayne.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Fort Wayne purchasing page.",
  },
  {
    id: "ia-linn-county",
    name: "Linn County Purchasing",
    jurisdiction: "Linn County",
    state: "IA",
    country: "US",
    level: "district",
    url: "https://www.linncountyiowa.gov/149/Purchasing",
    searchUrl: "https://www.linncountyiowa.gov/149/Purchasing",
    domain: "linncountyiowa.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Linn County purchasing page.",
  },
  {
    id: "ks-johnson-county",
    name: "Johnson County Purchasing",
    jurisdiction: "Johnson County",
    state: "KS",
    country: "US",
    level: "district",
    url: "https://www.jocogov.org/department/financial-management-administration/purchasing",
    searchUrl:
      "https://www.jocogov.org/department/financial-management-administration/purchasing",
    domain: "jocogov.org",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Johnson County purchasing page.",
  },
];
