import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_014: DirectRfpPortal[] = [
  {
    id: "tx-lubbock",
    name: "City of Lubbock Purchasing and Contract Management",
    jurisdiction: "City of Lubbock",
    state: "TX",
    country: "US",
    level: "district",
    url: "https://ci.lubbock.tx.us/departments/purchasing-contract-management",
    searchUrl:
      "https://ci.lubbock.tx.us/departments/purchasing-contract-management",
    domain: "ci.lubbock.tx.us",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Lubbock procurement page.",
  },
  {
    id: "mi-lansing",
    name: "City of Lansing Purchasing",
    jurisdiction: "City of Lansing",
    state: "MI",
    country: "US",
    level: "district",
    url: "https://www.lansingmi.gov/271/Purchasing",
    searchUrl: "https://www.lansingmi.gov/271/Purchasing",
    domain: "lansingmi.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Lansing procurement page.",
  },
  {
    id: "va-alexandria",
    name: "City of Alexandria Purchasing",
    jurisdiction: "City of Alexandria",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.alexandriava.gov/Purchasing",
    searchUrl: "https://www.alexandriava.gov/Purchasing",
    domain: "alexandriava.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Alexandria procurement page.",
  },
  {
    id: "va-prince-william-county",
    name: "Prince William County Purchasing",
    jurisdiction: "Prince William County",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://www.pwcva.gov/department/purchasing",
    searchUrl: "https://www.pwcva.gov/department/purchasing",
    domain: "pwcva.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official Prince William County procurement page.",
  },
  {
    id: "co-boulder",
    name: "City of Boulder Bids and Purchasing",
    jurisdiction: "City of Boulder",
    state: "CO",
    country: "US",
    level: "district",
    url: "https://bouldercolorado.gov/services/bids-and-purchasing",
    searchUrl: "https://bouldercolorado.gov/services/bids-and-purchasing",
    domain: "bouldercolorado.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Boulder procurement page.",
  },
  {
    id: "mn-minneapolis",
    name: "City of Minneapolis Procurement",
    jurisdiction: "City of Minneapolis",
    state: "MN",
    country: "US",
    level: "district",
    url: "https://www2.minneapolismn.gov/business-services/doing-business-with-the-city/procurement/",
    searchUrl:
      "https://www2.minneapolismn.gov/business-services/doing-business-with-the-city/procurement/",
    domain: "www2.minneapolismn.gov",
    accessMode: "public_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "catalog_only",
    notes: "Official City of Minneapolis procurement page.",
  },
];
