import type { DirectRfpPortal } from "./directRfpPortals";

export const GENERATED_DIRECT_RFP_PORTALS_041: DirectRfpPortal[] = [
  {
    id: "ca-city-of-pasadena-opengov",
    name: "City of Pasadena Procurement Portal",
    jurisdiction: "City of Pasadena",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/pasadena/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/pasadena/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Pasadena public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "az-city-of-tucson-opengov",
    name: "City of Tucson Procurement Portal",
    jurisdiction: "City of Tucson",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/tucson-az/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/tucson-az/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Tucson public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "pa-city-of-pittsburgh-opengov",
    name: "City of Pittsburgh Procurement Portal",
    jurisdiction: "City of Pittsburgh",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/pittsburghpa/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/pittsburghpa/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Pittsburgh public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "fl-city-of-tampa-opengov",
    name: "City of Tampa Procurement Portal",
    jurisdiction: "City of Tampa",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/cityoftampa/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/cityoftampa/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Tampa public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "ca-city-of-santa-cruz-opengov",
    name: "City of Santa Cruz Procurement Portal",
    jurisdiction: "City of Santa Cruz",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/santacruzca/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/santacruzca/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Santa Cruz public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "fl-city-of-st-petersburg-opengov",
    name: "City of St. Petersburg Procurement Portal",
    jurisdiction: "City of St. Petersburg",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/stpete/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/stpete/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of St. Petersburg public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "ca-city-of-palm-desert-opengov",
    name: "City of Palm Desert Procurement Portal",
    jurisdiction: "City of Palm Desert",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/cityofpalmdesert/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/cityofpalmdesert/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of Palm Desert public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "ca-county-of-sacramento-opengov",
    name: "County of Sacramento Procurement Portal",
    jurisdiction: "County of Sacramento",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/saccounty/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/saccounty/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for County of Sacramento public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "fl-orange-county-opengov",
    name: "Orange County, Florida Procurement Portal",
    jurisdiction: "Orange County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/orangecountyfl/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/orangecountyfl/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Orange County, Florida public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "ca-city-of-west-sacramento-opengov",
    name: "City of West Sacramento Procurement Portal",
    jurisdiction: "City of West Sacramento",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/cityofwestsacramento/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/cityofwestsacramento/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for City of West Sacramento public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "pa-scranton-city-school-district-opengov",
    name: "Scranton City School District Procurement Portal",
    jurisdiction: "Scranton City School District",
    state: "PA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/ssdedu/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/ssdedu/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Scranton City School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "fl-monroe-county-school-district-opengov",
    name: "Monroe County School District, FL Procurement Portal",
    jurisdiction: "Monroe County School District",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/keyschools-mcsd/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/keyschools-mcsd/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Monroe County School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "md-baltimore-county-opengov",
    name: "Baltimore County, Maryland Procurement Portal",
    jurisdiction: "Baltimore County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/baltimorecountymd/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/baltimorecountymd/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Baltimore County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "nj-passaic-city-school-district-opengov",
    name: "Passaic City School District Procurement Portal",
    jurisdiction: "Passaic City School District",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/passaicschools/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/passaicschools/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Passaic City School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "fl-volusia-county-opengov",
    name: "County of Volusia Procurement Portal",
    jurisdiction: "Volusia County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/volusia/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/volusia/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Volusia County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "fl-pinellas-county-school-district-opengov",
    name: "Pinellas County School District Procurement Portal",
    jurisdiction: "Pinellas County School District",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/pcsb/project-list",
    searchUrl: "https://procurement.opengov.com/portal/embed/pcsb/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Pinellas County School District public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "ga-dekalb-county-opengov",
    name: "County of DeKalb, GA Procurement Portal",
    jurisdiction: "DeKalb County",
    state: "GA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/dekalbcountyga/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/dekalbcountyga/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for DeKalb County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "nj-jersey-city-public-schools-opengov",
    name: "Jersey City Public Schools Procurement Portal",
    jurisdiction: "Jersey City Public Schools",
    state: "NJ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/jcboe/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/jcboe/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Jersey City Public Schools public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "fl-santa-rosa-county-opengov",
    name: "Santa Rosa County Procurement Portal",
    jurisdiction: "Santa Rosa County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/santarosafl/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/santarosafl/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Santa Rosa County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "oh-cleveland-metropolitan-school-district-opengov",
    name: "Cleveland Metropolitan School District Procurement Portal",
    jurisdiction: "Cleveland Metropolitan School District",
    state: "OH",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/clevelandmetroschools/calendar",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/clevelandmetroschools/calendar",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement calendar for Cleveland Metropolitan School District public RFP, RFQ, RFI, and project opportunities; calendar browsing is public.",
  },
  {
    id: "ca-orange-county-opengov",
    name: "County of Orange Procurement Portal",
    jurisdiction: "Orange County",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/ocgov/calendar",
    searchUrl: "https://procurement.opengov.com/portal/embed/ocgov/calendar",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement calendar for County of Orange public RFP, RFQ, RFI, and project opportunities; calendar browsing is public.",
  },
  {
    id: "ca-san-bernardino-city-unified-school-district-opengov",
    name: "San Bernardino City Unified School District Procurement Portal",
    jurisdiction: "San Bernardino City Unified School District",
    state: "CA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/sbcusd/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/sbcusd/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for San Bernardino City Unified School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "fl-alachua-county-opengov",
    name: "Alachua County, Florida Procurement Portal",
    jurisdiction: "Alachua County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/alachuacounty/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/alachuacounty/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Alachua County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "va-richmond-public-schools-opengov",
    name: "Richmond Public Schools Procurement Portal",
    jurisdiction: "Richmond Public Schools",
    state: "VA",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/rvaschools/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/rvaschools/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Richmond Public Schools public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "fl-clay-county-opengov",
    name: "Clay County Procurement Portal",
    jurisdiction: "Clay County",
    state: "FL",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/claycounty/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/claycounty/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Clay County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "az-chandler-unified-school-district-opengov",
    name: "Chandler Unified School District Procurement Portal",
    jurisdiction: "Chandler Unified School District",
    state: "AZ",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/cusd80/project-list?departmentId=all&status=all",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/cusd80/project-list?departmentId=all&status=all",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Chandler Unified School District public RFP, RFQ, RFI, and project opportunities; opportunity browsing is public.",
  },
  {
    id: "md-wicomico-county-opengov",
    name: "Wicomico County Procurement Portal",
    jurisdiction: "Wicomico County",
    state: "MD",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/wicomicocounty/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/wicomicocounty/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 2,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Wicomico County public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
  {
    id: "sc-richland-school-district-two-opengov",
    name: "Richland School District Two Procurement Portal",
    jurisdiction: "Richland School District Two",
    state: "SC",
    country: "US",
    level: "district",
    url: "https://procurement.opengov.com/portal/embed/richland2/project-list",
    searchUrl:
      "https://procurement.opengov.com/portal/embed/richland2/project-list",
    domain: "procurement.opengov.com",
    accessMode: "dynamic_html",
    requiresKey: false,
    requiresLogin: false,
    tier: 3,
    parserStatus: "needs_parser",
    notes:
      "Official buyer-specific OpenGov procurement portal for Richland School District Two public RFP, RFQ, RFI, and project opportunities; active project browsing is public.",
  },
];
